### ISSUE TITLE
Philippines need certification of confinement with admitting Diagnosis

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#100]
Philippines need certification of confinement with admitting Diagnosis

**Comment by tangollama** [comment]
The follow artifact was provided by the Tebow CURE Hospital. We're determining requirements inline with comments, etc. We'll document finds in the ticket. https://docs.google.com/document/d/1uwCX8NdDGsEMkqHtV1DqHC7NKzMGh9XKMAdRlUiH63o/edit

**Comment by tangollama** [comment]
After discussion with @jkleinsc, this feels like it's related to our need for a Forms framework for HospitalRun. From that, we see a few specific requirements for forms:
1. Forms that stay under some reasonable amount of content need to be able to print on standard-size paper.
2. Forms are not just for data intake. They can/could/need to produce printable output.
3. Forms need workflow that could (for instance) both capture an admitting diagnosis in one form and produce a printable certificate as well as write that data to the patient care system.

**Comment by tangollama** [comment]
@taras per our conversations re: Ember Sherpa working more closely with HospitalRun as an example project, here's a ticket for consideration.
