### ISSUE TITLE
No Way to Edit Imaging Pricing Type List, 

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#1007]
**Expected behavior:**
Going to Administration\Lookup Lists \ Imaging Pricing Types should result in an editable list of Pricing Types.
**Actual behavior:**
Imaging Pricing Types Do Not Show

The Only way to Add to the list is when adding an Imaging Request.  Then there is no means of editing or removing the Imaging Pricing Type just added.

Not Possible to Remove or Edit from the List.

**OS and Browser:**
Ubuntu , Chrome and Firefox.

**Comment by jkleinsc** [comment]
@garylm Imaging Pricing types are editable through billing, not the lookup list.  Go to Billing->Prices->Imaging Pricing.  You can edit existing Imaging Types or Add New ones there.

**Comment by garylm** [comment]
Thanks & Sorry for misunderstsnding.  Howeverf, there are still some “issues”.

  *   Image Pricing List has an Upload process that does not work.

  *   Lab Pricing List seems to have the same issues.

Gary
Gary Miller
gary@groupmiller.com<mailto:gary@groupmiller.com>

**Comment by jkleinsc** [comment]
@garylm that is true.  Import doesn't work for those items, so that is an issue.
