### ISSUE TITLE
Search in docker install

### ISSUE THREAD

**Issue by fgiorlando** [HospitalRun/hospitalrun-frontend#1011]
In a new docker install using the install docs, the search field doesn't return any results.
Is there a way to enable elastic search in docker?

**Comment by jkleinsc** [comment]
@fgiorlando there is a way to do search without Elasticsearch, but there seems to be an issue with it right now that I am resolving.  There is work underway to dockerize https://github.com/HospitalRun/hospitalrun-server and part of that is to include Elasticsearch.  The frontend docker setup is really just for testing the development environment, not for production deploys.

**Comment by jkleinsc** [comment]
@fgiorlando this issue is now fixed in the latest code.

**Comment by fgiorlando** [comment]
thanks, trying a docker upgrade but having some problems building currently, will post a new issue.
