### ISSUE TITLE
Modify navigational paradigm

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#103]
After a bit of research and studying paradigms of how other similar administrative systems are handling navigation these days, I've come up with a new navagational paradigm that I'd like to implement. The idea would be a persistent sidebar nav (that could be collapsible for maximum screen real estate on desktop or on mobile).

Here's the rough comp of the new system:

![img](https://s3.amazonaws.com/f.cl.ly/items/472e2j2p0S0c1U1P3P1F/Image%202015-05-18%20at%204.00.47%20PM.png)

And collapsed would look like:

![img](https://s3.amazonaws.com/f.cl.ly/items/432y033x3i0l3q0j2R1G/Image%202015-05-18%20at%204.05.14%20PM.png)

Some inspiration that I drew from includes:

![img](https://s3.amazonaws.com/f.cl.ly/items/1R1Q0I2t2b0g2A3D3W3R/Image%202015-05-18%20at%204.08.24%20PM.png)

Before I branch and start modifying code (I will open a pull request for this one), any major concerns?

cc @tangollama @jkleinsc

**Comment by jkleinsc** [comment]
@jglovier What are you thinking in regards to search?

**Comment by jglovier** [comment]
@jkleinsc oh - good question. Forgot to add that part in, but there's a couple ways we could handle it. Easiest would be to add an icon below the logo bit and right above the nav items with a spot for search there.

**Comment by jglovier** [comment]
Here's a mock with the search in place.

![img](https://s3.amazonaws.com/f.cl.ly/items/183i0M012515382n1o2j/Image%202015-05-18%20at%209.57.59%20PM.png)

**Comment by jglovier** [comment]
So the gear is intended to be a place to put additional options that don't necessarily belong in the primary app navigation, like user settings, admin stuff, logout link, etc.

For example:

![image](https://cloud.githubusercontent.com/assets/1319791/7867582/f124364c-0544-11e5-9f3a-af0c7b2e231a.png)

Right now I'm just putting the Logout link in there, but is it right to assume we will have other items to put in there eventually?

---

Also, where can I drop basic jQuery to add functionality to this little thing? I remember asking about this before, but it's been so long (a year maybe?) that I can't seem to recall.

**Comment by jkleinsc** [comment]
@jglovier the logic for this control belongs in the navigation controller and template and should use Ember to control its operation, not jQuery.  For showing/hiding the menu, we simply need to tie an action to the gear (see http://guides.emberjs.com/v1.11.0/templates/actions/)

**Comment by jglovier** [comment]
>For showing/hiding the menu, we simply need to tie an action to the gear (see http://guides.emberjs.com/v1.11.0/templates/actions/)

:metal:

**Comment by tangollama** [comment]
@jglovier, I feel like we can close this issue. Do you agree?

**Comment by jglovier** [comment]
I haven't finished this yet (mobile bit is unresolved still), but if you want to close it out and open a new issue for the mobile styling that's fine with me.

**Comment by tangollama** [comment]
@jglovier, should I assign this one to you to finish when you have the time or do you need something from me / JK on this one?

**Comment by jglovier** [comment]
Yeah, go ahead and assign to me and I'll finish it as soon as I can. :+1: Hoping to find some time before the end of the year to address this.

**Comment by jglovier** [comment]
For my own reference/reminder, see also #135

**Comment by tangollama** [comment]
@jglovier  Assigned to you so that you can decide if you need to do it or not.

**Comment by tangollama** [comment]
@jglovier bump.

**Comment by fox1t** [comment]
@StefanoMiC Take a look on this issue.
