### ISSUE TITLE
Imaging requests - changes to notes, field order and completed by

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#1033]
This is an enhancement request

1.  Add a "request notes" field, right after the image type selection field.   This would be where the ordering doctor specifies the details of the request (i.e.   please take an image of the upper left arm)

2. Rename the existing notes field to be "results notes"   This will be used by either the tech taking the image, or the radiologist reading the image, to add notes, observations, etc.   

3. A system populated field named "completed by" should be added when the image request is completed.  

It is important to note that technicians take images, radiologist interpret them.   So, who completes the image should be captures in all cases, but the radiologist that interprets and comments on the image is a second optional piece of information

the relevant field order, top to bottom should be:

1. image type
2. request notes
3. radiologist
4. results notes
5. completed by:

**Comment by baoqchau** [comment]
I can help with this one

**Comment by baoqchau** [comment]
I have one question: Right now in the "Imaging request" we have two fields: `Result` and `Notes`. So, for @mnorbeck request, should I change `Result` field into `Result Notes` and `Notes` into `Requested Notes`? And for `complete by` field, I will add `completeBy` into the `imaging` models. Is this a good solution for you? @jkleinsc

**Comment by jkleinsc** [comment]
@baoqchau Yes, change the label of `Result` to `Results Notes` and `Notes` to `Request Notes`.
And you can add a `completedBy` field to the `imaging` models.
