### ISSUE TITLE
Searching for appointments - search field not labeled correctly.

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#1035]
**Expected behavior:**
Scheduling > Appointment Search has a field that displays a list of Appointment status values.   The field should be labeled "Status" or "Appointment Status".  

**Actual behavior:**

The field is labeled "First Name"

**Steps to reproduce:**

**Screenshots (if applicable):**

<img width="1024" alt="screen shot 2017-03-28 at 12 54 44 pm" src="https://cloud.githubusercontent.com/assets/6825179/24417324/fe9c8e06-13b5-11e7-9068-46e571207693.png">

**OS and Browser:**

**Comment by BogdanAlexandru** [comment]
Do a quick sync to the latest version, PR https://github.com/HospitalRun/hospitalrun-frontend/pull/1028 should've taken care of this.

**Comment by jkleinsc** [comment]
#1028 from @BogdanAlexandru fixed this issue, so I am closing this.
