### ISSUE TITLE
website not running locally on windows 32 bit machine

### ISSUE THREAD

**Issue by swekshajha12** [HospitalRun/hospitalrun-frontend#1042]
**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by tangollama** [comment]
@swekshajha12 is this still an issue?

**Comment by stukalin** [comment]
@swekshajha12 I'd close this issue since it lacks the details. If you're still facing it, please reopen.
