### ISSUE TITLE
Missed appointments screen should be removed

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#1047]
**Expected behavior:**
Missed appointments should be searchable
**Actual behavior:**
The missed appointments screen only shows missed appointments for the current week
**Steps to reproduce:**
Create an appointment from last week and set the status to Missed.  Navigate to Scheduling/Missed Appointments (/appointments/missed).   The appointment will not appear.
**Screenshots (if applicable):**
NA
**OS and Browser:**
All

It turns out that Appointment Search allows us to already filter on missed appointments, so that screen should be used to find missed appointments.  This means that the Missed Appointments screen isn't really needed and therefore should be removed from the system.

**Comment by StIvEk** [comment]
HI @jkleinsc, @tangollama. I would like to contribute on this issue.
