### ISSUE TITLE
Can't delete patient (new installation via docker)

### ISSUE THREAD

**Issue by fgiorlando** [HospitalRun/hospitalrun-frontend#1049]
**Expected behavior:**
In the patient view, the "delete" button should remove that patient record

**Actual behavior:**
Nothing happens when I press delete. The patient record is not deleted and no dialogue is presented.

**OS and Browser:**
OS X 10.11
Firefox 52.0.2

**Comment by jkleinsc** [comment]
@fgiorlando there is a bug with patient deletion that was introduced with a change to a newer version of ember-concurrency.  I am working on a fix now.
