### ISSUE TITLE
Error running initcouch2.sh on ubuntu 16.04

### ISSUE THREAD

**Issue by bot101** [HospitalRun/hospitalrun-frontend#1053]
**Expected behavior:**
Running script was supposed to create new user according to installation guide
**Actual behavior:**
Throws an illegai_database_name error and exits script
**Steps to reproduce:**
After setting up couchdb on system, run ./script.initcouch2.sh in directory where hospitalrun was cloned.
**Screenshots (if applicable):**
![coucherror](https://cloud.githubusercontent.com/assets/8009733/24854415/4c8c45aa-1dd6-11e7-94f5-d445c4fe890a.png)

**OS and Browser:**
Ubuntu 16.04 32 bit

**Comment by jkleinsc** [comment]
@bot101 can you let me know what the results of running this command produces on your system:
```
curl localhost:5984
```

**Comment by bot101** [comment]
I have successfully set it up on a windows machine and have deleted all its files from my linux machine so I can't run that. Thanks.
