### ISSUE TITLE
Poor calander pop-up

### ISSUE THREAD

**Issue by bdheeman** [HospitalRun/hospitalrun-frontend#1054]
**Expected behavior:** Allow the user/operator may/can choose year and month separately.

**Actual behavior:** User/operator needs to click unwanted arrow buttons repeatedly, entering date of birth :-( 

**Steps to reproduce:** Try adding a new patient and enter her/his date of birth

**Screenshots (if applicable):** Not required

**OS and Browser:** Most of the java-script enabled browsers have nothing to do with it.

**Comment by jkleinsc** [comment]
@bdheeman The popup calendar was supposed to allow you to click on the month and/or the year to change them.  At some point this broke.  I have a fix forthcoming that will allow the month and year to be changed via clicking on them.
