### ISSUE TITLE
Error running initcouch2.sh on Win10

### ISSUE THREAD

**Issue by TBuc** [HospitalRun/hospitalrun-frontend#1061]
**Expected behavior:**
All the commands issued by the script shall return: _{"ok":true}_.
**Actual behavior:**
At line 18, the following command:
`curl -X PUT $SECUREHOST/_users/_security -d '{ "admins": { "names": [], "roles": ["admin"]}, "members": { "names": [], "roles": [admin]}}'`
returns this message:
`{"error":"bad_request","reason":"invalid UTF-8 JSON"}`
**Steps to reproduce:**
Run `.bash -o igncr /scripts/initcouch2.sh` in a cygwin environment.
**Screenshots (if applicable):**

**OS and Browser:**
Software versions:
- Windows 10 x64
- CouchDB 2.0.0.1
- CYGWIN_NT-10.0 2.3.1(0.291/5/3) x86_64 Cygwin

**(Maybe) a solution:**
Fixed locally by modifying the command, adding the missing double quotes to the latest _admin_ role:
`curl -X PUT $SECUREHOST/_users/_security -d '{ "admins": { "names": [], "roles": ["admin"]}, "members": { "names": [], "roles": ["admin"]}}'`
This way it worked fine (at least, an _{"ok":true}_ was returned by issuing the so-fixed command).

**Comment by jonathanihm** [comment]
I had the same issue and the fix posted here works as well.  I can submit a PR.

**Comment by tangollama** [comment]
@jonathanihm please do and thanks to you and @TBuc

**Comment by TBuc** [comment]
I'm pretty new so I was awaiting feedback before doing anything. Thank you @jonathanihm for submitting the PR, great :-)
