### ISSUE TITLE
Navigation arrows obscure database column headings

### ISSUE THREAD

**Issue by bethgw** [HospitalRun/hospitalrun-frontend#1068]
The arrows that are used to scroll between screens of the databases in HospitalRun are placed such that sometimes they cover the headings of columns in the databases. The placement should be revised so that, in all user views, this does not occur.

For example, logged in as "hr.doctor@hospitalrun.io", navigate to the "Medication" tab. I have attached a screenshot where you can see the arrows obscuring the "Status" heading (top right of the screen).

This is using Chrome on Debian Jessie, I haven't yet tested on other OSs or browsers but I will do so and update this report accordingly.

![hospitalrunarrows](https://cloud.githubusercontent.com/assets/26877437/25338535/7a9b7f70-28f7-11e7-9ca8-d4865ce3fa63.png)

**Comment by bethwhite** [comment]
Can confirm, the same issue is seen on a Mac in Chrome, and in Firefox.

However, the only login I have observed it with so far is hr.doctor@hospitalrun.io, presumably because the doctor login allows access to more elements of patient files than other roles. I have tested with hr.nurse, hr.social.worker, hr.hospital.office and hr.lab.tech.

**Comment by tchan** [comment]
Can anyone provide some sample data that I can load to test this? Assuming you are using it in a production environment so your data is confidential.

**Comment by bethwhite** [comment]
Hi @tchan, actually no I'm not using it in a production environment, my plan was to contribute to HR so I have been testing out features using their beta page and test logins:

https://beta.hospitalrun.io/#/login
Username: hr.doctor@hospitalrun.io
Password: HRt3est12

**Comment by tchan** [comment]
Ohh, thank you for letting me know about that, had no idea that existed!

**Comment by bethwhite** [comment]
No problem. I can't find the page with all the test logins so it's probably not easy to stumble upon! Will link it here if I find it.

**Comment by tchan** [comment]
I found it here :)
http://hospitalrun.io/demo/

**Comment by the-oem** [comment]
Hi peeps! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!
