### ISSUE TITLE
Create the electron windows 64-bit download/install

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1075]
**Expected behavior:**
Availability of the code as a win32 download.

**Actual behavior:**
Currently unavailable.

**Steps to reproduce:**
- Checkout the project on a win32x64 development device.
> npm install
> bower install
> ember electron:make --platform=win32x64

Talk to me on Slack @tangollama to become part of the build team process.

**Comment by andrew-werdna** [comment]
@tangollama I'm about to join the slack channel when I get back home, I would love to help out and contribute in any way that helps. I have a dual boot (Windows 7/Ubuntu 16.04) development machine at my disposal. I'll jump on slack in a little bit and make myself available for whatever anyone needs.

**Comment by tangollama** [comment]
Awesome. Thx. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by andrew-werdna** [comment]
My apologies, took longer than I expected. I'll be available in about 15
minutes.

I also completely understand if it's too late for today. But I'll be on
slack shortly to see if anyone is still on!

**Comment by andrew-werdna** [comment]
At first when I ran the commands from the **Steps to reproduce** section, I got the following interesting error.

    Packaging Electron project.
	â Preparing to Package Application for arch: x64
	Failed to compile file: AppData\Local\Temp\electron-packager\win32-x64\HospitalRun-win32-x64\resources\app\ember\crossdomain.xml
	Compiling AppData\Local\Temp\electron-packager\win32-x64\HospitalRun-win32-x64\resources\app\ember\crossdomain.xml resulted in a MIME type of application/xml, which we don't know how to handle


	An error occured while making for target: squirrel
	Failed with exit code: 1
	Output:
	Fatal error: Unable to set icon

	 at ChildProcess.proc.on.code (hospitalrun-frontend\node_modules\electron-winstaller\lib\spawn-promise.js:62:16)
		at emitTwo (events.js:106:13)
		at ChildProcess.emit (events.js:191:7)
		at maybeClose (internal/child_process.js:877:16)
		at Socket.<anonymous> (internal/child_process.js:334:11)
		at emitOne (events.js:101:20)
		at Socket.emit (events.js:188:7)
		at Pipe._handle.close [as _onclose] (net.js:498:12)

However, I then noticed that in ember-electron/electron-forge-config.js, the electronWinstallerConfig.setupIcon property path appeared to be going up too many directories. When I changed it to only travel up one directory before going back down to assets/icons/favicon.ico, the `ember electron:make` completed successfully without complaining. What would you like me to do now? I have saved my one little change on a `hotfix/update_winstaller_config` branch on **my origin** (no PR or anything yet) and I have the electron-out folder with all the generated goodies.

**Comment by andrew-werdna** [comment]
I dare say we are good here. Submitting PR for the path fix in winstaller config
