### ISSUE TITLE
Inventory Valuation report, it seems that some GIK inventory reports as a “N”`

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#109]
There are times the report appears to report GIK = N when it is clearly a Y. This is according to Mimi in the Philippines.

**Comment by jkleinsc** [comment]
@tangollama I just tested this on my dev site which has a copy of the Philippines data and it works properly.  Can you validate with Mimi which inventory items she is seeing this with?

**Comment by tangollama** [comment]
Tested. Appears to be functioning correctly.
