### ISSUE TITLE
Could not start watchman

### ISSUE THREAD

**Issue by chinmaybhatk** [HospitalRun/hospitalrun-frontend#1095]
**Expected behavior:**
Go to http://localhost:4200/ in a browser and login with username hradmin and password test

**Actual behavior:**
 couldnot conect to http://localhost:4200/

> in console

Checking CouchDB...Starting ember server
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/appointments.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "hospitalrun/tests/fixtures/imaging.js" as it exceeds the max of "100KB".

**Steps to reproduce:**
sudo npm start

**Screenshots (if applicable):**

**OS and Browser:**
 ubuntu 14.04 Firefox chrome
ember-cli: 2.10.0
node: 6.9.0
os: linux ia32
npm : 3.10.8

i could set up and run hospitalrun-server and wanted hospitalrun-frontend to modify something..

when i start using npm start or ember serve i am getting 
Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.

i downgraded from node 7 + to 6.9.0 as i followed #798 but didnt help..
and port 4200 is used by ember
 tcp6       0      0 :::4200                 :::*                    LISTEN      7095/ember

how to run this? please help me

**Comment by chinmaybhatk** [comment]
i could connect to the server and use the application.. but error still exist

**Comment by jkleinsc** [comment]
@chinmaybhatk the watchman message is just a warning that is safe to ignore.  For more information, please refer to this: https://ember-cli.com/user-guide/#watchman
