### ISSUE TITLE
setup script/server

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#11]
@jkleinsc can we setup a `script/server` command that initiates both Couch and `ember serve`?

**Comment by jkleinsc** [comment]
@jglovier I suppose we could.  The couch part would be different depending on OS.  We could at the very least have a script that tests to see if couch is up before running ember serve.

**Comment by jglovier** [comment]
Yeah, even if it just triggered `ember serve`, it would benefit those familiar with the `script/server` convention by standardizing the approach. If more things were required, it could also output a warning like `Be sure to run Couch.app`, etc.

**Comment by filipesperandio** [comment]
I like the idea.
I am also very fan of `Makefile`s and I can open a PR for that if people think it is valuable and are comfortable using `make`.

**Comment by jkleinsc** [comment]
@filipesperandio I don't think we need a Makefile since there aren't any executables for this project that get built.  It's an ember web app and the way it gets built is via `ember build`.

**Comment by filipesperandio** [comment]
I understand that. `make` helped me in the past even on script projects smoothing out dependencies.
for example a target `make serve` could depend on `ember-cli` and `bower` being installed.

**Comment by filipesperandio** [comment]
@jglovier `script/server` OR `scripts/server` ? (with an `s` at the end of scripts)

**Comment by jkleinsc** [comment]
@filipesperandio gotcha.  Thanks for clarifying.

**Comment by jglovier** [comment]
@filipesperandio I prefer `script/server` but probably just because it is a convention [we use at GitHub](http://githubengineering.com/scripts-to-rule-them-all/).

**Comment by filipesperandio** [comment]
Cool, I will adjust.
