### ISSUE TITLE
Frequently asked questions documentation

### ISSUE THREAD

**Issue by tchan** [HospitalRun/hospitalrun-frontend#1101]
Hello everyone, do you think there's value in starting a FAQ section within either the README.md and/or contributing guide for developers. I've been lurking in the slack channel and so far have seen
two people ask the same question in May:
https://hospitalrun.slack.com/archives/C02BT7ZBK/p1494594494461678
https://hospitalrun.slack.com/archives/C02BT7ZBK/p1493972891279875

This would probably make it less daunting for new developers.

edit: Or it could be a pinned item in #general channel or something.

**Comment by jkleinsc** [comment]
@tchan an FAQ would be awesome!
