### ISSUE TITLE
When i run "forever start ./script/server" the forever logfile says that "set -euo pipefail" is Unexpected string

### ISSUE THREAD

**Issue by HasaanAli** [HospitalRun/hospitalrun-frontend#1103]
I am trying to run this frontend project using forever on aws instance. I modified start command in package.json file with this: "start": "forever start ./script/server". So that when i'll do "npm start" it will actually run the server script inside forever. But when I do forever list it shows that my process is stopped and shows me path to log file. See below:

<img width="884" alt="forever list showing logfile with stopped status" src="https://user-images.githubusercontent.com/8423737/26922892-f88244ac-4c59-11e7-8b57-f12701322557.png">

When I view this log file its like this:

<img width="761" alt="forever log file" src="https://user-images.githubusercontent.com/8423737/26923017-52e1ec4a-4c5a-11e7-8b1b-0050e2fc8d48.png">

I tried changing **set -euo pipefail** in ./script/server file to **bash -c "set -euo pipefail"** thinking that it might work but it didn't.

Any help would be really appreciated. Thanks.

**Comment by baoqchau** [comment]
Hi @HasaanAli. I tried to run hospitalrun on my laptop with the following start command: `forever start -c 'npm start' ./script/server` and it worked. I found the solution here [https://github.com/foreverjs/forever/issues/540](url). Hope this help you solve your problem.

**Comment by tangollama** [comment]
@HasaanAli, it looks like @baoqchau's reply addresses the issue. Closing. Let me know if this is a concern.
