### ISSUE TITLE
Missing some translations for French language

### ISSUE THREAD

**Issue by richiethomas** [HospitalRun/hospitalrun-frontend#1110]
**Expected behavior:**
I would expect to see the following translation keys in the French language:
`admin.customForms.labels.expenseTo`
`admin.customForms.labels.labFormType`
`admin.customForms.labels.opdReportFormType`
`admin.customForms.labels.operativePlanFormType`
`admin.customForms.labels.otherOptionLabel`
`admin.customForms.labels.patientFormType`
`admin.customForms.labels.socialworkFormType`
`admin.customForms.labels.visitFormType`
`admin.header.editTitle`
`admin.header.facilityName`
`admin.lookup.incidentDepartments`
`admin.lookup.titles.deleteLookupValue`
`admin.lookup.titles.deleteLookupValue`
`admin.roles.capability.addSocialwork`
`admin.workflow.clinicPrepaymentLabel`
`admin.workflow.followupPrepaymentLabel`
`admin.workflow.outpatientImagingLabel`
`admin.workflow.outpatientLabLabel`
`admin.workflow.outpatientMedicationLabel`
`admin.workflow.titles.optionsSaved`
`admin.workflow.workflowLabel`
`appointments.calendarTitle`
`appointments.titles.theaterSchedule`
`billing.buttons.addOverride`
`billing.labels.actualCharges`
`billing.messages.flatDiscountMsg`
`messages.reportError`
`messages.requiredFieldsCorrectErrors`
`messages.saveActionException`
`navigation.subnav.theaterSchedule`
`patients.labels.patientTypeCharity`
`reports.titles.newOPDReport`
`reports.titles.opdReport`
`visits.buttons.newOPDReport`

**Actual behavior:**

These labels are currently missing, therefore their values are not visible in the UI

**Steps to reproduce:**
Visit "Scheduling => Theater Schedule" link in the sidebar navigation.  You'll see a page title in English, but none if you switch your default language to French and refresh the page.

**Screenshots (if applicable):**
"Theater Schedule" screen in English (note- contains page title)
<img width="1440" alt="screen shot 2017-06-23 at 1 21 17 pm" src="https://user-images.githubusercontent.com/3839713/27493036-50544c4e-5816-11e7-947c-021c323ad01a.png">
"Theater Schedule" screen in French (note the missing page title)
<img width="1440" alt="screen shot 2017-06-23 at 1 21 07 pm" src="https://user-images.githubusercontent.com/3839713/27493035-4e3cf38e-5816-11e7-8194-0feda1189afc.png">

**OS and Browser:**
n/a- occurs in all operating systems and browsers

**Comment by jkleinsc** [comment]
Resolved by #1104
