### ISSUE TITLE
In Priscription Every time user have to add one by one. Need of Multi Medication List in priscription.

### ISSUE THREAD

**Issue by knowngate** [HospitalRun/hospitalrun-frontend#1111]
**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by glearner** [comment]
@knowngate Thank you for reporting it. I am working on it and try to solve problem as soon as possible.

**Comment by tangollama** [comment]
@glearner, are you working on this? If so, I'll tag this as in progress.

**Comment by glearner** [comment]
@tangollama  Yes I am working on this. I am very close to solution.

**Comment by tangollama** [comment]
Awesome blossom. Thx for the reply.

**Comment by wilsonkasey** [comment]
How far are you now? Do you need any help here?

**Comment by tangollama** [comment]
@glearner any update for @wilsonkasey who is offering to assist?

**Comment by wilsonkasey** [comment]
Yes please.

**Comment by niinortey** [comment]
Any headway with this please?

**Comment by tangollama** [comment]
@niinortey, I expect that either @wilsonkasey or @glearner have or are close to a solution?

**Comment by joelelangovan1985** [comment]
Hi any solutions yet @glearner?
