### ISSUE TITLE
getting error on running . Please help

### ISSUE THREAD

**Issue by glearner** [HospitalRun/hospitalrun-frontend#1119]
![image](https://user-images.githubusercontent.com/29622895/27804169-177d5522-604b-11e7-803f-5373038a7dd6.png)

**Comment by jonathanihm** [comment]
Could you attach your log file to the issue?

**Comment by santiago0697** [comment]
Hi, @glearner 
You could use "the other way" command: **ember serve**

**Comment by amarlearning** [comment]
Just prefix `sudo` in the command and it will work.

**Comment by tangollama** [comment]
@glearner closing this issue unless you reply otherwise.
