### ISSUE TITLE
Upload patients

### ISSUE THREAD

**Issue by christianmls** [HospitalRun/hospitalrun-frontend#1122]
Hello,

Please, Can you help me, I need the format to upload patients, I have about 1000 patients that I want to upload to the system.

I need simple  format for patients, I reviewed sample-data.txt but it is very complex to verify the format to only upload patients.

Thank you.

**Comment by santiago0697** [comment]
We could design one method for upload massive patients from csv or json file with all the fields it's necessary for create a basic profile, it would complete with the time when some one check that profile and see some fields are empty. 

What do you think about it.

**Comment by christianmls** [comment]
It's perfect, I do not have much experience in Ember, But I help you in whatever you need my email is christianmls@hotmail.com

**Comment by santiago0697** [comment]
Do we need the approval of the coordinator of this project. I'm new in the world of contributions and i don't know exactly how it works

**Comment by tangollama** [comment]
@santiago0697 @christianmls the basic concept makes sense. We want to encourage ease of adoption HospitalRun and having a simple format for basic demographic data is in line with that philosophically. When you submit the PR, it would be helpful to highlight what fields you are and are not supporting in the simple upload. Otherwise, go for it.

**Comment by KenyanGeek** [comment]
@tangollama still on the same issue is it possible to use the LoadDB feature on the look up list to load patient data?

**Comment by tangollama** [comment]
@KenyanGeek, no that's not possible. Currently, the only format available is in the LoadDB tab under Administration. I'd recommend a few concerned parties put together a proposed scaled-down json format for importing patient demographic data. From there, we can create a feature issue and ask someone to work on it. 

As I have time myself, I'd be happy to look into this as well. But, no, at present there is not a simplified format for importing patients.

**Comment by KenyanGeek** [comment]
@tangollama thanks again for your prompt response. It would be great to be able to do this as hospitals would want to be able to access historical data and move away from paper completely. So indeed your contribution would go a long way :-)
