### ISSUE TITLE
Users module doesn't work with CouchDB 1.6 

### ISSUE THREAD

**Issue by waleplanet** [HospitalRun/hospitalrun-frontend#1129]
**Expected behavior:**
All functionality of the Users module should work with CouchDB 2.0
**Actual behavior:**
1, When a logged in user with couchdb admin rights navigates to the users module, they are redirected to login.
2 , Unable to add A new user through the add user form
**Steps to reproduce:**
Setup HospitalRun to use CouchDB 1.6
Navigate to the Users module
**Screenshots (if applicable):**
N/A
**OS and Browser:**
all

**Comment by tangollama** [comment]
@waleplanet I'm confused by this issue. Are you saying that the system doesn't fully support CouchDB 2.0? If so, we've already documented that in the [installation instructions](https://github.com/HospitalRun/hospitalrun-frontend#installation). Please clarify.

**Comment by fooksupachai** [comment]
what version of erlang are you running? Ensure it is supported
erl -noshell -eval 'io:put_chars(erlang:system_info(otp_release)).' -s erlang halt
## are the erlang crypto (SSL) libraries working?
erl -noshell -eval 'case application:load(crypto) of ok -> io:put_chars("yay_crypto\n") ; _ -> exit(no_crypto) end.' -s init stop

**Comment by noxecane** [comment]
This is actually a reference to #953 with couchdb 1.6.1
