### ISSUE TITLE
Log out button (UX issue)

### ISSUE THREAD

**Issue by tchan** [HospitalRun/hospitalrun-frontend#1134]
While playing around with the dropdown selector for the language selector. I kept accidentally click the logout button. You can select it even though if you are not directly hovering over the text (pic below) which makes for an unideal user experience.
![](https://puu.sh/wQQwv.png)

**Comment by dmcfaddengalway** [comment]
How can i get this issue assigned to me so I may work on it? Please let me know.

**Comment by tchan** [comment]
@dmcfaddengalway Hi Daniel, I've already fixed this issue in the commit that I have referenced above, just by doing some simple styling which has not been reviewed. 

If you can think of a better way to do it, then by all means submit another pull request to get your first contribution on this project :)

**Comment by dmcfaddengalway** [comment]
@tchan Hi yes I just saw your PR after I commented, so sorry! Looking forward to contributing in other ways!

**Comment by tangollama** [comment]
Hopefully, this will be addressed soon when we roll in #1135
