### ISSUE TITLE
Missing "Type" field from both Lab Pricing and Image Pricing Screens.

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#1139]
**Expected behavior:**  All Pricing Screens under Billing should have a place to set the "Type".

**Actual behavior:**  Lab and Imaging do Not have the Type field appearing on the Add or Edit functions, but the lists have a column for Type.  In comparison both Procedure and Ward Pricing do have the Type field on their Add/Edit screens.

Here is a screen shot of Imaging Pricing screen w/o Type
[OWH Image Pricing Screen wo Type.pdf](https://github.com/HospitalRun/hospitalrun-frontend/files/1180600/OWH.Image.Pricing.Screen.wo.Type.pdf)

Here is the Imaging Pricing List showing Type as a Column
[OWH Image Pricing List showing Type column.pdf](https://github.com/HospitalRun/hospitalrun-frontend/files/1180602/OWH.Image.Pricing.List.showing.Type.column.pdf)

Here is a screen shot of Procedure Pricing screen with Type
[OWH Procedure Pricing Screen w Type.pdf](https://github.com/HospitalRun/hospitalrun-frontend/files/1180601/OWH.Procedure.Pricing.Screen.w.Type.pdf)

**OS and Browser:**  Chrome and Firefox, running Docker Server on Ubuntu

**Comment by KenyanGeek** [comment]
@garylm experiencing same issue. 'Type" used to be there but seems to have disappeared and hence not possible to add "billable" Lab or Imaging charges on the invoice. @jkleinsc any reason where this was deprecated?

**Comment by tangollama** [comment]
@garylm I'm looking into this now.

**Comment by tangollama** [comment]
@garylm @KenyanGeek this was an intentional decision in the system to limit the type field for Lab and Imaging prices (see: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/pricing/edit/controller.js line 102). Can you articulate a reason why we should make this change? If so, it's a pretty easy change and PR.

**Comment by KenyanGeek** [comment]
Hi @tangollama thanks for your response. In the case of a Hospital with an extensive list of procedures it would be useful to be able to pre-input these procedures from a csv. Because otherwise the end user is confused on how this works and how it connects to the billing at the end. I hope that makes sense?

**Comment by tangollama** [comment]
@KenyanGeek I'm confused by your response. What do lists of Procedures have to do with a type field being present on Imaging and Lab Prices?

**Comment by KenyanGeek** [comment]
Hi @tangollama I meant lab and imaging modules have no where to edit for the "Type" field in the billing module. Procedures and wards on the other hand work perfectly as they have this feature. The lack thereof seems to affect their appearing in the frontend.

**Comment by jkleinsc** [comment]
#877 was the reason these were changed to not be editable.  The backstory is that the reason they are not there is that they do not do anything for labs or imaging.  The bigger question here is what would you expect types to do in the system for labs and imaging?  This is clearly an enhancement, and I would like clarification on what you are looking for.

**Comment by KenyanGeek** [comment]
Hi @jkleinsc maybe i am asking the wrong question. Let me try illustrate with screenshots.
I was expecting that when i add a new imaging or lab pricing item in the billing section as such
![capture1](https://user-images.githubusercontent.com/29902073/29005338-efbc5b4e-7ae1-11e7-8830-4934e031e2b7.JPG)


i can be able to access it from the imaging/lab type dropdown auto suggest when i am making a new imaging/lab request as such

![capture 2](https://user-images.githubusercontent.com/29902073/29005341-f4436dc4-7ae1-11e7-93b7-1b2cf8adcf98.JPG)

At present the lab/imaging item does not appear and hence adding labs/imaging items is of no use in the billing section.

The workaround i have been using is to do it one by one from the frontend as such.

![capture3](https://user-images.githubusercontent.com/29902073/29005394-66423df0-7ae3-11e7-80ac-dff925293d93.JPG)

 When i do that i get the labs/imaging in the autosuggest as such
![capture-6](https://user-images.githubusercontent.com/29902073/29005398-72584346-7ae3-11e7-9689-4dde059aaef8.JPG)


 and in the billing section as such


![capture-4](https://user-images.githubusercontent.com/29902073/29005397-6e198268-7ae3-11e7-8126-a4053795dead.JPG)

For a facility with many imaging/lab items and who would like these to be preconfigured it would be useful to do this from the billing section or even better from the look up list. 

Hope this tome makes sense :-)

**Comment by jkleinsc** [comment]
@KenyanGeek you should be seeing the items you add under pricing in the auto suggest box.  Maybe it is a caching issue.  What happens when you close the browser and reopen?  Do you then see the items you added under pricing?

**Comment by KenyanGeek** [comment]
@jkleinsc you are right it might be a caching issue. When i compare my running server with the desktop app, the latter lab works fine but server verson doesn't. Would i be missing something?

**Comment by NuttasitBoonwat** [comment]
I'm confused by your response. What do lists of Procedures have to do with a type field?
