### ISSUE TITLE
Refinement: Custom Forms - Header/Sub-header object

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#1140]
It is awkward to create sub-section headers on Custom Forms as there is no such object choice.  There needs to be a form object that is description only with no associated data input field.

My current solution to use Check Box objects as shown below:

[OWH Custom Form Sub Headers.pdf](https://github.com/HospitalRun/hospitalrun-frontend/files/1195111/OWH.Custom.Form.Sub.Headers.pdf)

The result obviously is cluttered with meaningless check boxes.

**Comment by tangollama** [comment]
@garylm this is a great enhancement request. Categorizing now. I'll tweet about it :)

**Comment by galantlex** [comment]
Hi @tangollama, I'm a first-time contributor to open source who's been lurking here for a while, and I'd love to see if I can tackle this issue!

**Comment by tangollama** [comment]
Lexi, awesome blossom! Please have it. I'll mark this as in progress. Feel free to reach out directly to Gary (who submitted the issue) to talk about use case / requirements issues / questions.

**Comment by garylm** [comment]
Some thoughts on approach to Headers
- As user customizable as possible.
- Two parts:  
          - Header Description/Name as a user entered Text String.
          - Header "Line" as a user entered Text String - allows the user to chose like "-----", "____", " - - - ", etc.
- This header object should be implemented as another Type drop down choice when "Add Field" is chosen on a Custom Form.

**Comment by galantlex** [comment]
👋 Hello, I'm sorry to say that I have actually been much busier than expected recently, so I haven't actually gotten the chance to look into this. Just wanted to check in and release it back up for grabs, in case anyone else wants to tackle it.

**Comment by tangollama** [comment]
Thx for letting us know @galantlex. Here's hoping your schedule frees up more going forward.

**Comment by darrylpargeter** [comment]
Hey, @tangollama,
Is this issue still up for grabs? As if it is would like to give it ago.

**Comment by tangollama** [comment]
@darrylpargeter yes. Have at it.
