### ISSUE TITLE
Enhancement : Provision to include blood group sub-type in Add new patient form

### ISSUE THREAD

**Issue by sskavitha** [HospitalRun/hospitalrun-frontend#1143]
**Expected behavior:** It would be nice to have provision to add sub blood groups like A1+ve, A2 +ve into patients information . Adding sub list into the existing blood-group list would make list lengthy and non-user friendly.
Rather than existing list box can be changed into editable list box which will solve it.
**Actual behavior:**
Blood type list box having 8 main category of blood groups.
**Steps to reproduce:**
New patients form -> Blood type list box
**Screenshots (if applicable):**
attached
![bloodgroups](https://user-images.githubusercontent.com/31200668/29509769-f8e9df8e-8676-11e7-8625-97ce8a04d48d.png)

**OS and Browser:**
All

**Comment by imalexsq** [comment]
What if we keep the 8 main categories, but add an "Other" option at the bottom of the list that creates a field underneat the user can write in additional sub-groups?

**Comment by tangollama** [comment]
@sskavitha @imalexsq, if the blood types is incomplete, the best idea would be to adjust the hospitalrun/mixins/blood-types mixin. That would be a good PR.

**Comment by imalexsq** [comment]
I'll work on it

**Comment by sskavitha** [comment]
@imalexsq @tangollama Thanks for taking this up! I am happy to contribute to a very active forum.

Blood group is categorized as 8 main types which are already listed, works fine. But the provision is not there to add sub types of blood groups. 

Number and types of blood group (main and sub type) is very generic across the world, adding 'other' option will be the workout for input fields like 'Education qualification', 'job profile' which would vary based on locality.

As per reference, there are 20 different known subgroups in medical science, adding those sub groups along with main groups will be a good idea with little bit compromising of user experience. Because we have to list all 8 + 20 categories in the same list where the list would be lengthy. 

Here my suggestions are
#1  we can make list box as editable list box where if a user knows his blood sub type can be entered by his own.
#2  Adding all 20 sub types in the list and make the list box as 'Searchable text box along with list ' where a user can search in the box by typing and get his value quickly from the list.

Below is my reference links for blood group and sub category of blood group:
http://www.redcrossblood.org/learn-about-blood/blood-types.html
http://www.sankalpindia.net/subtypes-blood-group

**Comment by tangollama** [comment]
@sskavitha thanks for the detail. I'll review and circle back with a response in the next day or two.

**Comment by imalexsq** [comment]
@tangollama 
Here is a list I compiled with help from @sskavitha . If this works, I'll make a commit.
```
'A+',
'A1+ (A1 +ve)',
'A-',
'A1- (A1 −ve)',
'A1B+ (A1B +ve)',
'A1B- (A1B −ve)',
'AB+',
'AB1+ (AB1 +ve)',
'AB1- (AB1 -ve)',
'AB-',
'A2+ (A2 +ve)',
'A2- (A2 −ve)',
'A2B+ (A2B +ve)',
'A2B- (A2B −ve)',
'AB2+ (AB2 +ve)',
'AB2- (AB1 +ve)',
'B+',
'B+ (B +ve)',
'B-',
'B- (B −ve)',
'B1+ (B1 +ve)',
'O+',
'O+ (O +ve)',
'O- (O −ve)',
'O-'
```

**Comment by JosephPB** [comment]
It would seem that the list provided @imalexsq contains 25 items, whereas @sskavitha was talking about needing 20+8, are there some missing or is that list correct?

Additionally, Alex's list seems to add all of the other known sub types into one big list. If I am not mistaken the current drop down list is incorrectly labeled anyway. A, B, AB and O are the blood types, where as what is listed in the current list of 8 are a selection of the most common sub types.

My proposal:
Have one list for blood type (i.e.: A, B, AB, O)
Have a second list for blood sub type who's elements are decided upon by the user input into the first (i.e. if the user selects A as the blood type then the drop down list for sub type contains the relevant sub types of type A or the user to select from)

Would this satisfy the requirements?

**Comment by imalexsq** [comment]
@JosephPB: in an email @sskavithatold me the order of this list works. Instead of complicating the UI with additional drop-downs, how about we use a single drop-down with a search/autocomplete so users don't have to look through the whole list?

**Comment by JosephPB** [comment]
Thanks for clarifying @imalexsq, just wanted to double check.

I think it would potentially be a neater solution, however, the search/autocomplete would essentially just be giving you the same extra drop down menu customised to what the user typed. Was just thinking for easy of use (and ease of code editing in the future), so as to make it clear sub type was required in the field, a second list would make it more obvious. 

Might be good to see it in action though.

**Comment by imalexsq** [comment]
I'll work on the search/autocomplete with extended list of blood types over the weekend.
