### ISSUE TITLE
payment profile not loaded in windows 64 bit OS

### ISSUE THREAD

**Issue by sskavitha** [HospitalRun/hospitalrun-frontend#1144]
**Expected behavior:**
Payment profile is not loaded for me. I am using windows 64 bit OS installation exe file for installation.
**Actual behavior:**
Payment profile should list mode of payments.
**Steps to reproduce:**
Add new patients form
**Screenshots (if applicable):**
 Attached
**OS and Browser:**
Windows OS, stand alone exe
![payment](https://user-images.githubusercontent.com/31200668/29510447-66eb4bc4-8679-11e7-8bf0-1b8c5353d1cc.png)

**Comment by imalexsq** [comment]
Hi @sskavitha 
I cannot reproduce the bug. I started with brand new installation, added a test Price Profile, under Billing. Then went to Patients > New Patient and the test Payment Profile shows up.

**Comment by KenyanGeek** [comment]
Yes as @imalexsq states you have to add a pricing profile in the billing section to be able to access them.

**Comment by sskavitha** [comment]
Thanks @imalexsq @KenyanGeek ! After adding pricing profile able to see an entry there.

**Comment by sskavitha** [comment]
The product is working as expected, hence I am closing this issue.
