### ISSUE TITLE
Add contact form clearance issue

### ISSUE THREAD

**Issue by sskavitha** [HospitalRun/hospitalrun-frontend#1145]
**Expected behavior:**
After clicking add contact button under the new patient tab, a window is popped with the prepopulated value which is entered for the previous patient.
**Actual behavior:**
Form clearance should be done
**Steps to reproduce:**
- fill 'Add contact' window details under new patient
- click 'Add' in the window
- and then click 'Add' in the new patient form
- add another new patient, click add contact button, which has the previous patient values
**Screenshots (if applicable):**
N/A
**OS and Browser:**
All

**Comment by tchan** [comment]
I'll take a look at this in a second.
