### ISSUE TITLE
Total number of patients under Report should be in 'Int'

### ISSUE THREAD

**Issue by sskavitha** [HospitalRun/hospitalrun-frontend#1146]
**Expected behavior:**
Total number of patients under Report should be in 'Int'
**Actual behavior:**
The total number of patients under Report is in the decimal point.
**Steps to reproduce:**
- add new patients
- select ' Total Patient days' in Report type under Report section
- Displayed value should be in the 
![numberofpatients](https://user-images.githubusercontent.com/31200668/29651460-80590af0-88be-11e7-83aa-c9ed3c6526a1.png)
whole number
**Screenshots (if applicable):**

**OS and Browser:**

**Comment by imalexsq** [comment]
@sskavitha Yes, you're correct. I can reproduce this bug

**Comment by SiddharthaSarma** [comment]
@tangollama @imalexsq 
I would like to contribute something to Hospital run by taking up this issue.
Please let me know can I take up this issue or not?

**Comment by tchan** [comment]
@SiddharthaSarma no problem :)
Be sure to read the [contributing guide](https://github.com/hospitalrun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md) and request an invite to join the [slack channel](https://hospitalrun-slackin.herokuapp.com/) if you haven't already.

**Comment by SiddharthaSarma** [comment]
Sure thanks, @tchan :)
