### ISSUE TITLE
issue : Report generation in future date

### ISSUE THREAD

**Issue by sskavitha** [HospitalRun/hospitalrun-frontend#1147]
**Expected behavior:**
Reports can be generated from the past to current date.
**Actual behavior:**
Validation not done in report generation date field which allowing future date for report generation
**Steps to reproduce:**
- under Report generation section, select the future date in the date field.
![futuredate](https://user-images.githubusercontent.com/31200668/29651724-bf9c61ca-88bf-11e7-932e-5131b5671927.png)

**Screenshots (if applicable):**
Attached. Please find the attachment.
**OS and Browser:**
N/A

**Comment by tchan** [comment]
Seems to be an easy fix, I'll take a look at it in a second.

**Comment by EvanSays** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by tchan** [comment]
@EvanSays sorry to steal your thunder EvanSays, I've already submitted a pull request that addresses this issue in the post above yours.

Please join the slack channel https://hospitalrun-slackin.herokuapp.com/ if you haven't already if you have any other  questions :)
