### ISSUE TITLE
Add analytics

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#115]
It may be too early to think much about this, but something that will be really helpful for improving how people use the app is installing some analytics to see what pages and routes users are using most, and gain UX insights from. The Atom team uses Google Analytics and a [custom package](https://github.com/atom/metrics) for this, which also has the benefit of providing aggregate stats about how many total users there are for the app, and what their activity on a weekly/monthly basis is like.

**Comment by tangollama** [comment]
It would be good to analyze this as well as what we might be able to do instrumenting with New Relic.

**Comment by Lewiscowles1986** [comment]
What metrics are you looking to monitor, or facilitate is probably the best way to approach "analytics", if it's page / resource access, etc, a standard ga with user-id or username works fine for my business apps, we literally have this in our footer.

```html
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', '{{ ga.account_id }}', {'siteSpeedSampleRate': 50});
	ga('set', '&uid', '{{ user.id }}'); 
	ga('send', 'pageview');
</script>
```

It allows us to get live user data, and use google analytics dashboard to show us where users are clicking, their usage, their flow through the app, but our app is heavily PHP, and less JS, so I'm not sure how in-line with your aspirations, or work-flow this is. Were you thinking of something more substantive?

The main benefit to us over newrelic, are

 * ga is free
 * until our product is proven this seems to be adequate for our needs
 * distributes analytics as non-critical, offloaded to client-side, leaving more server-time for more users, and leaner costs
 * NewRelic can be a bit overwhelming with it's alerts, it's level of detail and in our tests it's drain on the server from constant polling

**Comment by jglovier** [comment]
> if it's page / resource access, etc, a standard ga with user-id or username works fine for my business apps, we literally have this in our footer.

Yeah, I think that's sufficient for now. Eventually I'd like to add some event tracking for things like which buttons or nav links get clicked within the app, etc. But just getting basic GA setup in the app by default would be rad. :metal:

**Comment by Lewiscowles1986** [comment]
cool, I'll get on it, it will track interactions such as clicks by default unless you use event.preventDefault() on the links and buttons :wink:

**Comment by Lewiscowles1986** [comment]
Patch is WIP over at https://github.com/Lewiscowles1986/hospitalrun-frontend/tree/patch-1

I'll test ASAP, but it follows ember docs, so it should work. On the testing side, I have no clue how to test that...

**Comment by jglovier** [comment]
@Lewiscowles1986 :metal:

![picard-slow-clap](https://cloud.githubusercontent.com/assets/1319791/11008842/1dad2e04-84a1-11e5-82b0-caae4b3983c0.gif)

**Comment by Lewiscowles1986** [comment]
I don't know what that means lol, you guys should try to get to MozFest in 2016 btw, people would be all over this project; as soon as I have tested the analytics I'll submit a PR :wink: 

Should I leave in my placeholder analytics code (there is not a security risk), or build some form of management setting where users can set it?

**Comment by jglovier** [comment]
>I don't know what that means lol

Hah, sorry, it means I'm applauding your effort, and excited to see this happening.

>Should I leave in my placeholder analytics code (there is not a security risk), or build some form of management setting where users can set it?

So honestly, I don't think this is something we want to give users control to modify. This is primarily for our purposes in building the project. Having this data about how people are using the software is primarily for our purposes in building it, not for the individual instances where hospitals are using the software. Does that makes sesnse?

**Comment by Lewiscowles1986** [comment]
right, I'll try to test it in the week, going to mozfest2015 tomorrow, but it will be done soon, and in the mean time, if you, or anyone else has time right now, feel free to leave issues on the fork, I'll get any of those squared away; there is only one bit to copy-paste over and that would be using the site url's UA-XXXX-XX number over the existing one :wink:

**Comment by Lewiscowles1986** [comment]
Update: This won't run on Node 5... Do you have a vagrant machine or list of dependencies (non-js), so that I can setup a testing environment, as I'd like to square this one away

**Comment by jglovier** [comment]
bump @jkleinsc @tangollama :point_up_2:

**Comment by jkleinsc** [comment]
@Lewiscowles1986 we are using Ember CLI which is currently shows this message if you are using a version of node other than 0.12:
"Future versions of Ember CLI will not support v4.1.0. Please update to Node 0.12
 or io.js."
I have been using node 0.12 and node 4 without problems, though Ember cli does throw a warning with node 4 but it seems to work fine.  Other than that I don't think there are any specific dependencies.  We have successfully tested against CouchDB 1.5.x and 1.6.x.

**Comment by Lewiscowles1986** [comment]
I'll keep on meddlin, but when I'm done, I think I'll PR a vagrant box for others too...

**Comment by Lewiscowles1986** [comment]
**Update:**, I have a vagrant that deploys, so now I can test hospitalrun offline (it pretends to be hospitalrun beta using vagrant hostsupdater for now) 

The edit has not worked yet, it looks like the docs are missing something

**Comment by jkleinsc** [comment]
@Lewiscowles1986 Just to verify have you run the following steps:
1. Install [ember-cli v1.13.8](https://www.npmjs.org/package/ember-cli): `npm install -g ember-cli@1.13.8`
2. Install [bower](https://www.npmjs.org/package/bower): `npm install -g bower`
3. `npm install` and `bower install`to install needed node modules and bower modules.
4. Install  [couchdb](http://couchdb.apache.org/) including running the `initcouch.sh` script
5. Copy the server/config-example.js to server/config.js.
6. Start the server so you can view the repo in your browser by running `ember serve` from the `frontend` directory.
7. Go to `http://0.0.0.0:4200/` in a browser and login with username `hradmin` and password `test`.

Does login work?  And when you say edit has not worked yet, what edit are you talking about?

**Comment by Lewiscowles1986** [comment]
Hi @jkleinsc,

I meant the analytics is not registering any hits with my analytics account. I managed to build a working vagrant yesterday. Turns out I was running ubuntu scripts inside a debian jessie... my bad.

The app works 'ish and lets me login, but there are several things it won't let me do, which I have been troubleshooting by adding domains to `config/environment.js`

Strange things happen if I run ember for the hostname I have setup (it won't let me connect, not sure why)

**Comment by jkleinsc** [comment]
If you want to change the hostname, you have to also change it in server/config.js  By default config.server is set to localhost.  Change it to the hostname you need

```javascript
var config = {    
    couch_db_server: 'localhost',
    couch_db_port: '5984',
    couch_db_use_ssl: false,
    couch_db_changes_since: 'now',
    couch_admin_user: 'couchadmin',
    couch_admin_password: 'test',
    google_client_id: 'FOR GOOGLE SSO; GOOGLE CLIENT ID GOES HERE',
    google_client_secret: 'FOR GOOGLE SSO; GOOGLE CLIENT SECRET GOES HERE',
    server_port: '3000', <---- CHANGE PORT NUMBER IF NEEDED
    server: 'localhost', <---- PUT YOUR HOSTNAME HERE
    use_ssl: false        
};
```

**Comment by Lewiscowles1986** [comment]
I shall try that in a moment :wink: :+1:

**Comment by cd2-public** [comment]
:cry: doesn't help me even from new...

```
vagrant@beta:~/hospitalrun-frontend$ ember serve
version: 1.13.8
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/

Build successful - 17291ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
ConcatWithMaps                                | 6499ms
ES6: App Tree                                 | 3216ms
TemplateCompiler                              | 1194ms
BrocText                                      | 908ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
ConcatWithMaps (4)                            | 7101ms (1775 ms)
ES6: App Tree (1)                             | 3216ms
TemplateCompiler (3)                          | 1387ms (462 ms)
Babel (13)                                    | 1122ms (86 ms)
BrocText (1)                                  | 908ms

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
vagrant@beta:~/hospitalrun-frontend$
```

**Comment by cd2-public** [comment]
![image](https://cloud.githubusercontent.com/assets/15682597/11122500/64756098-8953-11e5-8883-e8fdc6fa9861.png)

**Comment by cd2-public** [comment]
I think I'll ditch the domain name for now, one thing at a time and all that...

**Comment by Lewiscowles1986** [comment]
also tried with `--host beta.hospitalrun.io` switch

(vagrant is set to pretend to be beta.hospitalrun.io)

**Comment by jkleinsc** [comment]
@cd2-public That error you are seeing occurs when couchdb isn't running.  Can you verify that couchdb is running?

**Comment by cd2-public** [comment]
so it's stopped crashing now I set the couch-db server back to localhost, but still if I supply a host name it does not accept connections and we get a console error every few seconds

**Comment by Lewiscowles1986** [comment]
Currently stuck on this, learning a little more about ember.js so I can provide a useful mid to long-term solution

**Comment by Lewiscowles1986** [comment]
over at http://jsfiddle.net/LewisCowles1986/c3ze1178/ I have working analytics code in Ember, but I am worried it uses an incompatible version of ember... will test soon, sorry guys, been busy

**Comment by jglovier** [comment]
@Lewiscowles1986 thanks for the update! 

Have you checked out how the Atom team is collecting metrics in Atom, and the [package they built](https://github.com/atom/metrics)? Atom isn't an Ember app (but it is node based), but perhaps their metrics package will give you some ideas for getting through where you are stuck.

**Comment by Lewiscowles1986** [comment]
Oh the JSFiddle is an ember app and it's receiving analytics events, I just have to add it to the ember app, it will likely work from copy->paste; I'm testing in about an hour when I'm done with work for the day :wink:

**Comment by tangollama** [comment]
@Lewiscowles1986 I'll look into this issue this week and try to give you some useful feedback. Commenting now just to let you know I'm noticing your requesting input and that I intend to offer it. Thanks.

**Comment by Lewiscowles1986** [comment]
:+1: The jsfiddle code does not work as a dropin; I have reviewed https://github.com/atom/metrics, but from an abstract maintainability perspective I think it isn't using analytics "the google way". It seems like the nasty way some PHP dev's signal analytics.

**Comment by Lewiscowles1986** [comment]
On the plus side there are no longer code errors :laughing: 

I had to modify `config/environment.js` to get ember-cli's Content Security Policy to do one and let me embed google analytics; I have a problem that the problem is where I am adding to app

```js
App.Router = Ember.Router.extend({
  didTransition: function() {
    this._super(...arguments);
    console.log(this.get('url')); // just for debugging
    return ga('send', 'pageview', {
      'page': this.get('url'),
      'title': this.get('url')
    });
  }
});
```

**Comment by Lewiscowles1986** [comment]
got it working :+1: writing PR now (may need refactoring later, but it works)

**Comment by Lewiscowles1986** [comment]
for next iteration https://github.com/poteto/ember-metrics will probably be used

**Comment by jkleinsc** [comment]
@Lewiscowles1986 it looks like tests aren't passing on the PR.  I suspect if you switch the PR to use ember-metrics the tests should pass.

**Comment by tangollama** [comment]
Set to In Progress, per the new contribution policy. https://github.com/HospitalRun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md

**Comment by jglovier** [comment]
@Lewiscowles1986 is this still being worked on?

**Comment by Lewiscowles1986** [comment]
I Haven't had a chance to try ember-metrics yet, so nothing since the other commit. I'll have a try when I have more time, but if someone else can get it done faster, or more in line with the project they can.

**Comment by tangollama** [comment]
@Lewiscowles1986 it's been a bit on this. Is this still on your radar? Thanks.

**Comment by Lewiscowles1986** [comment]
I couldn't get ember metrics to work :disappointed:

**Comment by Lewiscowles1986** [comment]
any tips on getting username out of hospitalrun?

**Comment by Lewiscowles1986** [comment]
I've cleaned up a bit, you can find code over at [my clone](https://github.com/Lewiscowles1986/hospitalrun-frontend/tree/patch-1)

As I say it's not a real improvement on the last attempt which is why I haven't posted any updates, things that need work are

 * Tests fail (this happens before any changes and is likely inexperience of couchdb)
 * Needs new tests for metrics
 * Needs username
 * Environment tweaks might need some love

**Comment by Lewiscowles1986** [comment]
@jglovier @tangollama I'd appreciate some feedback on the linked branch before continuing

**Comment by jglovier** [comment]
@Lewiscowles1986 sorry for the delayed response! I know both @tangollama and I have been swamped with non-HR work the last couple weeks. Can you please open a pull request to this repo for review?

**Comment by stukalin** [comment]
I've created a draft of analytics feature with GA. Please, have a look at the PR, @tangollama, @jglovier. We can think of a proper analytics strategy right there or just leave it as it is and turn back to that once we feel the real need of it. Anyways we'd need the GA ID.
