### ISSUE TITLE
Resolve npm warning for crypto

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1155]
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated crypto@1.0.0: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by AlokDebnath** [comment]
@tangollama What is the status of this issue? Is it being addressed?
Also, the last commit made about this issue, does it provide a complete solution?

**Comment by tangollama** [comment]
I believe this PR addresses it: https://github.com/HospitalRun/hospitalrun-frontend/pull/1230. I haven't had a chance to merge it yet.
