### ISSUE TITLE
Moving away from bower?

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1156]
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path, but please help to create it: https://github.com/bower/bower/issues/2467

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by DerekTBrown** [comment]
Probably should consider moving to yarn instead.  Working on a PR.

**Comment by stukalin** [comment]
Why `yarn` und not simply `npm`? It has package.lock now etc.

**Comment by DerekTBrown** [comment]
@stukalin I think you may be right.  Per your suggestion in the PR, I am going to try to break this up into smaller pieces.  Working on a PR which just moves everything into NPM.

**Comment by DerekTBrown** [comment]
In order to facilitate this, we are going to need to add a `package.json` file into the hospitalrun-maintained fork of `JsBarcode`. Opening a new PR.

**Comment by stukalin** [comment]
Could be useful. Things which are to be migrated 
- [ ] JsBarcode
- [ ] bootstrap 
- [ ] filer.js
- [ ] idb.filesystem
- [ ] octicons
- [ ] pikaday
- [ ] typeahead.js
- [ ] pouchdb-load
- [ ] pretender 
- [ ] fullcalendar 
- [ ] fullcalendar-scheduler
- [ ] timekeeper
- [ ] webrtc-adapter

**Comment by donaldwasserman** [comment]
I'll just close this one.
