### ISSUE TITLE
move to uuid module

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1157]
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by nzidol** [comment]
Based on upstream dependencies probably requires update of:
- ember-cli (2.15.1 is latest stable) with related updates....
    "ember-cli-babel": "^6.3.0",
    "ember-cli-eslint": "^4.0.0",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-qunit": "^4.0.0",
    "ember-data": "~2.15.0",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "loader.js": "^4.2.3"
- ember-electron (2.6.0 is latest version).
- package "follow" (1.0.0) used in "hospitalrun-dblisteners" for which there is a greenkeeper PR....
- and related updates in bower.json
    "ember-cli-shims": "^1.1.0",
    "ember": "~2.15.0",

**Comment by tangollama** [comment]
@nzidol thanks for the detailed eval. Makes the update process more clear for a potential contributor.

**Comment by MatthewDorner** [comment]
Due to updates since @nzidol's writeup, the only place I still see node-uuid is:
hospitalrun-dblisteners@1.0.0-beta > follow@0.12.1 > request@2.55.0 > node-uuid@1.4.8.

But the current version of follow still uses request@2.55.0. There is a [PR to update this since Dec.](https://github.com/jhs/follow/pull/1)

**Comment by stukalin** [comment]
The PR in `follow` has been merged. Time to update other dependencies

**Comment by nzidol** [comment]
Looks like the updated hospitalrun-dblisteners has not yet been published to npmjs.com, may need to assign new version number? (1.0.0-beta2?)
Updating package.json with "hospitalrun-dblisteners": "https://github.com/HospitalRun/hospitalrun-dblisteners.git" resolves this issue but is probably not preferred solution....

**Comment by nzidol** [comment]
Also added this one to dblistners [issues](https://github.com/HospitalRun/hospitalrun-dblisteners/issues/8) 
`warning hospitalrun-dblisteners > snyk > proxy-agent > socks-proxy-agent > socks@1.1.10: If using 2.x branc, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0`
