### ISSUE TITLE
move from stylelint-rule-tester@0.6.2 to stylelint-test-rule-tape

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1158]
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated stylelint-rule-tester@0.6.2: Use stylelint-test-rule-tape instead

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by stukalin** [comment]
I've submitted a new PR to the dependency: https://github.com/sh-waqar/stylelint-declaration-use-variable/pull/23.
If the author is still there we'd get our fix soon.
