### ISSUE TITLE
Create new number component

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#116]
Right now our number validation allows for numbering like 123,456 but codewise we are expecting numbers without commas.  We should create a component that will let people enter a number with commas but will save the value without commas.

Either that or we need to change how validation works to eliminate commas but that is not as friendly

## TODO
- [ ] Create number component

**Comment by jkleinsc** [comment]
@zinyando is looking into this one.

**Comment by tangollama** [comment]
Question to @zinyando, where did you get with this?

cc: @jkleinsc

**Comment by zinyando** [comment]
@tangollama I got a little busy but I will take another stab at it tomorrow. Will post the link to the PR when its ready in a day or 2 cc @jkleinsc

**Comment by tangollama** [comment]
Great. Thank you. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by zinyando** [comment]
@jkleinsc is this issue still valid? Validation seems to not accept commas in numbers anymore.

**Comment by jkleinsc** [comment]
@zinyando you are correct in that validation doesn't allow commas.  For usability purpose, I still think we should create a component that will let people enter a number with commas but will save the value without commas.

**Comment by tompaana** [comment]
Note that depending on the localization a comma is considered a decimal point.

**Comment by tangollama** [comment]
@zinyando are you thinking about working this?
