### ISSUE TITLE
update minimatch

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1160]
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by Divya063** [comment]
@tangollama I would like to work on this

**Comment by tangollama** [comment]
@Divya063, we'd love to have you contribute, but it looks like this PR (https://github.com/HospitalRun/hospitalrun-frontend/pull/1186) addresses this.
