### ISSUE TITLE
update fs-promise

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1161]
@jkleinsc feel free to set to Help Wanted

**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by stukalin** [comment]
This can be closed now @tangollama @jkleinsc
