### ISSUE TITLE
move transformers to jstransformers

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1162]
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by Rabinzon** [comment]
I gonna help with it

**Comment by tangollama** [comment]
Thx @Rabinzon

**Comment by abc985** [comment]
Why do not you need the NPM time warnings?

**Comment by MatthewDorner** [comment]
This may be fixed if #1159 is fixed, since transformers is only required by jade:
 `├─┬ electron-prebuilt-compile@1.8.4
│ ├─┬ electron-compilers@5.9.0
│ │ ├─┬ jade@1.11.0
│ │ │ ├─┬ transformers@2.1.0`
