### ISSUE TITLE
replace wrench with fs-extra

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#1163]
**Expected behavior:**
npm install with no warning

**Actual behavior:**
npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

**Steps to reproduce:**
checkout the project
navigate to the frontend directory
npm install

**Screenshots (if applicable):**
N/A

**OS and Browser:**

**Comment by zzbazinga** [comment]
I checked fs-extra and got this: http://jprichardson.github.io/node-fs-extra/
Then I use npm install --save fs-extra
So I got this:
![image](https://user-images.githubusercontent.com/29006655/29993420-3552d5be-8fd4-11e7-9c6d-0744c19be146.png)
Before that I only use npm install and got this result:
![image](https://user-images.githubusercontent.com/29006655/29993432-77b7b79e-8fd4-11e7-854a-c79a9e7ebf3a.png)

**Comment by zzbazinga** [comment]
I think problem is solve if we use npm install --save fs-extra

**Comment by nzidol** [comment]
According to yarn.lock wrench is required by flatten-packages@^0.1.4 which is required by electron-windows-store@^0.9.3 which is required by electron-forge@2.9.0 which is required by ember-electron@2.1.0 which is in our package.json file. So probably needs to be resolved upstream, looks like they have not done so yet... https://github.com/felixrieseberg/electron-windows-store/blob/master/package.json

**Comment by efx** [comment]
To nzidol's point, this is a sub-sub module dependency that we'll need to resolve by bumping electron-forge it seems:
```sh
$ npm ls -a wrench
hospitalrun@1.0.0-beta /hospitalrun-frontend
└─┬ electron-forge@5.1.1
  └─┬ electron-windows-store@0.12.0
    └─┬ flatten-packages@0.1.4
      └── wrench@1.5.9 
```
