### ISSUE TITLE
Cannot View Any Custom Form Data

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#1166]
We have created a number of Custom Forms to attach or use with Patients, Labs, etc. We have multiple Lab Custom Forms for more detailed, test focused data.  Also there is an expectation that the "always include" flag on a custom form would cause the form flow with the standard form it is attached to.

**Actual behavior:**

No custom form can be viewed after being saved.  We have been unable to find a way to view any custom form after completed.  

Patients:  Created a custom form for more extensive patient history detail.  We can complete the form when adding the patient.  But there is no way to later view the custom form when looking at patient screens.
 
Labs: A good example is using a custom form to log more specific result details of a blood test.  The lab tech can use a custom form and save it.  Once the lab is completed, there is no way to go back into the lab & thus no way to return to the saved custom form data.

-- Fundamentally, the problem seems to be that there is no provision for viewing any custom form attachment.

**Steps to reproduce:**

Just create and use a custom form.

**Comment by NuttasitBoonwat** [comment]
https://forums.adobe.com/thread/305250

**Comment by garylm** [comment]
Does this imply the need to change All standard forms and reports throughout the HR+ package?  
   - Every view of a standard form with a custom form attached needs to be changed to show the custom form data.
          - Ex: When viewing the Patient / Imaging history or Patient / Lab history
   - Every report needs to change to also show any associated custom form data.  

It appears to be a large task.

**Comment by tangollama** [comment]
@garylm the changes that @stukalin implemented should resolve this issue. Please verify and close this issue if so.

**Comment by stukalin** [comment]
At least some of them;)
