### ISSUE TITLE
Mac standalone client is not signed with an Apple Developer ID

### ISSUE THREAD

**Issue by justlurking** [HospitalRun/hospitalrun-frontend#1191]
**Expected behavior:**
Software should run on macOS devices using default macOS security configuration and without requiring the user to weaken their security posture.
**Actual behavior:**
Software does not run without disabling Gatekeeper, one of the primary methods for preventing malware on macOS.
**Steps to reproduce:**
Download the Mac client from http://hospitalrun.io/tryit/ and try to launch it. Macs with default 'Gatekeeper' settings will refuse to install due to the lack of an [Apple Developer ID](https://developer.apple.com/developer-id/).

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/11887492/30241408-756d3526-9548-11e7-9056-a7fc96516103.png)

**OS and Browser:**
macOS Sierra (10.12.6) and Chrome 60 (stable channel)

**Comment by NuttasitBoonwat** [comment]
first got to  System Preferences -> Security & Privacy press the key button from the bottom left corner and input the passcode to unlock  it's will show Gatekeeper's setting that'll show chisel level application from 2 level is

accept application from Mac App Store only
accept application from Mac App Store and assure developer 

I reccommend you to chooes 2 choice permanently for safety  ,for sure it mabe complicated  to open application in first without register

**Comment by justlurking** [comment]
Hi there, I'm familiar with macOS Gatekeeper and what I would need to get it to run. The reason I opened the issue is that a user shouldn't have to modify their Gatekeeper settings in order to get the software to run out-of-the-box. 

While I realize HospitalRun is in beta, getting a developer ID and signing your software isn't particularly hard, and it increases trust. For software that deals with sensitive health information it should be expected, IMHO.

Just in case this is a bug, I am attaching some additional diagnostic information:

`
~/Downloads ❯❯❯ codesign --verify --deep --strict --verbose=2 /Applications/HospitalRun.app/
/Applications/HospitalRun.app/: code object is not signed at all
In architecture: x86_64
`

`
~/Downloads ❯❯❯ spctl -a -t exec -vv /Applications/HospitalRun.app/
/Applications/HospitalRun.app/: rejected
source=no usable signature
`

**Comment by tangollama** [comment]
@justlurking thx for the issue. Any chance you're interested in helping to resolve this with the Electron build process?

**Comment by justlurking** [comment]
@tangollama I confess I know very little about this project and nothing about the build process (I downloaded the software out of curiosity based on an interesting blog post to investigate further), but I'm willing to poke around a bit to see if I can help, if you can point me in the right direction?

**Comment by evalsocket** [comment]
@justlurking you are right. I will try to figure out what we can do 

https://github.com/electron-userland/electron-osx-sign/wiki/1.-Getting-Started

**Comment by zacharyparrish** [comment]
@evalsocket I'm willing to give this a go if this isn't being worked on already

**Comment by tangollama** [comment]
@zacharyparrish @evalsocket work it out between you who is working on this. It'd be great to see it resolved.
