### ISSUE TITLE
First Stable Version 1.0 && kubernetes deploy guide?

### ISSUE THREAD

**Issue by jujes** [HospitalRun/hospitalrun-frontend#1200]
Calendar and Deploy Issue:

Someone know when is release the first stable version?? and some guide to deploy using kubernetes?

Thanks in advance,

**Comment by jkleinsc** [comment]
@jujes that I know of no one has deployed HospitalRun to Kubernetes.  I'm sure it could be done, but we don't have a guide for it.

**Comment by evalsocket** [comment]
@jkleinsc is it useful for community ?  Kubernetes support ?

**Comment by jkleinsc** [comment]
@evalsocket I suppose it could be useful.

**Comment by evalsocket** [comment]
I ask you because docker also have docker-swarm which is similar to Kubernetes.

**Comment by DerekTBrown** [comment]
I am not really sure this is something we need to add.  We already have a Docker image, and so any "guide" that would need to exist would be generic to Kubernetes.  For instance, using [kompose](https://github.com/kubernetes/kompose), one can use the `docker-compose.yml` file we already supply to run HospitalRun on Kubernetes with one command.

I would recommend closing.  @jujes if you find complications, feel free to submit documentation- it would be much appreciated!
