### ISSUE TITLE
New Appointment - For Clinic - End Time

### ISSUE THREAD

**Issue by SaiBabajiAnanda** [HospitalRun/hospitalrun-frontend#1223]
**Expected behavior:**
selected end time (hour and min) should be displayed after selection.
**Actual behavior:**
Selected End time (hour and min) not displayed after selection. 

**Steps to reproduce:**
Go to Scheduling -> Add Appointment 
Select a Patient 
Select Type as Clinic 
Select Date and Start Time
Select End Time (hour and min) 
 
**Screenshots (if applicable):**
![end time b4](https://user-images.githubusercontent.com/29377369/30775788-69ae2d30-a060-11e7-9f18-4c323575b576.jpg)
![end time 2](https://user-images.githubusercontent.com/29377369/30775787-69ae44aa-a060-11e7-9e4e-97ce42d211d8.jpg)

**Comment by nzidol** [comment]
If you increase the size of the browser window does the information show?
Looks to be a css issue where controls don't have an appropriate minimum size....

**Comment by eei34** [comment]
@tangollama I will be submitting a PR for this momentarily.
