### ISSUE TITLE
Error when i npm start ,What happen? 

### ISSUE THREAD

**Issue by teerapat2539** [HospitalRun/hospitalrun-frontend#1229]
![image](https://user-images.githubusercontent.com/26427910/30895344-d60f1ed8-a373-11e7-9b0e-f67ba4b1630b.png)

**Comment by evalsocket** [comment]
did you install dependency  npm install ?

> npm install -g ember-cli@latest && npm install -g bower
> npm install
> bower install --allow-root
use above commands to install dependency

**Comment by keangkai** [comment]
i think you do not install npm

**Comment by tangollama** [comment]
Closing b/c related to an account that as blocked due to involvement in SPAM PR's.
