### ISSUE TITLE
i config in local sever, i follow all step but Username or password is incorrect.

### ISSUE THREAD

**Issue by teerapat2539** [HospitalRun/hospitalrun-frontend#1237]
![image](https://user-images.githubusercontent.com/26427910/31026001-ea10556c-a56e-11e7-93c1-fbbe7eb9091a.png)

**Comment by nzidol** [comment]
Most likely initcouch.sh was not executed correctly to create the inital database. Are you running cygwin? Also review how your system handles unix-style line-endings.

**Comment by tangollama** [comment]
@nzidol I blocked this user from responding / contributing to the project today, based on it's relationship to a series of SPAM-y PR's. FYI.
