### ISSUE TITLE
Backing Up Hospitalrun

### ISSUE THREAD

**Issue by docbby** [HospitalRun/hospitalrun-frontend#1241]
Good day,
I am a doctor and I have just begun to use the Hospitalrun on Mac [iOS] platform
How do I back-up the data in my Hospitalrun Folder with rsync command

**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by rmNyro** [comment]
Hello, I'm not a participant in the project but I'll try to answer as best as I can.

If you're willing to use the terminal to do your backups (with rsync command for instance) I think the instructions at https://github.com/HospitalRun/hospitalrun-server#db-to-csv should be enough.
In fact what you will want to backup is the database(s) so I guess you can do something like `node utils/db-dump.js hospital.bkp` and then do something like `rsync -av –delete hospital.bkp folderDestinationToBackup`.

But again I've just very recently taken a look at the project (just surface look) and I'm not familiar at all with rsync. So the commands above are almost certainly wrong.

Hope it helped somehow.
Cheers.
