### ISSUE TITLE
Right-to-left languages don't trigger a layout change to right-to-left

### ISSUE THREAD

**Issue by BogdanAlexandru** [HospitalRun/hospitalrun-frontend#1247]
**Expected behavior:**
Right-to-left languages like Urdu change the display layout of text.

**Actual behavior:**
The text is still rendered as if a left-to-right language is used.

**Steps to reproduce:**
Start up HospitalRun.
If Urdu is not selected, select Urdu from the languages dropdown.

**Screenshots (if applicable):**
![Imgur](https://i.imgur.com/5XE2kCJ.png)

**OS and Browser:**
Windows 10 + Chrome.

The layout should be similar to:
![Imgur](https://i.imgur.com/1bRpnto.png)

**Comment by tangollama** [comment]
@BogdanAlexandru that's a big, tall order. Setting this to a help wanted tag.

**Comment by LinKassem** [comment]
I will work on it.

**Comment by disposedtrolley** [comment]
I don't have enough experience with Ember to implement this, but we could possibly modify the `selectLanguage()` method in `language-select.js` to add a `direction: rtl` CSS rule to `div`s. Would also be good to have a mapping of which languages read right-to-left somewhere so we don't end up with a big switch statement.

<img width="1249" alt="screen shot 2017-11-01 at 3 37 24 pm" src="https://user-images.githubusercontent.com/4476568/32260231-a1cbdcca-bf1a-11e7-915e-064cc7165c60.png">

This seems to shift everything properly except for the table header, which has a `text-align: left` rule applied. There's also some tidying to be done re: the spacing between the text and icon in the action buttons.

**Comment by BogdanAlexandru** [comment]
Marking each rtl language as rtl could likely be done in `/<locale>/config.js` as can be seen [here](https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translation-Compiler).

There's in fact support for the rtl flag in ember-i18n. This is what it does by default: https://en.wikipedia.org/wiki/Right-to-left_mark

**Comment by MhdTlb** [comment]
Can I work on this?

**Comment by morsh** [comment]
Is this one still open for grabs?

**Comment by tangollama** [comment]
Yes. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by morsh** [comment]
@tangollama - added Hebrew translation (#1389), added 'rtl' attribute to urdu (#1388) and added support for RTL layout/style (#1388).
