### ISSUE TITLE
Filter Inventory by Location report by Location

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#126]

**Comment by capurp** [comment]
I would like to see if I can help address this issue

**Comment by tangollama** [comment]
@BrianHC are you still working on this one?

**Comment by BrianHC** [comment]
@tangollama sorry for long absence, I am still working on this feature! I will try to get this feature implemented sometime this week.

**Comment by tangollama** [comment]
Awesome. Thx. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by tangollama** [comment]
@BrianHC consider this a friendly #bump on this issue. Are you still working it?

**Comment by BrianHC** [comment]
Hi Joel! Thank for friendly reminder. I've been looking into it, on the
screen it looks like there is a drop-down to filter the inventory report by
location already. Is there any more requirements specified for this request?

**Comment by jkleinsc** [comment]
@BrianHC you are correct that there is a filter that appears to meet this requirement
@tangollama it looks like we already do this or are you looking for something else:
![screen shot 2016-05-16 at 12 11 39 pm](https://cloud.githubusercontent.com/assets/609052/15295635/6ccb2bda-1b5f-11e6-8c6d-c8fbc0bf5a47.png)

**Comment by tangollama** [comment]
It's a open source miracle! Seriously, sorry I didn't follow up on this before I reached out @BrianHC. I'll close this. You up for tackling something else?

**Comment by BrianHC** [comment]
No problem! It was still fun taking a look into how our report system works. Absolutely, I'll take a look at what issues are still open and put my name on one. Unless you have any that you recommend?
