### ISSUE TITLE
Addition of Biometric Devices

### ISSUE THREAD

**Issue by sgatibaru** [HospitalRun/hospitalrun-frontend#1267]
**Expected behavior:**
Use of biometric devices is recommended in many facilities. I really loved hospitalrun and i hoped it would handle biometrics for user interaction(billing & registration). 
**Actual behavior:**

**Steps to reproduce:**
Are there any API's i can look into regarding use of biometric devices? I would appreciate if you point me in the right direction.
**Screenshots (if applicable):**

**OS and Browser:**

**Comment by tangollama** [comment]
Agreed. @sgatibaru are you offering to work this issue?

**Comment by Lily418** [comment]
Looks like in the future this will be possible to implement via the [Web Authentication API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Authentication_API) 

This is currently in the "Candidate Recommendation" stage and as such makes it an experimental technology.
[Web Authentication: An API for accessing Public Key Credentials Level 1](https://www.w3.org/TR/webauthn/)

At the moment it would only be possible to implement in the Electron version via [Node Native Modules](https://electronjs.org/docs/tutorial/using-native-node-modules) to bridge to a native library 

[How can I get data from a fingerprint scanner in to a NodeJS application?](https://stackoverflow.com/questions/33720934/how-can-i-get-data-from-a-fingerprint-scanner-in-to-a-nodejs-application)

But I don't think adding this feature just to Electron version would be desirable?

**Comment by fox1t** [comment]
What do you think about 2FA authentication using a companion mobile app with TouchID and/or FaceID (and Android equivalent)?
