### ISSUE TITLE
#1268 need to use UTC in dob-days to pass tests in different timezones

### ISSUE THREAD

**Issue by aivong** [HospitalRun/hospitalrun-frontend#1268]
**Expected behavior:**
All tests pass.
**Actual behavior:**
1 dob-days test fails.
**Steps to reproduce:**
1) Switch to CST (Central time)
2) Run tests with ember test

**Screenshots (if applicable):**
<img width="698" alt="screen shot 2017-10-16 at 11 07 32 pm" src="https://user-images.githubusercontent.com/4594252/31647140-fb916438-b2cb-11e7-85ca-2c148dff2019.png">
<img width="336" alt="screen shot 2017-10-16 at 11 07 20 pm" src="https://user-images.githubusercontent.com/4594252/31647148-06f8e2a6-b2cc-11e7-9d67-3e8163dca482.png">

**OS and Browser:**
MacOS
Firefox

**Comment by aivong** [comment]
@tangollama I would like to work on this. Have a small fix in mind.

**Comment by aivong** [comment]
After switching to UTC:
<img width="720" alt="screen shot 2017-10-16 at 11 59 07 pm" src="https://user-images.githubusercontent.com/4594252/31647835-1edc6100-b2d0-11e7-87e2-b0bd32f771ce.png">
<img width="226" alt="screen shot 2017-10-16 at 11 59 12 pm" src="https://user-images.githubusercontent.com/4594252/31647838-24b6bb02-b2d0-11e7-8c55-c1e07e5b142f.png">

**Comment by tangollama** [comment]
@aivong go for it.

**Comment by aivong** [comment]
Updated PR. Thanks!

**Comment by tangollama** [comment]
This was addressed by your PR. Thanks @aivong.
