### ISSUE TITLE
Upload Documents

### ISSUE THREAD

**Issue by egibar** [HospitalRun/hospitalrun-frontend#1286]
**Expected behavior:** Possibility to upload and view pdfs. In order to can track a patients cases, I think it would be useful to add the possibility to upload documents as pdf.

**Actual behavior:** only photos

**Steps to reproduce:** In the same way that we have the photos menu, have one with documents

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by donaldwasserman** [comment]
MongoDB now has a way to store documents directly in the DB. I wonder if couch can be extended for that.

**Comment by fox1t** [comment]
I think that even if MongoDB supports storing documents, it is not well suited for the task. PouchDB also supports storing binary data: https://pouchdb.com/api.html#save_attachment, but as for MongoDB, it is sub-optimal. In the 2.0.0 version we will support arbitrary file uploads and it will be handled by some object storage/disc.
