### ISSUE TITLE
Is scripts/bootstrap really worth keeping?

### ISSUE THREAD

**Issue by BogdanAlexandru** [HospitalRun/hospitalrun-frontend#1289]
It's by far the most annoying step in the setup process, which can be seen in the fact that it has the largest number of **Note**s  and workarounds.

It doesn't really do all that much, I just ignore it completely, it's less hassle and I run into much fewer problems if I deconstruct it. Left some comments wrt my interpretation of it.

```
# make the script stop if it encounters a failure
# apparently it's not very reliable: http://mywiki.wooledge.org/BashFAQ/105
set -e

cd "$(dirname "$0")/.."

# useless since we just cloned, as per the instructions
git pull

# this will always be true as long as the project uses node
if [ -f "package.json" ]; then
  echo "==> Installing packages…"
  npm install
  npm install -g phantomjs-prebuilt
fi

# same for this, but for bower
if [ -f "bower.json" ]; then
  echo "==> Installing bower components…"
  bower install
fi
```

> Note: Windows users must use Cygwin.  If that is your case, please run the script in the following way to remove trailing \r characters:
bash -o igncr script/bootstrap

Asking the users to install Cygwin just for this step is overkill. I can set up HR+ on Windows just fine without Cygwin if I deconstruct the bootstrapping script. If anything there's Git Bash on Windows already for anyone using Git, but it seems to do just fine with the regular Command Prompt on Win 7.

> Note: If installing packages globally via npm requires root access on your machine (see ember-cli installation), running script/bootstrap will also require root access to install PhantomJS2. The contained bower install step will fail when running as root. A fix for this is to edit script/bootstrap and add the --allow-root option to the command: bower install --allow-root.

This is the main reason I deconstruct the bootstrapping script even on a Linux VM; changing npm/node permissions on a clean Ubuntu install each time I bring up a VM is so much work because I can't remember what needs doing unless I google each time.

---

Ways to streamline set up:

Move `npm install -g phantomjs-prebuilt` together with the already separate instructions for `npm install -g bower` and `npm install -g ember-cli`. These can be merged in a single `npm i -g` command/step.

Have a single step that tells the user to go to HR's directory and run `npm install` followed by `bower install`. No more root issues, no more cygwin required.

That's about all if I haven't missed anything.

Thoughts?

**Comment by stukalin** [comment]
@BogdanAlexandru I agree. Actually the script didn't work for me even under Linux. Now, since the phantom is gone, your suggestion does make sense even more. Would you make a pull request or should put a _help wanted_?

**Comment by BogdanAlexandru** [comment]
@stukalin 
A help wanted would be a good idea, it's been a while since I last built the project and I'm not up to date with the new stuff like phantomjs' removal.
