### ISSUE TITLE
DOB formatting unit tests fail

### ISSUE THREAD

**Issue by stukalin** [HospitalRun/hospitalrun-frontend#1294]
**Expected behavior:**
All tests pass

**Actual behavior:**
2 tests fail (`convertDOBToText date string` and `convertDOBToText date string short format`) with the 1d difference

**Steps to reproduce:**
* Run tests

**OS and Browser:**
Ubuntu, Chrome

Some thoughts regarding this issue. 
1. I've fixed it (the PR is attached)
2. There was an error in the `dob` module when we're trying to parse a string. No one noticed that since this functionality is not used nowhere except unit tests. The fix (and the code) smells since it implies that we receive the date string in the specific format. _My question then: should we maybe remove the whole parsing part?_
3. I rolled back the #1268, because the author has fixed one test in the CST but broke 2 in the EST. The reason was that in the test we were passing the value 789109200000, which is
`new Date(789109200000) --> Tue Jan 03 1995 06:00:00 GMT+0100 (CET)` so it was the time part which broke the math here. I'd say that since we're working with dates only (the only consumer is the `patient` module which doesn't have a time component) we should work in the the same timezone. Or, let's convert everything to UTC then? For additional security I've put both dates there to the midnight. @aivong could you please verify that it works in your TZ?

If you have any thoughts regarding this, welcome :)

**Comment by arr99** [comment]
康福中国ID99用户名使用4年了突然掉线在登陆用户名无效

亲爱的康福领导你好。我是之前99马甲的主任康福99马甲我使用了4年我是大概2013.8月分左右使用的我是在康福中国中国区的 经销商那里购买的，1250美金购买的，我使用了4年都没有什么问题，在2016年7月分的一天，我在康福中国一个小房间和交个朋友在唱歌玩，我的99马甲突然掉线我在登陆用户名无效，我就给你们康福联系，你们也帮忙给我找康福99马甲了。我登陆不了但是邮箱还是我的我用邮箱找回密码就发过来消息说邮箱以被拦截，这个事情我把截图也发给你们了。康福每天叫我输密码什么的。说着20天就过去了突然99马甲登陆了是一个30马甲更改的，我就问他99马甲什么情况他说他是康福买的300美金我要喜欢那500美金，你们康福那时间给我的我99马甲没问题，我就没有在和那30更改99人联系了。说着一个月回去了突然我看见99马甲直接登陆了。是一个中国人在使用，我问那中国人99马甲他说他朋友在康福够买的，我给你们康福说这个事情你们就在也不回来我话了，我心里很生气，在这个时间有一个美国人说他可以帮忙找回来，我说可以，跟着就把马甲的的原因从头 到尾说一遍。三个月过去了我99马甲没有找回来我还花了300美金买软件。说着又一个软件公司说忙吧找马甲，我又花200多美金，到现在马甲没有音信，康福领导我求求你们帮忙给我查看看看我的马甲为什么就这样不叫我使用了。谢谢康福领导 9

**Comment by arr99** [comment]
![photo 2017_11_18 20-50-22](https://user-images.githubusercontent.com/23447807/33079073-97c76c12-cf0f-11e7-8338-f20a8f719e9a.jpg)

**Comment by arr99** [comment]
康福中国ID99用户名使用4年了突然掉线在登陆用户名无效

亲爱的康福领导你好。我是之前99马甲的主任康福99马甲我使用了4年我是大概2013.8月分左右使用的我是在康福中国中国区的 经销商那里购买的，1250美金购买的，我使用了4年都没有什么问题，在2016年7月分的一天，我在康福中国一个小房间和交个朋友在唱歌玩，我的99马甲突然掉线我在登陆用户名无效，我就给你们康福联系，你们也帮忙给我找康福99马甲了。我登陆不了但是邮箱还是我的我用邮箱找回密码就发过来消息说邮箱以被拦截，这个事情我把截图也发给你们了。康福每天叫我输密码什么的。说着20天就过去了突然99马甲登陆了是一个30马甲更改的，我就问他99马甲什么情况他说他是康福买的300美金我要喜欢那500美金，你们康福那时间给我的我99马甲没问题，我就没有在和那30更改99人联系了。说着一个月回去了突然我看见99马甲直接登陆了。是一个中国人在使用，我问那中国人99马甲他说他朋友在康福够买的，我给你们康福说这个事情你们就在也不回来我话了，我心里很生气，在这个时间有一个美国人说他可以帮忙找回来，我说可以，跟着就把马甲的的原因从头 到尾说一遍。三个月过去了我99马甲没有找回来我还花了300美金买软件。说着又一个软件公司说忙吧找马甲，我又花200多美金，到现在马甲没有音信，康福领导我求求你们帮忙给我查看看看我的马甲为什么就这样不叫我使用了。谢谢康福领导 9
