### ISSUE TITLE
search is not working 

### ISSUE THREAD

**Issue by saumil1** [HospitalRun/hospitalrun-frontend#1298]
**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by Bikraji** [comment]
Hi, 
Here, you can see that I have Harold as a patient![image](https://user-images.githubusercontent.com/3222434/33572192-387694d8-d958-11e7-9bad-179f44d97ca3.png)

 However when I search it shows no result found as below:
![image](https://user-images.githubusercontent.com/3222434/33572294-7fb8318a-d958-11e7-9fac-44c1908ff017.png)

**Comment by peterparkers** [comment]
it's work well for me

**Comment by abc985** [comment]
I can use it normally.

**Comment by DarkSoulCool** [comment]
I can use search box normally. Maybe that's where your files are.

**Comment by Baimaikp** [comment]
i can search

**Comment by saumil1** [comment]
i have login using bellow detail 
hr.hospital.admin@hospitalrun.io
PW: HRt3st12
i have attach video for that please check it 
[search_is_not working.mkv.zip](https://github.com/HospitalRun/hospitalrun-frontend/files/1564557/search_is_not.working.mkv.zip)

**Comment by tangollama** [comment]
@saumil1 forgive the question, but do you have the elastic search running?

**Comment by saumil1** [comment]
I have tested it on http://hospitalrun.io/demo/
using bellow access detail
hr.hospital.admin@hospitalrun.io
PW: HRt3st12

i think that the demo site have installed all dependencies 
so i have reported it 
if your demo site does not have updated or all dependencies installed then you can ignore it 
i think i have to provide this information at report time 
sorry for that

**Comment by RigoTheDev** [comment]
Should we close? @stukalin

**Comment by stukalin** [comment]
@RigoTheDev well, I think we'd be able to close all similar issues once I configure the demo instance again.

**Comment by RigoTheDev** [comment]
@stukalin What's wrong with the demo instance? I'd be glad to help

**Comment by chaitanya-y** [comment]
how to install and configure elasticsearch
