### ISSUE TITLE
Sample data for development

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#13]
As we are building out and designing for new components, having a data migration/sync solution in place would add a lot of efficiency to our development process.

@jkleinsc can you get something like this setup? It would be especially useful for me as I'm doing style work on the patient details section, etc.

**Comment by jglovier** [comment]
Bump. Any progress on this?

**Comment by tangollama** [comment]
Thought: we could create an administration function that loaded a set data into a database for this purpose. I think this 100% makes sense, since we're trying to make "make it easy to develop in" a goal.

**Comment by jglovier** [comment]
Bump. With the new influx of folks interested in helping out, having seed data would be really helpful for local dev. And still would be really helpful for me as I'm working on the UI. :grin:

**Comment by jglovier** [comment]
![help-me-obiwan](https://cloud.githubusercontent.com/assets/1319791/11639656/17b0e46e-9cfc-11e5-9afd-aad0f698c389.gif)

**Comment by jkleinsc** [comment]
We should be able to use [pouchdb-load](https://github.com/nolanlawson/pouchdb-load) and [pouchdb-dump-cli](https://github.com/nolanlawson/pouchdb-dump-cli) to do this.
Basically, we just need someone to do the following:
1. Setup a new empty instance of HospitalRun frontend
2. Populate that instance with sample data.
3. Run [pouchdb-dump-cli](https://github.com/nolanlawson/pouchdb-dump-cli) to dump out the current couchdb.  e.g. ```pouchdb-dump http://localhost:5984/main -u hradmin -p test | cat > sample_data.txt.```
4. Create a node utility that uses [pouchdb-load](https://github.com/nolanlawson/pouchdb-load) to load the dump.

**Comment by jglovier** [comment]
@jkleinsc okay, I'll run through steps 1-3 and then probably will need help with step 4.

**Comment by jkleinsc** [comment]
@jglovier did you get anywhere with this? If not I am going to run with it.

**Comment by jglovier** [comment]
@jkleinsc I did, but haven't found time to get it finished. If you feel like you want to tackle it and can get it done before I will go ahead. I'm not sure I'll have a chance to pick it back up in the next few days.

**Comment by jkleinsc** [comment]
I've got a working solution and it turn out way better than I was originally envisioning.  Expect an update soon
<img width="295" alt="load-db" src="https://cloud.githubusercontent.com/assets/609052/12036894/c13ac85a-ae0f-11e5-9fb1-969769eaea46.png">

**Comment by jglovier** [comment]
![img](http://gifs.joelglovier.com/excited/noice.gif)
