### ISSUE TITLE
Cannot login after 

### ISSUE THREAD

**Issue by amad4biz** [HospitalRun/hospitalrun-frontend#1319]
**Expected behavior:**
I followed all the setup and got the login screen but if enter the username and password I get incorrect username and password
**Actual behavior:**
it should log me in
**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**
Windows 10 local server

**Comment by DerekTBrown** [comment]
More details are needed.  What did you try?

**Comment by amad4biz** [comment]
Hi,
here what I did
I installed couchdb in my machine

I then installed the frontend version and run the following ./script/initcouch2.sh which created a user hradmin and password test . but when I launch the application on localhost:4200 I can see the login screen and anytime I enter the username : hradmin and password: test I receive the error "Username or password is incorrect." Please assist

**Comment by DarkSoulCool** [comment]
I think Because the project owner some of the demo users were either deleted or had their passwords changed.

**Comment by amad4biz** [comment]
how can I recreate a user that has access to this. Please assist if you an idea

**Comment by amad4biz** [comment]
I was able to fix this issue. if one experience this. please make sure you install your couch db in the root of the C drive in windows and then run the script it will work as expected
