### ISSUE TITLE
New Feature: Communication between professionals

### ISSUE THREAD

**Issue by epolicardo** [HospitalRun/hospitalrun-frontend#1325]
**Expected behavior:**
When we edit a patient, show a tab communication or professionals like labs, medication and others, where can comunicate to another professional by chat, mail or call/videocall, or maybe group chat room too
That can make a diference when patient's care mathers.

**Actual behavior:**
None
**Steps to reproduce:**
None
**Screenshots (if applicable):**
None
**OS and Browser:**

**Comment by epolicardo** [comment]
I have working on this features. 
This is my idea:
![captura de pantalla de 2017-12-07 17-43-21](https://user-images.githubusercontent.com/7814653/33737858-54cffd0c-db76-11e7-9f34-953174043e6c.png)
When you select a patient from patients list, a communication tab is showed, selecting it you can see what professional are involved with this patient and communicate directly

**Comment by ZiruZanrgeiff** [comment]
@epolicardo Should I continue from this point?

**Comment by epolicardo** [comment]
@ZiruZanrgeiff You can continue from this point. You can check my github repo to take advantage of my progress...

**Comment by tangollama** [comment]
@epolicardo this is an interesting idea. I look forward to reviewing the PR.

**Comment by drakemedic** [comment]
This would be a great feature. The epr I use just now has a task function where you can communicate with other users of the system within a patient's record. I'm sure it's quite a lot of work though.
