### ISSUE TITLE
Can't able to login through by different PC

### ISSUE THREAD

**Issue by hasanahmed94** [HospitalRun/hospitalrun-frontend#1337]
**Expected behavior:**
should sign in and show dashboard

**Actual behavior:**
Generating Error:
[Report Only] Refused to load the script 'http://_ipaddress_:7020/livereload.js' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval' _ipaddress_:7020 0.0.0.0:7020 undefined:7020".

**Steps to reproduce:**
host on node server and try to access through by different PC on local network

**Screenshots (if applicable):**
![screenshot_1](https://user-images.githubusercontent.com/24221505/34103246-e0734e50-e40d-11e7-843f-69ce5cb3145c.png)

**OS and Browser:**
Windows 10, Browser google chrome

**Comment by geordin** [comment]
Facing the same issue here. Anybody please help.
