### ISSUE TITLE
Temp styles need cleaned up/removed

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#134]
There's a bunch of temp/misc styles that need put into their correct partials.

**Comment by tangollama** [comment]
@jglovier I'm thinking this is definitely in progress, but is there a chance this is completed given last week's work?

**Comment by jglovier** [comment]
>is there a chance this is completed given last week's work?

@tangollama no, not quite. Basically this is still an issue as long as [this file](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/styles/_temp_misc.scss) still exists. Hoping to have it :fire: 🔜 though.

**Comment by tangollama** [comment]
@jglovier is this a possibility for a contribution at the yet-to-be-announced next Hack Day event?

**Comment by jglovier** [comment]
@tangollama absolutely. It'd be great to get some help on this, although I've been thinking lately about our CSS strategy and it involves what to do with this stuff, so I probably need to get that documented somewhere too.
