### ISSUE TITLE
Reset database end to end functional testing

### ISSUE THREAD

**Issue by matteobiagiola** [HospitalRun/hospitalrun-frontend#1342]
Hi, I'm Matteo,

first of all thank you for the great project, it is a very good idea.

Second of all, I'm selecting a certain number of open source applications for the purpose of performing end to end functional testing with them. HospitalRun is documented and very easy to install and these are some of the reasons for which it is appropriate for me.

I have to say that I have no experience with offline-first applications and with NoSQL databases but, for end to end testing, one approach could be that of putting the application state in a desired state before running each test case. In case of HospitalRun I really don't have any idea about how to do that. 

From the technological point of view, at the moment, I have to use Java with Selenium WebDriver that controls the browser. For interacting with CouchDB I found this Java library https://github.com/helun/Ektorp that seems reliable and well maintained; however, I didn't find any way to interact with PouchDB in order to set the state of the client side.

Do you have any idea or suggestions about that? Is it possible to configure the application so that it runs without the offline features?

Thank you a lot!

**Comment by donaldwasserman** [comment]
@matteobiagiola Thanks for the feedback. If you checkout the folder `tests/fixtures` and `tests/acceptance` you can see how ember tests work. Right now, selenium/puppeteer really isn't needed since the test suite/fixtures can handle all of that independently.
