### ISSUE TITLE
Tests fail after Travis CI update

### ISSUE THREAD

**Issue by stukalin** [HospitalRun/hospitalrun-frontend#1344]
**Expected behavior:**
builds are ok

**Actual behavior:**
some tests fail

**Steps to reproduce:**
run Travis build

You probably noticed that our Travis bulds fail after the latest Travis update. Even recommended `deprecated` setting doesn't help. Let's try to fix this. 

I've created a PR where I try to use latest Ember blueprints and recommended Travis settings. Some tests still fail there though. Everyone is welcome to help me with them

**Comment by stukalin** [comment]
Looks like rolling back the `ember-data` helped with the failed tests. Now the PR can be merged and other PRs - rebased.

**Comment by broerse** [comment]
Also this seems to be needed temporary until Travis is fixed:

https://github.com/broerse/ember-cli-blog/commit/8d7f612fd39c68c5fefd577d1a97db7f10e5ad56

**Comment by stukalin** [comment]
@broerse well, for my PR it works without your change so far, but who knows...

**Comment by tangollama** [comment]
I’ll look this over and try to get it merged today.
