### ISSUE TITLE
Minimized sidebar variation

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#135]
As part of #103, I still need to create a minimized sidebar variation. I can accomplish this with CSS alone, however that would be limited to media queries for viewport width.

The more user-empowering approach would be to add a class for `minimized`, and let users choose when they want it fully open, or minimized. That's going to require some ember help, however.

**Comment by tangollama** [comment]
I can assist. Where should the class get added?

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by jglovier** [comment]
>Where should the class get added?

I think directly on the `nav.sidebar-nav` element. The trigger will have to be one of it's children though, so I guess that would get handled with bubbling? `¯\_(ツ)_/¯`

**Comment by tangollama** [comment]
@jglovier, assign back to me when/if this is insufficient.

**Comment by jglovier** [comment]
@tangollama :metal:

**Comment by tangollama** [comment]
@jglovier, I *think* this might be just waiting on you. No pressure on timing, but I know you'd said you were waiting on some stuff from my side. In the interim, you could address this one.

**Comment by iskandergaba** [comment]
Is this still on?
