### ISSUE TITLE
Cannot get to https://beta.hospitalrun.io/

### ISSUE THREAD

**Issue by jbryson3** [HospitalRun/hospitalrun-frontend#1363]
**Expected behavior:**
I expect to be able to get to the site https://beta.hospitalrun.io/ as referenced in the documentation (http://hospitalrun.io/demo/)

**Actual behavior:**
I cannot get to the website - connection refused

**Steps to reproduce:**
go to https://beta.hospitalrun.io/ 

**Screenshots (if applicable):**
<img src="https://user-images.githubusercontent.com/675098/35995035-35bdcca0-0ce0-11e8-8d36-0613e92cbabd.png" width="200"/>

**OS and Browser:**
MacOS 10.12.6
Chrome 64.0

**Comment by jkleinsc** [comment]
@jbryson3 thanks for reporting this.  The issue has been identified and the site is now back up.
