### ISSUE TITLE
Move 'navigation' to a component in order to fix the deprecation

### ISSUE THREAD

**Issue by stukalin** [HospitalRun/hospitalrun-frontend#1366]
**Expected behavior:**
No deprecation warning

**Actual behavior:**
There is a warning

> DEPRECATION: Please refactor `{{render "navigation"}}` to a component and invoke via `{{navigation}}`. (\\\'hospitalrun/templates/application.hbs\\\' @ L2:C2)  [deprecation id: ember-template-compiler.deprecate-render] See http://emberjs.com/deprecations/v2.x#toc_code-render-code-helper for more details.

**Steps to reproduce:**
Run `ember test` for instance

**Comment by James-Byrne** [comment]
I can have a go at this if its available

**Comment by stukalin** [comment]
It's available. Please, feel free to take

11 февр. 2018 г. 5:11 ПП пользователь "James Byrne" <
notifications@github.com> написал:

**Comment by stukalin** [comment]
@James-Byrne any luck with the issue?

**Comment by msalahz** [comment]
Hi, I'm available to take care of this, Is this in progress or I can take it ?

**Comment by James-Byrne** [comment]
Hey sorry for the delay in replying, I got side tracked while working on it. @msalahz if you want to take it up go ahead.

**Comment by msalahz** [comment]
Got it, Thanks @James-Byrne.
@tangollama: I'm taking over this issue.

**Comment by msalahz** [comment]
Hi @tangollama , @stukalin , Sorry I will not be able to complete this task because I got a new job that made me very busy.
The work done on this task can be found [here](https://github.com/msalahz/hospitalrun-frontend/commits/1366-render-deprecation) in case anyone want to start from what I got done instead of starting from scratch.
Look forward to get back to you soon.

**Comment by MatthewDorner** [comment]
Hey. I've been looking at this and made some progress, but I'm still learning the framework so I'm not too confident about it yet. I will look at your code though, and compare with what I have.

**Comment by stukalin** [comment]
@msalahz @MatthewDorner I think I've finished the issue. See the attached PR and don't hesitate to review.

**Comment by stukalin** [comment]
Oh, @msalahz , would you mind to sign the CLA? https://github.com/HospitalRun/hospitalrun-frontend/pull/1397#issuecomment-374610817

**Comment by msalahz** [comment]
Done @stukalin , Thank you for completing my work.
