### ISSUE TITLE
Replace ember-select-list with em-select

### ISSUE THREAD

**Issue by stukalin** [HospitalRun/hospitalrun-frontend#1369]
The `ember-select-list` (https://github.com/begedin/ember-select-list) was last modified in 2015. We use another library - `ember-rapid-forms` which has select helper as well (http://piceatech.github.io/ember-rapid-forms/#/controls/select). So I believe `ember-select-list` could be removed completely in favor of rapid-forms.

Additionally we'll get rid of a deprecation message `ember-views.did-init-attrs`. So, whoever takes this please remove the `deprecation-workflow.js` record.

**Comment by stukalin** [comment]
@ben-muldrow any luck with the issue?

**Comment by msalahz** [comment]
Hi, I'm available to take care of this, Is this in progress or I can take it ?

**Comment by ben-muldrow** [comment]
@stukalin Still hammering away! Been swamped lately -- going to try to finish by the start of next week.

**Comment by efx** [comment]
bumping the issue as I'm looking to contribute.
@ben-muldrow could you link your branch of what you have so far?

**Comment by ben-muldrow** [comment]
@efx Sure thing! Sorry it's taking so long, I got stuck on one of the instances. Would love to go over it with you if you have time. Here's my branch with progress so far https://github.com/ben-muldrow/hospitalrun-frontend/tree/ember-select-list-deprecation

**Comment by efx** [comment]
Sweet, no problem at all. Fixing deprecations in ember apps can be quite grueling. I'll peek through that branch later today or tomorow. Perhaps sometime in the next couple weeks we could connect over Hospital Run's slack if you want to go over it together.

**Comment by MatthewDorner** [comment]
I'd be able to join the discussion as well. I looked at it a little bit before.

**Comment by MatthewDorner** [comment]
@efx @ben-muldrow Any updates on this? I started on it myself and got it replaced on all instances and working, just need to clean up a little then I'll post my code. I'd like to discuss it though.

**Comment by MatthewDorner** [comment]
ok, I started a conversation on there

**Comment by efx** [comment]
We are actively working on this in this branch: https://github.com/MatthewDorner/hospitalrun-frontend/tree/em-select-squashed. I'll be giving PR reviews on those changes until we can open a single squashed PR against Hospital Run master.
