### ISSUE TITLE
initcouch2.sh doesn't set to single-node, other issues

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1391]
Hello, I think I'm having an issue with the initcouch2.sh script. It's the same whether I start by installing CouchDB 2.1.1 with apt-get, or use a docker image via "docker pull apache/couchdb:2.1.1". I get this output if I run the script:
![output using default script](https://user-images.githubusercontent.com/36939751/37083993-de4ee1b6-21b6-11e8-914b-8ec3b4534627.png)

It appears the script wants to setup in single-node mode (please correct if I'm wrong, I'm going off the comment in the script and in the previous commit where that code was added) but actually the command on line 10:
`curl -X POST $HOST/_cluster_setup -H 'Content-Type: application/json' -d '{"action":"enable_cluster","username":"couchadmin","password":"test","bind_address":"0.0.0.0","port":5984}'`
is applying the "enable_cluster" setting. The manual says "enable_cluster" is to "Configure the local or remote node as one node, preparing it to be joined to a new CouchDB cluster." I changed it to "single_node" (and removed the following line as it's not necessary to "finish_cluster" anymore) and I get the following output:
![output after fixed single-node](https://user-images.githubusercontent.com/36939751/37084116-44809bf0-21b7-11e8-9ee7-78940c4b936e.png)
still getting errors on the later authentication settings being applied. I changed on line 27 and 28 the "couchdb@localhost" to "_local" and now these are working for me as well and I can confirm the settings are being applied by checking in the CouchDB management app. The manual says "The literal string _local serves as an alias for the local node name". The manual also says "the default node name has changed from couchdb@localhost to couchdb@127.0.0.1" so that would probably also work. I had been looking at the manual for 2.1.0 found here: media.readthedocs.org/pdf/couchdb/latest/couchdb.pdf.

**OS and Browser:**
Ubuntu 16.04

If you think these changes should be committed, I will open a PR. Thanks.

**Comment by falexsandro** [comment]
@MatthewDorner Hi, Matthew. After the modifications that you did to the script, you got the application running ?

**Comment by MatthewDorner** [comment]
I've only just begun looking at the application so I can't say comprehensively that it's "working" but I get CouchDB installed now and I don't get any CouchDB login error when launching "npm start" the way I would before. Is there a test suite I can run for CouchDB functionality or anything?

**Comment by falexsandro** [comment]
It's a good thing!
There is a set of test scripts, that is more comprehensive, that can be run.
I believe that is triggered by calling `ember test`.

**Comment by MatthewDorner** [comment]
Yes, the tests do pass.

**Comment by MatthewDorner** [comment]
here are changes I made to my copy: [comparison](https://github.com/MatthewDorner/hospitalrun-frontend/compare/master...MatthewDorner:fix-initcouch2-script?diff=unified&name=fix-initcouch2-script)
