### ISSUE TITLE
hospitalrun demo is too slow

### ISSUE THREAD

**Issue by LabN36** [HospitalRun/hospitalrun-frontend#1409]
**Expected behavior:**

**Actual behavior:**
this is my first time I'm trying this application(apologies if i missed anything) but it seems very slow to me, can anyone guide me why is that? is it because of it's on the demo version or deployed in small resource server?

from my experience it's taking way more than and average software took time to load and process

**Steps to reproduce:**
just login with any credential provided here
http://hospitalrun.io/demo/
**Screenshots (if applicable):**

**OS and Browser:**
Windows 7 and Google Chrome

**Comment by donaldwasserman** [comment]
Closed for #1470
