### ISSUE TITLE
Add internationalization support

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#141]
In order to support different languages in HospitalRun we need to implement [ember-i18n](https://github.com/jamesarosen/ember-i18n) throughout the app

**Comment by billybonks** [comment]
Hi, i have been looking for some way to contribute to the project, and i think this is a good issue to work on, since it's a nice way to explore the code base :smile:

**Comment by jkleinsc** [comment]
@billybonks One of the things on my todo list is to upgrade to Ember 1.13, then fix the deprecation warnings in preparation for Ember 2.x

Do you know how much of a difference there is between 3.x i18n and 4.x?  If they are significantly different, I would prefer to wait until we can pull in 4.x.

**Comment by tangollama** [comment]
@billybonks, given that this conversation went cold back in July b/c of the upgrade work, I'm guessing you didn't start anything with this; but I wanted to ask if this was on your radar or if I should be looking for someone else to look into it? No worries either way. Just asking.

**Comment by billybonks** [comment]
@tangollama, let me try set this up this weekend otherwise, ill drop it :+1: my time has been limited lately

**Comment by tangollama** [comment]
Word.

**Comment by jonkoops** [comment]
@billybonks Any update on this?, would love to help out.

**Comment by jkleinsc** [comment]
@jonkoops @billybonks had a PR that setup localization and that has been merged and at this point what is needed is to convert all of the templates to use localized text.  I was intending on creating issues for each functional area to convert the templates but I haven't done so yet.

**Comment by jonkoops** [comment]
@jkeinsc Alright, let me know when you do then I'll pick some up.

**Comment by jkleinsc** [comment]
@jonkoops The following localization issues have been added:
#274, #275, #276, #277, #278, #279, #280, 281

**Comment by mDantas** [comment]
@jkleinsc @jonkoops just wanted to say hi and that'd I'd be interested in helping out too.

**Comment by jonkoops** [comment]
@mDantas I'll take the Patients module, maybe you can work on the Appointments module at the same time?

**Comment by jkleinsc** [comment]
Once all the localization has been completed, we should add [ember-cli-template-lint] https://github.com/rwjblue/ember-cli-template-lint to verify that all of our templates are using translated strings.

**Comment by jkleinsc** [comment]
All issues complete.  Closing this issue.
