### ISSUE TITLE
Update to Ember 1.13

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#143]
We need to update to Ember 1.13 in preparation for Ember 2.x

**Comment by jkleinsc** [comment]
Code has been updated to ember 1.13

**Comment by tangollama** [comment]
Woo hoo!!

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by jglovier** [comment]
![its-happening](https://cloud.githubusercontent.com/assets/1319791/9971543/a0ba6124-5e2a-11e5-8a74-5fa0f3514e9e.gif)
