### ISSUE TITLE
Deleting visit breaks any associated invoice to that visit

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1439]
**Expected behavior:**
Not sure.

**Actual behavior:**
Similar to #383. If you add an invoice, you must associate a visit to the invoice. If you then delete that visit, any listing at /invoices that would have included your invoice just won't render. You will get this error:
![invoice visit relationship error](https://user-images.githubusercontent.com/36939751/40276650-41d4dea4-5bd5-11e8-9723-cb84c9fb1ec0.png)

**OS and Browser:**
Ubuntu 16.04, Chromium

**Comment by MatthewDorner** [comment]
Oh, this also happens when you delete the "blank" location from an inventory item. By "blank" location, I mean the one that has no name that all your items go to when you first add / purchase them. Here, the solution may just be to not let you delete that location.
![location relationship](https://user-images.githubusercontent.com/36939751/40276822-61211bac-5bd9-11e8-8eff-528ca48d4fcb.png)

**Comment by ghobs91** [comment]
Is the objective to delete the invoice along with the deleted visit, or to keep the invoice but have it not break?

**Comment by MatthewDorner** [comment]
We wouldn't want to simply delete the invoice. Maybe a message warning like "Invoice _____ attached to this visit will also be deleted. Do you want to continue with deletion?" or refuse to delete and say "Cannot delete visit while attached invoice _____ exists." I think I prefer the latter.

We should review other models that have a similar relationship and see how it's handled there. I suspect that since there are these two, there may be a couple more that have this problem.


I also noticed the model for invoice has a belongsTo for visit, but the model for visit doesn't have any association for invoice. I wonder if that is related to the behavior.

**Comment by MatthewDorner** [comment]
Working on this. There's code for cascading deletions when deleting patient records, https://github.com/HospitalRun/hospitalrun-frontend/pull/457/files, but there needs to be similar code for visits.

I wouldn't have thought to delete invoices automatically when deleting visit/patient but that's how we handle it already when deleting a patient. It's not supposed to delete things entirely though, just archive them https://github.com/HospitalRun/hospitalrun-frontend/commit/20dd5b29cf697b23f0df179d30fe951e31744d0f, but there are issues around this as well. I think some record types are being deleted entirely instead of archived.

Anyway working on it here: https://github.com/MatthewDorner/hospitalrun-frontend/tree/deletions-fix
