### ISSUE TITLE
Update to ember-pouch

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#144]
As part of the update to Ember 1.13 (see #143), we need to update our ember data adapter to [ember-pouch] (https://github.com/nolanlawson/ember-pouch).

**Comment by jkleinsc** [comment]
We may need to migrate data as part of this update.

**Comment by jkleinsc** [comment]
We definitely need a migration script.  Working on that now.

**Comment by jkleinsc** [comment]
Migration script is now available at https://github.com/HospitalRun/hospitalrun-server/blob/master/utils/pouch-mig.js

**Comment by broerse** [comment]
:+1:
