### ISSUE TITLE
Demo, beta.hospitalrun.io login 'Username or password is incorrect.'

### ISSUE THREAD

**Issue by grahamperrin** [HospitalRun/hospitalrun-frontend#1443]
Credentials at http://hospitalrun.io/demo/ include: 

> Lab Technician
> `hr.lab.tech@hospitalrun.io`
> PW: HRt3st12

For those credentials at https://beta.hospitalrun.io/#/login the result is: 

> Username or password is incorrect.

Duplicate of #1292 maybe?

**Comment by donaldwasserman** [comment]
Closed for #1470
