### ISSUE TITLE
The demo is not working

### ISSUE THREAD

**Issue by aalmangour** [HospitalRun/hospitalrun-frontend#1445]
**Expected behavior:**
Login Successful
**Actual behavior:**
Login failed with a message saying website is offline
**Steps to reproduce:**
Try to login with any user
**Screenshots (if applicable):**

**OS and Browser:**
Any

**Comment by tangollama** [comment]
We know. I’m working on it. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by donaldwasserman** [comment]
Closed for #1470
