### ISSUE TITLE
Impossible login first time

### ISSUE THREAD

**Issue by JSFonta** [HospitalRun/hospitalrun-frontend#1459]
**Expected behavior:**
Log with "hradmin" and "test" the first time I use HospitalRun

**Actual behavior:**
Get this answer : "Username or password is incorrect."

**Steps to reproduce:**
(NodeJS 8.11.3 x64 Windows, CouchDB 1.7.1)
Follow exactly that : https://github.com/HospitalRun/hospitalrun-frontend#installation

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/15943909/42922615-93465f0a-8b60-11e8-9bd3-d9dd5aec7f20.png)

**OS and Browser:**
Windows 10.0.17134 Pro
Google Chrome Version 67.0.3396.99 (Build officiel) (64 bits)

I tried to fully uninstall and then retry, nothing change.

Thank's for your help !

**Comment by MatthewDorner** [comment]
Were you able to run initcouch.sh during the setup?

**Comment by JSFonta** [comment]
It runs, but an error occured at the end : 

`Add hradmin user for use in HospitalRun
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1624  100  1499  100   125   4570    381 --:--:-- --:--:-- --:--:--  4951{"error":"EXIT","reason":"{{badmatch,\n     {error,\n         {enoent,\n             [{erlang,open_port,\n                  [{spawn,\n                       \"c:/Program Files (x86)/Apache Software Foundation/CouchDB/lib/couch-1.7.1/priv/couchspawnkillable ./couchjs.exe ../share/couchdb/server/main.js\"},\n                   [stream,{line,4096},binary,exit_status,hide]],\n                  []},\n              {couch_os_process,init,1,\n                  [{file,\n                       \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_os_process.erl\"},\n                   {line,148}]},\n              {gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},\n              {proc_lib,init_p_do_apply,3,\n                  [{file,\"proc_lib.erl\"},{line,237}]}]}}},\n [{couch_query_servers,new_process,3,\n      [{file,\n           \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_query_servers.erl\"},\n       {line,477}]},\n  {couch_query_servers,lang_proc,3,\n      [{file,\n           \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_query_servers.erl\"},\n       {line,462}]},\n  {couch_query_servers,handle_call,3,\n      [{file,\n           \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_query_servers.erl\"},\n       {line,322}]},\n  {gen_server,try_handle_call,4,[{file,\"gen_server.erl\"},{line,607}]},\n  {gen_server,handle_msg,5,[{file,\"gen_server.erl\"},{line,639}]},\n  {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}"}

Add audit document for FHIR API data
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1501  100  1499  100     2   6876      9 --:--:-- --:--:-- --:--:--  6885{"error":"EXIT","reason":"{{badmatch,\n     {error,\n         {enoent,\n             [{erlang,open_port,\n                  [{spawn,\n                       \"c:/Program Files (x86)/Apache Software Foundation/CouchDB/lib/couch-1.7.1/priv/couchspawnkillable ./couchjs.exe ../share/couchdb/server/main.js\"},\n                   [stream,{line,4096},binary,exit_status,hide]],\n                  []},\n              {couch_os_process,init,1,\n                  [{file,\n                       \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_os_process.erl\"},\n                   {line,148}]},\n              {gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,306}]},\n              {proc_lib,init_p_do_apply,3,\n                  [{file,\"proc_lib.erl\"},{line,237}]}]}}},\n [{couch_query_servers,new_process,3,\n      [{file,\n           \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_query_servers.erl\"},\n       {line,477}]},\n  {couch_query_servers,lang_proc,3,\n      [{file,\n           \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_query_servers.erl\"},\n       {line,462}]},\n  {couch_query_servers,handle_call,3,\n      [{file,\n           \"c:/cygwin/relax/apache-couchdb-1.7.1/src/couchdb/couch_query_servers.erl\"},\n       {line,322}]},\n  {gen_server,try_handle_call,4,[{file,\"gen_server.erl\"},{line,607}]},\n  {gen_server,handle_msg,5,[{file,\"gen_server.erl\"},{line,639}]},\n  {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,237}]}]}"}`

**Comment by MatthewDorner** [comment]
aha, that's probably it. I'm not familiar with that error but it looks close to this: https://github.com/apache/couchdb/issues/991 so you can try the workaround shown there.

**Comment by JSFonta** [comment]
Ok it works ! I uninstall CouchDB and then install again but directly into my "C:/".
Thank you MatthewDorner !
