### ISSUE TITLE
Remove Bower

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1465]
Bower has been deprecated, is minimally used, which presents a challenge to getting started for new contributors. 

I have a PR that's a work in progress that is moving the following packages need to npm: 

- [x] Bootstrap
- [x] JsBarcode (handled by addon)
- [x] filer.js
- [x] idb.filseystem
- [x] octicons
- [x] pikaday
- [x] typeahead.js
- [x] pouchdb-load
- [x] pretender
- [x] fullcalendar (handled by addon)
- [x] fullcalendar-scheduler (handled by addon)
- [x] timekeeper (used for tests only)
- [x] webtrc-adapber (not used possibly)

**Comment by stukalin** [comment]
@donaldwasserman we had this already in #1156. Could you maybe if applicable merge the info from both and close one of them?

**Comment by donaldwasserman** [comment]
@stukalin Sorry - not sure why I didn't see that.

**Comment by donaldwasserman** [comment]
Sorry to leave this hanging for so long, just have a few more tests to figure out why they're failing all of a sudden
