### ISSUE TITLE
Beta/Demo Site Issues

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1470]
Demo and Beta Sites should work awesome and present a great experience to potential users throughout the globe on any device

There have been various issues surrounding the demo and beta experience: 

- [ ] Site Outages
- [ ] Incorrect Login info
- [ ] CI/CD Automated Updates
- [ ] Error Reporting

**Comment by MatthewDorner** [comment]
There's #388 regarding automated updates to the beta site. One thing I've noticed is when you install hospitalrun-server, you don't get the most recent frontend. It gets the frontend code from here https://libraries.io/npm/hospitalrun, which is no longer being updated since the 1.0.0-beta release.

**Comment by donaldwasserman** [comment]
@MatthewDorner Should we close #388 too? 

Just looking through some of that, we really should be able to use travis for some of the deployment stuff.

**Comment by MatthewDorner** [comment]
Maybe we should leave it until we get a better understanding of the bigger picture regarding infrastructure and CI/CD. It seems like at the end of #388 they expanded the scope beyond just the demo site but then it didn't get finished.

**Comment by cgd1** [comment]
I am also experiencing the login issue when I try deploy using docker
