### ISSUE TITLE
Connecting Frontend to Backend

### ISSUE THREAD

**Issue by Arjanguglani** [HospitalRun/hospitalrun-frontend#1479]
I downloaded and set up the hospital run-frontend development environment on my Mac. I also set up an EC2 instance on AWS with HospitalRun-Server. How do I connect the backend I have set up with the front end? I feel like the config file would be the best place to do this, but what field would I change. 

Also, how would I export the project to a .exe format after I have made the configuration change?

On a side note: If ANYBODY with experience setting up HosptialRun could give me a call and help me sort some issues I have, I would be willing to pay you for an hour of your time (Email guglaniarjan@yahoo.com if you are interested). Time is of the essence in my situation so I do not have a lot of time to keep emailing back and forth.

**Comment by dvehar** [comment]
You can try [slack](https://github.com/HospitalRun/hospitalrun-frontend#troubleshooting-your-local-environment) or maybe even joel@hospitalrun.io

**Comment by MatthewDorner** [comment]
If trying to use the app in production, hospitalrun-server does not require you to set up the frontend separately. As described in the instructions below, the app should be accessible over port 8055:
https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md

If instead you are trying to set up a development environment for the frontend so you can work on the code, you don't need to use hospitalrun-server. Just run the frontend and couchDB.

**Comment by donaldwasserman** [comment]
@Arjanguglani Not sure if you still need help, I hope you check into slack to see what you need. 

In any event, this issue really belongs on the https://github.com/HospitalRun/hospitalrun-server repo, so if you are still having problems, open and issue there, or send me a message on slack `@djwasserman`
