### ISSUE TITLE
Personas  / user research thread...

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#148]
I want to start a discussion about how we can do research for the design of this thing. If we are going to hit the mark of "think people enjoy using/want to use", then we will certainly need to do research up front.

Partial list of things we need to study are:

how people use existing tools (to inform product requirements)
what pain points do people have with their existing toolsets (aim to improve on those things)
what things to they find to work well in their existing tools (avoid breaking those things)
Who we should aim to interview:

doctors, nurses, staff admins within the cure network
doctors, nurses, staff admins outside the cure network, and within charity hospitals
doctors, nurses, staff admins outside the cure network, and within non-charity hospitals (may be less informative, but still relevant)
How should we go about planning to do this research? I'm looking for input and suggestions, but to get the discussion started I'd say we craft a survey, and aim to a) do recorded interviews where we ask people these questions and absorb as much information as possible, and b) observe people using their existing tools where possible
 @jglovierjglovier added the UX label on Feb 28, 2014
@mnorbeck

mnorbeck commented on Mar 1, 2014
Jag - awesome stuff. Ever run across personas? So, instead of a "user", you speak in terms of "Bruce, a visiting physician". You develop a basic profile of Bruce: background, education/experience, goals/desires within the context of the site/system you are building. I have seen it go as far as to pick real-world people and use them as the personas (really cool when they can meet the dev team, and be your beta users!). Have a picture with the profile, make them real, make them human. Development then adopts the behavior of using these personas in all their conversations about the system. "Bruce needs to look up his appointment schedule for today, so he can plan his day and resolve any potential conflicts". Which would possibly be a single user story. I have seen a wiki set up, with all the persona pages, for quick reference by the dev team. Becomes a very important project artifact.

 @jglovier
  Owner
jglovier commented on Mar 1, 2014
@mnorbeck yup! I'm very familiar with persona's. Formalized user personas will be part of the outcome of our user research, as well as part of the planning for it.

I have seen it go as far as to pick real-world people and use them as the personas
I've always liked using real world people, so if we can go that route I'm very much in favor, but my only concern with that is that we don't rely to heavily on feedback/input/etc from a sample size of one. Ideally we'll have a few people that match each persona for research and testing.

But major +:100: for crafting personas, and using them to inform every step of the UXR process. :thumbsup:

 @jglovier
  Owner
jglovier commented on Mar 1, 2014
For reference, GitHub has some nice real world user personas, although I don't think ours are public. MailChimp also has some rear ones and pretty sure theirs are public.

These will be great for our marketing site, too. They're just as useful for helping prospective users decide if the software is right for them/reinforce that we get their use cases as they are for us in designing and building the product.

 @tangollama
  Owner
 tangollama commented on Mar 1, 2014
100% on board with personas, but I have some perspective that we should
probably all discuss regarding how useful input will be from the user base.
It boils down to usability testing being more valuable then the users in
the requirements process. A topic for the first project meeting....

**Comment by tangollama** [comment]
For safe-keeping, @mnorbeck worked on this document https://docs.google.com/spreadsheets/d/1qN8pB6BYv2gUar1ueJ4wjgLoEYrCAOrxQZEH4NGPrlk/edit#gid=0

**Comment by jglovier** [comment]
:metal: :heart: :zap:

**Comment by tangollama** [comment]
As another input to this discussion, I'd like to contribute the work done by a young woman from Oxford at CURE Malawi, analyzing and recommending an implementation for that hospital to HospitalRun. 
https://docs.google.com/document/d/1ffl0OYzUc9JjLQ-0mIceVRUygRaYJO7JoWXWMn2JWTM/edit

**Comment by jglovier** [comment]
@tangollama awesome!! Thanks for sharing. :zap: :metal: :zap:

BTW, in the discussion of :fire: my CURE email address, guessing that means I'll no longer have access to those Google docs then?

**Comment by tangollama** [comment]
Negative ghost rider. You can share the doc with anyone you want, including people outside the domain. I do it all the time. Also, that document in specific is set to be readable by anyone who has the link.

**Comment by jglovier** [comment]
>Negative ghost rider. You can share the doc with anyone you want, including people outside the domain. I do it all the time. Also, that document in specific is set to be readable by anyone who has the link.

![zoolander](https://cloud.githubusercontent.com/assets/1319791/11486455/4a57f0e4-9787-11e5-9912-55d9cd5eb6bd.gif)

**Comment by mnorbeck** [comment]
@tangollama.  I vote to close this issue out.   Personas are so 20th century.   Jobs to be Done are more relevant!    But more seriously, what is the actionable items here?   Are there any, at this point?
