### ISSUE TITLE
Appointment can be created with start date later than end date.

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1484]
**Expected behavior:**
Start date of appointment should be equal or earlier than end date.

**Actual behavior:**
Validation is only performed on end date, so you can enter a valid end date and then change the start date to a later date.

.**Steps to reproduce:**
- Create an appointment of type "Admission"
- Set end date to a date later than start date
- Set start date to a date later than end date
- Save the appointment

**Screenshots (if applicable):**
![appointment](https://user-images.githubusercontent.com/36939751/44318032-c4476e80-a3f9-11e8-81f9-7f79970df9fe.png)

**Comment by arch-lord** [comment]
@tangollama I'm a new contributor to hospitalrun. I am interested in working on this issue and am installing hospitalrun right now. `CONTRIBUTING.md` said that I should mention you "to let our product management function know your intentions."

**Comment by arch-lord** [comment]
I am unable to continue trying to fix this, due to #1487.

**Comment by arch-lord** [comment]
That is now resolved enough for me to attempt fixing this.

**Comment by MatthewDorner** [comment]
For installation issues, you can also join the Slack https://hospitalrun-slackin.herokuapp.com/ and join the #troubleshooting channel.

The config.js should have couchadmin as the username, not hradmin. hradmin gets created when you run the initcouch.sh script.

**Comment by AaronTJDev** [comment]
@tangollama @donaldwasserman Hey guys, I'm a first time contributor. If this issue is still open I'd like to take a crack at it.
