### ISSUE TITLE
Errors Encountered While Installing

### ISSUE THREAD

**Issue by arch-lord** [HospitalRun/hospitalrun-frontend#1487]
**Expected behavior:**
A fresh install of hospitalrun should go smoothly without errors.

**Actual behavior:**
Two errors are encountered when following the official instructions.

**Steps to reproduce:**
1. Install latest version of NodeJS (currently 10.9.0).
2. Run `npm install -g ember-cli@latest` and `npm install -g bower`.
3. Clone the repo
4. Run `npm install`
5. There is already an error (see the first screenshot), but finish following [the instructions](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/README.md#installation).
6. Run `npm start` or `ember serve` (see the second screenshot).

**Screenshots (if applicable):**
![screenshot1](https://user-images.githubusercontent.com/42556441/44373164-b3036e00-a49c-11e8-9c17-50388a3e9126.PNG)
![screenshot2](https://user-images.githubusercontent.com/42556441/44373293-5c4a6400-a49d-11e8-9aac-09b120a6a7ab.PNG)

**OS and Other Info:**
Windows 10 x64 Version 1803 Build 17134.228
NodeJS 10.9.0
NPM 5.6.0, 8.11.4, 6.14.4
Ember 3.3.0
Bower 1.8.4

**Comment by MatthewDorner** [comment]
Instructions says "We recommend that you use the most-recent "Active LTS" version of Node.js." which is currently 8.x.

https://github.com/nodejs/Release

Although there might also be issues with 8.x. You can try it, but 6.x is what I'm using which should definitely work.

**Comment by arch-lord** [comment]
@MatthewDorner Ok I will try it with 8.x and then 6.x if that doesn't work.

**Comment by arch-lord** [comment]
Same problem with Node 8.11.4 LTS.

**Comment by arch-lord** [comment]
@MatthewDorner Same problem with 6.14.4. Also, I forgot to mention that first I also have to install `broccoli-funnel` and `broccoli-export-text` before getting the final error.

**Comment by MatthewDorner** [comment]
I see. It is happening to me as well. Must be due to a recent change. You might want to just change the line in package.json:

"ember-validations": "HospitalRun/ember-validations#2.0.0",

temporarily back to:

"ember-validations": "2.0.0-alpha.5"

until it gets fixed.

**Comment by donaldwasserman** [comment]
Bummer - who wrote that terrible code?

**Comment by arch-lord** [comment]
@MatthewDorner @donaldwasserman I updated that but it still has the same error.

**Comment by MatthewDorner** [comment]
Can you screenshot the error and your package.json file? It shouldn't have the exact same "2.0.0" error..

**Comment by arch-lord** [comment]
Besides a bunch of deprecation messages, everything is working fine now. This really should be changed, though.

**Comment by donaldwasserman** [comment]
@arch-lord - Thanks for the help!

**Comment by arch-lord** [comment]
@donaldwasserman You're welcome :smile:
