### ISSUE TITLE
Get To Node 8/10x, add .nvmrc

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1488]
This application should, at a minimum work across one of the default Ember supported LTS node releases: 

Node 6.x, 8.x, 10.x

There are a few different addons who are misbehaving and need to be updated in order to meet this use case. 

Also, add a `.nvmrc` file to help automatically use the right node version. [See NVM](https://github.com/creationix/nvm)

**Comment by stukalin** [comment]
@donaldwasserman I thought it was working under the 6. Which addon(s) caused the issue?

**Comment by donaldwasserman** [comment]
@stukalin I'm not sure, but I had to use 7 to get it install. It may have been my bad version of ember validations, in retrospect.

**Comment by stukalin** [comment]
I fixed ember-validations by the way. It was me who used a wrong git tag. Yarn understands when you write `#2.0.0` even though the tag is called `*v*2.0.0`
