### ISSUE TITLE
Appointments Calendar and Search Filter Bugs

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1494]
Appointments Calendar and Appointments Search both have controls to filter on Status, Type, With, and Location. These are not producing the correct set of appointments for a given filter.

**Actual behavior / How to reproduce:**
On Calendar, set a non-blank value on any of the filter controls and apply the filter. All appointments disappear, regardless of what filter you use. On Search, problem appears the opposite way in that no appointments ever disappear, so it's like your filter has no effect. The problems on both pages seem to be related if not the exact same cause.

I notice that when you use a filter (when the problem occurs), the query uses the pouchdb-list dependency and it seems like queries that use this pouchdb-list (those that use the call to db.list(...) in adapters/application.js) are always returning zero results on the Calendar page, and erroring out (the if(err) block right underneath the db.list(...)) on the Search page. I tried older versions of pouchdb-list but that didn't fix it.

Chromium and Firefox, Ubuntu 16.04.
Also tested on a 1.0.0-beta frontend and same problems exist there.

**Comment by FergusInLondon** [comment]
@donaldwasserman I reproduced this the other day when working testing the work done on #1515. Mind if I jump in on this? @MatthewDorner's description is awesome, and this looks like it should be quite a good one to fix.

**Comment by MatthewDorner** [comment]
Go ahead, btw you can enable database debugging in the browser console by adding a line PouchDB.debug.enable('*'); in services/database.js at the top of the setup() function, and in serviceworkers/pouchdb-sync.js at the top of the file.

**Comment by FergusInLondon** [comment]
That's awesome, and thanks for the tip - that sounds _verrryyy_ useful!

**Comment by donaldwasserman** [comment]
Thanks @FergusInLondon
