### ISSUE TITLE
Help greenkeeper to update ember-cli-template-lint

### ISSUE THREAD

**Issue by stukalin** [HospitalRun/hospitalrun-frontend#1499]
Have a look at the #1446. The build is failed because apparently some new rules were introduced. 

**Goal**: where applicable and clear - fix templates; where requires much effort - disable rules.

**Comment by oxiqu** [comment]
I will give this one a try. Will post updates as I go.

**Comment by oxiqu** [comment]
Update: almost all errors resolved. 9 items left. Will fix those tomorrow.
