### ISSUE TITLE
Create New Date/Timepicker Solution

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1501]
Currently, HR frontend is using a datepicker solution that relies on an outdated and unmaintained date/time picker library: https://github.com/owenmead/Pikaday

See: 
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/date-picker-wrapper.js
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/date-picker.js

Developing a better solution that relies on ember-power-calendar or a different better date picking library would be ideal.

**Requirements**

- A user must be able to type, select, edit dates with a keyboard or mouse
- No jQuery dependency
- All existing acceptance tests must pass
- Use Ember best practices (like contextual components)
- Must integrate with existing validations library
- Prefer an existing, maintained, ember addon

**Comment by donaldwasserman** [comment]
@surajdubey That would be great - I added some requirements above. If you're taking a stab at it, i'll mark this issue as in progress!

Thanks for the help!

**Comment by surajdubey** [comment]
Sure @donaldwasserman 
Thanks for modifying the tags.

**Comment by pat154** [comment]
@surajdubey Hey mate, are you still looking at this issue? If not I'd be happy to take over or help out. Cheers!

**Comment by jackcmeyer** [comment]
Closing issue in favor of hospitalrun/components#34
