### ISSUE TITLE
Replace bootstrap.js with ember-bootstrap

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1511]
All of the javascript behavior using `$.bootstrap()` can be replaced with the jquery/bootstrap-less functionality of `ember-bootstrap.` This will help provide some benefits: 

- Smaller payload size
- Better abstractions, especially in modal functionality
- Path to removing jQuery

**Comment by nathanhbsimmons** [comment]
@donaldwasserman I'd like to tackle this one.
