### ISSUE TITLE
Issue when create the web app package for Windows10 desktop 

### ISSUE THREAD

**Issue by Yenle9** [HospitalRun/hospitalrun-frontend#1518]
Hi, I have just jumped to the project therefore sorry if any my foolish.
I would like to build the web app package for Windows10 desktop.

I used windows 10 for building and running project.
I followed the steps:
-Clone the frontend project
-npm install
-bower install
-ember electron:make --platform=win32

But there's an issue here:
D:\010_HospitalRun\hospitalrun-frontend>ember electron:make --platform=win32
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-cli-content-security-policy -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-cli-active-link-wrapper -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-cli-template-lint -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-i18n -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-i18n -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-simple-auth -> ember-cookies -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-simple-auth -> ember-getowner-polyfill -> ember-cli-babel
| Building and assembling[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: BrocText
- Building and assembling[API] Warning: Plugin uses .read/.rebuild API: ember-browserify
| Building and assembling[API] Warning: Plugin uses .read/.rebuild API: ember-browserify
cleaning up...
Built and assembled Electron project successfully. Stored in "D:\010_HospitalRun\hospitalrun-frontend\tmp\package_task-tmp_path-yAcW4sIZ.tmp".
Packaging Electron project.
- Compiling ApplicationFailed to compile file: C:\Users\YENN~1.LE\AppData\Local\Temp\electron-packager\win32-x64\HospitalRun-win32-x64\resources\app\ember\crossdomain.xml
Compiling C:\Users\YENN~1.LE\AppData\Local\Temp\electron-packager\win32-x64\HospitalRun-win32-x64\resources\app\ember\crossdomain.xml resulted in a MIME type of application/xml, which we don't know how to handle
√ Compiling Application
√ Preparing native dependencies
rcedit.exe failed with exit code 1. Fatal error: Unable to set icon

Does anyone know how to fix or how to create web app package for desktop?

**Comment by yenle91** [comment]
When I modified the path of icon in electron-forge-config.js file from:
icon: 'assets/icons/icon', -> 'icon: 'assets/icons/favicon'
this issue has gone but another exist like:

D:\010_HospitalRun\hospitalrun-frontend>ember electron:make --platform=win32
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-cli-content-security-policy -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-cli-active-link-wrapper -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-cli-template-lint -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-i18n -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-i18n -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-simple-auth -> ember-cookies -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: hospitalrun -> ember-simple-auth -> ember-getowner-polyfill -> ember-cli-babel
- Building and assembling[API] Warning: The .read and .rebuild APIs will stop working in the next Broccoli version
[API] Warning: Use broccoli-plugin instead: https://github.com/broccolijs/broccoli-plugin
[API] Warning: Plugin uses .read/.rebuild API: BrocText
\ Building and assembling[API] Warning: Plugin uses .read/.rebuild API: ember-browserify
- Building and assembling[API] Warning: Plugin uses .read/.rebuild API: ember-browserify
cleaning up...
Built and assembled Electron project successfully. Stored in "D:\010_HospitalRun\hospitalrun-frontend\tmp\package_task-tmp_path-nGrcjen6.tmp".
Packaging Electron project.
\ Compiling ApplicationFailed to compile file: C:\Users\YENN~1.LE\AppData\Local\Temp\electron-packager\win32-x64\HospitalRun-win32-x64\resources\app\ember\crossdomain.xml
Compiling C:\Users\YENN~1.LE\AppData\Local\Temp\electron-packager\win32-x64\HospitalRun-win32-x64\resources\app\ember\crossdomain.xml resulted in a MIME type of application/xml, which we don't know how to handle
√ Compiling Application
√ Preparing native dependencies
Making Electron project.
Couldn't find packaged app at: D:\010_HospitalRun\hospitalrun-frontend\out\HospitalRun-win32-x64

**Comment by donaldwasserman** [comment]
This issue has come up before, and we just need some bandwidth to look into it.

**Comment by MatthewDorner** [comment]
Made the changes with the icon settings, then I get the same error you do, "Couldn't find packaged app..."

I think that's this: https://github.com/felixrieseberg/ember-electron/issues/362 which you can test fixing by using the changes in this: https://github.com/felixrieseberg/ember-electron/pull/363 in your node_modules/ember-electron/lib.

But that only gets you to a different error, "An error occurred while making for target: squirrel" and the ENOENT error which appears to be the same as this: https://github.com/electron/windows-installer/issues/220

**Comment by MatthewDorner** [comment]
btw you can enable debug messages for the build in Windows by Control Panel -> System -> Advanced System Settings -> Environmental Variables -> and then add a variable of "DEBUG" with value "*". At least that works for me using git-bash.

**Comment by MatthewDorner** [comment]
I got it to build both zip and squirrel executables for both 32 and 64 bit. Here is everything I did:

- make the icon changes as mentioned earlier in thread
- use the ember-electron changes from here https://github.com/felixrieseberg/ember-electron/pull/363
- add this additional "asar" option in electron-forge-config.js:
![electron-forge-config](https://user-images.githubusercontent.com/36939751/46126754-126b4100-c1f4-11e8-9a8b-36fc1417986b.png)
- make sure to install .NET framework on your windows system (I installed 4.5.2 and that worked)
- do all of this on a 64-bit version of Windows (in my case, 7 x64 Pro)
- to build the 32-bit version you have to do "ember electron:make --platform=win32 --arch=ia32", "ember electron:make --platform=win32" will build 64-bit

not sure if all of the above are strictly necessary but it's what eventually got it working for me

**Comment by MatthewDorner** [comment]
Yes, the fix is that PR I listed, which is merged in now but not released yet. Once it's released on npm we'll get it automatically.

**Comment by nourudeen** [comment]
Pls I want to try this app. How do I do step by step on windows 10?

**Comment by MatthewDorner** [comment]
@nourudeen there are Electron for Windows files here for the beta release: https://github.com/HospitalRun/hospitalrun-frontend/releases/ or the demo site http://hospitalrun.io/demo/
