### ISSUE TITLE
Can't Deploy HospitalRun on Ethernet

### ISSUE THREAD

**Issue by Ethicalinfotec** [HospitalRun/hospitalrun-frontend#1520]
I Have deployed Hospitalrun on UBUNTU 16.04. It is perfectly working on machine on 172.18.0.5 but how do i make it available on Intranet.. Any help will be appreciated.

**Comment by Ethicalinfotec** [comment]
Actually i am new to this. After i deployed it on my machine its working fine but someone else with same network tries to ping my IP it does open the default login page of hospitalRun. How ever i am not sure how to use DomainName. I have a domain i pointed it to my server's IP but Nginx returns an verification error.

**Comment by MatthewDorner** [comment]
Can you post the Nginx error?

**Comment by Ethicalinfotec** [comment]
nginx_1          | Installation succeeded.
nginx_1          | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx_1          | Plugins selected: Authenticator standalone, Installer None
nginx_1          | Obtaining a new certificate
nginx_1          | Performing the following challenges:
nginx_1          | http-01 challenge for www.remoteopd.com
nginx_1          | Waiting for verification...
nginx_1          | Cleaning up challenges
nginx_1          | Failed authorization procedure. www.remoteopd.com (http-01): urn:ietf:params:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://www.remoteopd.com/.well-known/acme-challenge/7jikYcRqZCNbEYUTo5K3LRFQUudVKnqJHwpgNp0MzGA: Timeout during connect (likely firewall problem)
nginx_1          | IMPORTANT NOTES:
nginx_1          |  - The following errors were reported by the server:
nginx_1          | 
nginx_1          |    Domain: www.remoteopd.com
nginx_1          |    Type:   connection
nginx_1          |    Detail: Fetching
nginx_1          |    http://www.remoteopd.com/.well-known/acme-challenge/7jikYcRqZCNbEYUTo5K3LRFQUudVKnqJHwpgNp0MzGA:
nginx_1          |    Timeout during connect (likely firewall problem)
nginx_1          | 
nginx_1          |    To fix these errors, please make sure that your domain name was
nginx_1          |    entered correctly and the DNS A/AAAA record(s) for that domain
nginx_1          |    contain(s) the right IP address. Additionally, please check that
nginx_1          |    your computer has a publicly routable IP address and that no
nginx_1          |    firewalls are preventing the server from communicating with the
nginx_1          |    client. If you're using the webroot plugin, you should also verify
nginx_1          |    that you are serving files from the webroot path you provided.
nginx_1          | 2018/09/28 08:05:08 [emerg] 219#219: BIO_new_file("/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1          | nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
hospitalrunserver_nginx_1 exited with code 1

**Comment by MatthewDorner** [comment]
It seems like a firewall issue. Your firewall must allow the incoming connection from LetsEncrypt's servers in order to get your SSL certificate set up.

LetsEncrypt is mostly intended for setting up HospitalRun on a cloud server or one that will be made accessible over the internet, but there's another option where you can supply your own SSL certificate instead. See "To instead use your own SSL cert..." here:

https://github.com/HospitalRun/hospitalrun-server/blob/master/DEPLOYMENT_GUIDE.md

The server does require an SSL certificate one way or another, as it won't work over regular http.

**Comment by Ethicalinfotec** [comment]
nginx_1          | Saving debug log to /var/log/letsencrypt/letsencrypt.log
nginx_1          | Plugins selected: Authenticator standalone, Installer None
nginx_1          | Obtaining a new certificate
nginx_1          | Performing the following challenges:
nginx_1          | http-01 challenge for www.remoteopd.com
nginx_1          | Waiting for verification...
nginx_1          | Cleaning up challenges
nginx_1          | Failed authorization procedure. www.remoteopd.com (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://www.remoteopd.com/.well-known/acme-challenge/IJLk-Yzz3lb8lH1VzPBDYUo29v9klyosnBZtJdL-DWU: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"
nginx_1          | IMPORTANT NOTES:
nginx_1          |  - The following errors were reported by the server:
nginx_1          | 
nginx_1          |    Domain: www.remoteopd.com
nginx_1          |    Type:   unauthorized
nginx_1          |    Detail: Invalid response from
nginx_1          |    http://www.remoteopd.com/.well-known/acme-challenge/IJLk-Yzz3lb8lH1VzPBDYUo29v9klyosnBZtJdL-DWU:
nginx_1          |    "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body
nginx_1          |    bgcolor=\"white\">\r\n<center><h1>404 Not
nginx_1          |    Found</h1></center>\r\n<hr><center>"
nginx_1          | 
nginx_1          |    To fix these errors, please make sure that your domain name was
nginx_1          |    entered correctly and the DNS A/AAAA record(s) for that domain
nginx_1          |    contain(s) the right IP address.
nginx_1          | 2018/10/01 07:33:50 [emerg] 56#56: BIO_new_file("/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx_1          | nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/www.remoteopd.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
hospitalrunserver_nginx_1 exited with code 1
