### ISSUE TITLE
Create Electron Build/Deployment Script That Can Run In CI

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1521]
We need to improve the durability/availability of Electron Builds. An essential component is building/deploying electron executables to a cloud storage area (we're using [DigitalOcean, but has the same API as S3](https://developers.digitalocean.com/documentation/spaces)).

### Project
Create script that runs the electron build commands, then uploads the build artifacts into remote storage that matches the tags of the current build. See @donaldwasserman for more information

### Acceptance Critera
* Configured with environment variables from CI (including credentials, bucket names, etc)
* Written in ES6+ Javascript
* Can be run with minimal configuration in Travis and Appveyor

**Comment by MatthewDorner** [comment]
After some troubleshooting on https://github.com/HospitalRun/hospitalrun-frontend/issues/1518, I got Appveyor to build the Electron build artifacts:

https://github.com/MatthewDorner/hospitalrun-frontend/tree/appveyor-test
https://ci.appveyor.com/project/MatthewDorner/hospitalrun-frontend/build/12
https://ci.appveyor.com/project/MatthewDorner/hospitalrun-frontend/build/artifacts
