### ISSUE TITLE
Replace Typeahead.js

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1522]
Twitter's Typeahead.js autocomplete widget has been mostly abandoned. There are better, more performant ways of doing typeahead search. 

Replace typeahead.js with a combination of ember-power-select, ember-concurrency, or https://github.com/cibernox/ember-power-select-typeahead

**Comment by darrylpargeter** [comment]
@tangollama/ @donaldwasserman would it be possible to tackle this one?

**Comment by donaldwasserman** [comment]
@darrylpargeter Thanks for the help!

Please be sure to reference this issue in your PR and include relevant tests!

If you have any questions, don't hesitate to check-in on slack

**Comment by FalkF** [comment]
@darrylpargeter is this still WIP or may I give it a try?

**Comment by cukejianya** [comment]
@darrylpargeter @FalkF @donaldwasserman Is this issue still being worked on? If not, can I work on it?

**Comment by fox1t** [comment]
Hi, we are in the process of the complete HospitalRun rewrite using React and more modern tools.  Any further PRs to the current version (1.0.0-beta) will be not merged. 
However, if you want to contribute, we will be happy to have you on board for the 2.0.0 release.

**Comment by cukejianya** [comment]
@fox1t That would be great. So should I be focusing on issues with the `v2.x` tags only?

**Comment by fox1t** [comment]
@cukejianya Exactly! We are almost ready to reveal the public roadmap and open the first issues. Then we can focus on v2.x. At the moment that tag is used to mark "old issues" that will need to be addressed also in the upcoming version. :)
