### ISSUE TITLE
Create Script To Find Missing Translations

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1523]
We should have appropriate translations for all strings in the application. A bit of time has passed since the initial translation efforts, and we need a more robust way to tracking, cataloguing, and prioritizing missing translations. 

### Project
- Create an npm script that can be run that outputs a list of missing translations
- Ideally we could run these in some sort of automated fashion and create a code-climate-esq report of the current translation status
- Investigate pro-bot as a solution to this

**Comment by PatrM** [comment]
Hey!
I"d like to work on this

**Comment by donaldwasserman** [comment]
@PatrM Thanks!

**Comment by rakhi2104** [comment]
If @PatrM isn't working on it yet, I'll take this up.

**Comment by donaldwasserman** [comment]
Hey @rakhi2104 If you could do that, it would be great!

**Comment by chadian** [comment]
Just a note that this might be resolved with the move to `ember-intl` on my PR: #1553. At build time `ember-intl` checks which translations are missing between the language.

**Comment by donaldwasserman** [comment]
@chadian Thanks for all your help - I created this ticket before there was a solid plan on what was happening iwth ember-i18n. 

I'll close this for now.
