### ISSUE TITLE
Replace Ember I18n with Ember-Intl

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1524]
The Internalization system in Hospital Run works quite well right now for strings. However, in the time since HR originally was written, there have been several developments in both browser API's and technologies that changed some of the underlying assumptions of Ember-Intl. 

There are several points of difference between the Ember-I18N and Ember-Intl: 

- Ember I18n doesn't support ICU syntax and isn't aware of new browser locale API's
- Ember I18n [plans to deprecate itself](https://github.com/jamesarosen/ember-i18n/issues/481)
- Ember-Intl also handles date, relative time, and number formatting
- Ember-Intl also supports asynchronous loading of translation files

There are several outstanding issues that could be solved by this: #990, #1501, #1430 etc 

This is somewhat of a major effort, but there may be a [community driven codemod solution outlined here](https://github.com/jamesarosen/ember-i18n/issues/481)

**Comment by chadian** [comment]
Hello, I would like to give this a shot. I've worked with both libraries in separate ember apps and think it would be interesting.

**Comment by donaldwasserman** [comment]
Hey @chadian Sorry for taking a while to get back from you, but we'd love to have the help!

**Comment by chadian** [comment]
Hello @donaldwasserman. No problem! Yeah, I'm still interested in this issue. Thanks.

**Comment by donaldwasserman** [comment]
@chadian - I don't have the link handy, but I saw that DockYard published a codemod to help with the transition.
