### ISSUE TITLE
incident reports don't work

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1527]
**Expected behavior:**
Incident/reports route should let you generate the two reports there: "Incidents by Department" and "Incidents by Category".

**Actual behavior:**
Clicking the "Generate Report" button doesn't do anything, shows error in Javascript console: "Error: undefined at incident/reports/controller.js:161".
Also the "Generate Report" button doesn't visually match other buttons, it's black text on green instead of white text on green.
I made sure to enter Incident Categories, Incident Departments and Incidents into the database before trying this.

**OS and Browser:**
Ubuntu 18.04, Chromium

**Comment by jackcmeyer** [comment]
@MatthewDorner I'd like to take a shot at this!

**Comment by AaronTJDev** [comment]
Hi, I'm a first time contributor. Can I take this? @matthewdorner

**Comment by donaldwasserman** [comment]
Well @jackcmeyer looks like he got here first, so I'm going to mark it in progress for him to take care of. If @jackcmeyer doesn't want to do it, it's all your's @AaronTJDev. 

@AaronTJDev, I'd be happy to find the perfect ticket for you!

**Comment by AaronTJDev** [comment]
@donaldwasserman @jackmeyer yeah my page hadn't refreshed before I commented lol. And sounds good, Thank you.

**Comment by jackcmeyer** [comment]
@MatthewDorner I noticed that the Export Report button for Incidents is different than inventory. Would you like me to fix that as apart of this issue as well, or open a new issue?

![image](https://user-images.githubusercontent.com/18731800/47195128-218b6d80-d320-11e8-93d4-40501a680a93.png)

![image](https://user-images.githubusercontent.com/18731800/47195139-2e0fc600-d320-11e8-812b-d49a8d94f156.png)

**Comment by MatthewDorner** [comment]
Thanks. We can fix it at the same time along with this issue.
