### ISSUE TITLE
Ember Upgrade Paths

### ISSUE THREAD

**Issue by donaldwasserman** [HospitalRun/hospitalrun-frontend#1528]
This ticket contains a few different issues centered around maintaining ember + friends (these are the community packages of `ember-source`, `ember-data`, and `ember-cli`. There are few things to make this easy (TM). 

- [ ] Install [Ember Cli Update](https://github.com/ember-cli/ember-cli-update). This addon makes it easy to upgrade the three main ember packages + associated filesystem changes + possible codemods needed
- [ ] Implement [Ember Try](https://github.com/ember-cli/ember-try) to run the test suite against future versions of ember

**Comment by donaldwasserman** [comment]
cc: @AaronTJDev If you're interested, let me know!

**Comment by AaronTJDev** [comment]
I'll take it! 👍

**Comment by donaldwasserman** [comment]
Thanks!

**Comment by AaronTJDev** [comment]
Alright, so I've been able to implement ember-try. It ran the test suite, but failed the 4 tests. So, I'm not sure if I'm done with this, is my objective to just implement it so we can run the tests with ember try. Or implement so we can run and pass the tests with ember try?

**Comment by donaldwasserman** [comment]
Thanks for the work!

So all the tests _should_ pass with the current and beta scenarios. We may have some issues upgrading from 2.18 to 3.5. 

So maybe the best thing is to create 1 PR upgrading ember, and a second implementing ember try. I’m out on vacation this week, but we can connect next week via slack.
