### ISSUE TITLE
Move config from DB to configuration file

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#153]
Right now there is a Couch/Pouch config database that we currently only use to determine whether or not to use google auth for login.  This should be replaced with a value in the config.js file used by the server.

Additionally we use that pouchdb to store oauth credentials locally.  This needs to use [Ember Simple Auth](http://ember-simple-auth.com/) for storage.

**Comment by tangollama** [comment]
Where is this at @jkleinsc?
