### ISSUE TITLE
While running "Yarn install" inside the cloned folder.Can anyone help me to solve these error?

### ISSUE THREAD

**Issue by akash65** [HospitalRun/hospitalrun-frontend#1531]
**Expected behavior:**
While running "Yarn install" inside the cloned folder.error occurs
**Actual behavior:**
It taking too much time too retrive the package
**Steps to reproduce:**

**Screenshots (if applicable):**
![screenshot 141](https://user-images.githubusercontent.com/12798776/46850073-fe3c5c00-ce0f-11e8-9a93-541a9fa6c757.png)

**OS and Browser:**
windows 8.1 pro

**Comment by koshyviv** [comment]
Have the exactly same issue

**Comment by MatthewDorner** [comment]
I'm not having any problem with node 6.14.4, npm 3.10.10, yarn v1.9.4.

@koshyviv what version is your yarn? (yarn -v)

**Comment by koshyviv** [comment]
I have:

Yarn - 1.10.1
NPM - 6.4.1
Node - 6.14.4

**Comment by MatthewDorner** [comment]
could it be related to having an older version of yarn?

**Comment by koshyviv** [comment]
My yarn version is the latest, do you want me to try downgrade it ti 1.9.4?

Do you think also this maybe a node/npm issue?

**Comment by MatthewDorner** [comment]
or you could also just try npm install, we only just changed the instructions to use yarn instead, but yarn had been working fine.

**Comment by koshyviv** [comment]
Thanks @MatthewDorner. Its working now - seems to be a network issue. 

Increased the timeout to 10mins in the `.yarnrc` ([source](https://github.com/yarnpkg/yarn/issues/5540#issuecomment-374069461))
`network-timeout 600000`

@akash65 you can try the same

**Comment by ShivaAnan** [comment]
Hello i'm having this issue when i tried to enter sudo yarn install
Yarn version: 
  1.15.2
Node version: 
  10.15.3
Platform: 
  linux ubuntu 16.04 - x64
![Screenshot from 2019-04-16 03-30-49](https://user-images.githubusercontent.com/18366231/56168258-35c2d580-5ff8-11e9-8288-1a59bb7246ff.png)

P.S: im new to node and npm.. Please help me with this

**Comment by XuYanMa** [comment]
I have the same question with @Shivv33 .
