### ISSUE TITLE
incident report doesn't display current date if no end date is selected

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1543]
When generating an incident report without an end date, the report does not display the current date for the end date in the report title or the file name of the exported report. I think this is especially confusing if a user saves this file for records, since it will not have an end date.  

**Expected behavior:**
Unsure, however I think that either of the following would make sense: 
1. Require both start and end date and not allow a report to be generated if one is not supplied and display an error to the user
2. Display the current date in the report title and exported report

I think two makes the most sense because it seems that it was deliberately coded to make it so an end date would not have to be selected. 

**Actual behavior:**
End date is not displaying in the title if none is selected.

**Steps to reproduce:**
1. Go to Incidents -> Reports
2. Select a start date
3. Do not select an end date
4. Generate Report
5. Look at report title
6. Export Report
7. Look at report file name

**Screenshots (if applicable):**
![image](https://user-images.githubusercontent.com/18731800/47402125-b370ed00-d709-11e8-9d1f-7e63c5af5d12.png)

**OS and Browser:**
MacOs, Chrome

**Comment by MatthewDorner** [comment]
I also think 2. Also Inventory and Patient reports have the same problem.

We could also say "Present" instead as it's more accurate to what the database query is. Just thinking of if the user PC's date was off or if there were multiple time zones, depending on how "current date" is determined.

**Comment by MatthewDorner** [comment]
There could also be a separate field, "Date report generated" which would be understood as based off whatever "current date" the software determines. This would be helpful for all reports really.

Not sure what's best, just what came to mind.

**Comment by jackcmeyer** [comment]
After doing a quick test with `moment()`, it appears that it uses the user's system time to calculate "current date". 

I think putting "Present" in the title is a good idea, however, this might be weird when saving files.

**Comment by donaldwasserman** [comment]
@jackcmeyer @MatthewDorner As a quick drive-by comment, whatever we choose for a label in this instance, we should try to find something we have a lot of translations for already :)
