### ISSUE TITLE
Swap ember-browserify for ember-auto-import for npm-installed modules

### ISSUE THREAD

**Issue by chadian** [HospitalRun/hospitalrun-frontend#1544]
**Expected behavior:**
Use npm modules without `ember-browserify` as it is deprecated and the community is moving to `ember-auto-import`

**Actual behavior:**
Use `ember-auto-import` and drop `npm:` prefixes in imports

**Steps to reproduce:**
N/A

**Screenshots (if applicable):**
N/A

**OS and Browser:**
N/A

**Comment by chadian** [comment]
I would like to try to submit a PR against but wanted to first document it for reference.

**Comment by donaldwasserman** [comment]
@chadian - If you take a stab at that, it would be great! 

I initially tried doing that when removing bower, but ran into several issues that I couldn't resolve. To be honest, I'm not sure ember-browserify is really being used. I used broccoli to import some of the other dependencies when I removed bower.

A few other issues to be aware of surrounding this:

#1522 - Replacing typeahead
#1501 - Replacing Pikaday
#1511 - Replacing bootstrap.js with ember bootstrap

**Comment by chadian** [comment]
I think removing bower could be a separate effort, but this should lay the groundwork for re-implementing packages from bower via npm.
