### ISSUE TITLE
Hebrew translation issues

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1566]
While testing https://github.com/HospitalRun/hospitalrun-frontend/pull/1553, we found issues in the Hebrew translation file `translations/he.json`.

- Some translations are causing warning messages to show when the Ember app starts up. These are due to either empty `{}` parameters in the translation string or other invalid characters. I'm not sure if this means these will use the English fallback locale or not.
- Others don't cause warnings, but they cause uncaught errors in the app when the translation is used. These are due to the parameter name itself having been translated. For example, `"incidentCategorySaved": "הקטגוריה {שם} נשמרה."`. The text inside of the `{}` should not have been translated, it should just be `name` because that's the parameter name.

In some of these cases, you can make a guess as to the correct fix, but others require someone with knowledge of Hebrew. It could be better to wait and have it all done by that person, particularly if the translator may have thought the parameter name was part of the message instead of a parameter, or something like that, and so they might have translated other parts of the message differently.

**Comment by MatthewDorner** [comment]
@morsh, it seems that you did the original translations. If you're able to help again, I can answer any questions you may have.

**Comment by morsh** [comment]
@matthewdorner - sure, but it will take me ~2 weeks since I'm traveling ATM
