### ISSUE TITLE
Intermittent acceptance test failures

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1574]
**Expected behavior:**
All tests pass or fail consistently.

**Actual behavior:**
Some acceptance tests fail intermittently. I observed this every once in a while since I started working on the project, but it has gotten worse at some point in the past few months, causing Greenkeeper builds to fail: https://github.com/HospitalRun/hospitalrun-frontend/issues/1546,  https://github.com/HospitalRun/hospitalrun-frontend/issues/1565, https://github.com/HospitalRun/hospitalrun-frontend/issues/1571, https://github.com/HospitalRun/hospitalrun-frontend/issues/1572. Not clear if it's been affected by https://github.com/HospitalRun/hospitalrun-frontend/pull/1560. Two of the build failures happened before that PR but two happened after. All the builds passed after I restarted them.

I ran the test suite many times and found these tests failed most often:
1123 Chrome 70.0 - Acceptance \| patient notes: add a note from Edit Patient
1124 Chrome 70.0 - Acceptance \| patients: visiting /patients route
1194 Chrome 70.0 - Acceptance \| visits: Edit visit

These failed, but not as often:
1018 Chrome 70.0 - Acceptance \| appointments: visiting /appointments/search
1019 Chrome 70.0 - Acceptance \| appointments: Theater scheduling
1026 Chrome 70.0 - Acceptance \| Incidents: Incident category management
1089 Chrome 70.0 - Acceptance \| invoices: pricing profiles
1097 Chrome 70.0 - Acceptance \| invoices: Calculate totals
1119 Chrome 70.0 - Acceptance \| Operative Plan and Operation Report: Plan and report creation
1154 Chrome 70.0 - Acceptance \| patients: Delete a patient record
1169 Chrome 70.0 - Acceptance \| procedures: Edit procedure
1191 Chrome 70.0 - Acceptance \| visits: Add OPD visit

I would like to think that by looking at these particular tests, I could figure out what they have in common, but haven't been able to do it so far.

**OS and Browser:**
Chrome 70.0, Ubuntu 18.04

**Comment by mansona** [comment]
So I have just come across this with my PR to help get the master building again: https://github.com/HospitalRun/hospitalrun-frontend/pull/1616

It seems like these tests might have something to do with PouchDB rather than Ember. I have done a little bit of digging into the issue over the weekend and it seems like we're either using a real CouchDB connection when running tests (when running `npm start` and visiting http://localhost:4200/tests) or we are using an in-memory CouchDB/PouchDB instance when running tests in CI. 

I have seen some documentation about eventual consistency in PouchDB so that could be what is causing the tests to sometimes fail, some of the tests are dependent on each other and sometimes they happen in a slightly different order which means that the store is populated with slightly different data for a test.

**Comment by lifeart** [comment]
Any Ideas why CI is failing on

![image](https://user-images.githubusercontent.com/1360552/62853864-54ab4d00-bcf6-11e9-9264-a9bcbb9e1074.png)

?

**Comment by MatthewDorner** [comment]
@mansona the app always runs an in-memory PouchDB (in fact, it runs two of them - one in the main thread and one in the service worker), but I don't think this problem involves eventual consistency.

The database requests from the app go to the main thread PouchDB, which does nothing except proxy them over to the service worker PouchDB (where the data is stored in the browser's indexedDB) so the database operation can run without blocking the UI thread, and then that service worker PouchDB runs two-way replication with the remote CouchDB if it exists. If CouchDB doesn't exist, the app behaves the same way but the data only makes it into the service worker PouchDB / indexedDB, and I don't think it uses CouchDB during the tests so the data flow during tests should be pretty simple.

I thought this bug must involve the test engine but I couldn't figure out where to even start.

**Comment by mansona** [comment]
So the thing that I have found is that some of the tests depend on data that either a) is missing for some random reason or b) was actually created in a previous test

I notice that ember-exam is installed but for some reason it's not quite working when I run it  🤔 if we ran ember-exam with some concurrency and randomization we would find all of the tests that have interdependencies very quickly
