### ISSUE TITLE
Unabe to login to the frontend

### ISSUE THREAD

**Issue by habibhermes** [HospitalRun/hospitalrun-frontend#1577]
**Expected behavior:**I followed all the steps in the installation guideline but I am not able to login into the system.

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**
When I run yarn start, this is a screensot of the error i get:
![image](https://user-images.githubusercontent.com/22241610/50377797-9d08e400-061b-11e9-8740-f86459a49e7a.png)

This is the error i get when i try to login
![image](https://user-images.githubusercontent.com/22241610/50377776-4ac7c300-061b-11e9-9c11-9b8c564f7191.png)

**OS and Browser:**

**Comment by donaldwasserman** [comment]
What password are you using? The one that’s defined in the config file or the existing config?

**Comment by mikeelemuel** [comment]
I was able to login using the Username: `hradmin` and password: `test`

**Comment by mikeelemuel** [comment]
@habibhermes what is the version of your couchDb?
