### ISSUE TITLE
Operation Report doesn't save Diagnoses

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1578]
**Expected behavior:**
When you create an Operative Plan, it automatically populates the Diagnoses from the Patient. When you create an Operation Report (by completing an Operative Plan), it automatically populates the Diagnoses from the Operative Plan.

**Actual behavior:**
While Operation Report does copy the Diagnoses from the Operative Plan, it doesn't save them. So when you originally create the Operation Report, you'll see the Diagnoses listed. If you close your browser and go back to that Operation Report, you'll see: 
![operation report bug](https://user-images.githubusercontent.com/36939751/50576326-4ea2d480-0dd5-11e9-9d3d-a71438083bc1.png)

**Steps to reproduce:**
- Create a Patient
- Add some Diagnoses
- Create an Operative Plan and click "Complete" so it turns into an Operation Report
- Observe that the Diagnoses appear at the top of the Operation Report
- Close and re-open browser and go back to that Operation Report (listed under "Procedures" on the patient summary)
- Observe that the Diagnoses are blank and console error appears.

Also notice that the "Add Diagnosis" button on the Operation Report doesn't work.

**OS and Browser:**
Ubuntu 18.04, Chrome v70

**Comment by jackcmeyer** [comment]
Can I take a look at this one @MatthewDorner?

**Comment by MatthewDorner** [comment]
@jackcmeyer  sure

**Comment by MatthewDorner** [comment]
Actually I guess there are pre-op and post-op diagnoses. To clarify where the diagnoses are supposed to come from, see: https://github.com/HospitalRun/planning/blob/master/Requirements/v1_0/Operation-Report.md
