### ISSUE TITLE
Search Doesn't Work

### ISSUE THREAD

**Issue by aalmangour** [HospitalRun/hospitalrun-frontend#1583]
Expected behavior: 
Search result

Actual behavior: 
No result is returned even though the data contains the searched for term.

Steps to reproduce: 
Search for a patient from the patients list using first name for example.

Screenshots (if applicable):
![image](https://user-images.githubusercontent.com/25371349/51782082-bb3e9400-2133-11e9-92c9-bcbfc3653673.png)

OS and Browser: 
Windows 10, Chrome

The search doesn't work anywhere with me and I keep getting this error in the browser console:
error: "bad_request"
message: "Referer header must match host."
name: "bad_request"
reason: "Referer header must match host."
status: 400

I don't have Elasticsearch installed, I don't know if it's required for the search to work or not.

**Comment by MatthewDorner** [comment]
I haven't seen this. ElasticSearch is not required.

I guess I would try to find what the referer and host headers are for the request that's causing your issue. This may be found in couchdb.log. There is some info here https://github.com/pouchdb/pouchdb/issues/5810.

**Comment by aalmangour** [comment]
I changed the the couchdb config file and added the origin and it worked!
Thank you @MatthewDorner

**Comment by degodfather** [comment]
@aalmangour could you share the steps to fix the search?  I'm kinda stuck. Even the online demo has the same issue.

**Comment by OmarBest7** [comment]
I have the same problem, how did you solve it?
