### ISSUE TITLE
I can input any value on the *Civil Status* field

### ISSUE THREAD

**Issue by mikeelemuel** [HospitalRun/hospitalrun-frontend#1590]
**Expected behavior:**

I should be able to select a value that are listed on the frontend for `Civil Status`

**Actual behavior:**

I was able to type any text with regards to may `Civil Status`

**Steps to reproduce:**

Please navigate top `Patients` > Edit Patient > Social Work. Click the `Add Family Member` and input any text on the `Civil Status` field and click `add`

**Screenshots (if applicable):**

<img width="1680" alt="screen shot 2019-02-15 at 10 58 10 am" src="https://user-images.githubusercontent.com/29329111/52831745-bbb5c380-3110-11e9-96c9-686ad6501819.png">
<img width="1680" alt="screen shot 2019-02-15 at 10 58 21 am" src="https://user-images.githubusercontent.com/29329111/52831750-be181d80-3110-11e9-9055-9bb6901a0ec5.png">

**OS and Browser:**
OS: `macOs Mojave`
Browser: `Google Chrome`

**Comment by MatheusNtg** [comment]
@tangollama I'll try to fix it
