### ISSUE TITLE
Error should occur for duplicate value

### ISSUE THREAD

**Issue by mikeelemuel** [HospitalRun/hospitalrun-frontend#1591]
**Expected behavior:**

I should be getting error if I input the same name that had already been on the list

**Actual behavior:**

I was able to create another family member on `Social work` tab with the same name that had already been added previously.

**Steps to reproduce:**

Please navigate top `Patients` > Edit Patient > Social Work. Click the `Add Family Member` and input the same name you've added previously and click `add`

**Screenshots (if applicable):**

<img alt="screen shot 2019-02-15 at 10 58 10 am" width="1680" src="https://user-images.githubusercontent.com/29329111/52831745-bbb5c380-3110-11e9-96c9-686ad6501819.png">

<img alt="screen shot 2019-02-15 at 10 58 21 am" width="1680" src="https://user-images.githubusercontent.com/29329111/52831750-be181d80-3110-11e9-9055-9bb6901a0ec5.png">

**OS and Browser:**
OS: `macOs Mojave`
Browser: `Google Chrome`

**Comment by Gibbo3771** [comment]
What if there are two family members with the same name?

I have both an uncle and a cousin called Jim Baxter.

**Comment by pdrzq8** [comment]
> 
> 
> What if there are two family members with the same name?
> 
> I have both an uncle and a cousin called Jim Baxter.

Instead of an error, should it just show an alert pop-up, so the user can confirm whether or not they intended to enter a second entity with the same name?

**Comment by mikeelemuel** [comment]
I think a alert pop-up is useful.
