### ISSUE TITLE
BUILD error

### ISSUE THREAD

**Issue by binadiegha** [HospitalRun/hospitalrun-frontend#1601]
everytime i run `yarn install` i get the followin errors when fetching packages

`info electron-installer-debian@1.0.0: The platform "win32" is incompatible with this module.
info "electron-installer-debian@1.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info electron-installer-flatpak@0.8.0: The platform "win32" is incompatible with this module.
info "electron-installer-flatpak@0.8.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info electron-installer-redhat@0.5.0: The platform "win32" is incompatible with this module.
info "electron-installer-redhat@0.5.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info appdmg@0.4.5: The platform "win32" is incompatible with this module.
info "appdmg@0.4.5" is an optional dependency and failed compatibility check. Excluding it from installation.
info fs-xattr@0.1.17: The platform "win32" is incompatible with this module.
info "fs-xattr@0.1.17" is an optional dependency and failed compatibility check. Excluding it from installation.
info macos-alias@0.2.11: The platform "win32" is incompatible with this module.
info "macos-alias@0.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info electron-installer-debian@0.8.1: The platform "win32" is incompatible with this module.
info "electron-installer-debian@0.8.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/7] ⠐ waiting...
[2/7] ⠐ electron
[3/7] ⠈ node-sass
[4/7] ⠈ leveldown
error C:\Users\BYHESLB\Documents\hospital run files\hospitalrun-frontend-master\node_modules\pouchdb\node_modules\leveldown: Command failed.
Exit code: 2
Command: prebuild --install
Arguments:
Directory: C:\Users\BYHESLB\Documents\hospital run files\hospitalrun-frontend-master\node_modules\pouchdb\node_modules\leveldown
Output:
prebuild info begin Prebuild version 4.5.0
prebuild ERR! configure error
prebuild ERR! stack Error: Command failed: C:\python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! stack   File "<string>", line 1
prebuild ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! stack                                ^
prebuild ERR! stack SyntaxError: invalid syntax
prebuild ERR! stack
prebuild ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
prebuild ERR! stack     at ChildProcess.emit (events.js:189:13)
prebuild ERR! stack     at maybeClose (internal/child_process.js:970:16)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
prebuild ERR! not ok
prebuild ERR! build Error: Command failed: C:\python\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! build   File "<string>", line 1
prebuild ERR! build     import sys; print "%s.%s.%s" % sys.version_info[:3];
prebuild ERR! build                                ^
prebuild ERR! build SyntaxError: invalid syntax
prebuild ERR! build
prebuild ERR! build     at ChildProcess.exithandler (child_process.js:294:12)
prebuild ERR! build     at ChildProcess.emit (events.js:189:13)
prebuild ERR! build     at maybeClose (internal/child_process.js:970:16)

`

**Comment by prbobba** [comment]
which version of python are you using?

**Comment by tehKapa** [comment]
Hi @binadiegha! 
We're [now working on a new major version](https://github.com/HospitalRun/hospitalrun-frontend/issues/1605#issuecomment-518749445) (2.0) of HospitalRun. Sadly, your request can't be resolved, so we're forced to close this issue.
