### ISSUE TITLE
docker-compose fails to build web service

### ISSUE THREAD

**Issue by junelsolis** [HospitalRun/hospitalrun-frontend#1604]
**Expected behavior:**
Running `docker-compose up -d` will build and bring up the containers

**Actual behavior:**
Running `docker-compose up -d` fails to build the web service. The image build fails at `Step 5/14  RUN cd /tmp && yarn install --silent`. The last error lines shown before the process exits are
``` 
warning pouchdb-load > pouchdb-ajax > request > tough-cookie@2.2.2: ReDoS 
vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
warning pouchdb-load > pouchdb-ajax > request > node-uuid@1.4.8: Use uuid module instead

error ansi-escapes@4.1.0: The engine "node" is incompatible with this module. Expected version ">=8". Got "6.17.1"
error Found incompatible module
```
**Steps to reproduce:**
- clone the hospitalrun-frontend repository
- `cd hospitalrun-frontend`
- `docker-compose up -d`

**Comment by moda20** [comment]
This is a real issue, did anybody fix it somehow ?

**Comment by rssfed23** [comment]
Also experiencing this
`Step 3/14 : RUN yarn global add ember-cli@latest
 ---> Running in fb3d26c888e2
yarn global v1.15.2
[1/4] Resolving packages...
warning ember-cli > broccoli-babel-transpiler > @babel/polyfill@7.4.4: 🚨 As of Babel 7.4.0, this
package has been deprecated in favor of directly
including core-js/stable (to polyfill ECMAScript
features) and regenerator-runtime/runtime
(needed to use transpiled generator functions):

  > import "core-js/stable";
  > import "regenerator-runtime/runtime";
[2/4] Fetching packages...
error broccoli@3.1.2: The engine "node" is incompatible with this module. Expected version "8.* || >= 10.*". Got "6.17.1"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
ERROR: Service 'web' failed to build: The command '/bin/sh -c yarn global add ember-cli@latest' returned a non-zero code: 1`

**Comment by zenny** [comment]
+1

Same at this end:

```
# docker-compose up
Building web
Step 1/14 : FROM node:6-alpine
 ---> dfc29bfa7d41
Step 2/14 : RUN apk update && apk add   bash   curl   g++   git   make   python   sudo   wget
 ---> Using cache
 ---> 5c2178d25cfc
Step 3/14 : RUN yarn global add ember-cli@latest
 ---> Running in eeafdcdceb9b
ERROR: Service 'web' failed to build: The command '/bin/sh -c yarn global add ember-cli@latest' returned a non-zero code: 139
```

**Comment by tehKapa** [comment]
Hi @junelsolis! 
We're [now working on a new major version](https://github.com/HospitalRun/hospitalrun-frontend/issues/1605#issuecomment-518749445) (2.0) of HospitalRun. Sadly, your request can't be resolved, so we're forced to close this issue.
