### ISSUE TITLE
Looking for hospital list 

### ISSUE THREAD

**Issue by rschugh** [HospitalRun/hospitalrun-frontend#1617]
We are a IT company in India and our few clients are interested to know about existing Hospitals reference list where hospital run software is running and implemented, so we can implement hospital run software also there.

Regards
Rupinder Singh

Tradeboox tech India pvt ltd 

### Please note that this issue tracker is not a help forum and this issue may be closed.

Before you submit an issue we recommend you drop into our [Spectrum channel](https://spectrum.chat/hospitalrun) and ask any questions you have or mention any problems you've had getting started with HospitalRun.

**Comment by rschugh** [comment]
Waiting for revert on it

**Comment by tehKapa** [comment]
Hi @rschugh. 
Please note that this issue tracker is not a help forum. We recommend you to join our [Spectrum channel ](https://spectrum.chat/hospitalrun) and ask any questions you have.
