### ISSUE TITLE
RTL support and new features 

### ISSUE THREAD

**Issue by mkhaleel** [HospitalRun/hospitalrun-frontend#1618]
Hello all
i would like to thank you for this application it cover almost every thing in a simple way to use for end users .
am a .net developer and i have a huge interested in work in health apps .
i was wondering if you planning to support RTL templates translation , (Hospitality management), doctor and stuff management .
i really would like to help so please feel free to share any tasks .

regards

**Comment by fox1t** [comment]
Hi @mkhaleel of course are planning to support RTL.  We are in the process of rewriting HospitalRun, using React and Fastify. We opened a new repository: https://github.com/HospitalRun/components
Would you mind to open an issue there, so we can track this? 

And welcome on board! :)
