### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by PhearZero** [HospitalRun/hospitalrun-frontend#1620]
## 🚀 Feature Proposal

Build Triggers and Package Release

## Motivation

The new [mono repository](https://github.com/HospitalRun/hospitalrun) is responsible for triggering the publishing of new packages via merging upcoming `next` features into `master` of this repository. 

- This project should run a release on any changes to master. 
- All feature/fix branches are merged into the `next` branch

## [Contributor Flow](https://nvie.com/posts/a-successful-git-branching-model/)
> Uses git-flow based branching model with `next` as the target development branch
1. Create fork
2. Clone Fork and switch to the `next branch`
3. Create branch with the following name `feat-1` replacing feat with the issue type and 1 with the top level issue this relates to. Bug example `bug-1`
4.  Create a Pull Request from your feature/fix branch to `upstream:next`
5. If the pull request is accepted and merged into `next` then the build server will trigger a mono-repo release
6. The mono-repo will run tests and then merge next into master triggering a package release or comment on the issues that have broken the build

# Backlog:

- [x] Implement Travis CI NodeJS builds
- [x] Trigger Mono Repo Build on changes to to `next branch`
- [ ] Trigger Release on changes to `master branch`

**Comment by evalsocket** [comment]
@PhearZero can i pick this one ?

**Comment by tehKapa** [comment]
@evalsocket come on in our Slack workspace and let's talk about i.

**Comment by evalsocket** [comment]
@tehKapa check contributors channel
