### ISSUE TITLE
Warnings and Errors in browser while trying to connect to the server

### ISSUE THREAD

**Issue by ruben713** [HospitalRun/hospitalrun-frontend#1622]
#### You have already researched for similar issues?

I have seen a post called 'hospitalrun loading for long time' and I tried to do the same, but it didn´t work.
#### Are you sure this is an issue with HospitalRun or are you just looking for some help?

I am looking for help because I have been searching different alternatives but any of them worked. My problem is that when I start the server by running 'yarn start' It builds successfully and everything seems fine. Nevertheless, when I go to 'localhost:4200' in any browser It is always loading and there are the following errors and warnings:
![Issue](https://user-images.githubusercontent.com/44987651/64612214-2b501080-d3cb-11e9-80fe-53af0061c56b.PNG)

If anyone knows what to do or what is the cause I will be looking forward your answer.
Thank you.

**Comment by muzafa-popo** [comment]
i came back again...  what link i needed to join.... i just no add in to link, and for the arange trade i give u all.. i want to create wallet till now i don't have..hehehe

**Comment by muzafa-popo** [comment]
can run, thank for help if ask for me about she setup, i thing next yer maybe cannot use.. hope luck have for u all.
