### ISSUE TITLE
Building docker container error

### ISSUE THREAD

**Issue by habibhermes** [HospitalRun/hospitalrun-frontend#1627]
Hello. I am trying to install the frontend module but I am not able to create the HospitalRun container using docker.
`docker run -it --name hospitalrun-frontend -p 4200:4200 --link couchdb:couchdb -d hospitalrun-frontend` .

Error mesage: docker: invalid reference format.

Thanks

**Comment by tehKapa** [comment]
Hi! 
Subscribe to our [Spectrum channel](https://spectrum.chat/hospitalrun) to talk about these issues.
