### ISSUE TITLE
DEPRECATION: The `bind-attr` helper 

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#165]
We need to address deprecation warnings like this: DEPRECATION: The `bind-attr` helper ('hospitalrun/appointments/edit/template.hbs' @ L22:C23) is deprecated in favor of HTMLBars-style bound attributes.

**Comment by billybonks** [comment]
ill do this you can assign me to it

**Comment by jkleinsc** [comment]
@billybonks it's yours.  You can fork, make the changes in your fork and then submit a pull request.

**Comment by billybonks** [comment]
https://github.com/HospitalRun/hospitalrun-frontend/pull/177

**Comment by billybonks** [comment]
you can close this issue now
