### ISSUE TITLE
Create New Patient

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1671]
## Scenario
**AS** a user with patient write access
**I WANT** to be able to create a new patient
**SO THAT** I can enter a new patient into my system

## Acceptance Criteria
**GIVEN** there is a new patient to be added to the system
**WHEN** I access the /new/patients page
**THEN** I should see a form that allows me to enter the following data: 

* Name - (prefix, given name, family name, suffix)
* Sex
* Date of Birth
* Approximate Age
* Patient Type
* Occupation
* Preferred Language
* Phone Number
* Email
* Address

**GIVEN** a new patient form
**WHEN** I select the approximate age checkbox
**THEN** A new text box appears that allows me to enter an approximate age
**AND THEN** when I enter the approximate age, the date of birth field should be populated with the date which equals current date - approximate age.

## Technical Notes
https://www.hl7.org/fhir/patient.html

## Related Issues
* #1612

**Comment by pragyanone** [comment]
there is a small typo in the Acceptance Criteria:
THEN I should see a form that allows me to enter the following ~~date~~ data

**Comment by jackcmeyer** [comment]
Thanks @pragyanone 😊
