### ISSUE TITLE
DEPRECATION: Using `{{controller}}` or any path based on it

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#169]
We need to address deprecation warnings like this: DEPRECATION: Using `{{controller}}` or any path based on it ('hospitalrun/templates/components/em-iinput.hbs' @ L2:C31) has been deprecated. [deprecation id: view.keyword.controller] See http://emberjs.com/deprecations/v1.x#toc_view-and-controller-template-keywords for more details.

**Comment by billybonks** [comment]
has this been fixed ? cant find any instances

**Comment by jkleinsc** [comment]
@billybonks it shows up in the command line console as output from ember serve (eg if you run ember serve &> deprecations.txt you can see the deprecation there).
This particular deprecation is coming from [Ember-Forms](https://github.com/indexiatech/ember-forms) which apparently isn't going to support Ember 2.x, but there is a fork [Ember-Rapid-Forms](https://github.com/piceatech/ember-rapid-forms) that should be a suitable substitute.

**Comment by jkleinsc** [comment]
@billybonks I am going to take care of this one.
