### ISSUE TITLE
Success toast after creating a patient

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1701]
## Scenario
**AS**

As a user with write access to patient data

**I WANT**

A success toast to be displayed after a patient has been successfully created 

**SO THAT**

I know that the system did what I wanted it to do.

## Acceptance Criteria
**GIVEN**

The save patient button was clicked

**WHEN**

The system successfully creates a patient 

**THEN**

It should display a toast saying that the patient was successfully created. 

## Related Issues
#1671

**Comment by theashraf** [comment]
I'd like to help with this one

**Comment by jackcmeyer** [comment]
> I'd like to help with this one

Hey @theashraf. I've been working on this issue to accomplish some other features that are currently being developed. Be on the look out for a whole bunch of new issues being opened that will be a good opportunity to contribute!
