### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#171]
Right now we have a README with basic setup instructions, and a Wiki with very minimal info about the project. We should really improve the docs ASAP for benefit of new contributors.

TODO:
- [ ] Improve README
  - [x] Add contribution info
  - [ ] Add basic info about Ember relevant to developing for it
  - [ ] Add links to more info on the server setup/server readme's
- [ ] Improve Wiki or kill it
- [ ] Surface docs on the [marketing site](http://hospitalrun.github.io/) (ultimately, this is where the docs should really live)
- [ ] Surface docs within the app (for offline use)

**Comment by bpacreau** [comment]
Hi jglovier,

I, with @g12l, are interested in helping you on this issue.
As this will be our first PR, we would like to start by working on the README improvment only.
Do you still need some helps on this part of the issue?

Thanks for your answer

**Comment by jglovier** [comment]
@bpacreau awesome! Thanks for your help.

>As this will be our first PR, we would like to start by working on the README improvment only.
Do you still need some helps on this part of the issue?

Sounds good. Yes, I still think there is a little room left for improvement in the README, although it has been improved significantly since I opened this issue. But feel free to look for areas that could be improved and work on them.

The main concern at this point (which you could address after your README improvement) is the actual codebase docs. We have some in the Wiki, but I'd like to move all of that into the app itself (possibly as a git submodule) that could be accessed directly from within the app

**Comment by g12l** [comment]
Thank you for your answer. With @bpacreau we have not found relevant improvements to do on your Readme. We won't be able to help you on this issue :(.
It's a great project anyway and we wish you all the best !

**Comment by jglovier** [comment]
Going to start a list of really great examples of docs that could serve as inspiration for ours:
- http://getbootstrap.com/css/
- https://docs.getexponent.com/versions/v9.0.0/index.html
- https://guides.emberjs.com/v2.8.0/
- https://www.polymer-project.org/1.0/docs/about_10
- https://docs.angularjs.org/api
