### ISSUE TITLE
Conditionally include New Relic Instrumentation

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#176]
Setup a config to include (or not) the ability to instrument the frontend using New Relic Insights. https://blog.newrelic.com/2015/04/03/new-relic-insights-browser-instrumentation-js-api/

**Comment by tangollama** [comment]
Actually, the server agent automatically includes the JS api. Now I just need to conditionally (i.e. check if the API is available) call events.

**Comment by jkleinsc** [comment]
@tangollama I added New Relic support with c8c36019a1d5eb24cee90d1fe28b9e5ac42e5378 (which pulls in New Relic if so configured in your config.js file.  See https://github.com/HospitalRun/hospitalrun-server-routes/releases/tag/0.9.2 for more detail.  I think that means we can close this, but can you verify?

**Comment by tangollama** [comment]
Will do. Thank you @jkleinsc.

**Comment by tangollama** [comment]
@dswanson not to pigeon-hole you, but would you be cool verifying this?
