### ISSUE TITLE
Clicking on related person should navigate to patient profile

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1763]
## Scenario
**AS**

A user who has read access to patients

**I WANT**

The ability to click on a related person and have it bring me to their patient profile

**SO THAT**

I can view information about that related peron

## Acceptance Criteria
**GIVEN**

An existing patient

AND

An existing related person

AND 

Read access to patiens
**WHEN**

I click on the related person 
**THEN**

The application should navigate the to that related person's patient profile at `/patients/:id`

**Comment by ocBruno** [comment]
Almost finished this one up, just have to finish the tests.
