### ISSUE TITLE
Add `New Patient` button on the Patients page

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1766]
## Scenario
**AS**
A user with write access to patients

**I WANT**
A `New Patient` button on the Patients page

**SO THAT**
I can quickly create new patients

## Acceptance Criteria
**GIVEN**
I access to the `/patients` route and I have write access to patients

**WHEN**
I navigate to `/patients`

**THEN**
I should see a `New Patient` button
AND
when I click on it, it should navigate me to `/patients/new`

## Related Issues
HospitalRun/hospitalrun-frontend#1671 

## Technical Notes
Button should be type `btn btn-outline-primary` and have the have an Icon with type `patient-add`

**Comment by oizuldan** [comment]
Is there anybody doing this task or can I do it?

**Comment by jackcmeyer** [comment]
I have been working on this one.
