### ISSUE TITLE
Remove related person

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1768]
## Scenario
**AS**

A user who has write access to a patient

**I WANT**

To be able to remove a related person

**SO THAT**

My data can be free of any unnecessary entries 

## Acceptance Criteria
**GIVEN**

A user with write access to patients

AND

An existing patient with related persons

**WHEN**

I go to the related persons screen

**THEN**

I should see a delete button next to each related person

AND

when I click on it the related person should be removed

## Related Issues
HospitalRun/hospitalrun-frontend#1689

**Comment by ocBruno** [comment]
I was going to give this a shot for pratice.Does anyone have any guidelines on the best design pattern approach?
I see we are storing related persons in an array and considering redux state is immutable should we create something like this code example with a new relatedPersons and just not insert the related person with a certain id?

I'm trying to leave good first issues to attract new contributors but i'm not confident in my patterns enough so I will leave some code snippets and ideas here if anyone has anything to complement or spot any bad design patterns or mistakes please give me a heads up!
```

  const onRelatedPersonSave = (relatedPerson: RelatedPerson) => {
    const newRelatedPersons: RelatedPerson[] = []

    if (patient.relatedPersons) {
      newRelatedPersons.push(...patient.relatedPersons)
    }

    newRelatedPersons.push(relatedPerson)

    const patientToUpdate = {
      ...patient,
      relatedPersons: newRelatedPersons,
    }

    dispatch(updatePatient(patientToUpdate))
    closeNewRelatedPersonModal()
  }

  const onRelatedPersonDelete = (relatedPersonId: string) => {
    const updatedRelatedPersons: RelatedPerson[] = []

    if (patient.relatedPersons) {
      patient.relatedPersons.forEach((relatedPerson) => {
        relatedPerson.id !== relatedPersonId ? updatedRelatedPersons.push(relatedPerson) : console.log('aes')
      })
    }

    const patientToUpdate = {
      ...patient,
      relatedPersons: updatedRelatedPersons,
    }

    dispatch(updatePatient(patientToUpdate))

  }
```
If someone knows of a good project with some nice design patterns we can use as reference I can analise it and try to apply some of the patterns to hospitalrun!

**Comment by aprameyakatti** [comment]
hi, I wanna contribute to this issue can I know how would I start contributing for this issue?

**Comment by jackcmeyer** [comment]
Hi @aprameyakatti. I've actually been working on this issue. I apologize for not assigning into myself to make it clear.
