### ISSUE TITLE
Add notes to patients

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1771]
## Scenario
**AS**

A user with write access to patients

**I WANT**

The ability enter notes about the patient 

**SO THAT**

I can keep track of information about the patient

## Acceptance Criteria
**GIVEN**

A user with write access to patients and an existing patient

**WHEN**

I navigate to the notes tab

**THEN**

I should see a button that allows me to add a new note. 

## Technical Notes
* Notes should be a rich text editor
* New tab where notes are located

**Comment by Pranav2612000** [comment]
I can work on this. 
A new "Notes" Tab needs to be created right?

**Comment by wwbarros** [comment]
@jackcmeyer I'd like to help with this

**Comment by jackcmeyer** [comment]
@wwbarros I've assigned this to you.

**Comment by wwbarros** [comment]
Hi guys!
Are there any rich text component recommended for use here?

**Comment by jackcmeyer** [comment]
@wwbarros Our components library has a rich text editor in it that we should use! https://components.hospitalrun.io/?path=/story/richtext--default-rich-text-editor

**Comment by wwbarros** [comment]
Hi everybody,

I'm facing some issues on creating the tests (PR #1896 ). The test to open a new modal fails to render a rich text.

`TypeError: doc.body.createTextRange is not a function`

Looking for a solution, I just found [a closed issue on tinymce project](https://github.com/tinymce/tinymce-react/issues/61).

Any suggestion?
