### ISSUE TITLE
Lint command is not fixing properly the code

### ISSUE THREAD

**Issue by fox1t** [HospitalRun/hospitalrun-frontend#1775]
## 💥 Regression Report

In this [PR](https://github.com/HospitalRun/hospitalrun-frontend/pull/1736) we discovered that the code wasn't formatted properly. 

## Last working version

Worked up to version: We don't really know

## To Reproduce

* Commit some code that is clearly not properly formatted, ex. `import {cuzz} from 'cuzzo'` instead of the correct`import { cuzz } from 'cuzzo'`.

## Expected behavior
In the above example the code should be formatted and committed correctly. 
```typescript
`import { cuzz } from 'cuzzo'`
```

**Comment by matteo1976** [comment]
can I work on this issue?

**Comment by jackcmeyer** [comment]
@matteo1976 of course!

**Comment by tehKapa** [comment]
@matteo1976 seems there is already a PR https://github.com/HospitalRun/hospitalrun-frontend/pull/1780

**Comment by ocBruno** [comment]
> can I work on this issue?
hey @matteo1976 I did a little troubleshooting here also and it seems to be something with husky and it's pre-commit lint-staged hook. Haven't figured out what's happening yet if you are also troubleshooting.
