### ISSUE TITLE
Updating patient causes duplicate due to document version conflict

### ISSUE THREAD

**Issue by MatthewDorner** [HospitalRun/hospitalrun-frontend#1783]
## 🐛 Bug Report
When you update an existing document in PouchDB, you need to give the database the `_rev` of the document that's currently in the database. If you supply an older `_rev`, it will cause a document update conflict. When we update a Patient, this creates a new `_rev` but we are not pulling that out of the database and updating our Redux state with it. The logic in `saveOrUpdate` currently falls back to a regular save when an error is thrown from `db.put`, so if you try to update a Patient twice it creates a duplicate document (the first update works).

## To Reproduce
Create a Patient and add two Related Persons. The Patient will be duplicated.

**Comment by ocBruno** [comment]
> ## 🐛 Bug Report
> When you update an existing document in PouchDB, you need to give the database the `_rev` of the document that's currently in the database. If you supply an older `_rev`, it will cause a document update conflict. When we update a Patient, this creates a new `_rev` but we are not pulling that out of the database and updating our Redux state with it. The logic in `saveOrUpdate` currently falls back to a regular save when an error is thrown from `db.put`, so if you try to update a Patient twice it creates a duplicate document (the first update works).
> 
> ## To Reproduce
> Create a Patient and add two Related Persons. The Patient will be duplicated.

Hey @MatthewDorner!

I want to learn about pouchdb and thought this issue would give me a chance to dive into it a bit more. 

- Do you suggest we create a helper to retrieve the document to be updated's _rev value beforeUpdate or keep it stored in redux to begin with. Not sure which solution is the more performant choice for when we start working with large datasets.

- For now I will try rework the logic in saveOrUpdate to return appropriate errors.

**Comment by MatthewDorner** [comment]
I'm not totally clear on the Redux stuff yet. Maybe try to find other codebases that use PouchDB and Redux and see how they do it?

**Comment by ocBruno** [comment]
> I'm not totally clear on the Redux stuff yet. Maybe try to find other codebases that use PouchDB and Redux and see how they do it?
> 
> There is also a concept of "isDirty" for telling when a data model has been modified but not been saved to database yet, that probably connects with this issue somehow.

I was taking a look at this code sample and it seems like we are sending a _rev when we update but on error we do seem to save the current state and not supply any error messages.
I'll continue troubleshooting but if anyone has any insights drop in!

  `async save(entity: T): Promise<T> {
    const { id, rev, ...valuesToSave } = entity
    const savedEntity = await this.db.put({ _id: getTime(new Date()).toString(), ...valuesToSave })
    return this.find(savedEntity.id)
  }
try {
      const existingEntity = await this.find(entity.id)
      const { id, rev, ...restOfDoc } = existingEntity
      const entityToUpdate = {
        _id: id,
        _rev: rev,
        ...restOfDoc,
        ...entity,
      }
      await this.db.put(entityToUpdate)
      return this.find(entity.id)
    } catch (error) {
      return this.save(entity)
    }`

**Comment by MatthewDorner** [comment]
saveOrUpdate does:

```
await this.db.put(entityToUpdate)
return this.find(entity.id)
```

and then `updatePatientSuccess` is supposed to set that Patient to state. So that all seems like it ought to work. I'd try debugging around those functions and see what the `_rev` of the patient being passed around it, to see where it's breaking.

**Comment by ocBruno** [comment]
> saveOrUpdate does:
> 
> ```
> await this.db.put(entityToUpdate)
> return this.find(entity.id)
> ```
> 
> and then `updatePatientSuccess` is supposed to set that Patient to state. So that all seems like it ought to work. I'd try debugging around those functions and see what the `_rev` of the patient being passed around it, to see where it's breaking.

Currently doing some debugging considering I'm having trouble even adding a related person having something to do with missing patientId on save.
