### ISSUE TITLE
Related Persons screen always shows loading when there are no related persons

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1789]
🐛 Bug Report

When a patient does not have a related person, the related person tab always shows loading. 

## To Reproduce

1. Navigate to a patient without a related person
2. Navigate to the related persons tab
3. See that the related person tab always shows loading

## Expected behavior
A warning message should appear stating that there are no related persons and describe how to add one. 

However, it should show a loading message when it is loading.

**Comment by Pranav2612000** [comment]
Hey! Is anybody working on this? I would like to contribute.

**Comment by jackcmeyer** [comment]
@Pranav2612000 go ahead! issue is all yours!

**Comment by Pranav2612000** [comment]
I have started working on the task. Is it as simple as changing the "Loading..." text to something more informative say "No Related Members"

**Comment by jackcmeyer** [comment]
Not quite @Pranav2612000. 

It should show loading when the page is loading. 

And when it’s done loading, it should either show related persons or something more helpful.

**Comment by ocBruno** [comment]
Hey @archwheeler I forgot to give notice I had started this one but feel free to take it over, I am going to leave a commit here incase you want to adapt something into your PR.

**Comment by Pranav2612000** [comment]
Hey!! I too had started working on the project and have made the changes as requested, adding a 'isLoading' state to show "Loading..." when the component is loading and "No related persons have been added yet" to show when no related persons are present.

**Comment by Pranav2612000** [comment]
@ocBruno Tried your commit, couldn't get it to work. It still shows "No related persons. Insert one by click above on New Related Person." for a fraction of second before transitioning to the list of related persons.

**Comment by ocBruno** [comment]
> @ocBruno Tried your commit, couldn't get it to work. It still shows "No related persons. Insert one by click above on New Related Person." for a fraction of second before transitioning to the list of related persons.

@archwheeler feel free to remove anything unnecessary, I had noticed that it loaded very quickly I couldn't even see the loading message.I stopped when I was trying to learn to use breakpoits on the chrome inspector to make sure the loading message was appearing
