### ISSUE TITLE
Cleanup logs in tests

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1804]
## 🐛 Bug Report

There many extraneous logs in the test suite that can get removed.
* i8next logs on many tests

## To Reproduce

Run test suite

```bash
yarn test
```

## Expected behavior

Logs statements should be reduced 

## Your Environment

- _node version_: 10,12,13
- _os_: Mac, Windows, Linux
- _any other relevant information_

**Comment by MatthewDorner** [comment]
I'm working on tests now so I can take a look at this.
