### ISSUE TITLE
Edit Appointment

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1807]
## Scenario
**AS**

A user with write access to appointments

**I WANT**

To be able to edit details about an appointment

**SO THAT**

The appointment can change after creating it

## Acceptance Criteria
**GIVEN**

An existing appointment and a user with write access to the appointments

**WHEN**

I navigate the `/appointments/:id`, then I should see an edit button on the screen in the top right corner. 

AND

I click the button, the form should become editable (except for the patient input) and I should be able to edit the form.

AND 

I edit the fields and click the save

**THEN**

If there are no validation errors, then the appointment should be successfully saved and the form should go back to readonly.

If there are validations errors, I should get an error message and the form should stay editable and the appointment should not have been updated in the database. 

Validations: 

Start date is before end date

**Comment by MatthewDorner** [comment]
I can take this one, should be pretty easy to do in the same manner as Edit Patient.
