### ISSUE TITLE
Bundle size too large

### ISSUE THREAD

**Issue by fox1t** [HospitalRun/hospitalrun-frontend#1808]
## 💥 Regression Report

Even if we use bundlephobia and try to have a very strict policy when adding new dependencies, we still managed to make the current bundle size too large for real world.
This is the message that popups after building the project:
```
❯ yarn build
yarn run v1.21.1
$ react-scripts build
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  1.04 MB (+210.84 KB)  build/static/js/2.bc562eca.chunk.js
  31.9 KB (-15.7 KB)    build/static/css/2.917ed045.chunk.css
  22.89 KB (+22.21 KB)  build/static/css/main.d4e9e0b1.chunk.css
  13.62 KB (+6.33 KB)   build/static/js/main.8ae9ba5d.chunk.js
  783 B                 build/static/js/runtime-main.7bae1e60.js

The bundle size is significantly larger than recommended.
```
We need to find a way to optimize our bundle.
To analyze the dependency tree I've added a new script to the package.json
`"analyze": "source-map-explorer 'build/static/js/*.js'"`

**NOTE**: the analyze process took 17m 24s on my machine (MacBook Pro 15" 2019, octa-core)

## To Reproduce

Steps to reproduce the behavior: build the project `yarn build` or run `yarn analyze`

## Expected behavior

We need to make our bundle much lighter than this. We can use code splitting if needed.

This is the `yarn analyze` output:
<img width="2553" alt="image" src="https://user-images.githubusercontent.com/1620916/73932040-ba5d4800-48d9-11ea-967f-8373f5b6f82e.png">

**Comment by ocBruno** [comment]
Taking a look at the bundles individually to see if there are any possible optimizations.

This issue https://github.com/FortAwesome/react-fontawesome/issues/70 might have some insight on reducing fortawesome bundlesize.

Not very experienced in this area but willing to learn, could we attempt some sort of tree shaking for reducing free-svg-icons and fortawesome bundle size?

**Comment by jackcmeyer** [comment]
@ocBruno, I think this is definitely worth some time exploring.

**Comment by ocBruno** [comment]
Had my first week of work so I wasn't as active as I could've been with all the adapting. 
Going to dive into this issue and others tonight and the rest of the weekend! 
Have a good weekend everyone!

**Comment by sujithnath** [comment]
@jackcmeyer  Is the issue still on? Can I take it? :)

**Comment by jackcmeyer** [comment]
Hi @sujithnath. Sorry I missed your comment earlier. Do you still want to work on this issue?

**Comment by sujithnath** [comment]
> Hi @sujithnath. Sorry I missed your comment earlier. Do you still want to work on this issue?

Sure :-)
