### ISSUE TITLE
Success message shows undefined instead of empty string if name part was not filled out when creating new patient

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1818]
## 🐛 Bug Report

When creating a new patient, the success message shows undefined instead of an empty string if name part was not filled out.

## To Reproduce

1. Navigate to new patient
2. fill in given and family names
3. Save patient
4. See that the succcess messages read `.... family given undefined`

## Expected behavior

The success message should read `... family given` 

## Your Environment

- _node version_: 10,12,13
- _os_: Mac, Windows, Linux
- _any other relevant information_

**Comment by igeagonz** [comment]
I'd like to take a look at this

**Comment by igeagonz** [comment]
PR for this: https://github.com/HospitalRun/hospitalrun-frontend/pull/1822
