### ISSUE TITLE
Add missing tests for Patient Appointment List

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1836]
🐛 Bug Report

Tests are missing for the Patient Appointment List Functionality. 

This includes tests missing for the following files and functions: 
`AppointmentList.tsx`
`fetchPatientAppointments()` in `appointments-slice.ts`
`searchPatientAppointments` in `AppointmentRepository.ts`

## To Reproduce
Run `yarn coveralls` and see missing line coverage
```

## Expected behavior
The Patient Appointment List should be well covered with tests. 

## Related Issues
#1769

**Comment by andrew-oxenburgh** [comment]
These files don't seem to exist anywhere in the repo:
```
AppointmentList.tsx
appointments-slice.tsx
AppointmentRepository.tsx
```

Also, couldn't find  ```fetchPatientAppointments()``` or ```searchPatientAppointments()``` anywhere.

**Comment by jackcmeyer** [comment]
> These files don't seem to exist anywhere in the repo:
> 
> ```
> AppointmentList.tsx
> appointments-slice.tsx
> AppointmentRepository.tsx
> ```
> 
> Also, couldn't find `fetchPatientAppointments()` or `searchPatientAppointments()` anywhere.

Functionality was completed in https://github.com/HospitalRun/hospitalrun-frontend/pull/1823.

Relevant files: 
* https://github.com/HospitalRun/hospitalrun-frontend/blob/master/src/patients/appointments/AppointmentsList.tsx
* https://github.com/HospitalRun/hospitalrun-frontend/blob/master/src/scheduling/appointments/appointment-slice.ts
* https://github.com/HospitalRun/hospitalrun-frontend/blob/master/src/clients/db/AppointmentsRepository.ts

**Comment by samgaudr** [comment]
Hey @jackcmeyer, can I give a shot t this one ?

**Comment by jackcmeyer** [comment]
@samgaudr sorry I missed this! Please let me know if you still want to tackle this issue

**Comment by samgaudr** [comment]
No problem, I still have time for it!

**Comment by jackcmeyer** [comment]
> No problem, I still have time for it!

Great! I’ve assigned this to you!
