### ISSUE TITLE
Patient Search should live search (debounce)

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1840]
## Scenario
**AS**
A user who has the ability to search patients

**I WANT**
The search box on the patients search page to search for patients as I type

**SO THAT**
I do not need to click enter or the search button to fire a search request 

## Acceptance Criteria
> **GIVEN**
> A user with the ability to search patients
> 
> **WHEN**
> I type in the search box 
> 
> **THEN**
> Searches should fire as I type

## Related Issues
#1798 

## Technical Notes
* Clicking enter or the search button should immediately fire the search
* https://dev.to/gabe_ragland/debouncing-with-react-hooks-jci

**Comment by emauricio** [comment]
Hi there, I'm new here. this popup on projects that I could help for first-issue, so I would like to give it a try. 😄

**Comment by tehKapa** [comment]
Ok @emauricio

**Comment by roy-stewart** [comment]
I'd like to work on this task if there is no one currently working on it.

**Comment by fox1t** [comment]
@roy-stewart absolutely!
