### ISSUE TITLE
Add new appointment button in patient's appointments tab

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1841]
## Scenario
**AS**
A user with the ability to create appointments

**I WANT**
A new appointment button in the patient's appointments tab so that 

**SO THAT**
I can quickly make a new appointment for that patient. 

## Acceptance Criteria
> **GIVEN**
> A user with the ability to create an appointment and an existing patient
> 
> **WHEN**
> I navigate to the patient's appointment tab
> 
> **THEN**
> I should see a new appointment button 

> **GIVEN**
> A user with the ability to create an appointment and an existing patient
> 
> **WHEN**
> I click the new appointment button 
> 
> **THEN**
> I should be navigate to the new appointments screen with the patients box filled out with the name of the patient which i just came from

## Technical Notes
* Button should have add appointment icon

**Comment by dexterastin** [comment]
I'd like to help with this

**Comment by jackcmeyer** [comment]
Sure, @dexterastin. I have assigned this to you.

**Comment by jackcmeyer** [comment]
@dexterastin any update on this?

**Comment by oizuldan** [comment]
I'd like to do this task

**Comment by jackcmeyer** [comment]
I've assigned this to you, @oizuldan.
