### ISSUE TITLE
Breadcrumbs shows time to seconds precision when viewing an appointment

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1853]
## 🐛 Bug Report

When viewing an appointment, the breadcrumb link shows the start date and end date the seconds precision. 

## To Reproduce

1. Create a new appointment
2. Click on the appointment in the calendar
3. See the breadcrumb

![image](https://user-images.githubusercontent.com/18731800/75213749-baba6780-5750-11ea-8264-fc806758d93a.png)

## Expected behavior

The time should only be precise to the minutes since the seconds are not relevant for appointment start date and end date.

**Comment by oliv37** [comment]
I can work on it

**Comment by tehKapa** [comment]
Assigned
