### ISSUE TITLE
Breadcrumb for edit appointment is not correct

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1854]
The breadcrumb for edit appointment shows `Patient`, which is not correct

## 🐛 Bug Report
When editing an appointment, the breadcrumb shows `Patient`

## To Reproduce
1. Create new appointment
2. Click on appointment in calendar
3. Click on edit button
4. View incorrect breadcrumb

![image](https://user-images.githubusercontent.com/18731800/75213838-0836d480-5751-11ea-98ed-40f196e5ffe5.png)

## Expected behavior
Breadcrumb should show: `Dashboard/Appointments/Appoint Start Date - Appointment Edit Date/Edit Appointment`

## Your Environment

- _node version_: 10,12,13
- _os_: Mac, Windows, Linux
- _any other relevant information_

**Comment by patrick-salvatore** [comment]
Hello, I'd like to help out with this bug.

**Comment by tehKapa** [comment]
Hi, @patrick-salvatore. Thanks for your interest. Issuer assigned to you!

**Comment by oliv37** [comment]
> When editing an appointment, the breadcrumb shows Patient

This is wrong, the breadcrumb doesn't show **at all**, because the hook `useAddBreadcrumb` is not called into this view. You see see `Patient` because it is the label of the first field, this label is not related to the breadcrumb

**Comment by jackcmeyer** [comment]
> > When editing an appointment, the breadcrumb shows Patient
> 
> This assumption is wrong, the breadcrumb doesn't show at all (because the hook `useAddBreadcrumb` is not called into this view).
> 
> You see see `Patient` because it is the label of the first field, this label is not related to the breadcrumb

Thanks for the extra information @oliv37 :).

**Comment by tehKapa** [comment]
@patrick-salvatore, the original contributor who made the breadcrumbs has already fixed the bug. Thank you for your availability!
