### ISSUE TITLE
Saving related person navigates to wrong route

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1855]
## 🐛 Bug Report

After adding a new related person, the tool navigates to `/patient/:id` instead of `/patient/:id/relatedpersons`

## To Reproduce
1. Create a new patient
2. Add a new related person
3. See that tool navigates you to `/patient/:id`

## Expected behavior
Tool should navigate to `/patient/:id/relatedpersons`

## Technical notes
Instead of using the `updatePatient()` function in `patient-slice-ts`, it might be worth while creating a `addRelatedPerson()` function in `patient-slice.ts`.

Obviously, the two will share a lot of code, but we can have a helper function that has shared logic.

**Comment by MatthewDorner** [comment]
Same for adding a new Allergy. I was wondering if the `history.push()` should even be in the `updatePatient()` function. Or alternatively there could be an argument to `updatePatient()` that tells it where to redirect to? I'm not sure which is best. If we're just trying to make it stay on the same route, does it even need to redirect at all as long as we make sure the new information is populated?

**Comment by fox1t** [comment]
I agree that it is correct to put the redirect in the same function that creates the resource. I like the idea to add another parameter: if no string is passed, no redirect will happen; otherwise it will happen. We can open new issue and link it here.

**Comment by jackcmeyer** [comment]
@MatthewDorner you are right, the same is true for adding allergies (and now diagnoses). 

The reason that `history.push()` is called from the action is because that is the only place in the code that currently knows when the action of updating a patient has successfully completed. 

I think that a preferable solution is to redirect from the component, since it seems like that is where the logic belongs. 

Another preferable solution would be something like what @fox1t is suggesting and pass the route it should go to rather than the history object. However, I don't believe that we can access the `react-router` context from the action without passing `history`.

In the case of adding a related person, adding allergy, or adding diagnosis, there is no need to redirect. 

However, in the case of editing a patient, we will need to redirect back to the patient profile.
