### ISSUE TITLE
Change `New Related Person` to `Add Related Person`

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1856]
* Change the `New Related Person` button text to `Add Related Person` in the Patient's Related Persons tab so that it is consistent and more accurately reflects what the button is doing.

* Change the Modal Title

* Change the Modal submit button

This also goes for 

## Technical Notes
* Refactor component name from `NewRelatedPersonModal` to `AddRelatedPersonModal`

**Comment by tallskys** [comment]
I'd like to help with this

**Comment by jackcmeyer** [comment]
@tallskys Sounds great, I've assigned this to you!

**Comment by mgm793** [comment]
Is this task done?

**Comment by tehKapa** [comment]
Hi @mgm793 no, but it's already been assigned. Thank you anyway for your interest.

**Comment by fox1t** [comment]
Any news on this, @tallskys?

**Comment by oizuldan** [comment]
I'd like to do this task

**Comment by hemantpandey17** [comment]
I can work on this

**Comment by jackcmeyer** [comment]
@oizuldan, since you have another issue in progress, I'm assigning this to @hemantpandey1!
