### ISSUE TITLE
Sidebar should be collapsible so only icons show

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1858]
## 🚀 Feature Proposal
The sidebar should be collapsible so only the icons show to maximize screen space.

This should be a user controlled behavior with some sort of expand/collapse icon. 

This should automatically happen when the screen becomes a smaller screen. 

## Motivation
The sidebar should be collapsible so only the icons show to maximize screen space.

## Example

See #103 for a detailed discussion and some examples.

**Comment by rabbihossain** [comment]
I think I can help with this. Should I start working on this?

**Comment by jackcmeyer** [comment]
@rabbihossain I've assigned this issue to you! let anyone on @HospitalRun/core-maintainers know if you need any help!

**Comment by rabbihossain** [comment]
Thanks for assigning this to me. I have already started working on it. I will get back to you once I finish implementing it.

**Comment by rabbihossain** [comment]
hello @jackcmeyer ,
I am almost done implementing this. here is a preview of how the sidebar collapse toggle works.

![Peek 2020-03-05 18-43](https://user-images.githubusercontent.com/4346154/75982901-bdb41580-5f11-11ea-91e8-47bdccb8dd06.gif)

Please let me know if you have any feedback. Should I make a pull request?

**Comment by jackcmeyer** [comment]
This is awesome! Please open a PR 😀

**Comment by rabbihossain** [comment]
@jackcmeyer, I am trying to make a pull request but when I run `npm run commit` (as it was written on the project readme document), it always fails on `npm run test:ci` step. Am I doing anything wrong?

**Comment by tehKapa** [comment]
@rabbihossain try to run this command: 

1. `yarn` 
2. `yarn lint:fix` 
3. `yarn commit`

**Comment by rabbihossain** [comment]
thanks @tehKapa for helping me out. Looks like my changes broke some of the test cases. So I updated those test cases according to my changes. I also made a pull request.
