### ISSUE TITLE
Implement navbar search behavior

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1859]
## 🚀 Feature Proposal
The Navbar should have some sort of quick search capability, for now, this will be just searching Patients using the existing Patient search functionality. 

When I type into the searchbox, I would expect that results appear as I'm typing (almost like a typeahead). By clicking in one of those boxes, it should take me directly to that resource. 

If I click the search button, then it should capture the search that I'm doing and take me to a search page where I can be more specific in my search criteria. 

## Motivation

Easy of access and quick searches.

## Example

Similar to how the GitHub search bar is implemented.

**Comment by rabbihossain** [comment]
@jackcmeyer , I can help on that. Can you please assign this to me? Once my previous PR gets merged, I will start working on it.

**Comment by tehKapa** [comment]
Done @rabbihossain :)

**Comment by jackcmeyer** [comment]
@rabbihossain  we have a `Typeahead` component that should be sufficient for this task, I think.

**Comment by rabbihossain** [comment]
Hi, there. Sorry I busy for a while. So, couldn't make any commit. Right now I am trying to make the changes. But I found that the Search on Navbar is from node_modules directory. Which is coming from the component repository of yours. Can I make changes on component repository? Should I send a PR to that repository instead? @jackcmeyer

**Comment by jackcmeyer** [comment]
@rabbihossain What changes do we need to make to the component repository? If changes need to be made to the component repository, feel free to open a pull request for whatever changes are necessary there!

**Comment by rabbihossain** [comment]
@jackcmeyer , what I found is that the navbar component is fully written in the component repository. on the front-end repository navbar component takes an object as prop and rests are handled in NavBar component in component repository. In order to add sear search suggestion container, I need to make changes to that component. Otherwise I might have to write the whole navbar in front-end repository again.

**Comment by LucasBN** [comment]
Do you want me to do this?

**Comment by jackcmeyer** [comment]
@LucasBN if you want to, go for it!

**Comment by hristijankiko** [comment]
I have created a new [issue](https://github.com/HospitalRun/components/issues/389) in the `HospitalRun/components` repository to implement the necessary features to the `Navbar` component needs to allow for this feature to be implemented.
