### ISSUE TITLE
Appointment Type `Walk Up` should be `Walk In`

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1869]
🐛 Bug Report

HospitalRun v2.0.0 currently uses `Walk Up` instead of `Walk In` for an appointment type. 

## To Reproduce
1. Create new appointment
2. Choose an appointment type
3. See Walk Up instead of Walk In

## Expected behavior
Walk up should be Walk In.

**Comment by alti21** [comment]
Can I work on this?

**Comment by jackcmeyer** [comment]
I've assigned this to you @alti21!
