### ISSUE TITLE
Resolve deprecations for Labs Module

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#188]
The deprecations for the labs module need to be resolved.

**Comment by jkleinsc** [comment]
@tangollama two issues remain:

Ember Suave error visible in ember serve console (or if you run ember test):
```requireSpaceAfterLineComment: Missing space after line comment at labs/charge/controller.js :
     3 |
     4 |export default ProcedureChargeController.extend({
     5 |  //needs: ['labs/edit'],
----------^
     6 |  labsEdit: Ember.inject.controller('labs/edit'),
     7 |  cancelAction: 'closeModal',
```
Also, I am seeing the following deprecation warning when updating/adding a new lab request:
 "You attempted to set `labType` from `<hospitalrun@controller:labs/edit::ember1514>`, but object proxying is deprecated. Please use `model.labType` instead." 

This is caused by line number 56 on app/labs/edit/controller.js

**Comment by tangollama** [comment]
Done. Thx for the feedback @jkleinsc

**Comment by tangollama** [comment]
Crap. Sorry. I thought I had it all working.
