### ISSUE TITLE
Add French language

### ISSUE THREAD

**Issue by Donokami** [HospitalRun/hospitalrun-frontend#1888]
## 🚀 Feature Proposal

It would be amazing to integrate translations of the app. Personally, I would invest myself in translating HospitalRun in french.

## Motivation

This app is quite incredible, as it could reduce a lot the big costs of hospital management software in low sized structures which are in hard times (in France in particular), and all around the world we speak different languages.

## Example

It would be integrated in the frontend part of the app, as the server is only for devs.

**Comment by mleralec** [comment]
What is the state of this issue ? I think I can help on it.

**Comment by jackcmeyer** [comment]
I don't think any progress has been made on it. Would you like it assigned to you?

**Comment by mleralec** [comment]
Yes, thanks.
