### ISSUE TITLE
Add Portuguese language

### ISSUE THREAD

**Issue by helenapaixao** [HospitalRun/hospitalrun-frontend#1891]
## 🚀 Feature Proposal

It would be amazing to integrate translations of the app. Personally, I would invest myself in translating HospitalRun in portuguese.

## Motivation
This app is quite incredible, as it could reduce a lot the big costs of hospital management software in low sized structures which are in hard times, and all around the world we speak different languages.

## Example

It would be integrated in the frontend part of the app, as the server is only for devs.

**Comment by martimfj** [comment]
I would also like to contribute to this feature. I've seen that there is already some translated values in `/src/locales/ptBr/translations` but I encontred some mistakes and missing values. In the schedule page for instance, some elements of the calendar are not mapped to use I18next.

**Comment by tehKapa** [comment]
Hi @martimfj 
Unfortunately, the first implementation of the i18n was done 3 months ago. So if you encounter any missing elements you can safely add what you think is best.

**Comment by martimfj** [comment]
Hi @tehKapa 

Is there a plan to translate the calendar component?

**Comment by wwbarros** [comment]
I'd like to contribute too

**Comment by tehKapa** [comment]
@martimfj there isn't an open issue about it. but you can create an issue and request the assignment.

@wwbarros what would you like to work on?

**Comment by martimfj** [comment]
@tehKapa I've created the issue on the components repository.

**Comment by LucasBN** [comment]
Don't mind doing this - do I just translate the entire locales/enUs folder into Portuguese and the locales/ptBr?

**Comment by jackcmeyer** [comment]
@LucasBN you got it! I can assign this to you if you want?

**Comment by LucasBN** [comment]
@jackcmeyer sure
