### ISSUE TITLE
Add language selector

### ISSUE THREAD

**Issue by tehKapa** [HospitalRun/hospitalrun-frontend#1893]
## 🚀 Feature Proposal

Add a menu selector to change the language

## Motivation

With merge of #1892, you can use multiple languages.

**Comment by oizuldan** [comment]
Can I take this one?

**Comment by tehKapa** [comment]
Ok

**Comment by fox1t** [comment]
This kind of interactions has to be added to "settings" section of the app. So we first need to address it.

@tehKapa would you mind to open a new issue?

**Comment by jackcmeyer** [comment]
@fox1t I have opened up #1948 to address the new settings page.

**Comment by oizuldan** [comment]
@fox1t @jackcmeyer Do I need the implementation of #1948 issue before doing this issue?

**Comment by jackcmeyer** [comment]
Yes. #1948 is in progress, so until that is finished this is blocked.

**Comment by kumikokashii** [comment]
This ticket was unintentionally worked on in the PR https://github.com/HospitalRun/hospitalrun-frontend/pull/2096
