### ISSUE TITLE
Success alert when new appointment is created

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1894]
## 🚀 Feature Proposal

When a new appointment is created, the user should be notified with a success message.

## Motivation

The user should be alerted when they do something.

**Comment by sotous** [comment]
Hi, I would like to contribute to this issue, may I have it assigned to me?, I would use the same alert that you guys used when creating new patients.

**Comment by sotous** [comment]
@jackcmeyer I already solved the issue, I only need a confirmation to have the issue assigned and create a PR. Thanks in advance :)

**Comment by jackcmeyer** [comment]
I've assigned this to you!

**Comment by sotous** [comment]
Thanks! @jackcmeyer
