### ISSUE TITLE
No Related Persons warning not showing actual text

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1899]
## 🐛 Bug Report

The No Related Persons warning text is showing the internationalization keys rather than the actual text.

## To Reproduce

1. Navigate to a patient with no related persons
2. See that the no related persons warning does not have the proper text

![image](https://user-images.githubusercontent.com/18731800/76583970-9d073500-64a8-11ea-856b-0572dcb37bdc.png)

Paste your code here:

## Expected behavior
It should have the proper text.

**Comment by Brahyt** [comment]
I would like to take this.

**Comment by rubencgt** [comment]
Hello I created a PR that would fix this.
https://github.com/HospitalRun/hospitalrun-frontend/pull/1905
please feel free to comment on it.
thanks

**Comment by tehKapa** [comment]
Hi, @rubencgt thanks for your contribution :) To avoid making other people work for nothing, as written [here](https://github.com/HospitalRun/hospitalrun-frontend#working-on-an-issue), we always recommend waiting for the assignment. PR is fine anyway. 
@Brahyt thank you for your helpfulness!!

**Comment by Brahyt** [comment]
No worries, always excited to help OSS.

**Comment by rubencgt** [comment]
@tehKapa @Brahyt  as this is my PR I didn't know how it works.
next time it wont happen, apologies for the miss-understanding
