### ISSUE TITLE
Delete appointment button text not displaying correctly

### ISSUE THREAD

**Issue by Brahyt** [HospitalRun/hospitalrun-frontend#1901]
# Bug Report
The button on an appointment is showing internationalization keys rather then the correct text.

## To Reproduce
- Navigate to 'Scheduling'
- Click on an appointment on the calendar

## Expected behavior
It should have the proper text on the button and title.

**Comment by Brahyt** [comment]
I would like to work on this

**Comment by fox1t** [comment]
Hi @Brahyt, thanks for reporting this. Assigned to you.
