### ISSUE TITLE
Patients Buttons position

### ISSUE THREAD

**Issue by medesaties** [HospitalRun/hospitalrun-frontend#1906]
## 🐛 Bug Report

Buttons are close to the `div.card-body`.

## To Reproduce

1. Patients
2. New Patient
3. Scroll down the page
![image](https://user-images.githubusercontent.com/52140011/76702697-a4962c00-66aa-11ea-8f46-90d07c86a593.png)

## Expected behavior

The same of Scheduling > New Appointment
![image](https://user-images.githubusercontent.com/52140011/76702739-09518680-66ab-11ea-933e-c4bbeb9af083.png)

**Comment by alti21** [comment]
Can I work on this?

**Comment by tehKapa** [comment]
@medesaties are you working on this already? Can I assign him to @alti21?

**Comment by medesaties** [comment]
> Can I work on this?

Yes!


> @medesaties are you working on this already? Can I assign him to @alti21?

I am not, because I have no experience, I'm still learning. Thanks for asking.
Yes, you can!

**Comment by jackcmeyer** [comment]
The same issue also exists on the new appointments screen. I will open another ticket and link it here.
