### ISSUE TITLE
Mark required fields as required for New Patient/Edit Patient

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1915]
## 🚀 Feature Proposal

Mark required fields with the `*`.

The following fields are required: 
* Given Name

Labels have the ability to be marked as required: https://components.hospitalrun.io/?path=/story/label--label. 

## Motivation

Fields that are required should be marked as required so the user is aware that the field is required before saving.

**Comment by alti21** [comment]
May I work on this?

**Comment by jackcmeyer** [comment]
I've assigned this to you @alti21!
