### ISSUE TITLE
Mark required fields in New Appointment/Edit Appointment

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1916]
# 🚀 Feature Proposal
Mark required fields with the `*`.

The following fields are required:
* Patient
* Start Date
* End Date

Labels have the ability to be marked as required: https://components.hospitalrun.io/?path=/story/label--label.

# Motivation
Fields that are required should be marked as required so the user is aware that the field is required before saving.

**Comment by rubencgt** [comment]
can I take this?

**Comment by jackcmeyer** [comment]
I've assigned this to you @rubencgt
