### ISSUE TITLE
Provide better feedback in the New Patient/Edit Patient form

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1918]
## 🚀 Feature Proposal

Currently, the only error message that appears in the New Patient/Edit Patient form is a banner message that gives an error message. 

When possible, we should provide feedback directly on the problematic field using: https://components.hospitalrun.io/?path=/story/textinput--invalid-text-field-with-error-message. 

After completing this issue the following should be true: 
* When a user does not enter a given name for the user, the given name should highlight in red, and have a feedback message of: `Given Name is required.`
* The banner message should read `Could not create new patient.`/`Could not update patient.`

## Motivation
Easier feedback cycle for a user.

**Comment by rubencgt** [comment]
maybe the isRequired from: https://components.hospitalrun.io/?path=/story/label--label
could be used?

**Comment by jackcmeyer** [comment]
> maybe the `isRequired` from: [components.hospitalrun.io/?path=/story/label--label](https://components.hospitalrun.io/?path=/story/label--label)
> could be used?

@rubencgt we have an issue: https://github.com/HospitalRun/hospitalrun-frontend/issues/1915 just for that.

**Comment by rubencgt** [comment]
then I'd be happy to work on this

**Comment by jackcmeyer** [comment]
@rubencgt I've assigned this to you.

**Comment by jackcmeyer** [comment]
Closed via #1938
