### ISSUE TITLE
Warn about missing translations

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1919]
## 🚀 Feature Proposal

I would like the application to warn about missing translations when starting the application or running tests. 

A preferable solution would be to have a library that does this for us, which could mean switching internationalization libraries. 

However, as a fallback, a custom script that runs as part of `yarn start` or `yarn test` should work as well. 

## Motivation

Translations are very hard to manage and they get out of sync very quickly.

**Comment by martimfj** [comment]
Hey Jack!

I agree, I`ve just added a few of the missing translations. A script that compares the english translation files to the others (languages) and adds a default, would be nice too.

**Comment by fox1t** [comment]
I agree that might be helpful have a script that checks the status of translations file. We can run it on CI/CD in a non-blocking fashion: we can display a warning.

**Comment by marcosvega91** [comment]
Hi guys I have added a new command to check missing translations comparing every language with the english one.
In the future I think that you could integrate an external service like [Crowdin](https://crowdin.com/).
The script could:

1. Send english translations to service
2. Download translations for all languages from the service
3. Update missing translations in locals folder

I remember that Crowdin is free for opensource project 
[Docusaurus](https://github.com/facebook/docusaurus/blob/master/docs/guides-translation.md) use this service
