### ISSUE TITLE
Secondary, tertiary (etc) addresses, phone numbers, and emails for a patient

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1920]
## 🚀 Feature Proposal
I would like the ability to define secondary, tertiary, etc. phone numbers, addresses, and emails for a patient. 

When creating a new patient or editing patient, I should be able to add these extra fields. 

It should also be able to label what kind of phone number, address, or email it is. 

Phone numbers can be one of the following: 
- home 
- work 
- temp 
- old
- mobile

Email can be one of the following: 
- home 
- work 
- temp 
- old
- mobile

Addresses can one of the following: 
- home
- work 
- temp 
- old 
- billing

## Motivation
We should be flexible in the type of data that can handle. 

## Example
* Apple Contacts

## Technical notes
* Will require changes to the Patient model to support a list of addresses, phone numbers, emails. 
* Will require changes to some models to support the label of the phone number, address, or email (in some cases it might even require creating new models).

**Comment by alti21** [comment]
May I help on this?

**Comment by jackcmeyer** [comment]
I've assigned this to you, @alti21. Please reach out if you have any questions!

**Comment by alti21** [comment]
@jackcmeyer I'm having some trouble with this. I'm quite new to typescript just to let you know. I'm having trouble with this: Will require changes to the Patient model to support a list of addresses, phone numbers, emails. I changed phoneNumber into an array in ContactInformation.ts:

`export default interface ContactInformation
{
  phoneNumber: string[],
  email?: string,
  address?: string
}
`
Sorry i'm not sure how to add a line break to the code here

But then when I try to access patient.phonenumber[0] in GeneralInformation.ts, I get an error saying that patient.phoneNumber is undefined

**Comment by jackcmeyer** [comment]
You have the right idea for adding how to define the phone numbers as an array.

I'm guessing that the patient that you are looking at has no phone numbers defined for them. 

If that's the case, then `patient.phoneNumber` is `undefined`. 

When using an array accessor on undefined, you'll receive the error that you are getting. 

Before accessing the patient's phoneNumber you'll want to check first its not `undefined`.

**Comment by alti21** [comment]
@jackcmeyer thanks for the help, I got that part figured out now. I do need some help with the translations, as I want to have different labels for the new fields. Is there a file that has the translations?

**Comment by sourabbanka22** [comment]
Hi @jackcmeyer, May I work on this issue?

**Comment by jackcmeyer** [comment]
@sourabbanka22 I've assigned this to you!

**Comment by sourabbanka22** [comment]
Hi , @jackcmeyer  I have implemented the feature to define secondary, tertiary, etc. phone numbers, addresses, and emails for a patient.

Following are some screenshots of the implemented functionality:

**Initial:**
<img width="947" alt="NewPatient_Before" src="https://user-images.githubusercontent.com/58421086/83059373-6d170900-a077-11ea-9bc7-0e9090263fd3.PNG">

<img width="954" alt="NewPatient_After" src="https://user-images.githubusercontent.com/58421086/83059417-7ef8ac00-a077-11ea-96c9-efd83a38de1c.PNG">

**After Adding PhoneNumber and Email:**
<img width="960" alt="NewPatient_View" src="https://user-images.githubusercontent.com/58421086/83059436-861fba00-a077-11ea-8634-11d98aa32fc5.PNG">

**Adding Multiple PhoneNumbers, etc**
<img width="959" alt="EditPatient_After" src="https://user-images.githubusercontent.com/58421086/83059459-8d46c800-a077-11ea-9540-a952bef1e772.PNG">

**Does this look OK to you?**

**Comment by tehKapa** [comment]
@lauggh @StefanoMiC

**Comment by jackcmeyer** [comment]
@sourabbanka22 could you open a PR that can build so we can play around on the preview?

**Comment by sourabbanka22** [comment]
@jackcmeyer  as I have made quite a few number of changes in the Patient model to support a list of addresses, phone numbers, emails also some additional changes to some models to support the label of the phone number, address, or email because of which some tests requires to be updated accordingly, I would require some help with that. Should I open a PR with these Test Cases failing?

**Comment by sourabbanka22** [comment]
@jackcmeyer I just opened a PR,  Currently I have commented out a few tests related to newly created Phone Number, Email and Address Models

**Please let me know if there are any Modifications or Changes required.**

**Comment by lauggh** [comment]
Screenshots look good.

**Comment by kumikokashii** [comment]
Hi, PR is ready for your review at https://github.com/HospitalRun/hospitalrun-frontend/pull/2113. Thank you!
