### ISSUE TITLE
Add Diagnosis Modal should provide better error feedback

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1923]
## 🚀 Feature Proposal
I would like the add diagnosis to provide better feedback for error messages. 

Currently, the only error message is a banner error message.

After the completion of this issue, I would like it to provide feedback at the field level when possible. 

The following should happen: 
* When a Diagnosis Name is not filled in, the diagnosis name field should highlight in red, and provide feedback saying `Diagnosis Name is required.`
* When a Diagnosis Date is not filled in, the diagnosis date should highlight in red, and provide feedback saying `Diagnosis Date is required.`
* The banner message should read `Unable to add new diagnosis.`.

## Motivation
Better user experience.

**Comment by mamoses** [comment]
I would like to assist with this issue

**Comment by jackcmeyer** [comment]
Ive assigned this to you @mamoses

**Comment by mamoses** [comment]
Hey jackcmeyer,

I was wondering if you could clarify some things for me, when you say the related person should highlight in red what do you mean because I do not see a related person field on the Add Diagnosis tool.

Thanks

**Comment by jackcmeyer** [comment]
@mamoses This is just a copy-paste error when I was making these issues. That should say diagnosis name should be highlighted in red.

I've updated the issue to reflect that.
