### ISSUE TITLE
Add Allergy should provide better error feedback

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1924]
## 🚀 Feature Proposal
I would like the add allergy modal to provide better feedback for error messages. 

Currently, the only error message is a banner error message.

After the completion of this issue, I would like it to provide feedback at the field level when possible. 

The following should happen: 
* When a name is not filled in, the name field should highlight in red, and provide feedback saying `Name is required.`
* The banner message should read `Unable to add allergy.`.

## Motivation
Better user experience.

**Comment by cfiorini74** [comment]
Hi Jack,
I'd like to work on this issue.

**Comment by jackcmeyer** [comment]
Sounds good, I've assigned this to you, @cfiorini74.

**Comment by hemantpandey17** [comment]
Is it still on ?

**Comment by jackcmeyer** [comment]
@hemantpandey17 looks like this still available. Would you like to complete it still? Sorry I missed this message.

**Comment by hemantpandey17** [comment]
I can take that.

**Comment by cfiorini74** [comment]
I think I might have done this feature already in [this pull request](https://github.com/HospitalRun/hospitalrun-frontend/pull/1945). Wasn't sure how to directly link it with this issue, sorry.

**Comment by jackcmeyer** [comment]
Confirmed that the PR @cfiorini74 linked closes this issue.
