### ISSUE TITLE
Add Diagnosis Modal should mark required fields

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1926]
## 🚀 Feature Proposal
The diagnosis name field and diagnosis date field should be marked with a `*` to indicate that it is required.

## Motivation
Better use experience.

**Comment by nwmandel** [comment]
Hi @jackcmeyer, mind if I tackle this issue? 😀

**Comment by jackcmeyer** [comment]
@nwmandel go ahead!
