### ISSUE TITLE
New Related Persons Modal should mark required fields

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1927]
## 🚀 Feature Proposal
The related person field and relationship type field should be marked with a `*` to indicate that it is required.

## Motivation
Better use experience.

**Comment by bmoore235** [comment]
I would love to tackle this issue, along with [Related Persons modal should provide better error feedback #1925](https://github.com/HospitalRun/hospitalrun-frontend/issues/1925)
