### ISSUE TITLE
`Add Diagnoses` should read `Add Diagnosis`

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1929]
# 🐛 Bug Report
`Add Diagnoses` should be `Add Diagnosis` instead.

## To Reproduce

1. View patient
2. Click Diagnoses tab
3. See that `Add Diagnoses` should read `Add Diagnosis`
4. Click `Add Diagnoses` button
5. See that modal title `Add Diagnoses` should say `Add Diagnosis`. 

## Expected behavior

Modal title and button text should read `Add Diagnosis` instead of `Add Diagnoses`.

**Comment by ACAYspace** [comment]
Hey Jackcmeyer,

May i be assigned to this Issue?

**Comment by jackcmeyer** [comment]
I've assigned this to you @ACAYspace

**Comment by ACAYspace** [comment]
Sorry, can you re assign me. hit the wrong button.
