### ISSUE TITLE
Related person can be the patient it self

### ISSUE THREAD

**Issue by martimfj** [HospitalRun/hospitalrun-frontend#1940]
## 🐛 Bug Report

On adding a related person to a patient, this person can be the patient it self? 

More on that... a related person must also be a patient?

**Comment by fox1t** [comment]
Hi. It can be a patient. In the "add related persion" form we have to:
1. allow search for other patients to be added as relative
2. allow input new related person (in this case it will not be a patient)

**Comment by jackcmeyer** [comment]
Closing this issue in favor of #1946 and #1947. 

Let me know if there is anything that I missed, @martimfj!
