### ISSUE TITLE
Patient can also be related person

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1946]
## 🐛 Bug Report

Current, when adding a related person, the current patient can be added as the related person. 

## To Reproduce

1. View patient
2. Navigate to Related Persons tab
3. Add Related Persons
4. Search for current patient in related person
5. See that current patient appears in related person

## Expected behavior
The current patient should not be returned in the results of the search if the current patient matches the search results.

**Comment by alti21** [comment]
Can I try this?

**Comment by jackcmeyer** [comment]
@alti21, sounds good! I've assigned this to you.

**Comment by alti21** [comment]
Hi @jackcmeyer do we need any search functionality when adding a new related person?
