### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1948]
## 🚀 Feature Proposal

As a user of HospitalRun, I would like a page where I can access my user settings and modify them if I wish.

I should see a Person icon in the top right of the Navbar. That Person icon should open up a dropdown that gives me options related to the current account that I am logged in as. 

One of those options should be a "Settings" option. 

When I click on that settings option, it should bring me to a route "/settings", where I will, one day, be able to change settings about my account. 

## Motivation
Customization of the application.

**Comment by sonofaforester** [comment]
I'd like to work on this issue

**Comment by sonofaforester** [comment]
This is ready to go on my machine. I just need someone to approve the PR on the components project.

[https://github.com/HospitalRun/components/pull/345](url)

This adds a navbar component that has an icon with dropdown list that's called for in the feature.

**Comment by jackcmeyer** [comment]
Hi @sonofaforester, the PR that you linked has been approved and merged. I've bumped the `@hospitalrun/components` dependency to v1.2.0, which includes the changes that you mentioned

**Comment by sonofaforester** [comment]
@jackcmeyer thanks for reviewing the PR. It seems the PR isn't completed and the changes aren't in v1.2.0. The build pipeline seems to be failing for something that I don't believe is within my control.

**Comment by jackcmeyer** [comment]
@sonofaforester you are correct. This wasn’t merged yet and was not included in the v1.2.0 release. I could have sworn that it was. Must have been tired that day. 

I’ve merged it now and we’ll get a release made ASAP. 

Sorry for the confusion.

**Comment by jackcmeyer** [comment]
@sonofaforester this is now in v1.3.0 https://github.com/HospitalRun/components/releases/tag/v1.3.0

**Comment by kumikokashii** [comment]
Hi, may I take this?

**Comment by kumikokashii** [comment]
Hi, PR is ready for your review: https://github.com/HospitalRun/hospitalrun-frontend/pull/2096
