### ISSUE TITLE
Labs should sort by requested date by default

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1966]
## 🚀 Feature Proposal
Labs should sort by requested date by default (the newest one should come first) when I am viewing the list of labs

## Motivation
Easier to find lab requests

## Blocked by
#1969

**Comment by akshay-ap** [comment]
I would like to work on this.

**Comment by jackcmeyer** [comment]
@akshay-ap sounds great! I've assigned this to you.

**Comment by akshay-ap** [comment]
@jackcmeyer Before starting to work on it, I have a suggestion: A new dropdown which will show the fields by which the list of Labs can be sorted in ascending or descending order: 
1. ResquestedOn 
2. Type 
3. Status  
By default, list will be sorted by ResquestedOn descending order.

![image](https://user-images.githubusercontent.com/16358982/79756052-a8ffd580-8337-11ea-97af-eb85044c983d.png)

**Comment by jackcmeyer** [comment]
@akshay-ap

 I like this idea. However, most of the sorting functionality is going to be fully implemented inside of the Table component. 

For now, the intent of this was to get basic functionality implemented so that it is a usable feature. 

If the solution that you are suggesting is simple enough, then I'd say go for it. However, it is likely that the UI part of the story will change in the future.

**Comment by jackcmeyer** [comment]
Closed via #2004
