### ISSUE TITLE
Add paging and sorting functionality to find all/search functionality 

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1969]
## 🚀 Feature Proposal

Add paging and sorting functionality to the search/find all functions for patients, appointments, lab.

## Motivation
* Patient Search/List, Appointment List, Lab List

**Comment by akshay-ap** [comment]
Can I take this one?

**Comment by jackcmeyer** [comment]
Sounds good @akshay-ap. 

i've already done sorting for the `findAll`, however, we need to implement it for `search` yet.

For this, I'm hoping we can end up with: 

`search(searchCriteria: SearchCriteria, sort?: SortRequest, page?: PageRequest)`

and

`findAll(sort?: SortRequest, page?: PageRequest)`

if a page request is provided, it should return a `Page<T>` of whatever. Page should look like: 

```ts
class Page {
	T[] content;
	size: number; // the size of the page
	number: number; // the page number of the returned page
    totalElements: number; // the total elements that would be returned by query
    totalPages: number; // total number of pages that would be for this query
	getNextPage(): Page<T>
    getPreviousPage(): Page<T>
    hasNextPage: boolean
    hasPreviousPage: boolean
}
```

Page request should look like: 

```ts
interface PageRequest {
  number: number; // requested page number
  size: number; // requested size of the pages
}
```

sort and page should always be optional and if they are not provided then we should default to Unsorted and Unpaged.

paging and sorting should always be done at the PouchDB level

we should be able to support getting a specific page and getting the next and previous page.

**Comment by akshay-ap** [comment]
@jackcmeyer Thanks for the pointers!

**Comment by jackcmeyer** [comment]
@akshay-ap No worries, please let me know if you have any questions. I've done a little bit of research into this.
