### ISSUE TITLE
ability to filter by status on `/labs` screen

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1971]
## 🚀 Feature Proposal
Add the ability to filter by lab status on the `/labs` screen. 

Add a form, with a lab status selector that allows me to select the lab status I wish to search for. 

When I click on the search button, the table will be filtered by the status which I chose. 

## Motivation
Easier use of the lab screen

**Comment by sotous** [comment]
Hi @jackcmeyer , may I have this issue assigned?

**Comment by sotous** [comment]
Thanks!
