### ISSUE TITLE
Create labs tab in view patient screen

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1972]
## 🚀 Feature Proposal
If I have the ability to view labs and view patients, there should be a labs tab in the View Patient screen. 

The labs tab should show a list of labs that are associated with the patient. The table should show the lab type, the lab status, and the requested on date.. 

Clicking on one of the labs should bring me to `/labs/:id`. 

## Motivation
Linking patients and labs.

**Comment by rubencgt** [comment]
I'd be happy to take this

**Comment by jackcmeyer** [comment]
Sounds great @rubencgt! I have assigned this to you.

**Comment by rubencgt** [comment]
Do we need also a button (Add new Lab) that opens a modal that allows to create a new Lab?
similar to the modal in tab notes for creating new notes.
