### ISSUE TITLE
Cleanup small issues with lab section

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1973]
## 🐛 Bug Report

A few minor bugs can be seen in the labs section: 

1. On the new lab screen, the patient typeahead label is showing the internationalization key
2. On the new lab screen and the view lab screen, the notes field is marked as required when it shouldn't be.
3. When on the `/labs` route the following error message appears: 
`Warning: Each child in a list should have a unique "key" prop.`

**Comment by alti21** [comment]
Can I take this?

**Comment by jackcmeyer** [comment]
Yes! I've assigned this to you @alti21

**Comment by mleralec** [comment]
Is @alti21 still on it ? I can take it if not

**Comment by alti21** [comment]
Yes I'm still working on it
