### ISSUE TITLE
Create/Edit Patient inputs are not validated

### ISSUE THREAD

**Issue by martimfj** [HospitalRun/hospitalrun-frontend#1976]
When creating and editing a patient, only the required `givenName` is validated. The email and tel inputs can be anything and the date of birth can be a day greater than today.

## 🐛 Bug Report

Input fields from Editing/Creating Patients are not validated.

## To Reproduce

Input a text in the telephone field
Input a text that is not an email in the email field
Input a date in 2021 in the date of birth field

The components already give a way to add validation feedback to the user, but it is not used at the time.

**Comment by BrunaKimura** [comment]
Should text fields also be validated to avoid numeric inputs?

For example:
- Suffix
- Preffix
- Given Name
- Family Name
- Occupation
- Preferred Language

**Comment by LucasBN** [comment]
Would like to take a crack at this, could someone assign me?

**Comment by jackcmeyer** [comment]
@LucasBN I think validating addresses may be difficult due to needing to support any address format for any location in the world; however I have not looked into it. I think we can just tack it on to this one.

**Comment by jackcmeyer** [comment]
> Should text fields also be validated to avoid numeric inputs?
> 
> For example:
> 
> * Suffix
> * Preffix
> * Given Name
> * Family Name
> * Occupation
> * Preferred Language

@BrunaKimura I think that preventing numeric inputs is reasonable except for Occupation.

**Comment by LucasBN** [comment]
> @LucasBN I think validating addresses may be difficult due to needing to support any address format for any location in the world; however I have not looked into it. I think we can just tack it on to this one.

Yeah I also thought that might be a problem. I'm going to look into it anyway as I'd like to contribute somewhat - will let you know if I get anywhere. (I'll look at avoiding numeric inputs whilst I'm at it).

**Comment by jackcmeyer** [comment]
> > @LucasBN I think validating addresses may be difficult due to needing to support any address format for any location in the world; however I have not looked into it. I think we can just tack it on to this one.
> 
> Yeah I also thought that might be a problem. I'm going to look into it anyway as I'd like to contribute somewhat - will let you know if I get anywhere. (I'll look at avoiding numeric inputs whilst I'm at it).

sounds great!
