### ISSUE TITLE
Date of Birth date picker should have max date of the current date

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1984]
## 🚀 Feature Proposal

The Date Picker component supports defining a maximum date. The date of birth date picker should set the maximum date as today. 

## Motivation

Ease of use

**Comment by jlato89** [comment]
I'd like to take a crack at this. Seems a good place to start.

**Comment by jlato89** [comment]
Hopefully that PR was done right. I couldn't find this so called storybook so if someone wants to fill me in i can update it.
