### ISSUE TITLE
Add translation for patient.Code

### ISSUE THREAD

**Issue by akshay-ap** [HospitalRun/hospitalrun-frontend#1993]
## 🐛 Bug Report

![image](https://user-images.githubusercontent.com/16358982/79637609-8be3cf00-819e-11ea-9bf2-2c345bcd47ac.png)

## To Reproduce

In local development env navigate to: /patients

## Expected behavior

![image](https://user-images.githubusercontent.com/16358982/79637655-db29ff80-819e-11ea-8c0f-2341eacad18f.png)

## Your Environment

- *node version*: 6
- *fastify version*: >=1.0.0
- *os*: Windows
- *any other relevant information*

**Comment by akshay-ap** [comment]
I would like to work on this issue.

**Comment by jackcmeyer** [comment]
sounds good @akshay-ap
