### ISSUE TITLE
Edit Appointment screen is showing translation key for breadcrumb and title

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1996]
## 🐛 Bug Report

The breadcrumb and title are showing the translation key on the Edit Appointment Screen. 

## To Reproduce

1. Create a new appointment
2. Navigate and view that appointment
3. Click the edit button
4. See that the the breadcrumb and title of the edit screen are the translation key

## Expected behavior

They should be the correct header and breadcrumb instead of the translation key

**Comment by mleralec** [comment]
Can I take it ?

**Comment by mleralec** [comment]
Can I take this ?

**Comment by jackcmeyer** [comment]
@mleralec I have assigned this to. you.
