### ISSUE TITLE
Reason is incorrectly being marked as required field on edit/new appointment screen

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1997]
## 🐛 Bug Report
The reason field is being marked as required when it should not be. 

## To Reproduce
1. Navigate to edit or create appointment screen 

## Expected behavior
The reason should not be marked as required.

**Comment by JDarke** [comment]
Hi Jack, I'd like to take a shot at this one for my first actual contribution...

**Comment by jackcmeyer** [comment]
Sounds great @JDarke. I've assigned this to you

**Comment by JDarke** [comment]
Hi Jack,  I think that fixes it, though I had a bit of a messy time trying to install Yarn, which has modified the package.json.  I don't know if you can just accept the commit for the fix and ignore that, or if you need me to submit a new PR?
