### ISSUE TITLE
Delete appointment button is showing translation key

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#1998]
## 🐛 Bug Report

The delete button is showing the translation key

## To Reproduce

1. create an appointment
2. navigate to the created appointment
3. see that the delete button is showing the translation key

## Expected behavior

it should not show the translation key

**Comment by alti21** [comment]
Can I take this?

**Comment by jackcmeyer** [comment]
Yes! I've assigned this to you @alti21

**Comment by mleralec** [comment]
In fact, I have fix this with my PR #2006 with an another missing label on appointment.

**Comment by fox1t** [comment]
I've just merged #2006

**Comment by mleralec** [comment]
I think you can close this issue since the fix is merged

**Comment by jackcmeyer** [comment]
Confirmed this is working. Closing issue.
