### ISSUE TITLE
Error while searching Patient

### ISSUE THREAD

**Issue by akshay-ap** [HospitalRun/hospitalrun-frontend#1999]
## 🐛 Bug Report
```
Uncaught (in promise) SyntaxError: Invalid regular expression: /Adk\/: \ at end of pattern
    at RegExp (<anonymous>)
    at a.<anonymous> (PatientRepository.ts:21)
    at s (2.726afb2a.chunk.js?__WB_REVISION__=15200f807ae5907c400b:sourcemap:2)
    at Generator._invoke (2.726afb2a.chunk.js?__WB_REVISION__=15200f807ae5907c400b:sourcemap:2)
    at Generator.next (2.726afb2a.chunk.js?__WB_REVISION__=15200f807ae5907c400b:sourcemap:2)
    at r (2.726afb2a.chunk.js?__WB_REVISION__=15200f807ae5907c400b:sourcemap:2)
    at c (2.726afb2a.chunk.js?__WB_REVISION__=15200f807ae5907c400b:sourcemap:2)
    at 2.726afb2a.chunk.js?__WB_REVISION__=15200f807ae5907c400b:sourcemap:2
    at new Promise (<anonymous>)
    at a.<anonymous> (2.726afb2a.chunk.js?__WB_REVISION__=15200f807ae5907c400b:sourcemap:2)
```

## To Reproduce

1. Create a patient
2. Enter text like 'Adk/\'(string containing '/\') in patient search bar.

## Expected behavior

No error.

## Your Environment

- *node version*: 12
- *fastify version*: >=1.0.0
- *os*: Windows

**Comment by jackcmeyer** [comment]
Thanks for the report @akshay-ap. Confirmed that this is an issue. Seems like we should validate the characters in the search field.

**Comment by JDarke** [comment]
I've got a fix that simply removes any backslashes, to avoid escaping the regexp.  Does it need a wider-ranging check for other characters, or maybe just remove anything other than A-Z...?

PatientRepository.ts - Line 16 added, line 22 modified to replace 'text' with 'cleanText':

```
import shortid from 'shortid'
import Patient from '../../model/Patient'
import Repository from './Repository'
import { patients } from '../../config/pouchdb'

const formatPatientCode = (prefix: string, sequenceNumber: string) => `${prefix}${sequenceNumber}`

const getPatientCode = (): string => formatPatientCode('P-', shortid.generate())

export class PatientRepository extends Repository<Patient> {
  constructor() {
    super(patients)
  }

  async search(text: string): Promise<Patient[]> {
    const cleanText = text.replace(/\\/g, '')
    return super.search({
      selector: {
        $or: [
          {
            fullName: {
              $regex: RegExp(cleanText, 'i'),
            },
          },
          {
            code: text,
          },
        ],
      },
    })
  }

  async save(entity: Patient): Promise<Patient> {
    const patientCode = getPatientCode()
    entity.code = patientCode
    return super.save(entity)
  }
}

export default new PatientRepository()

```

Either way, happy to take this one on if it's free.

**Comment by akshay-ap** [comment]
The issue seems to be with string ending with any special characters in regex like `[` or  String  having only `*` character.
```Unhandled Rejection (SyntaxError): Invalid regular expression: /Test[/: Unterminated character class```.
```Unhandled Rejection (SyntaxError): Invalid regular expression: /*/: Nothing to repeat```.
@JDarke, I would sugesst to find all the such cases rather than fixing the issue for just one case.

**Comment by JDarke** [comment]
Ah, I thought it was just the backslash.  I'll write a general case solution to remove anything that's not whitespace or alphabetical if Jack assigns me to the bug.

Is it better to fix as shown, by cleaning the search string, or by stopping the text field from accepting any disallowed characters in the first place?

**Comment by jackcmeyer** [comment]
@JDarke I've assigned this to you.

**Comment by JDarke** [comment]
Do international alphabetical characters need to be factored in to this, or is localisation being handled separately?

**Comment by jackcmeyer** [comment]
international characters should be handled here. numbers, apostrophes, and other characters found in a name should also be supported.

**Comment by JDarke** [comment]
Will do.

**Comment by JDarke** [comment]
@akshay-ap ...I've run through numerous special characters, and so far my list of chars that break the search is as follows:

\ - Backslash
[  - Opening square bracket
* - Lone asterisk (with no preceding chars) 
** - Consecutive asterisks (with or without preceding chars) 
( ) - opening OR closing parentheses
? - Question mark

Does this cover all the instances you experienced?

**Comment by jackcmeyer** [comment]
@JDarke I think that we can safely remove all of those characters you listed.

**Comment by JDarke** [comment]
Ok, those are all removed in my last commit.

I think this should also be addressed at the Add New Patient input stage, too;  currently it's possible to create a patient with a name containing those special characters, which the user will now not be able to accurately search for.  

Separate issue to be raised, or to be included with this issue?

**Comment by JDarke** [comment]
I've just had this bug re-occur.

Can anyone else reproduce the error by entering a search string ending in backslash into the patient list search bar?

![Screen Shot 2020-06-17 at 13 11 28](https://user-images.githubusercontent.com/52716187/84896599-2166e680-b09c-11ea-8dfb-3a6b8e25272a.png)
![Screen Shot 2020-06-17 at 13 10 13](https://user-images.githubusercontent.com/52716187/84896495-f5e3fc00-b09b-11ea-8b03-e1b781528a1d.png)
