### ISSUE TITLE
Add translation for labs.lab.patient

### ISSUE THREAD

**Issue by akshay-ap** [HospitalRun/hospitalrun-frontend#2008]
## To Reproduce

Navigate to new lab request.
![image](https://user-images.githubusercontent.com/16358982/80119115-e6b66580-85a6-11ea-99ee-a983877f2ba6.png)

## Expected behavior

Translation for labs.lab.patient to be added.

## Your Environment

- *node version*: 12
- *fastify version*: >=1.0.0
- *os*:  Windows

**Comment by jackcmeyer** [comment]
This is a duplicate of #1973
