### ISSUE TITLE
View Appointment screen is showing translation key for title

### ISSUE THREAD

**Issue by mleralec** [HospitalRun/hospitalrun-frontend#2009]
## 🐛 Bug Report

The title show the translation key on the View Appointment Screen.

## To Reproduce

1. Create a new appointment
2. Navigate and view that appointment
3. See that the title of the screen is the translation key

## Expected behavior
It should be the correct title instead of the translation key

**Comment by mleralec** [comment]
Can I take my own issue ?

**Comment by jackcmeyer** [comment]
Closed via #2016
