### ISSUE TITLE
Improve sidebar readability

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2019]
## 🚀 Feature Proposal

Right now, the sidebar is hard to read, especially when sub items are selected. 

We should improve the readability by doing the following: 
* Don't highlight selected sub-items
* The background of subitems should be a slightly more gray than the main items. 
* The height of the subitems list item should be smaller than that of the main items

Inspiration from v1: 
![image](https://user-images.githubusercontent.com/18731800/80321888-90d00080-87e6-11ea-8db5-68fb7fcd543f.png)

**Comment by JDarke** [comment]
I'd like to take a run at this one, please.

**Comment by JDarke** [comment]
The sub-item height is already slightly smaller than the main items, so do you want maybe another 10% reduction...?

**Comment by JDarke** [comment]
![SidebarEnhance](https://user-images.githubusercontent.com/52716187/80417385-93595580-88cd-11ea-8cde-a79153759717.png)

Something like that?  

I'm not sure if it's the right approach, but I made these changes by passing in some extra css properties to ListSubItemStyle & ListSubItemStyleNew (Sidebar.tsx) to override the bootstrap styles:

```
const listSubItemStyleNew: CSSProperties = {
    cursor: 'pointer',
    fontSize: 'small',
    borderBottomWidth: 0,
    borderTopWidth: 0,
    color: 'black',
    padding: '.6rem 1.25rem',
    backgroundColor: 'rgba(245,245,245,1)',
  }

  const listSubItemStyle: CSSProperties = {
    cursor: 'pointer',
    fontSize: 'small',
    borderBottomWidth: 0,
    borderTopWidth: 0,
    color: 'black',
    padding: '.6rem 1.25rem',
    backgroundColor: 'rgba(245,245,245,1)',
  }
```

**Comment by jackcmeyer** [comment]
I think that this looks great!

**Comment by fox1t** [comment]
@StefanoMiC i think you can paste here the new sidebar we are working on, so @JDarke can see it.

**Comment by StefanoMiC** [comment]
Hi @JDarke, thank you for your contribution! Actually, we are few days away from the release of the complete new graphics of the platform. The new sidebar will look something like this:

![image](https://user-images.githubusercontent.com/26657904/80506197-8d1eb400-8975-11ea-8694-2cdb425682a9.png)

As you can see we resolved readability issues and thought of a navigable menu to reduce clutter.
There will be issues providing the new design for pages and components soon so stay tuned! :)

**Comment by JDarke** [comment]
Hah!  Yeah, that makes mine just a little redundant... :)

Looks great!

**Comment by StefanoMiC** [comment]
Thank you @JDarke! I'm glad you like it :)
