### ISSUE TITLE
Date/Datetime pickers are too small

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2020]
## 🐛 Bug Report
The date/date time pickers are too small and do not fit to their parent element.  

## To Reproduce
Navigate to anywhere there is a date/date time picker
* patient date of birth
* appointment start date/end date

## Expected behavior
The date/date time picker should take up the width of its parent element similar to how the text input/fields work.

**Comment by alti21** [comment]
Can I take this?

**Comment by jackcmeyer** [comment]
> Can I take this? 

I’ve assigned this to you @alti21!
