### ISSUE TITLE
Error while searching appointments

### ISSUE THREAD

**Issue by akshay-ap** [HospitalRun/hospitalrun-frontend#2029]
## 🐛 Bug Report

Special characters in input string causing issue.

## To Reproduce

1. Create a patient
2. Navigate to Patient details
3. Click appointments tab.
4. Enter text in search box.
5. Click search.

![image](https://user-images.githubusercontent.com/16358982/80735413-46c08500-8b2e-11ea-9491-cb340a1e2856.png)

Problemtic inputs:
1. String ending with `\` or `[`
2. `*`
3. `{<number>}`
The list is not exhaustive.

## Expected behavior
No error.

## Your Environment

- *node version*: 14
- *fastify version*: >=1.0.0
- *os*: Windows

Similar to: #1999

**Comment by JDarke** [comment]
I'm working on #1999;  Once my submitted fix is accepted, I can apply it to the rest of the inputs to escape all special regex characters.

**Comment by JDarke** [comment]
Sorry about the multiple commits.  I tried resetting my local repo and then making the changes again, as my master branch was out of sync with the master repo and things were getting untidy.  Looks like I still managed to send multiple commits.  :|
