### ISSUE TITLE
Ability to report an incident

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2037]
## 🚀 Feature Proposal

Create the ability to report an incident. This will require a new module to be built called "Incidents". 

An incident is comprised of: 
- A date when the incident occurred
- The department where the incident occurred
- The category an category item of the incident
- A description of the incident
- Who the incident was reported by
- When the incident was reported

**Comment by marcosvega91** [comment]
I see that this feature is for core-team but If you want I can help you 😃

**Comment by jackcmeyer** [comment]
> I see that this feature is for core-team but If you want I can help you 😃

Thanks @marcosvega91 :) I'm only doing a minimal implementation, so there will still some work that will need to come out of this.
