### ISSUE TITLE
[Discussion] Project planning

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#205]
Following up from some prior discussion about how to surface project planning and roadmap goals, I thought it might be worthing having some further discussion here.

AFAIK so far we have just been using labels for roadmap goals, which is okay. But I'll be the first to admit that GitHub issues suck for actual project planning use. While we use them internally at GitHub for that purpose, most of our teams also use an additional tool (Trello, or Pivitol Tracker) to help make it actually manageable. The key reason being the visibility that Agile tooling gives you over the state of the project, what's on deck, and what's in progress – something which GitHub issues alone simply fails at.

So my suggestion is that we consider using a public Trello or Pivitol board for managing the roadmap. We can still use the labels we are using to manage things on the GitHub side, but using an Agile style board could helps us better coordinate what projects are in progress, who is working on them, where they are in the process, and what's on deck – as well as bring better public visibility to those things for the benefit of interested contributors wondering where they can jump in.

cc @HospitalRun/owners

**Comment by jglovier** [comment]
Also, here are a couple examples of such boards being used by open source projects currently:
- [movi.im](http://movi.im/) (https://github.com/mislav/movieapp) is using a [public Pivitol board](https://www.pivotaltracker.com/n/projects/449605)
- [Jasmine](http://jasmine.github.io/) uses a [public Pivitol board](https://www.pivotaltracker.com/n/projects/10606)
- Adobe's [Brackets project](http://brackets.io/) is using a [public Trello board](https://trello.com/b/LCDud1Nd/brackets)
- Nylus [N1 team](https://trello.com/b/hxsqB6vx/n1-open-source-roadmap) is using a public Trello board
- [This Trello blog post](http://blog.trello.com/going-public-roadmapping-with-a-public-trello-board/) lists several others
- [This Quora thread](https://www.quora.com/What-are-some-really-interesting-examples-of-public-Trello-boards) has some other really interesting examples of public boards

**Comment by jkleinsc** [comment]
@jglovier I am not opposed to doing something like this, but my concern is who is going to maintain it?  Using Github has provided us with a low barrier of entry and at least for now gives us what we need.

**Comment by tangollama** [comment]
I see this as a project management function - so me for now. Let's discuss more in real life. Jag and I had a good talk about (also in real life) last night. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by jglovier** [comment]
>I see this as a project management function - so me for now.

Yeah, that's the general idea. The project manager should be responsible for maintaining it.

**Comment by tangollama** [comment]
FYI, I'm trying waffle on for size. https://waffle.io/HospitalRun/hospitalrun-frontend

**Comment by jglovier** [comment]
>FYI, I'm trying waffle on for size.

:cool:. Do they have any way to create epics and attach multiple stories to them?

**Comment by jglovier** [comment]
I spun up a Pivotal Tracker board to try out. Currently adding all of my tasks there, and creating a few epics. I made an epic for the 1.0 release, and a couple others.

https://www.pivotaltracker.com/n/projects/1519497

**Comment by jglovier** [comment]
Added a PT integration to our Slack so the PT activity will be fed into the #project-activity room in Slack. :zap:
