### ISSUE TITLE
Appointments List should provide more information on listed appointments

### ISSUE THREAD

**Issue by samgaudr** [HospitalRun/hospitalrun-frontend#2053]
## 🚀 Feature Proposal

Appointments list should provide more information on listed appointments, like location, type and/or reason of the appointment.

## Motivation

Currently, only the start time of the appointment is displayed in the list, but the search bar does only search on the location, reason and type field. It would also make the list more intuitive for the user.

**Current appointment list**
![Screenshot from 2020-05-05 20-14-16](https://user-images.githubusercontent.com/28734986/81127699-0afe3480-8f0d-11ea-9810-f2d8075a0767.png)

**Comment by darrylpargeter** [comment]
Hey, is it possible to attempt this one?

**Comment by tehKapa** [comment]
Sure @darrylpargeter!

**Comment by darrylpargeter** [comment]
@jackcmeyer @tehKapa 
I started looking at this and found this comment on a PR https://github.com/HospitalRun/hospitalrun-frontend/pull/1823#pullrequestreview-358683785 which mentions that this should use the Table component once it has been done.

However, from a look at the component, it still seems to be a WIP and is in need of a bit TLC to be considered usable.

From my point of view the table is missing, in terms of this issue:
1) An on click event on the rows themselves, though this does seem to be being worked on here https://github.com/HospitalRun/components/issues/330
2) Showing the pagination controls dynamically or by a flag on the component or within the `tableProperties` object (not sure if you guys have a prefered way of this working?)
3) A new property in `tableProperties` to control the `thead` class. So the `thead-light` class from bootstrap can be added to keep the table style inline with the preexisting tables in the app (I'm suggesting a new property so it can be changed on the fly, over hardcoding it within the table comp)
4) a `Cell` function to the `date` type in the `generateColumns` function to allow the creation of a more user-friendly/ location-based format of the dates

Would there be any objections from me adding (2-4) in the prefered way to the table comp?

**Comment by jackcmeyer** [comment]
@darrylpargeter I think that these are all great ideas. I'm thinking we may want a different interface to the Table component. 

I've opened an issue here for discussion: https://github.com/HospitalRun/components/issues/411

**Comment by janmarkusmilan** [comment]
Hello,

If this issue is still up for grabs, I was wondering if I could attempt it?

**Comment by jackcmeyer** [comment]
@janmarkusmilan I've assigned this to you!

**Comment by janmarkusmilan** [comment]
Just a quick inquiry.

If the goal is to just add more information about the appointments (type, location, reason), then would either of these work:

![Sample_1](https://i.imgur.com/8LI3y2r.png)

![Sample_2](https://i.imgur.com/yFV7iZb.png)

**Comment by jackcmeyer** [comment]
I think the information that you have provided is good! However, I think it would be better displayed in a table. What do you think?

**Comment by janmarkusmilan** [comment]
Sounds good!
