### ISSUE TITLE
Consider adding breadcrumb to UI

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#206]
There is [a lot of evidence](http://www.nngroup.com/articles/breadcrumb-navigation-useful/) that breadcrumbs are an extremely helpful navigational tool for users (and have been for 20 years lol), especially when navigation can't be easily ascertained from a URL, such as often is the case in web apps.

I'm fairly confident that our current navigational paradigm is working, but for now my confidence is largely anecdotal. I'd like to do some user testing to know if our current paradigm works well, or is problematic for users, and if it's not working as well as I think it is we should consider a breadcrumb approach.

Simply tacking on a breadcrumb somewhere is likely not the solution, as it would result in a 4th place to ascertain where you are, and could be more confusing than helpful if approached that way. If we determine that a breadcrumb would be helpful, I'll need to rethink some of the layout.

So the next step is doing some qualitative research (interviews and observations), and then try to draw some conclusions from there.

**Comment by tangollama** [comment]
@jglovier where are you at with deciding if you want this or not?

**Comment by jglovier** [comment]
I think it is still worth exploring for the future, but going to close for now since we have other priorities. I'll add a new label for `revisit-later`.
