### ISSUE TITLE
Standardize mock store setup in tests

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2062]
## 🐛 Bug Report

In some cases, the mock store setup in tests are different. We should use `createMockStore` in all cases instead of `configureMocks

**Comment by kumikokashii** [comment]
@jackcmeyer Hi, may I take this one?

**Comment by tehKapa** [comment]
@kumikokashii sure!

**Comment by kumikokashii** [comment]
PR is ready for your review. Thank you! https://github.com/HospitalRun/hospitalrun-frontend/pull/2075
