### ISSUE TITLE
Add an A,B,C ranking to inventory items

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#207]
A items are inventory items that should never stock out.
B is the middle
C is lower priority

We need the ability to rank items under the A, B, C categorization. This would be a great feature add for a newbie.

**Comment by turboMaCk** [comment]
I'm interested in implementing this one. :rocket:

**Comment by tangollama** [comment]
Awesome. Please do. I'll pull it off the help wanted list tomorrow. See me @tangollama for requirements clarification. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by turboMaCk** [comment]
I just opened PR with early implementation steps. Let's move discussion in here to keep it specific to code: https://github.com/HospitalRun/hospitalrun-frontend/pull/225

**Comment by turboMaCk** [comment]
Should be closed: https://github.com/HospitalRun/hospitalrun-frontend/pull/225

**Comment by jkleinsc** [comment]
Closing as this was addressed in pr #225
