### ISSUE TITLE
Add ability to resolve an incident

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2078]
## Scenario
**AS**
A user who has the ability to resolve an incident

**I WANT**
A button that I can click that sets the incident's status to resolved

**SO THAT**
I can determine when an incident is no longer needed to be opened.

## Acceptance Criteria

> **GIVEN**
> A user who has the ability to resolve an incident and an incident that is in the reported status
> 
> **WHEN**
> I navigate to the incident that is in the reported status
> 
> **THEN**
> I should see a required text field and a button at the bottom of the page that says `Resolve`. 

> **GIVEN**
> The incident 
> 
> **WHEN**
> I click on the resolve button
> 
> **THEN**
> The incident's status should be set as `resolved` and the `resolvedOn` date should be set to the current time.

> **GIVEN**
> The incident 
> 
> **WHEN**
> I click on the resolve button
> 
> **THEN**
> The incident's status should be set as `resolved` and the `resolvedOn` date should be set to the current time.

> **GIVEN**
> The incident 
> 
> **WHEN**
> I click on the resolve button and there is no content in the Resolution text field
> 
> **THEN**
> An error message should appear stating that the incident could not be resolved and the Resolution field should have feedback stating that it is required.

## Technical Notes
* New, required, text field called `resolution` should be displayed when viewing an incident
* New permission `ResolveIncident` should be added
* New redux thunk named `resolveIncident`

**Comment by christiantgolden** [comment]
I'd like to give this one a shot as a first time contributor.

**Comment by jackcmeyer** [comment]
> I'd like to give this one a shot as a first time contributor.

Sounds great!

**Comment by christiantgolden** [comment]
I'm running into an issue trying to set incident properties. I receive an error that an incident's properties are read only. I've modeled my code largely off of ReportIncident related code, but is initially called from within ViewIncident. I know this isn't much to go on just yet, but before I seek more detailed assistance, and provide more in depth info, does anything come to mind off the top of your head that I might be overlooking when it comes to read/write access to object properties?

**Comment by jackcmeyer** [comment]
The reason that you are getting that error is you are likely directly modifying a redux object, which are immutable. 

Feel free to open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) an I can review the code and better help debug.

**Comment by christiantgolden** [comment]
Oh wow. I didn't know draft PRs were a thing! Thanks for offering to review. I'll submit a draft PR soon.

**Comment by nischayv** [comment]
Is this still being worked on, otherwise I don't mind taking a shot at it?

**Comment by blestab** [comment]
Hi @jackcmeyer 
I see this is back to needing an assignee? You can put it on my name.
