### ISSUE TITLE
Patient Care Plan

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2079]
## 🚀 Feature Proposal
A Patient should have the ability to have a Care Plan. 

A care plan gives describes how care is going to be given to a patient. 

A care plan consists of: 
- an identifier
- status of `draft`, `active`, `on hold`, `revoked`, `completed`, `unknown` 
- intent of `proposal`, `plan`, `order`, `option`.
- title
- description
- patient
- start date, end date
- created on date (when the care plan was created)
- diagnosis (the diagnosis the care plan addresses)
- note

## Motivation
Be able to define a care plan for a patient

**Comment by Elveskevtar** [comment]
Hey @jackcmeyer I was wondering if you were still working on this feature. If not, I would be happy to take over the feature. Otherwise, do you know of a medium/high effort task that the team needs done?

I am looking to contribute to an open source project and found HospitalRun really cool.

**Comment by tehKapa** [comment]
Hi @Elveskevtar no one is currently developing this feature. If you'd like we can assign it to you. Let's wait for @jackcmeyer to confirm

**Comment by jackcmeyer** [comment]
@Elveskevtar and @tehKapa I've been working on this issue :)
