### ISSUE TITLE
Reports that utilize the A,B,C categorization

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#208]
Along with #207, add a report to Inventory that allows a user to see current status on items by A, B, and C items.

**Comment by dKab** [comment]
@tangollama I'm taking this issue.

**Comment by dKab** [comment]
@tangollama just wanted to clarify the requirements. In scope of this feature a checkbox should be added to the list of Fields to Include, is this correct? And should it be visible for all types of reports or only for some of them? If the checkbox is checked we should see new column Rank in the report table.
