### ISSUE TITLE
Patient Care Goal

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2080]
## 🚀 Feature Proposal
Add the ability to define care goals for a patient.

Care Goal is WHAT e.g. Decreases blood pressure by 15 points
Care Plan is HOW e.g. Exercise for 1 hour each day and decrease soda intake to 1 serving per week.

A care goal is defined as: 
- an identifier
- status: `proposed`, `planned`, `accepted`, `active`, `on hold`, `completed`, `cancelled`, `rejected`
- achievementStatus:`in progress`, `improving`, `worsening`, `no change`, `achieved`, `not achieved`, `no progress`, `not attainable`
- priority: `high`, `medium`, `low`
- description
- patient
- start date
- due date
- created date
- note

## Motivation
Define care goals for a patient

**Comment by EmilioCastilloW** [comment]
Hi! I see that this post is now open for contributions. Can you elaborate a little bit more? Where will the "care goal" be implemented? As part of the Patient information? As a separate function?

**Comment by jackcmeyer** [comment]
Hi @EmilioCastilloW. 

The Care Goal, for now, will be a tab right next to Care Plan. 

It will just be another property that is located on the patient object.

**Comment by EmilioCastilloW** [comment]
Thanks, I will give it a try and share it with you.

**Comment by jackcmeyer** [comment]
Awesome, I've assigned this to you @EmilioCastilloW

**Comment by blestab** [comment]
> 
> ## 🚀 Feature Proposal
> 
> Add the ability to define care goals for a patient.
> 
> Care Goal is WHAT e.g. Decreases blood pressure by 15 points
> Care Plan is HOW e.g. Exercise for 1 hour each day and decrease soda intake to 1 serving per week.
> 
> A care goal is defined as:
> 
>     * an identifier
> 
>     * status: `proposed`, `planned`, `accepted`, `active`, `on hold`, `completed`, `cancelled`, `rejected`
> 
>     * achievementStatus:`in progress`, `improving`, `worsening`, `no change`, `achieved`, `not achieved`, `no progress`, `not attainable`
> 
>     * priority: `high`, `medium`, `low`
> 
>     * description
> 
>     * patient
> 
>     * start date
> 
>     * due date
> 
>     * created date
> 
>     * note
> 
> 
> ## Motivation
> 
> Define care goals for a patient

I think the Care Goal needs to belong/be linked to a Care Plan, and this would be a 1 to many relationship i.e. 1 Care Plan is made up of 1 or more Care Goals

**Comment by jackcmeyer** [comment]
@blestab yes! you're certainly right. We had plans of linking these together, however, we were going to do that in a future issue. You're more than welcome to work on it 🙂

**Comment by rsousaj** [comment]
No one working on this ? I'd be glad to help

**Comment by blestab** [comment]
Hi @rsousaj I am busy with this one, we'll find you something else to do.

**Comment by blestab** [comment]
hi @rsousaj, good news, just realised i have another PR on my name i still need to fix so i have put this one you your name, if that's alright

**Comment by rsousaj** [comment]
Yeah, off course. I'm glad to help

**Comment by rsousaj** [comment]
I presume that Care Goal will come first than Care Plan at Tab Header, am I right ?

**Comment by blestab** [comment]
Hi @rsousaj 

> _I presume that Care Goal will come first than Care Plan at Tab Header, am I right ?_ I've just realized that makes more sense to comes after Care Plan. But I'll leave here to clarify.

The Care Goal, for now, will be a tab right next to Care Plan. i.e. it will come after
> 
> And Care Goal also has a title, right ?

Not for now, see the specification of fields right at the top
