### ISSUE TITLE
Alert given emails addresses when items are in danger of stocking out

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#209]
Along with changes to #207, fire an alert to an email address when a stock item reaches less than 14 days of stock remaining. Along with this, we need a configurable way to both define who is alerted, the # of days as a threshold, and the A,B,C category of the item(s) to trigger the alert.

And yes, I know this leads into a larger alerting function in the system.

**Comment by turboMaCk** [comment]
I think it makes sense to implement logic for `in danger of stocking out` on backed/couchdb side. It should be send as another property on model (`Boolean`?) than the component `inventory/rank-select` from my PR or any other component (adding icon `!` to name?) should display some indication directly in list/detail. This should be the first step before implementation of alerts and emailing. Let's close ranking thing first and then I might have a look if I can help with this one too.

**Comment by turboMaCk** [comment]
:rocket: Lets start. Let me know if anyone has some ideas on this one.

**Comment by turboMaCk** [comment]
First part done in: https://github.com/HospitalRun/hospitalrun-frontend/pull/232

**Comment by tangollama** [comment]
Closing this issue. The remainder of the issues needs to be addressed by https://github.com/HospitalRun/hospitalrun-server/issues/6 and https://github.com/HospitalRun/hospitalrun-server/issues/18
