### ISSUE TITLE
Add quick create feature in the navbar

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2099]
## 🚀 Feature Proposal
In the top right of the navbar, there should should be a feature that allows me to quickly navigate to create pages that I have access to do. 

## Technical Notes
- Icon should be the `add` icon from `@hospitalrun/components`
- Options should be listed in the same order as the sidebar
- Only options that I have access to view should show up

**Comment by kumikokashii** [comment]
PR is ready for your review. Thank you. https://github.com/HospitalRun/hospitalrun-frontend/pull/2108
