### ISSUE TITLE
Add Report Incident button in the incidents module

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2100]
## 🚀 Feature Proposal
In the incidents module, there should a `Report Incident` button similar to all of the other "create buttons like `New Patient, `New Appointment`, etc.

Clicking this button should navigate the user to the `/incidents/new` page

**Comment by alti21** [comment]
can i take this?

**Comment by jackcmeyer** [comment]
Hi @alti21! You definitely can. I've assigned it to you.
