### ISSUE TITLE
Use Select component where SelectWithLabelFormGroup is used

### ISSUE THREAD

**Issue by kumikokashii** [HospitalRun/hospitalrun-frontend#2101]
## 🚀 Feature Proposal

1. Use v1.8.1 of @hospitalrun/components
2. Replace `SelectWithLabelFormGroup` with `Label` and `Select`

Note: [Select component in v1.7.0](https://github.com/kumikokashii/components/blob/cb18ddada458b33953982fa15f41aa005344fb97/src/components/Select/Select.tsx) comes with a typeahead functionality. Please see examples in the [storybook](https://components.hospitalrun.io/?path=/story/select--select-one).

**Comment by rubencgt** [comment]
I'd be happy to take this, if possible

**Comment by kumikokashii** [comment]
@rubencgt It's yours. Thank you!

**Comment by tehKapa** [comment]
Hi @rubencgt, do you need some help?

**Comment by rubencgt** [comment]
hello @tehKapa since it seems to be critical,
is there a change someone more experienced would take this issue and I can take another one?

**Comment by tehKapa** [comment]
No problem! @kumikokashii can you take care of this?

**Comment by morrme** [comment]
What is the status of this issue? @jackcmeyer @kumikokashii @tehKapa

**Comment by cpondoc** [comment]
Hey @kumikokashii @tehKapa @jackcmeyer! Would love to look at this issue if it's still open.

**Comment by tehKapa** [comment]
Sure @cpondoc, you can take it.

**Comment by chadian** [comment]
@cpondoc Any progress on this? If possible I'd like to take it on.
cc: @blestab @tehKapa

**Comment by cpondoc** [comment]
Hey @tehKapa and @blestab! Nearly done -- took some time off of Hospital Run do to some developments in my personal life, but happy to be back on the project :) Will push a PR in the next day or two!

**Comment by tehKapa** [comment]
awesome @cpondoc
