### ISSUE TITLE
Sidebar should only show links which user has access to see

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2110]
## 🐛 Bug Report

Right now, the sidebar shows all links, no matter what the user has access to see based on their permissions. 

Sidebar links should be limited to what the user is allowed to see.

**Comment by blestab** [comment]
I am a little nervous but I would like to try this as my first issue. I have finished going through some reactjs/ts tutorials and have browsed around the repo; I feel I might be able to do this one.

**Comment by jackcmeyer** [comment]
@blestab sounds great! no need to be nervous :) reach out if you need help!

**Comment by blestab** [comment]
Looking further into this it looks like i would also have to apply the same fix to the top Navbar (for smaller screen sizes) as well as restrict the 'add new' and 'edit' buttons on the relevant pages such as Patients Listing/View, Appointment Listing/View? Or should i only focus on the Sidebar for now?
