### ISSUE TITLE
Make Navbar mobile friendly

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2117]
## 🐛 Bug Report

The Navbar is not mobile friendly. 

## To Reproduce

Render the Navbar on any mobile device

![image](https://user-images.githubusercontent.com/18731800/72583497-1a993500-38ac-11ea-9ad5-153d83154acf.png)

## Expected behavior

The Navbar options should be collapsed into a hamburger button. One the hamburger button is clicked, it should have a dropdown with all of the options that are a part of the navbar.

**Comment by kumikokashii** [comment]
Hi, PR is ready for your review: https://github.com/HospitalRun/hospitalrun-frontend/pull/2118 Thank you!
