### ISSUE TITLE
Allow edit of old purchases under Inventory

### ISSUE THREAD

**Issue by aniljava** [HospitalRun/hospitalrun-frontend#212]
Purchase entries once entered are non-editable. Allow editing in a case if there is a mistake.

**Comment by jkleinsc** [comment]
@aniljava this is intentional.  The idea is that any adjustments to inventory, including mistakes made entering a purchase would be adjusted via the Adjust button on a location.  The reason for this design is that it ensures that any adjustments to inventory have a clear audit trail.

**Comment by tangollama** [comment]
Agreed. Thanks for the input @aniljava. If you have further concerns re: this issue, feel free to reply. As @jkleinsc pointed out, the process for adjustments vs. edits came directly from user feedback.
