### ISSUE TITLE
Create a script to generate dummy data

### ISSUE THREAD

**Issue by kumikokashii** [HospitalRun/hospitalrun-frontend#2122]
## 🚀 Feature Proposal
Create a script to generate dummy data. Please note that its loading into the database will be implemented separately.

~~In the Account dropdown menu (located in the Navbar, at far right), create two menu items:~~
~~1. Log in as Test (Clicking on this will load pre-populated dummy data)~~
~~2. Log out (Clicking on this will reset data)~~

## Motivation
- It'll allow us to see the product from users' perspective
- Easier to test features that display data

**Comment by blestab** [comment]
Hi @kumikokashii 

I would like to give this a try but perhaps if you can elaborate more in terms of the requirements. 

I think i get the addition of the login/logout links part. I am not sure i quite get how best to approach the dummy dummy setup/teardown part. 

Will there be a back-end component where the dummy data will come from? or can this be for example json files that can be pulled to the client on demand and from a development point of view reside in the front-end space?

**Comment by kumikokashii** [comment]
@blestab Hi, this will be on frontend. And I think it'd be helpful to put it in a json file or something similar, for when we will use this test account data for backend down the line. What do you think about it? 🙂

**Comment by blestab** [comment]
Yes I think that makes sense. let me investigate further to see how i would implement this and then I will run it past you before i start any coding.

**Comment by EmilioCastilloW** [comment]
Hi I will like to help!, Im new to TypeScript and this seems to be a good first issue to work with. What is the status of this issue?

**Comment by blestab** [comment]
Hi @EmilioCastilloW 

I am busy with the dummy data generation now. 

So far I have added menu item and have it toggling between login and logout.

**Comment by kumikokashii** [comment]
@blestab @EmilioCastilloW Thank you, both. I updated the ticket status accordingly.

**Comment by blestab** [comment]
Hi @kumikokashii 

So, I have managed to generate some JSON documents with Patients, Diagnoses, Notes, Allergies, Appointments, and RelatedPersons links for now. I haven't done Labs, Incidents and CarePlans yet but will do so soon. 

Now I was attempting to store the data into the local store, however i have some issues and was wondering if you can point me in the right direction:
1) I noticed that currently when i add a new patient using logic borrowed from the new patient component, I see _pouch_**undefined**/_db/ stores getting created, any idea how i can either ensure they have an appropriate name e.g. _pouch_**test**/_db/ (see attached image)
2) Ideally i want to ensure this data is 'local only' and does not get synced synced back to the server, so wondering whether you know if it's possible to tell the sync process to ignore certain patient ids or whether we can add a new flag on the patient model e.g. isTestData which we can then use to let the sync to server process know that this patient and it's related data, should not be sent to the server.

![image](https://user-images.githubusercontent.com/5468546/84831203-348d9e00-b02b-11ea-96f6-3d168cdee9cf.png)

**Comment by kumikokashii** [comment]
@blestab Hello! Thanks for your detailed notes 😊 When we communicate with the database to create, delete, search, etc. data, we use db classes at [src/clients/db](https://github.com/HospitalRun/hospitalrun-frontend/tree/master/src/clients/db). We use these classes, instead of directly talking to the database, because they can do all of the work for us.

Now, with the json files you've created, I imagine:
- When user clicks on "Log out", the database will be reset (= delete all data in the database).
- When user clicks on "Log in to test" (or something like that), the database will be loaded (= create new data in the database from your json files)

I think, in the future, we might switch to having one database per account. Now, we use one database.

**Comment by kumikokashii** [comment]
@blestab And, in the current development stage, no need to consider what happens with the server database. So if it works in the browser, that means all good ☀️

**Comment by blestab** [comment]
Noted with thanks @kumikokashii 
Makes perfect sense.
