### ISSUE TITLE
Care Plan Note should not be required

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2127]
## 🐛 Bug Report

When creating a care plan, the note field should not be required.

## To Reproduce
1. navigate to patients -> care plan -> add care plan
2. fill in the required fields
3. note should not be required

## Expected behavior
1. note should not be required

## Technical notes
* remote validation from redux thunk
* remove required asterisk

**Comment by anyapawar** [comment]
Would like to take this one!

**Comment by tehKapa** [comment]
Assigned to @anyapawar
