### ISSUE TITLE
New fields for diagnosis

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2128]
## 🚀 Feature Proposal
Add new fields for a diagnosis: 

- onsetDateTime (Date Time picker that defines when the symptoms first occurred
- abatementDateTime (Date Time picker that defines when the symptoms went away)
- status (selection of the following fields: active | recurrence | relapse | inactive | remission | resolved)
- note: text box which allows someone to enter a note

**Comment by reidmeyer** [comment]
Would love to take this one.

**Comment by tehKapa** [comment]
Assigned to @reidmeyer

**Comment by AlexTan331** [comment]
Is there someone working on this issue currently? If not, could I be assigned?

**Comment by reidmeyer** [comment]
@AlexTan331 , please give me 72 hours to submit a pull request. I’ve been on a long vacation. Struggling with the test file.

**Comment by AlexTan331** [comment]
I saw that you were unassigned and no one tackled it since then, so I thought it maybe available.  
I am sorry about not knowing about that. You can keep working on it, no need to rush :)

**Comment by reidmeyer** [comment]
All good Alex. My fault for taking over a month! It’s all yours if I don’t complete in 72 hours.

**Comment by reidmeyer** [comment]
Good news is I'm back from vacation and can finally finish this issue soon. Bad news is there is something wrong with https://www.npmjs.com/package/@hospitalrun/components so I can't do npm install. I'm getting an esockettimeout. Waiting for this to be resolved to continue my work on the issue.

**Comment by reidmeyer** [comment]
It works now. back to work

**Comment by tehKapa** [comment]
There was an [issue with npm](https://status.npmjs.org/#past-incidents)
