### ISSUE TITLE
New hook to simplify the use of useTranslation 

### ISSUE THREAD

**Issue by kumikokashii** [HospitalRun/hospitalrun-frontend#2135]
## 🚀 Feature Proposal
1. Create a new hook that simplifies the use of the useTranslation hook. Starting point reference looks something like this: 
```
import { useTranslation } from 'react-i18next'

export default function useTranslator() {
  const { t } = useTranslation()

  function translate(key: undefined): undefined
  function translate(key: string): string
  function translate(key: any): any {
    return key !== undefined ? t(key) : undefined
  }

  return {
    t: translate,
  }
}
```
It'd be used like this:
`const { t } = useTranslator()`
`feedback={t(error?.dateOfBirth)}`

2. Edit translation instances to use the new hook, and test they are working.

## Motivation
In some places where useTranlation is currently used, it looks like this:
`feedback={error ? (error.dateOfBirth ? t(error.dateOfBirth) : undefined) : undefined}`

We'd like to simply lines like above.

**Comment by vault-developer** [comment]
Hello, can you assign me, please?

**Comment by tehKapa** [comment]
@vault-developer you're welcome!
