### ISSUE TITLE
Demo login problem

### ISSUE THREAD

**Issue by boricic** [HospitalRun/hospitalrun-frontend#216]
Hi guys,

I've been trying to login to the demo at beta.hospitalrun.io, but none of the user/pass combos seem to work. 
I keep getting the 401 {"error":"unauthorized","reason":"Name or password is incorrect."}

**Comment by tangollama** [comment]
Sorry you're experiencing issues. We'll look into it. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by ismail-s** [comment]
I get the same problems. See screenshot:
![image](https://cloud.githubusercontent.com/assets/3778413/11591804/6747290a-9a92-11e5-93cf-f51a72609e6d.png)

**Comment by ankitpise** [comment]
I faced the same error here!

**Comment by kauegimenes** [comment]
Same, the problem is with the `https://beta.hospitalrun.io/db/_session` request.

The response is `{"error":"unauthorized","reason":"Name or password is incorrect."}`

Maybe someone changed the users?

**Comment by flamingalah** [comment]
I'm having the same problem - none of the demo logins work.

**Comment by kauegimenes** [comment]
+1

**Comment by jkleinsc** [comment]
@boricic @ismail-s @ankitpise @flamingalah @kauegimenes some of the demo users were either deleted or had their passwords changed.  I reset the passwords to the what is described at http://hospitalrun.io/demo/
Please note that the system admin user is no longer available so that this can't happen again.  Thanks all for your interest in HospitalRun!

**Comment by rmrlangford** [comment]
Hi,

Please see error below when trying to login using the supplied credentials.

{message: "socket hang up",…}

https://beta.hospitalrun.io/#/login

Please can you investigate? 

Thanks

**Comment by tangollama** [comment]
Looking into it.
