### ISSUE TITLE
Patient successfully updated message is showing internationalization key

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2167]
🐛 Bug Report

The patient successfully updated message is showing the internationalization key rather than the actual text. 

## To Reproduce
1. Create a new patient
2. Click the edit button on the patient
3. Change some fields
4. Click save
5. See that the message is not correct

## Expected behavior
* The message should be the actual text rather than the internationalization key

**Comment by falkilani** [comment]
I'd like to do this one.

**Comment by jackcmeyer** [comment]
Sound great, @falkilani! I've assigned it to you.

**Comment by dallasg** [comment]
Is the key correct?  I noticed it's not included in any of the translations.

**Comment by janmarkusmilan** [comment]
@jackcmeyer Hi, I was wondering if this issue still needs to be worked on? If so, can I try it?

**Comment by janmarkusmilan** [comment]
@jackcmeyer I was wondering if this issue still needs to be worked on?
