### ISSUE TITLE
Display success toast when lab is completed

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2168]
## Scenario
**AS**
A user who can update lab

**I WANT**
A success toast displayed

**SO THAT**
I know that the lab was successfully completed

## Acceptance Criteria
**GIVEN**
A lab is being updated

**WHEN**
The lab is successfully updated

**THEN**
A success toast should be displayed saying `Completed ${lab.type} for ${lab.patient.name}.`

**Comment by samkik579** [comment]
Hi can I work on this issue and possibly the other success toast issues as well. I am with the washu team

**Comment by anyapawar** [comment]
Hi! Can I take this?

**Comment by jackcmeyer** [comment]
@samkik579 I have assigned this to you!

**Comment by samkik579** [comment]
Thanks! Excited to work on this

**Comment by yosephAHMED** [comment]
To whom it may concern,

Has there been any progress on this issue?

Best,
Yoseph

**Comment by samkik579** [comment]
Yes. There is one last thing to add and we are almost ready to submit a pr

**Comment by anyapawar** [comment]
#2258
