### ISSUE TITLE
Display success toast when lab is successfully updated

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2169]
## Scenario
**AS**
A user who can update lab

**I WANT**
A success toast displayed

**SO THAT**
I know that the lab was successfully updated

## Acceptance Criteria
**GIVEN**
A lab is being updated

**WHEN**
The lab is successfully updated

**THEN**
A success toast should be displayed saying `${lab.type} for `${lab.patient.name} successfully updated`

**Comment by anyapawar** [comment]
Can I take this as well?

**Comment by jackcmeyer** [comment]
@anyapawar I have assigned this to you!

**Comment by yosephAHMED** [comment]
To whom it may concern,

Has there been any progress on this issue?

Best,
Yoseph

**Comment by anyapawar** [comment]
#2258

**Comment by anyapawar** [comment]
#2258 this should be fixed now
