### ISSUE TITLE
Clicking "Why HospitalRun?" in footer should go to static page rather than google doc

### ISSUE THREAD

**Issue by vikram7** [HospitalRun/hospitalrun-frontend#217]
Current footer:

![screen shot 2015-12-04 at 10 55 34 am](https://cloud.githubusercontent.com/assets/7072744/11594003/a49d0350-9a75-11e5-9c18-384b34671e0d.png)

The link to `Why HospitalRun?` should go to a static page rather than a Google doc as it currently does.

**Comment by ltoshea** [comment]
Probably, but I kind of liked being able to read through the project brief - you probably wouldn't want that much text on a webpage. Would be nice to still have the brief available at least.

**Comment by jglovier** [comment]
Yeah, the intention is to make a page for it, and it's on my radar. :+1:

**Comment by jglovier** [comment]
Closing because issues for the marketing site belong in https://github.com/HospitalRun/hospitalrun.github.io, and we do have [an issue for this there](https://github.com/HospitalRun/hospitalrun.github.io/issues/15).

Thanks!
