### ISSUE TITLE
Add related person typeahead displays additional list item in dropdown

### ISSUE THREAD

**Issue by nischayv** [HospitalRun/hospitalrun-frontend#2175]
## 🐛 Bug Report

The add related person typeahead displays an additional list element with no data for the current patient if the name of the current patient is similar to the names in the item list.

## To Reproduce

Simply use the keyboard to navigate over the elements to find the element with no data.

![Screenshot from 2020-06-25 17-27-25](https://user-images.githubusercontent.com/13353147/85808551-0d5d5d80-b70a-11ea-8c55-58fb90eac5a0.png)

## Expected behavior

The typeahead should not display the additional list element in the dropdown.

**Comment by nischayv** [comment]
I can address this in the PR for #2132 if that's okay!

**Comment by jackcmeyer** [comment]
@nischayv feel free to complete this in PR for #2132
