### ISSUE TITLE
Enter key does not submit login form

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2181]
# 🐛 Bug Report
When I press the enter key in the login form, it should submit a login request. 

## To Reproduce

1. Enter username
2. Enter password
3. Click enter
4. see that it doesn't submit a login form

## Expected behavior
It should submit the login form

**Comment by kilcorse-michael** [comment]
I can fix this if no one has claimed it yet.

**Comment by jackcmeyer** [comment]
@kilcorse-michael i've assigned this to you

**Comment by jackcmeyer** [comment]
closes via #2221
