### ISSUE TITLE
Username and password should be requred 

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2182]
# 🐛 Bug Report
Username and password should be marked as required fields on the login form and when I try to submit the login form, it should prevent a login request from being made if username and password are not filled in.

## To Reproduce
1. Navigate to the login screen
2. Submit the login form
3. See that username and password are not required

## Expected behavior
* The username and password fields should be marked as required
* When submitting the form, there should be form validation saying username/password is required
* There should be a banner message saying that it was unable to login

**Comment by linus345** [comment]
Hey, can I be assigned to this?

**Comment by jackcmeyer** [comment]
@linus345 I've assigned this to you.
