### ISSUE TITLE
No message appears when wrong login credentials are entered

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2183]
# 🐛 Bug Report

When logging in, if wrong credentials are entered, then there should be a message that says: "Unable to login. Incorrect username or password".

## To Reproduce
1. Enter incorrect username or password
2. Click the login button
3. See that no message appears stating that the wrong credentials were entered

## Expected behavior
* There should be a message that says: "Unable to login. Incorrect username or password".

**Comment by Hrugved** [comment]
Hey,
I would like to work on this issue.
thanks
