### ISSUE TITLE
Link visit to lab request

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2184]
## Scenario
**AS**
A user who can create a lab requeset

**I WANT**
The ability to a visit to the request

**SO THAT**
I can understand more about why the request is happening

## Acceptance Criteria
**GIVEN**
A lab request is being made

**WHEN**
I'm on the lab request screen

**THEN**
I would to select an visit from the a dropdown

## Technical Notes
* After a patient is selected then the visit dropdown should be populated with visists for that patient
* Visists should be sorted by date, with the most recent visit at the top of the list.
* The patient field and visit field should appear in the same row in the form

**Comment by yosephAHMED** [comment]
To whom it may concern,

I would like to work on this issue. Please assign me to it.

Best regards,
Yoseph

**Comment by jackcmeyer** [comment]
@yosephAHMED I've assigned this to you.

**Comment by yosephAHMED** [comment]
To whom it may concern,

I opened a pull request for this issue. Thank you for the opportunity.

Best,
Yoseph Ahmed

**Comment by DrewGregory** [comment]
@jackcmeyer I'd be happy to take this on!

**Comment by DrewGregory** [comment]
Should the visit option be required? Linking a visit is required for Imaging Requests, for example.

**Comment by tehKapa** [comment]
@fox1t can you answer?
