### ISSUE TITLE
Create infographic widgets for incidents

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2185]
## 🚀 Feature Proposal
Create some infographic widgets for incidents.

Examples: 
* Line graph of reported incidents overtime 
* Number of new incidents (green down error if less than yesterday, red up error if more than yesterday)
* Average time from incident reported to incident resolved
* Any other ones that could be useful 

For now, I think we can create a tab called "visualize" underneath incidents where these graphs can be located

## Technical Notes
* Ideally, these widgets should be reusable so that they could be used on the dashboard or other places.

**Comment by yosephAHMED** [comment]
To whom it may concern,

I have a question regarding this issue. Would the use of ChartJS be acceptable?

Best,
Yoseph

**Comment by jackcmeyer** [comment]
@yosephAHMED ive assigned this to you.

**Comment by jackcmeyer** [comment]
> I have a question regarding this issue. Would the use of ChartJS be acceptable?

We have a `Graphs` component in our component library https://components.hospitalrun.io/?path=/story/graphs--bar-graph.

**Comment by yosephAHMED** [comment]
> > I have a question regarding this issue. Would the use of ChartJS be acceptable?
> 
> We have a `Graphs` component in our component library https://components.hospitalrun.io/?path=/story/graphs--bar-graph.

Very cool! Excited to work on this !!
