### ISSUE TITLE
Add blood type info to patient

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2186]
## Scenario
**AS**
A user who can see patient details

**I WANT**
Blood type information displayed

**SO THAT**
I can be aware of someone's blood type

## Acceptance Criteria

> **GIVEN**
> A patient needs to be created
> 
> **WHEN**
> I create the patient
> 
> **THEN**
> An option for blood type should be shown

> **GIVEN**
> A patient needs to be edited
> 
> **WHEN**
> I edit the patient
> 
> **THEN**
> An option for blood type should be shown

> **GIVEN**
> A patient
> 
> **WHEN**
> I view the patient
> 
> **THEN**
> The blood type should be shown

## Technical Notes
Possible blood types: 
A+
A-
AB+
AB-
B+
B-
O+
O-

**Comment by saksham93** [comment]
Hi,
I wish to work on this issue.
Thanks

**Comment by blestab** [comment]
> ## Technical Notes
> Possible blood types:
> A+
> A-
> AB+
> AB-
> B+
> B-
> O+
> O-

Maybe add an Unknown option as well?

**Comment by saksham93** [comment]
@blestab Sure!
