### ISSUE TITLE
Warn about potential duplicate patient during creation process

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2187]
## Scenario
**AS**
A user who can create a patient

**I WANT**
A warning about potential duplicate patient records

**SO THAT**
No duplicates enter the system

## Acceptance Criteria
**GIVEN**
A user is being created

**WHEN**
A new patient is created that matches name, sex and DOB 

**THEN**
The system should warn about a duplicate by popping up a modal. The modal should say "Potential duplicate of: [Patient Name](link to patient record). Are you sure you want to create this patient? The modal should have a "Continue" button which will create the record and a cancel button which would stop the creation process.

## Related Issues
#461

**Comment by blestab** [comment]
Hi @jackcmeyer I would like to go for this one seeing u am no longer eligible for 'good first issue' tasks :)

**Comment by janmarkusmilan** [comment]
Hello,

If no one is tackling this issue, may I be assigned to this one? I wish to work on it.

Best regards,
Jan Markus

**Comment by jackcmeyer** [comment]
@janmarkusmilan I've assigned this to you.
