### ISSUE TITLE
Fix warning about missing logout key

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2188]
## 🐛 Bug Report
The logout link in the user icon in the navbar is missing a translation per the warning message in the console: 

```
i18next::translator: missingKey en-US translation logout logout
```

## To Reproduce
1. Load any page
2. See the warning

## Expected behavior
The warning should not appear.

**Comment by Hrugved** [comment]
Hi,
I wish to work on this issue.

There is no translation key available for 'logout' in locales/enUs.
Should I add one?

Thanks

**Comment by jackcmeyer** [comment]
@hsorellana I've assigned this to you. 

> There is no translation key available for 'logout' in locales/enUs. Should I add one?

Yes, I believe this would be the solution to this issue.
