### ISSUE TITLE
Mobile interface is identical to desktop interface

### ISSUE THREAD

**Issue by njardus** [HospitalRun/hospitalrun-frontend#219]
The mobile interface is important - doctors don't always have access to a desktop, but most of them do have their phones and/or tablets.

A mobile interface should be developed so that full functionality can be attained on a small screen.

**Comment by stefanpenner** [comment]
potentially a responsive interface

**Comment by jglovier** [comment]
Out aim is to have the app responsive down the probably the 600px mark. #135 is the next step in that effort, which is on my immediate radar, and then I'll need to break down the work into chunks beyond that after, making the app as responsive as possible down to 600px.

However, mobile usage is not currently part of our goals – at least not for the 1.0 ship. In the developing world hospitals we are actually implementing HospitalRun in, staff always have laptops, or tablets. We don't see a real need for using the software on mobile, although it would certainly be a nice to have for a post 1.0 ship.

**Comment by njardus** [comment]
As someone that lives in the developing world (South Africa) with a laptopless and tabletless doctor wife working in the state hospital close to where we live, I have to disagree about tech availability. She often comes home from work to use her desktop machine to trace blood labs, for instance. I'd consider it much more important than a nice to have, even if it happens some time after 1.0.

(disclaimer: I haven't looked at #135 yet, going to do that now.)

**Comment by jkleinsc** [comment]
I think @jglovier misspoke when he said staff always have laptops and tablets in developing world hospitals.  It obviously depends on the hospital's resources and their commitment to technology.  Given the popularity/availability of mobile phones in the developing world, I would agree that a phone interface is needed, but it is a challenge to do this in a way that provides enough information to users on a smaller screen.  I think ideally a mobile interface includes the most vital info of the full blown interface, but it may not display the full information set.  I love the idea of a responsive app and would prefer to go that route and in fact the current app is responsive but designed with larger screens in mind.  The reason that we didn't tackle mobile immediately is that developing a desktop/tablet solution allows us to build out the full functionality and then make smart decisions about what belongs in a mobile interface and what doesn't.  As an aside I think this is one of the bigger challenges of an HIS/EMR in general --- how do you break down a large amount of information into usable chunks that provides good UX?

**Comment by jglovier** [comment]
>I think @jglovier misspoke when he said staff always have laptops and tablets in developing world hospitals.

@jkleinsc to clarify, [my words](https://github.com/HospitalRun/hospitalrun-frontend/issues/219#issuecomment-162386269) were specifically about the CURE hospitals where HR is currently deployed and the use case we are building for at this stage. Is it not accurate that in those cases the medical professionals using the system always have tablets or laptops available to them?
