### ISSUE TITLE
App route goes to "/" after refresh

### ISSUE THREAD

**Issue by vault-developer** [HospitalRun/hospitalrun-frontend#2201]
## 🐛 Bug Report
After page refresh app route goes to "/".
Also it slightly harms developer experience (impossible to use hot reload feature).

## To Reproduce
1. Go to any route except "/", for example "/patients/new".
2. Try to refresh a page

## Expected behavior
1. Route should stay same after page refreshing.

## Your Environment
- *node version*: 12.6.1
- *os*:  Linux

P.S. I want to help with solving this issue. I've already fixed it and I could make PR if you don't mind.

**Comment by tehKapa** [comment]
Sure, you can open up the PR fix. Thanks!
