### ISSUE TITLE
Add Icons to 'quick add' icon in Navbar

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2208]
## 🚀 Feature Proposal
In the 'plus' icon in the Navbar, there should be icons next to the links in the list. 

The icons should be the same icons that are used in the sidebar.

**Comment by vault-developer** [comment]
I can do it if you don't mind

**Comment by AlexTan331** [comment]
If this is still available, could you assign me?

**Comment by jackcmeyer** [comment]
@alexpelan I've assigned this to you.
