### ISSUE TITLE
Add icons to hamburger menu

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2209]
## 🚀 Feature Proposal

When the hamburger menu is present in the nav bar (make your chrome window small to see the hamburger icon), there should be icons in the list. The icons should be the same icons present in the sidebar.

**Comment by linus345** [comment]
I can do this

**Comment by YimniChan** [comment]
I can do this

**Comment by jackcmeyer** [comment]
@linus345, I've assigned this to you.

**Comment by jackcmeyer** [comment]
closed via #2220
