### ISSUE TITLE
Fix weird spacing issue in quick add icon

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2210]
# 🐛 Bug Report
There is a weird spacing issue in the quick add icon in the navbar. 
![image](https://user-images.githubusercontent.com/18731800/86867358-51e8e180-c098-11ea-9f07-75accf43ded2.png)

## To Reproduce
1. Open quick add menu
2. See weird spacing at the top

## Expected behavior
The weird spacing should not be present

**Comment by vault-developer** [comment]
Could I take it, please?

**Comment by ArslanM786** [comment]
If this is still available I would like to be assigned to it

**Comment by jackcmeyer** [comment]
@vault-developer I've assigned this to you.
