### ISSUE TITLE
Ability to view allergy

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2215]
# 🚀 Feature Proposal
Currently, the list of allergies are not clickable. This issue is to make them clickable and create a component that allows a user to view the allergy.

# Technical notes
* the routing should work similar to how care plan routes work

**Comment by gdemu13** [comment]
@jackcmeyer if this issue is still available I can do it

**Comment by AlexTan331** [comment]
If this is still available, I would like to take a shot. Could you assign me?

**Comment by jackcmeyer** [comment]
@gdemu13 I've assigned this to you.
