### ISSUE TITLE
update patient form (general information) UX

### ISSUE THREAD

**Issue by vault-developer** [HospitalRun/hospitalrun-frontend#2216]
## 🚀 Feature Proposal
Update general information form UX
1. Put "Unknown" checkbox under "Date of Birth" field.

## Motivation
Now we have input "Date of birth" and checkbox "Unknown"
1. It's not clear, that checkbox "unknown" is related to field "Date of birth".  User can suggest, that this checkbox is for "Patient type", because it's under this field.
2. If "Unknown" is checked, "Date of Birth" field is hidden. If someone will view such patient, there is no way to find out, what field does "Unknown" belong to.

![image](https://user-images.githubusercontent.com/28157258/86619003-4089d180-bfd3-11ea-98dc-091dc46464df.png)

P.S. I can work on this issue if you don't mind

**Comment by jackcmeyer** [comment]
To close the loop on this: 

I think the final requirement is merely a UI change, rather than a functionality change. The functionality we have now where checking unknown changes the input box to an integer input box for an estimate age is the desired behavior.
