### ISSUE TITLE
Implement "no patients" state on the /patients route

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2231]
## 🚀 Feature Proposal
Implement "no patients" state on the `/patients` route. When there are no patients in the database, then a page that looks like the following should show: 

![image](https://user-images.githubusercontent.com/18731800/87260221-343fc180-c476-11ea-80ff-5d886726985b.png)

## Technical Notes
- for now, we can use the already existing patients icon in place of the icon that is shown. 
- note: this is state is different than no patients returned via a search.

**Comment by Fibii** [comment]
hi, i'd like to work with this issue if possible.

**Comment by marcosvega91** [comment]
@Fibii I think that you can :D
