### ISSUE TITLE
Add ability for documenting visits for a patient

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2241]
## 🚀 Feature Proposal
There should be the ability to document a visit for a patient. 

There should be a new tab called visits on the patient profile screen. 

When the visits tab is active, there should be a button that allows a user to create a new visit. The visits tab should also display a table of information for that visit. 

When the user click on the new visits tab, the should be prompted to enter the following information: 

```
startDateTime: string
endDateTime: string
type: string;
status: `planned` | `arrived` | `triaged` | `in progress` | `on leave` | `finished` | `cancelled`
reason: string
location: string
```

The start date time should be auto populated to the current time.

A visit should also contain the following information that is auto generated by the system: 

```
id: string
createdAt: string
updatedAt: string
```

The table of visits should show the start date time, end date time, type, and status. 

## Technical Notes
* The routing should work similarly to the care plan routing

**Comment by YimniChan** [comment]
Could I get assign to work on this?
