### ISSUE TITLE
Create basic imaging module

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2242]
## 🚀 Feature Proposal
HospitalRun should have an imaging module. This issue is to start implementing the imaging module by implementing the basic functionality of creating an imaging request. 

### Sidebar/Navbar
There should be an imaging tab on in the sidebar. The options in the sidebar should be "New Imaging Request" and "Imaging Requests". 

There should be a new image request option in the quick add button in the navbar. 

#### Imaging Requests
- When clicking on the "Imaging Requests" link, it should bring you to a page that has a heading of "Imaging Request". 
- It should display a table of all imaging requests. It should the following in the table: date requested, requested by, imaging type, patient, and status. 
- There should be a button that allows the user to create a new imaging request

### New Imaging Requests
- It should prompt the user for the following information: patient (typeahead for searching patient), imaging type (input box), status (requested, completed, canceled in a select), notes (text box). 

## Motivation

Please outline the motivation for the proposal.

## Technical Notes
- similar implementation to lab module
- need to add permissions for imaging requests
- ability to view imaging request/edit imaging request/update imaging request will come later

The interface should look something like

```ts
interface ImageStudy extends AbstractDBModel {
  patient: string 
  type: string
  status: 'requested' | 'completed' | 'canceled'
  requestedOn: string
  requestedBy: string // will be the currently logged in user's id
  completedOn?: string
  canceledOn?: string
  notes?: string
}

**Comment by AlexTan331** [comment]
@jackcmeyer  I am not sure about the timeline for this issue, but I would like to give it a shot.

**Comment by AlexTan331** [comment]
And also, for this issue, it will not have the ability to view a singe imaging request yet?

**Comment by jackcmeyer** [comment]
@AlexTan331 I've assigned this to you. No particular time line in mind :). 

And. yes, you are right, no way to view single imaging request in this issue. Figured to keep scope small, we'll just start with the two screens.
