### ISSUE TITLE
Create Patient History tab

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2255]
## 🚀 Feature Proposal
There should be a patient history tab available in the patient profile. 

This history tab should show in chronological order events that have happened to the patient. 

To begin with this will be: 
- labs
- appointments

# Technical Notes
- Should use the `Callout` component
- will need some sort of special query that gets all entities that can be seen in the history timeline

**Comment by YimniChan** [comment]
Could I get assign to work on this issue?

**Comment by jackcmeyer** [comment]
@YimniChan I've assigned this to you.

**Comment by morrme** [comment]
Hi @YimniChan ! Just checking in on this issue. Are you blocked? Can we help in any way?

**Comment by VictorJuez** [comment]
Hello! I've been working a little bit on this issue and I came up with this. What do you think? I used a Table instead of a Callout because I wasn't sure how did you want to show the information with a Callout.
Anyway, I would like to continue working on this, so could I get assigned to it? Then we can discuss further the correct approach to solve it. Thanks 😃 
![HistoricalData](https://user-images.githubusercontent.com/18482730/95019599-8a339800-0666-11eb-81db-5f58d1be4168.png)

**Comment by JonnyMnemonic123** [comment]
Could I be assigned to work on this issue?

**Comment by tehKapa** [comment]
@VictorJuez sorry for delay. good mockup! 
@fox1t @jackcmeyer @StefanoMiC @lauggh your opinions about it?

@JonnyMnemonic123 I don't know if you want to work on it with @VictorJuez

**Comment by VictorJuez** [comment]
@tehKapa Cool! 😄 I will continue with this then.
And @JonnyMnemonic123 let me know if you want to collab with me

**Comment by JonnyMnemonic123** [comment]
Yes that would be great

**Comment by lauggh** [comment]
Is the table sortable by date? What other information do we expect to show for a Patient History?

**Comment by VictorJuez** [comment]
> Is the table sortable by date? What other information do we expect to show for Patient History?

Hello @lauggh ! Yes, it is sorted by date. And regarding the information, right now it is showing Labs and Appointments events.  For each of these events we can see:
- For Labs, it is shown the Lab Type
- For Appointments, it is shown the Appointment Reason  

Very concise information just to identify the events.

**Comment by baoqchau** [comment]
@jackcmeyer @tehKapa I saw that you closed the PR made by @VictorJuez. Will this issue still need to be addressed? If it is then I'm interested

**Comment by tehKapa** [comment]
@baoqchau assign to you

**Comment by baoqchau** [comment]
![Screenshot from 2021-03-24 22-07-48](https://user-images.githubusercontent.com/8473870/112422062-87e4f900-8ced-11eb-81de-731f59785c2f.png)
Hello maintainers. Will this design look alright to you? I'm doing something similar to what @VictorJuez did, but I divided `Appointment` and `Lab` into smaller events. For `Appointment`, we can have `Started` and `Ended` event. For `Lab`, we can have `Requested`, `Completed` or `Canceled` event. 
If it looks good, I will proceed with the tests and submit a PR soon

**Comment by tehKapa** [comment]
Good work @baoqchau. Create the PR so we can test it in an 'active' way
