### ISSUE TITLE
Fix basic auth popup happening during login process

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2256]
## 🐛 Bug Report
Sometimes a basic auth popup happens during the login process

## To Reproduce
Not clear what steps are to reproduce this issue. 

## Expected behavior
The system should use our login page rather than the ugly dialog popup to start the authentication process.

## Technical Notes
- https://docs.couchdb.org/en/stable/intro/security.html
- Library we use for pouchdb authentication: https://github.com/pouchdb-community/pouchdb-authentication

I think that it is likely related to the `skip_setup` flags not being configured properly.

**Comment by blestab** [comment]
@jackcmeyer you can put this on my name, i'll see if i can reproduce and then fix it. I know at soem point i had it on my local dev environment but can't recall when it stopped.

**Comment by jackcmeyer** [comment]
@blestab this has been assigned to you.
