### ISSUE TITLE
Update patient profile page to always display useful information

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2259]
## 🚀 Feature Proposal
The patient profile should always display the patient's most important information regardless of what tab they are on. 

The goal of this issue is to make a screen that looks similar to this: 
![image](https://user-images.githubusercontent.com/18731800/88730359-8251f780-d0fb-11ea-98e5-3f028f6df0a3.png)

## Notes
- don't worry about colors or matching the mockup exactly, this is simply to get the layout in place
- for sections that that do not yet exist (i.e. procedures), don't worry about adding them
- In the allergies box, each item should link to the view allergies page
- for now, the diagnoses section should just display  a list of diagnoses and the date that diagnosis was on (don't worry about status/ICD-10 or secondary diagnoses since we don't have that concept yet).
- for now, ignore the new visit button, since the concept of visits does not yet exist

**Comment by AlexTan331** [comment]
If this is still available, could I be assigned?

**Comment by tehKapa** [comment]
No one has come forward. We can assign it to you @AlexTan331

**Comment by AlexTan331** [comment]
Just need some clarification on this issue: 
- should I add this new layout component between the title component and the breadcrumbs component, or between the breadcrumbs component and the tabs component?  
- For now, are there only three sections being displayed: Allergies, Diagnoses, and Care plan?

**Comment by jackcmeyer** [comment]
@AlexTan331 not sure how I missed this :(. 

- it should display after the breadcrumbs, in my opinion. It might be necessary to stop using `useTitlte` hook, which I think is ok.
- The assumptions you are making are correct

**Comment by AlexTan331** [comment]
@jackcmeyer  
Just want to make sure I am on the right track. This is the layout I have come up with so far. 
Is this close to the image in your mind? 


![image](https://user-images.githubusercontent.com/40738727/89941647-52215300-dbe9-11ea-8bb1-d3a3130542ae.png)

![image](https://user-images.githubusercontent.com/40738727/89941671-5a798e00-dbe9-11ea-9103-a4c9017c2eb6.png)
