### ISSUE TITLE
Previous errors are showing up in lab request screen

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2260]
## 🐛 Bug Report
When creating a new lab request, if I request lab and it fails the validation and provides error feedback to the user, and then leave the page, and then come back, the previous errors are still on the page. 

## To Reproduce
1. Navigate to new lab request
2. Click the save button
3. see the validation errors
4. navigate to anywhere else in the system
5. navigate back to the new lab request screen
6. see that the errors are still present. 

## Expected behavior
The errors should no longer show when I navigate back to the lab request page.

**Comment by Tomastomaslol** [comment]
Hi @jackcmeyer, I think I should be able to help you with this issue.  Could you please assign it to me?

**Comment by jackcmeyer** [comment]
@Tomastomaslol I've assigned this to you

**Comment by Tomastomaslol** [comment]
Hi @jackcmeyer, 

I noticed a similar issue when creating a new patient. 

![Kapture 2020-08-01 at 14 37 21](https://user-images.githubusercontent.com/1872246/89094208-bf243400-d404-11ea-899d-a31c2a18856b.gif)

Are you happy for me to report it as an issue and suggest a fix for it?
