### ISSUE TITLE
Is REST Api supports?

### ISSUE THREAD

**Issue by santoshgistto** [HospitalRun/hospitalrun-frontend#227]

**Comment by jkleinsc** [comment]
@santoshgistto there isn't a specific HospitalRun REST API, but on the server side, HospitalRun uses [CouchDB](http://couchdb.apache.org/), which has a strong REST API: http://docs.couchdb.org/en/1.6.1/api/index.html#api

**Comment by santoshgistto** [comment]
@jkleinsc  Thank you
