### ISSUE TITLE
Remove redux in favor of react-query

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2271]
## 🚀 Feature Proposal
This is a tracking issue to remove redux and replace it with react-query.

Modules to complete: 

- [x] incidents
- [ ] patients
- [ ] scheduling
- [ ] medications
- [ ] labs

## Motivation
For the motivations on why see: hospitalrun/hospitalrun#404

**Comment by tehKapa** [comment]
Link #2273
