### ISSUE TITLE
Improve test on Login.tsx

### ISSUE THREAD

**Issue by tehKapa** [HospitalRun/hospitalrun-frontend#2278]
It's necessary to improve the testing of [Login.tsx](https://coveralls.io/builds/32646552/source?filename=src/login/Login.tsx) because it lowers the global percentage by a lot

**Comment by rsousaj** [comment]
Hi, I would like to try this one.

**Comment by tehKapa** [comment]
@rsousaj assigned

**Comment by rsousaj** [comment]
@tehKapa Working on this! Tks

**Comment by rsousaj** [comment]
Matteo, I still working on this trying to deliver best practices possibles. Is that fine ? @tehKapa
