### ISSUE TITLE
`react-hooks/exhaustive-deps` warnings do not appear when running `npm run lint`

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2280]
When running `npm run lint`, all linter errors should show up. When running `npm run lint` and there is a dependency issue with a `useEffect`, the warning should show.
```

## Expected behavior
When there is a violation of `react-hooks/exhaustive-deps`, `npm run lint` should report the error.

## Technical Notes
- this is likely do to not extending `react-app` in eslint configurations

**Comment by Tomastomaslol** [comment]
Hi @jackcmeyer ! I would love to take a look at this! If possible could you assign this to me?

**Comment by jackcmeyer** [comment]
@Tomastomaslol sounds great! I've assigned this to you!
