### ISSUE TITLE
Link diagnosis with visit

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2290]
## 🚀 Feature Proposal

A diagnosis should be able to be connected to a visit. When a diagnosis is being created, a list of visits for the current patient should show.

**Comment by janmarkusmilan** [comment]
Hi @jackcmeyer! I would love to try and tackle this issue.

**Comment by morrme** [comment]
Go for it @janmarkusmilan !
