### ISSUE TITLE
Create downloadable incidents csv report

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2292]
## 🚀 Feature Proposal
There should be the capability of downloading an incidents CSV report from the UI. This report should be based on the current search parameters defined on the view incidents screen. 

There should be a dropdown button above the table that says "Download Report". There should be an option for CSV in the list of options. 

Clicking on that button should export incident data as a csv for whatever is currently being displayed in the table.

**Comment by reidmeyer** [comment]
I'd be interested in being assigned this task.

**Comment by reidmeyer** [comment]
I'd be interested in giving a crack at this for the next 5 days.

**Comment by fox1t** [comment]
I've assigned this to you!

**Comment by reidmeyer** [comment]
I've noticed that when I create two incidents, and resolve one, the resolved one disappears, even when i switch the filter to "'resolved" or "all". Another issue might want to be created for this at some point. @fox1t.

Not sure if this will impede me working on this issue. I will continue forward.

**Comment by jackcmeyer** [comment]
@reidmeyer could you open another issue for this bug with steps to reproduce?

**Comment by reidmeyer** [comment]
@jackcmeyer Additionally, I noticed that when I change the filter to "all" it displays a blank incident that is a patient. This shouldn't happen, correct? I've added this to the new issue. #2300 
![image](https://user-images.githubusercontent.com/16112576/90140909-fd2e3a00-ddac-11ea-850b-fcb1f9c2cc8a.png)
