### ISSUE TITLE
Successfully created lab shows translation key and lab id instead of actual text and lab name

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2293]
## 🐛 Bug Report
When successfully creating a lab, the success message currently shows `lab.successfullyCreated test ${:id}.

## To Reproduce

1. navigate to new lab request
2. fill in information
3. save the lab
4. see the wrong error message

## Expected behavior
The success message should say `Successfully created ${labType} for ${patientName}

**Comment by ArslanM786** [comment]
I will start working on this. Can I be assigned?

**Comment by morrme** [comment]
@ArslanM786 Sure go ahead!

**Comment by morrme** [comment]
I just encountered this when reviewing another PR. Here is the screenshot if it helps: 
![Screen Shot 2020-08-17 at 1 49 42 PM](https://user-images.githubusercontent.com/26514778/90434119-820da200-e092-11ea-8cc1-3ef9e04e3c04.png)

**Comment by morrme** [comment]
@ArslanM786 How is everything going?  Are you blocked and/or do you need any support?

**Comment by krahulsrinivas** [comment]
I would like to start working on it. Can i be assigned?(This would be my first time contributing so i may need some help)

**Comment by gwal21** [comment]
Hello @jackcmeyer, I have fixed this bug, although I'm not sure if it was the best way of doing so. Please let me know if you would like to assign it to me. This will be my first time contributing to an open-source project, so I may need a little guidance.

![LabSuccess](https://user-images.githubusercontent.com/65289595/93924731-1f3ba600-fce3-11ea-8a1c-8847fd09a6fa.PNG)

**Comment by wiertek** [comment]
What is the status of this ticket?

**Comment by tehKapa** [comment]
Hi @gwal21. What you need to do is create a Pull Request from your forked repository to this repository.
