### ISSUE TITLE
Successfully completed lab shows translation key instead of actual text

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2295]
## 🐛 Bug Report
When completing a lab, it shows the translation key instead of the actual text. 

## To Reproduce
1. create a lab
2. complete the lab
3. see the key says lab.successfullyCompleted

## Expected behavior
The message should say `Successfully completed ${type} for ${patient}`

**Comment by ArslanM786** [comment]
I will start working on this. Can I be assigned?

**Comment by morrme** [comment]
@ArslanM786 👍🏾

**Comment by morrme** [comment]
@ArslanM786 Just checking on this one as well...let us know if we may be of assistance!

**Comment by gaweki** [comment]
@morrme i fix this in [here](https://github.com/HospitalRun/hospitalrun-frontend/pull/2376)

**Comment by morrme** [comment]
@gaweki  Please see @jackcmeyer  's note here: https://github.com/HospitalRun/hospitalrun-frontend/pull/2376#pullrequestreview-484648602

**Comment by gaweki** [comment]
@morrme would like to assign me?
