### ISSUE TITLE
Rename lab request related buttons

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2296]
## Feature Request
Rename the lab request related buttons to align with more domain specific language. 

- `New Lab Request` button should be renamed to `Request Lab`. 
- Sidebar `New Lab Request` should be renamed to `Request Lab`
- `Save` button in new lab request page should say `Request`

## Technical Notes
- refactor any variable names or function that references "saving" a lab request

**Comment by AlexTan331** [comment]
Can I be assigned to work on this one?
