### ISSUE TITLE
Support a list of notes for a lab request

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2297]
## 🚀 Feature Proposal
Currently, the lab requests page only supports one note. If there are multiple notes the one note field would have to be constantly updated. 

This feature is to support a list of notes for a given lab request. This should work similar to a comments section does. 

We can display past notes with the callout component. At the bottom of the note list, a text area should appear for adding a new notes.

**Comment by rsousaj** [comment]
Hey @jackcmeyer, I would like to challenge myself on this one as no one appeared yet

**Comment by morrme** [comment]
Go for it @rsousaj  !

**Comment by rsousaj** [comment]
Well guys, is this more or less what I should achieve ?

![screenshot01](https://user-images.githubusercontent.com/12521138/90813252-b33dda80-e2fd-11ea-8204-1e957c6e6619.png)

**Comment by blestab** [comment]
Just curious if we shouldn't maybe add the ability to remove notes e.g. one makes a mistake? Maybe we can log a separate issue for this since a PR is already under review for this.

**Comment by fox1t** [comment]
@blestab good point. Would you mind to open a new issue?
