### ISSUE TITLE
Add "Patient Listing" button to patient update confirmation dialog

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#230]
<img width="643" alt="screen shot 2015-12-07 at 8 11 28 pm" src="https://cloud.githubusercontent.com/assets/1319791/11645035/0c83ac0c-9d1f-11e5-94ec-6863bd900302.png">

Once you create a new patient record, or update an existing record, you get a confirmation dialog that basically just dismisses the dialog. There is a good chance once you're done updating the record you simply want to return to the Patient Listing index view, so lets put a button on that dialog that lets you go directly there so you don't have to click "Ok" to confirm, then scroll all the way back up to the listing and click there instead because efficiency.

**Comment by capurp** [comment]
Hi, I am interested in helping out on this project. Could I take a shot at implementing this request?

**Comment by tangollama** [comment]
Absolutely. Swing away. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by capurp** [comment]
Awesome! Thanks. I am still getting familiar with ember and trying to understand the application repo. So I apologize in advance if this fix will take a bit longer to implement...
