### ISSUE TITLE
Sidebar improvements proposal

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2305]
## 🐛 Bug Report

Whenever the Sidebar gets changed either by adding new links or reordering links. The Sidebar test will fail since it references hard-coded index locations of menu items. It might be better if the Sidebar tests, instead of expecting the menu items to be in specific locations (exception Dashboard (always first), Patients(always second), other modules then come, and then Incidents always last, since it is not linked to patients. 

This was the modules links between the Patients and Incidents links can be reordered without breaking the tests

## To Reproduce

Edit _src\shared\components\Sidebar.tsx_ by reordering the modules links

Change for example this:

```js
          {getMedicationLinks()}
          {getImagingLinks()
```
by reordering the function calls to be:

```js
          {getImagingLinks()
          {getMedicationLinks()}
```

This reorders the links on the rendered Sidebar, breaking the Sidebar tests since the tests are hard coded to look for the links in specific index positions.

## Expected behavior

Reordering the Sidebar links of modules other than the Dashboard, Patients, and Incidents links should not break the Sidebar tests.

We can maybe reorder the Sidebar links as below i.e. Dashboard (first), Patients(second), Incidents (last) and the rest can be in any order as long as its between Patients and Incidents links:

```js
          {getDashboardLink()}
          {getPatientLinks()}
          {getAppointmentLinks()}
          {getLabLinks()}
          {getMedicationLinks()}
          {getImagingLinks()}
          {getIncidentLinks()}
```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by rsousaj** [comment]
Can I give it a shot ?

**Comment by blestab** [comment]
Absolutely @rsousaj

**Comment by rsousaj** [comment]
Just to be sure, I checked in last commit and Incident is not the last item on Sidebar.

This is the actual order:

          {getDashboardLink()}
          {getPatientLinks()}
          {getAppointmentLinks()}
          {getLabLinks()}
          {getIncidentLinks()}
          {getMedicationLinks()}
          {getImagingLinks()}

Said that, what should be the right approach ?

**Comment by blestab** [comment]
Hi @rsousaj, you can do it this way. 

Dashboard
Patients
Appointments
Medications
Labs
Imaging
Incidents

Don't forget the Sidebar test as that's where things get interesting :)
