### ISSUE TITLE
Report Incident link duplicated in the quick create menu

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2306]
## 🐛 Bug Report

The Report Incident option is duplicated in the quick create menu

## To Reproduce

Click the quick create icon (**+** icon in the top right corner of the navbar)
Notice there are 2 "Report Incident" options, there should only be one.

![image](https://user-images.githubusercontent.com/5468546/90294999-1b1c9d00-de88-11ea-8f1b-72991f7fb7ea.png)

Navbar.tsx

```js
// For Desktop, add shortcuts menu
  const addPages = [
    pageMap.newPatient,
    pageMap.newAppointment,
    pageMap.newLab,
    pageMap.newMedication,
    pageMap.newIncident,
    pageMap.newIncident,
    pageMap.newImaging,
  ]
```

## Expected behavior

There should only be one Report Incident link in the quick create menu

Navbar.tsx:

```js
  const addPages = [
    pageMap.newPatient,
    pageMap.newAppointment,
    pageMap.newLab,
    pageMap.newMedication,
    pageMap.newIncident,
    pageMap.newImaging,
  ]
```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by thacherT1D** [comment]
@blestab could you please assign this to me? I have a fix ready for a PR

**Comment by morrme** [comment]
@thacherT1D  go for it!

**Comment by thacherT1D** [comment]
PR Submitted -- https://github.com/HospitalRun/hospitalrun-frontend/pull/2313
