### ISSUE TITLE
Disallow console log in ESLint

### ISSUE THREAD

**Issue by Tomastomaslol** [HospitalRun/hospitalrun-frontend#2307]
## 🐛 Bug Report

As a followup to https://github.com/HospitalRun/hospitalrun-frontend/issues/2286 I thought it might be desirable to not allow any log messages in the application using an ESlint rule https://eslint.org/docs/rules/no-console

## Proposed changes 
* Remove any `console` call from the application
* Add a rule in the ESLint config that would make the linter fail if there is a `console` call in the application

Is there any good reason why `console` logs should be kept in the application?

**Comment by jackcmeyer** [comment]
Seems reasonable to me. 

> Is there any good reason why console logs should be kept in the application?

If there is, we can allow console.log on a per file/line basis.

**Comment by tobireuen** [comment]
I would like to work on this!

Just so we're clear: you want ANY call to console removed and forbidden, right?

**Comment by fox1t** [comment]
I agree that we can whitelist `console.log`s where the call is really needed (spoiler alert: nowhere XD)
@tobireuen yes!

**Comment by tobireuen** [comment]
Okay but have a look at [App.tsx:24](https://github.com/HospitalRun/hospitalrun-frontend/blob/6434fd07784b4cddc886c5759b34dbbdab273006/src/App.tsx#L24).

If I remove the console.log there, I could as well remove the catch block. Are exceptions caught on a higher level? Or how would you handle this specific case?

Please bear with me, this would be my first contribution and I want to be extra cautious.

**Comment by Fibii** [comment]
@tobireuen, i don't think exceptions are handled on the higher level, a good way to handle that is by either informing the user with an alert or a notification with whatever error that is, or use some kind of a logger 

for now you can override no-console rule for that line, unless specified otherwise by the maintainers

**Comment by tobireuen** [comment]
@Fibii thank you, will do it as you suggested and override the rule

If someone would be so kind and assign this issue to me, I could open a pull request. 🙃

**Comment by tehKapa** [comment]
@tobireuen done! thanks for your contribution!
