### ISSUE TITLE
Refactor Patient notes to use React Query

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2335]
## 🚀 Feature Proposal
Refactor Patient notes to use React Query instead of redux. 

There should be three new hooks added: 
- usePatientNotes
- usePatientNote
- useAddPatientNote

The code for adding and viewing notes should be updated to use the new hooks. 

## Motivation
Remove redux

## Technical Notes
- See patient allergies for inspiration
- delete redux code that will become unused

**Comment by michaelkramer** [comment]
May I take this?

**Comment by jackcmeyer** [comment]
@michaelkramer You got it!
