### ISSUE TITLE
Refactor patient related persons to use react query

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2336]
## 🚀 Feature Proposal
Refactor patient related persons to use react query instead of redux

There should be 4 new hooks that get added
- usePatientRelatedPerson
- usePatientRelatedPersons
- useAddRelatedPerson
- useRemoveRelatedRelatedPerson

## Motivation
Remove redux

## Technical Notes
- Follow allergies for inspiration
- remove unused redux code after completion

**Comment by pjbass** [comment]
Hey @jackcmeyer, I would like to try to tackle this issue. Can you assign it to me?

**Comment by jackcmeyer** [comment]
@pjbass I've assigned this to you!
