### ISSUE TITLE
Refactor Patient Visits to use react query

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2337]
## 🚀 Feature Proposal
Refactor patient visit code to use react query instead of redux

Add 3 hooks
- usePatientVisits
- useAddVisit
- useVisit

Refactor code that currently accesses visits through the patient stored in the redux store to now use this code

## Motivation
Remove redux

## Technical Notes
- look diagnoses and imaging requests for code that links to visits
- use allergies code as inspiration
- remove unused redux code when finished

**Comment by Tomastomaslol** [comment]
Hi @jackcmeyer. I would love to take a look at this. Could you please assign this to me?

**Comment by morrme** [comment]
@Tomastomaslol  Sure! Thanks for volunteering!
