### ISSUE TITLE
Refactor scheduling module to use react query

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2338]
## 🚀 Feature Proposal
Refactor the scheduling module to to use react query instead of redux

Need 5 hooks
- useAppointment
- useAppointments
- useScheduleAppointment
- useUpdateAppointment
- useDeleteAppointment

Refactor the code to use these new hooks

## Motivation
Remove redux

## Technical Notes
- use incidents module for inspiration
- remove redux after completion

**Comment by WinstonPoh** [comment]
Hello, can I be assigned this issue please?:)

**Comment by morrme** [comment]
@WinstonPoh  Go for it! Thank you!
