### ISSUE TITLE
Refactor labs module to use react query instead of redux

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2339]
## 🚀 Feature Proposal
Refactor the labs module to to use react query instead of redux

Need 5 hooks

- useLab
- useLabsSearch
- useCancelLabel
- useCompleteLab
- useRequestLab

Refactor the code to use these new hooks

## Motivation
Remove redux

## Technical Notes
use incidents module for inspiration
remove redux after completion

**Comment by rsousaj** [comment]
Hey Jack, could you assign me on this one ?

**Comment by jackcmeyer** [comment]
I have assigned you this @rsousaj!

**Comment by rsousaj** [comment]
@jackcmeyer could you help me a little bit - or someone else ?

I was trying to figure out the best approach for ViewLab. That screen use lab and patient data and they are dependent query (patient only runs after lab.patient is available). So, the code below was my approach for usePatient that I would like to know if is it ok:

`function fetchPatient(_: any, id?: string): Promise<Patient> {
  return PatientRepository.find(id || '')
}

export default function usePatient(id?: string) {
  return useQuery(['patient', id], fetchPatient, { enabled: id })
}`
