### ISSUE TITLE
An array of allergies (new model) associated to patients

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#234]
Track allergies on a patient, for the purposes of eventual features to trace drug interactions. Philosophically, we don't want HospitalRun handling the interaction service. Instead, we'd prefer to both trace the list of allergies as well as the list of allergic reactions/interactions from a separate, centralized service. However, to to any of that, we need the allergies identified and associated with patient.

**Comment by trevorbunch** [comment]
If you are using an external drug / allergy interaction service (e.g.
through a Vidal or Lexicomp) - you should plan to use a standard Allergy Dx
code system (e.g. ICD-10-CM).

*Trevor Bunch * Chief Information Officer
<http://ae.linkedin.com/in/trevordbunch>  <https://twitter.com/trevorbunch>
Tel: +971 3 713 1161 | Address: PO Box 1016, Al Ain, UAE
tbunch@oasishospital.org | www.oasishospital.org

*Oasis Hospital:** Birthplace of Leaders for the Nation *
<http://www.facebook.com/oasishospital>
<http://www.twitter.com/oasishospital>
<http://www.instagram.com/oasishospital>

**Comment by mnorbeck** [comment]
@tangollama agree that the allergies need to be directly associated with the patient.  Say, as opposed to be down in a visit.   Doctors want to be able to quickly see the known allergies, similar to diagnosis, directly from patient info.

**Comment by jkleinsc** [comment]
Closed by #679
