### ISSUE TITLE
Refactor patient appointments to use react query instead of redux

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2341]
## 🚀 Feature Proposal
Refactor patient appointments to use react query instead of redux

Need one hook: 
- usePatientAppointments (given a patient id, returns a list of the patient appointments)

## Motivation
Remove redux

## Technical Notes
- use `usePatientDiagnoses` as inspiration
- remove redux code after

**Comment by Tomastomaslol** [comment]
Hi @jackcmeyer. I would love to take a look at this. Could you assign this to me?

**Comment by jackcmeyer** [comment]
@Tomastomaslol you got it!
