### ISSUE TITLE
Patient should be autopopulated when clicking New Appointment from Patient Appointments page

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2350]
## 🚀 Feature Proposal
When looking at a patient's appointments on their patient profile page and a user clicks the New Appointment button, the current patient should be autopopulated when the New Appointment page loads

**Comment by mani9896** [comment]
Hey @jackcmeyer i would like to have a try at this issue, and a little guidance would be appreciated

**Comment by morrme** [comment]
@mani9896 Welcome! Go ahead!

**Comment by UmairKamran** [comment]
Hi @morrme, first time contributor here. Seeing as this issue is still open mind if I give it a try?

**Comment by tehKapa** [comment]
ok @UmairKamran !

**Comment by WinstonPoh** [comment]
Hello! I'm currently finishing up refactoring the Scheduling/appointments module, so it might be good to pause this for a while?

**Comment by tehKapa** [comment]
Can you link your PR to this thread for reference?

**Comment by morrme** [comment]
@WinstonPoh  ^

**Comment by WinstonPoh** [comment]
#2338 @tehKapa

**Comment by tehKapa** [comment]
Ok! @UmairKamran can you wait for the completion of #2338 before starting?

**Comment by UmairKamran** [comment]
Sure @tehKapa! I'll keep an eye out for it.
Thanks for the heads up @WinstonPoh

**Comment by WinstonPoh** [comment]
@UmairKamran  the PR for my task is here just FYI :) https://github.com/HospitalRun/hospitalrun-frontend/pull/2424/

**Comment by WinstonPoh** [comment]
@UmairKamran #2424 has been merged now :) thanks for your patience!
