### ISSUE TITLE
Resolve issue with Patient Labs tests

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2356]
## 🐛 Bug Report

When running all tests, notice the warning just after the AddDiagnosisModal test pass confirmation. There is a warning that references Labs.

## To Reproduce

Run all tests.
Notice the warning about use of act() and a stack trace just after the AddDiagnosisModal test passed confirmation.

![image](https://user-images.githubusercontent.com/5468546/91835068-2c67f680-ec49-11ea-92fe-6210d998f3de.png)

## Expected behavior

We should not get errors or warnings when tests pass.

## Your Environment

- *node version*: 10
- *fastify version*: >=1.0.0
- *os*: Windows 10
- *any other relevant information*

**Comment by Tomastomaslol** [comment]
Hi @blestab

I believe there already has been an issue raised for this and https://github.com/HospitalRun/hospitalrun-frontend/issues/2357 at https://github.com/HospitalRun/hospitalrun-frontend/issues/2287.

I tried to solve it but got stuck while trying to fix one of the tests: https://github.com/HospitalRun/hospitalrun-frontend/issues/2287#issuecomment-683233602.

if someone else would like to take another look at this I'm happy to provide whatever support I can 🙂

**Comment by blestab** [comment]
Thanks @Tomastomaslol, i did not realise there was another issue already open for this 👍🏾

**Comment by blestab** [comment]
This is a duplicate of #2287
