### ISSUE TITLE
Care Plan list view action button shows translation key instead of translation text

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2372]
🐛 Bug Report

Care Plan list action button shows translation key, **actions.view** instead of translation text **View**

## To Reproduce

Create a Patient
Add a Diagnosis
Add a Care Plan for the Diagnosis you just added
View the list of Care Plans
Notice the view action button has a label that says actions.view instead of View

## Expected behavior

On the Care Plan listing, the view action button should display **View**

## Your Environment

- *node version*: 10
- *fastify version*: >=1.0.0
- *os*: Windows 10
- *any other relevant information*

**Comment by gaweki** [comment]
how to change label? @blestab

**Comment by gaweki** [comment]
@jackcmeyer would you add label in progress, mr?
