### ISSUE TITLE
create `usePatient` hook which will get patient by id and remove redux code

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2379]
## 🚀 Feature Proposal
Create a `usePatient` hook which will get a patient by id and remove all related redux code for getting a patient by id. 

## Motivation
- remove redux

## Technical Notes
- start using the `usePatient` hook for general information tab
- remove redux code and related tests

**Comment by Tomastomaslol** [comment]
Hi @jackcmeyer could I take a look at this?

**Comment by tehKapa** [comment]
Ok @Tomastomaslol!
