### ISSUE TITLE
Deployment process

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#238]
Here's a vision: I access the demo site, now I've got the whole app on my device. 

Now from within the app, I initiate the process to "create the app," meaning deploy the system to an EC2 instance (or whoever we make the cloud provider), including automatically transferring the data I've been capturing and entering on my local machine into the cloud instance.

With Pouch/Couch, we could get that.

**Comment by mnorbeck** [comment]
@tangollama   Do we really need this for v1.0?

**Comment by broerse** [comment]
If you use [ember-cli-deploy-couchdb ](https://www.npmjs.com/package/ember-cli-deploy-couchdb) and make PouchDB talk to itself via `api` with [ember-cli-deploy-couchdb-rewrites](https://www.npmjs.com/package/ember-cli-deploy-couchdb-rewrites) you can just sync data and app once to [cloudant](https://cloudant.com/) or any other CouchDB. After the one time sync you would run with your own data and app. You would not need something like EC2. I don't think we need this now but it is a nice vision.
