### ISSUE TITLE
Make GitPod work

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2384]
## 🐛 Bug Report
Currently GitPod doesn't work since the user cannot login. 

Looking at the logs, it looks like it gets a 404 when calling the database.

We will need to add: 
- links to documentation on how to set env varibales
- get gitpod to recognize the couchdb database
- tell gitpod to start up a couchdb database

**Comment by tehKapa** [comment]
@jackcmeyer do you mean this?
<img width="2711" alt="Screenshot 2020-09-09 at 16 21 28" src="https://user-images.githubusercontent.com/6388707/92610978-996a3480-f2b8-11ea-8ee4-dbf236837b6d.png">

**Comment by tehKapa** [comment]
Unfortunately we need to use remote database. You can add DB var by clicking on Account -> Settings

**Comment by fox1t** [comment]
Hmm so only in gitpod we need to have a remote db? I think we can solve this adding a `.env` file that is used only in gitpod.

**Comment by tehKapa** [comment]
How? Beyond the dedicated variables (starting with GITPOD) how do you specify that it is used only in GITPOD?
