### ISSUE TITLE
refactor patient diagnoses to use react query and remove redux code

### ISSUE THREAD

**Issue by jackcmeyer** [HospitalRun/hospitalrun-frontend#2401]
## 🚀 Feature Proposal
This issue is to refactor patient diagnoses to use react query and remove related redux code. 

There will need to be three new hooks

- `usePatientDiagnoses` which returns all patient diagnoses
- `useAddPatientDiagnosis` which validates creates a new diagnosis 
- `usePatientDiagnosis` which returns a diagnosis given an id and a patient

## Motivation
- Remove redux

## Technical Notes
- this will be very similar to the allergy refactor

**Comment by michaelkramer** [comment]
I would like to take this.

**Comment by michaelkramer** [comment]
I believe this issue has been corrected with this PR (https://github.com/HospitalRun/hospitalrun-frontend/pull/2409)
