### ISSUE TITLE
Resolve TitleProvider warnings logged in the browser console

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2417]
## 🐛 Bug Report

It was observed that react warning are logged to the browser console relating to the TitleProvider component. See comments on #2354 

## To Reproduce

![image](https://user-images.githubusercontent.com/5468546/94600059-a5329080-0291-11eb-9c23-3b194368be2d.png)

## Expected behavior

There should be no warnings/errors logged in the browser console. 

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by sohamsshah** [comment]
I would like to work on this issue...Thank you

**Comment by tehKapa** [comment]
Ok @sohamsshah

**Comment by dev-script** [comment]
If no one is working on this issue, I would like to

**Comment by tehKapa** [comment]
@dev-script currently is assign to @sohamsshah

**Comment by sohamsshah** [comment]
Hey @dev-script you can work on this man. I am a bit busy, so couldn't complete this. I will take another issue, idea is to get the work of the Open Source going on! Good luck!

**Comment by dev-script** [comment]
sure @sohamsshah  . Thanks
