### ISSUE TITLE
Resolve the linter warning messages

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2419]
## 🐛 Bug Report

Resolve the 70+ linter warning messages

## To Reproduce

Attempt to build the project, you will notice about 70 or linter warnings

![image](https://user-images.githubusercontent.com/5468546/94848158-e0fd5f80-0423-11eb-80e3-e14404067b0c.png)

## Expected behaviour

Where possible, linter warnings must be resolved.

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by tehKapa** [comment]
It should be similar or duplicate to this issue https://github.com/HospitalRun/hospitalrun-frontend/issues/2194.

**Comment by blestab** [comment]
> It should be similar or duplicate to this issue #2194.

Looks like they are related. I believe we can go ahead and close this as a duplicate.
