### ISSUE TITLE
Patient View: Add Visit button height fix

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2438]
🐛 Bug Report

The height of the Add Visit button on the Patient view is not consistent with the rest of the button such the Edit button just above it. 

![image](https://user-images.githubusercontent.com/5468546/97095090-88546780-165b-11eb-989f-11c3ddecfc17.png)

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select one existing patient to View or create a new one if no patients already exist and view the patient
3. Notice the Add Visit button height is twice (almost) that of the Edit button just above it

## Expected behavior

The Add Visit button height must be consistent with the rest of the buttons 

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by stephjs** [comment]
Hi @blestab I have an open [PR](https://github.com/HospitalRun/hospitalrun-frontend/pull/2457) that fixes this issue.

**Comment by blestab** [comment]
Awesome! Thanks @stephjs

**Comment by chadian** [comment]
@blestab Can this be closed?

**Comment by tehKapa** [comment]
Exactly, but the automatic close doesn't seem to have worked
