### ISSUE TITLE
Patient View: Date fields display format consistency

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2439]
## 🐛 Bug Report

Date display formats must be consistent

## To Reproduce

On https://staging.hospitalrun.io/

1. Login and go to patients,
2. Select one existing patient to View or create a new patient (specify a date of birth or approximate age) if none already exist and then view the patient
3. If you created a new patient in step 2 above, add a new Diagnosis and add a new Care Plan for this new patient
4. View the patient 
3. Notice the Date of Birth, Diagnosis Date (Diagnoses section) and the Care Plans Start/End Date all have different display formats. 

![image](https://user-images.githubusercontent.com/5468546/97095247-517f5100-165d-11eb-9926-7ecfbaf87ed8.png)

## Expected behavior

All dates must display using the same format. Use the Date of Birth's display format on the Diagnosis and Care Plans dates displays

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by merelj** [comment]
I'd like to work on this one

**Comment by blestab** [comment]
Thanks @merelj 
I have put this on your name.

**Comment by blestab** [comment]
Thanks @merelj 
I have put this on your name.
