### ISSUE TITLE
Patient View: Diagnoses section headings height fix

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2440]
## 🐛 Bug Report

Diagnoses section headers should be the same height as Care Plans headers

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select an existing patient to view or create a new one if no patients already exist, then view the patient
3. Notice the Diagnoses section's header is not the same height as that for the Care Plans

![image](https://user-images.githubusercontent.com/5468546/97095310-221d1400-165e-11eb-98a7-fcad904fa829.png)

## Expected behavior

Diagnoses and Care Plans headings should be the same height. To achieve this, 
1. Change "Diagnosis Name" to just "Name" and make sure the heights now match; if not, adjust the Diagnoses headings row height appropriately.
2. For consistency also change "Diagnosis Date" to just "Date"

![image](https://user-images.githubusercontent.com/5468546/97112490-47a52e80-16ed-11eb-84d3-8784be86bb7a.png)

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by gustavoplenamente** [comment]
May I be assigned to this issue?

**Comment by blestab** [comment]
Thanks @gustavoplenamente 

I have put this on your name.

**Comment by gustavoplenamente** [comment]
@blestab , the description says to change from "Diagnosis Name" to just "Diagnosis" but the example image is different. It changes "Diagnosis Name" to just "Name".
As it seems more appealing to me, I will change to jsut "Name", as the table name already tells the user it's about diagnoses.

**Comment by blestab** [comment]
> @blestab , the description says to change from "Diagnosis Name" to just "Diagnosis" but the example image is different. It changes "Diagnosis Name" to just "Name".
> As it seems more appealing to me, I will change to just "Name", as the table name already tells the user it's about diagnoses.

Thanks for picking this up, i have corrected the description. 

In summary we want to make the following changes: 
Diagnosis Name => Name
Diagnosis Date => Date
