### ISSUE TITLE
Patient View: Buttons hover style inconsistency

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2441]
## 🐛 Bug Report

Add Diagnosis/Add Care Plan buttons hover style is not consistent with the rest of the app's hover styles.

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select an existing patient to view or create a new one if no patients already exist, then view the patient
3. Hover over the Add Allergy button and notice the strong green background color. 
4. Hover over the Add Diagnosis and Add Care Plan buttons and notice they have a lighter green hover effect.

![image](https://user-images.githubusercontent.com/5468546/97095445-c5baf400-165f-11eb-8e7b-39903e69cbaf.png)

![image](https://user-images.githubusercontent.com/5468546/97095452-cf445c00-165f-11eb-8d82-f21878b31979.png)

![image](https://user-images.githubusercontent.com/5468546/97095455-d7040080-165f-11eb-811b-f8f293b2e2dd.png)

## Expected behavior

Add Diagnosis/Add Care Plan buttons hover style  must be the same as that of the Add Allergy button

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by smsriharsha** [comment]
can you assign this to me

**Comment by blestab** [comment]
Thanks @smsriharsha,
I have put this onto your name

**Comment by lordinkavu** [comment]
I see that this has not been resolved. Can you assign it to me?
