### ISSUE TITLE
Patient View: Medications tab missing

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2442]
## 🐛 Bug Report

Medications tab is missing from the list of available tabs under the Patient view.

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select an existing patient to view or create a new one if no patients already exist, then view the patient
3. Notice there is no Medications tab

## Expected behavior

Medications tab should exist between Notes and Labs tabs. This should show a list of all medications for this patient. See how the Labs tab works and use that as the basis for the Medications tab

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by dev-script** [comment]
I would like to work on this issue.

**Comment by blestab** [comment]
Sure thing @dev-script
