### ISSUE TITLE
Patient View: Add Allergy does not immediately update the list of allergies

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2443]
## 🐛 Bug Report

The Add Allergy button does not appear to immediately update the list of allergies, even though the Allergies tab gets an immediate update

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select an existing patient to view or create a new one if no patients already exist, then view the patient
3. Click the Add Allergy button in the Allergies section below Date of Birth
4. Add the Allergy details
5. Notice the Allergies tab updates immediately but not the Allergies section under Date Of Birth (see example screenshot, Peanuts is not yet displaying under the Allergies list even though it's there under the Allergies tab)

![image](https://user-images.githubusercontent.com/5468546/97095685-eb95c800-1662-11eb-856d-d55aecffda32.png)

But it eventually displayed

![image](https://user-images.githubusercontent.com/5468546/97095719-5515d680-1663-11eb-9d4b-d9485bb4b12c.png)

## Expected behavior

When a new allergy is added, it should immediately update the Allergies list under Date of Birth as well as the Allergies tab

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by blestab** [comment]
Thanks for the PR @dastgirp

It is recommended to first ask to be assigned an issue before creating a PR as per our contributing guidelines (https://github.com/HospitalRun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md) 

![image](https://user-images.githubusercontent.com/5468546/97110372-892fdc80-16e1-11eb-9454-e2fab6d005b1.png)

**Comment by dastgirp** [comment]
I agree @blestab , I totally missed that 2nd point.

**Comment by blestab** [comment]
No worries, thank you for assisting us with this.
