### ISSUE TITLE
Patient View: Widgets styling and alignment

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2450]
## 🚀 Feature Proposal

Need consistency with the Patient view for the display of Allergies, Diagnoses and Care Plans widgets. 

## Motivation

Currently the Allergies widget looks different to the Diagnoses/Care Plans widgets. 
For consistency: 
1. We need the Allergies widget to use the same display format as Diagnoses/Care Plans widgets
2. We also need to have the 3 widgets aligned horizontally in terms of where they start. Currently only Diagnoses/Care Plans widgets are aligned.

![image](https://user-images.githubusercontent.com/5468546/97111574-402f5680-16e8-11eb-81e7-66909980b2be.png)
 
The user experience is better when the UI is consistent and the widgets are aligned properly.

**Comment by Emalsha** [comment]
Can I try this.

**Comment by blestab** [comment]
Absolutely @Emalsha

**Comment by Emalsha** [comment]
![Screenshot 2020-10-27 011620](https://user-images.githubusercontent.com/7451018/97242007-07c86f00-17f3-11eb-89e5-8736e6ddfcb2.png)

**Comment by tehKapa** [comment]
@lauggh can you give us your opinion?
