### ISSUE TITLE
Patient View: Add Visit does not immediately update the list of visits in Add Diagnosis form

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2451]
## 🐛 Bug Report

The Add Visit button does not appear to immediately update the Add Diagnosis popup form, visit lookup, even though the Visits tab gets an immediate update. 
This is similar to #2443 so you may get ideas from how that was resolved.

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select an existing patient to view or create a new one if no patients already exist, then view the patient
3. Click the Add Visit button above the Diagnoses/Care Plans widgets
4. Add the Visit details
5. Notice the Visits tab updates immediately with the new visit details, but if you now click on Add Diagnosis, you will notice that the recently added visit cannot be seen in the list of visits lookup (see example screenshot, notice there are 2 visits yet the Add Diagnosis visit lookup only shows one of them)

![image](https://user-images.githubusercontent.com/5468546/97113174-3e1dc580-16f1-11eb-98ca-2b06c2306d0f.png)

Note that it eventually shows up 

![image](https://user-images.githubusercontent.com/5468546/97113546-cb621980-16f3-11eb-97e8-b5a2e765fe34.png)

## Expected behavior

A visit should become available to all visit lookups as soon as it has been created, in this case the one on the Add Diagnosis popup form, visit lookup.

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by Emalsha** [comment]
I like to give this a try

**Comment by jackcmeyer** [comment]
@Emalsha you got it!
