### ISSUE TITLE
Add diagnosis form - fix typo in one of the statuses

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2463]
## 🐛 Bug Report

There is a typo in remission on the list of statuses; it is spelt **remisison** instead of **remission**.

## To Reproduce

On https://staging.hospitalrun.io/
1. Login and go to patients, 
2. Select an existing patient to view or create a new one if no patients already exist, then view the patient
3. Click Add Diagnosis, this opens up the Diagnosis form; Click the status dropdown and notice remission is spelt incorrectly. 

![image](https://user-images.githubusercontent.com/5468546/97776470-f5db2900-1b70-11eb-8fe7-06a08a0072a4.png)

## Expected behavior

Spellings should be correct. i.e. **remission** instead of  **remisison**.

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by Mani-07** [comment]
Hi 
@blestab - Can u assign to me? I will work on it.

**Comment by Mani-07** [comment]
Hi @blestab
I have fixed this issue and raised PR.

https://github.com/HospitalRun/hospitalrun-frontend/pull/2465
