### ISSUE TITLE
Medication: New medication request quantity amount and unit not creating correctly

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2492]
## 🐛 Bug Report

When a new medication request is created, the quantity (value and unit) do not seem to be created correctly. 
This leads to the edit/view form not displaying the quantity value and unit. 
Editing however works as expected.

## To Reproduce

- Access staging: https://staging.hospitalrun.io/
- Create a new medication request, specifying a quantity amount and unit. NOTE: You may have to create a patient first if none exists.
- Go to the medication requests listing
- View the request you just created and notice the Quantity just displays "x" instead of amount x unit e.g. "15 x TAB"

![image](https://user-images.githubusercontent.com/5468546/101240609-faa77580-36f8-11eb-8ffb-9c99c46535a1.png)

![image](https://user-images.githubusercontent.com/5468546/101240629-304c5e80-36f9-11eb-8884-9cabbe91d6ef.png)

## Expected behavior

- New medication request should correctly update the quantity amount and unit when saving such the the display and edit screen can also access these values e.g. editing the above example to Quantity amount 30, unit CAPSULE, correctly updates the model
- See how edit request correctly updates these and fix the request medication functionality to do the same thing.

![image](https://user-images.githubusercontent.com/5468546/101240640-40fcd480-36f9-11eb-8c07-dd4995336595.png)

![image](https://user-images.githubusercontent.com/5468546/101240681-86210680-36f9-11eb-821b-dcc23077bbc0.png)

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Windows
- *any other relevant information*

**Comment by roy-stewart** [comment]
I'd be interested in working on this bug.

**Comment by blestab** [comment]
sure @roy-stewart , thanks

**Comment by blestab** [comment]
Hi @roy-stewart , compliments of the season and best wishes for 2021!
Just checking how this work is going.

**Comment by chadian** [comment]
Hello @roy-stewart not sure if you're still working on this but I spiked on a fix that's almost finished in #2554. If you have something else in mind I'd love to collaborate and check it out.

**Comment by blestab** [comment]
> Hello @roy-stewart not sure if you're still working on this but I spiked on a fix that's almost finished in #2554. If you have something else in mind I'd love to collaborate and check it out.

Thank you @chadian 
I had a quick look at the PR it seems to resolve the issue. I have put this onto your name.

**Comment by roy-stewart** [comment]
Sorry for the late response. I've been having issues with building and running HospitalRun on my computer for several weeks now so I haven't had a chance to finish the bug fix for this. Thanks for helping look into this @chadian!

**Comment by chadian** [comment]
All good @roy-stewart. If you'd like some help we can pair on getting your environment working, feel free to ping me on the hospital run slack.

**Comment by blestab** [comment]
> Sorry for the late response. I've been having issues with building and running HospitalRun on my computer for several weeks now so I haven't had a chance to finish the bug fix for this. Thanks for helping look into this @chadian!

That's alright @roy-stewart, thanks for helping out @chadian  #TogetherWeCan 

![image](https://user-images.githubusercontent.com/5468546/105962267-42f36c00-6088-11eb-9322-e52baf908dba.png)
