### ISSUE TITLE
Incidents: Add optional patient impacted field

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2493]
## 🚀 Feature Proposal

When recording a new incident or editing an existing one, add the ability to specify the impacted patient. This field will be optional.

## Motivation

Some incidents impact patients while others will not. The system should provide a way to specify an impacted patient (if any) 

#### Incident Model

Add an optional patient field:

```
patient?: string
```

#### Report Incident Form

Add an optional "Impacted Patient" field which updates the new patient field on the incident model
The user must either specify an existing patient or leave the field blank

_NOTE; See the Request Lab form for an example of how to add the patient form element to the report incident form_

**Comment by CreaTorAleXander** [comment]
I would like to take it

**Comment by blestab** [comment]
Absolutely @CreaTorAleXander, thanks

**Comment by rsousaj** [comment]
Hi, I think I can handle this one if its not under someone else development

**Comment by mattkuzco** [comment]
Hi, can I be assigned to this issue?

**Comment by tehKapa** [comment]
Wait a minute. Is anyone working on this? @blestab?

**Comment by blestab** [comment]
> Wait a minute. Is anyone working on this? @blestab?

Looks like @CreaTorAleXander removed themself as an assignee, I am guessing that means they are no longer looking at it? I think @mattkuzco or @rsousaj could be assigned to take over this one.

**Comment by rsousaj** [comment]
Yeah @mattkuzco, go ahead buddy

**Comment by mattkuzco** [comment]
Hey, sorry to bother :( I don't know if this is the best place to ask, but I'm having some trouble with the Typeahead component. I think I need the onInputChange callback to detect if the user is trying to enter a patient (to check if the field is blank, or in the case the patient doesn't exist to display an error message) but I'm not so confident with typescript so I'm not really sure how to add the callback. I tried editing the Typeahead.d.ts file and adding it there hoping it would be called from the typeahead.js but of course that's not the way

**Comment by rsousaj** [comment]
I don't think I'm the best here to help you but I'd like to try.

From what I've used, the component receives onChange and onSearch as callbacks. 

1) onSearch you pass a function that receive a string as argument and you return a Promise of the Search of that string from the Database.

2) onChange is when the user select a Patient. In this case, this callback receive a Patient as argument (actually an array of Patient but with just one Patient) and then you update the incidente state.

So, I didn't understand why you need to display an error message. If the user type a search string that does not return a Patient, the field will be empty and perhaps its fine.

I hope I've helped.

Ps.: The Typeahead component is based on AsyncTypeahead from 'react-bootstrap-typeahead', if you want to know more.

**Comment by mattkuzco** [comment]
Oh I thought about doing that, yeah for that onSearch and onChange are perfectly fine. It's just I wasn't sure if I had to it this way (pass a null patient on partial input) or prohibit an incident when patient field contains invalid input. Thank you!
