### ISSUE TITLE
Medication: canceled status i18n label not displaying

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2495]
## 🐛 Bug Report

The canceled status for medications shows the translation key instead of the label.

## To Reproduce

Visit staging https://staging.hospitalrun.io/
Access the medication requests page
Click on the filter by status field to reveal the filter status options
Notice the display medications.status.canceled instead of "Canceled"

The same can be seen when one views a medication request to edit, clicking the status field also shows canceled translation key instead of the translation text "Canceled"

![image](https://user-images.githubusercontent.com/5468546/101273992-110a0b80-37a3-11eb-9e43-29f5d15a62cf.png)

## Expected behavior

The Canceled status should be displayed not the translation key medications.status.canceled

src/shared/locales/enUs/translations/medications/index.ts:

```js
  medications: {
    label: 'Medications',
    filterTitle: 'Filter by status',
    search: 'Search Medications',
    status: {
      draft: 'Draft',
      active: 'Active',
      onHold: 'On Hold',
      canceled: 'Canceled',                 <==== change spelling to en-us i.e. with one "l" not "ll"
      completed: 'Completed',
      enteredInError: 'Entered In Error',
      stopped: 'Stopped',
      unknown: 'Unknown',
    },
```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Windows
- *any other relevant information*

**Comment by blestab** [comment]
@FanciestW this one might be good to get you comfortable with the codebase. What do you think?

**Comment by FanciestW** [comment]
@blestab I agree, can I be assigned to this issue as well?

**Comment by blestab** [comment]
> @blestab I agree, can I be assigned to this issue as well?

Awesome! I have put this on your name and for now removed the other one earlier assigned.

**Comment by FanciestW** [comment]
While fixing the spelling of 'canceled' for the usEn locale, I noticed that the ViewMedicines component has a much smaller width for the medicines table. Could I address this issue? And should another issue be created for this or can I make the fix under this issue?

**Comment by blestab** [comment]
> While fixing the spelling of 'canceled' for the usEn locale, I noticed that the ViewMedicines component has a much smaller width for the medicines table. Could I address this issue? And should another issue be created for this or can I make the fix under this issue?
Thanks @FanciestW i'll create a separate issue for you.

**Comment by FanciestW** [comment]
![Screen Shot 2020-12-07 at 10 27 38 AM](https://user-images.githubusercontent.com/9480166/101373182-ab894e00-387a-11eb-804f-39c944a291fa.png)
@blestab Here is a screenshot you can use if you'd like. Thank you
