### ISSUE TITLE
UI Inconsistency: Forms (new/edit) buttons labels

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2511]
## 🐛 Bug Report

There is an inconsistency in the form save button labels when we create a new entity (patient, appointment, lab, medication, imaging request, incident)

## To Reproduce

Create a new patient OR new appointment OR new medication OR new lab OR new incident OR new imaging request
Notice the footer buttons in some instances you have "Save" in other instances you have "Request"; we need to have uniformity.

### New entry creation
- For creating a new Patient the save button label should say "Create Patient"
- For scheduling an appointment the save button label should say "Schedule Appointment"
- For requesting a lab the save button label should say "Request Lab"
- For requesting a medication the save button label should say "Request Medication"
- For requesting imaging the save button should say "Request Imaging"
- For reporting an incident the save button should say "Report Incident" 

### Editing existing entries
 - Make sure all edit forms say "Update" + the name of the entity being updated e.g. "Update Patient", "Update Lab", "Update Medication", "Update Incident" , "Update Imaging", "Update Appointment"

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by cpondoc** [comment]
Hi, @fox1t @tehKapa @jackcmeyer -- would love to take this on!

**Comment by blestab** [comment]
> Hi, @blestab @fox1t @tehKapa @jackcmeyer -- would love to take this on!

Thanks @cpondoc , all yours.
