### ISSUE TITLE
UI: Forms footer buttons alignment

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2518]
## 🐛 Bug Report

Footer buttons in forms are not right aligned with the container immediately above them.

## To Reproduce

Access any new/view/edit form e.g. Patient, Lab, Medication, Incident, Imaging, you will notice the misalignment. 

View/Edit Patient
![image](https://user-images.githubusercontent.com/5468546/102173163-181bd280-3ea3-11eb-9a59-cc5f75830a56.png)

New Appointment
![image](https://user-images.githubusercontent.com/5468546/102173198-308bed00-3ea3-11eb-9f2d-446b97a4a6cd.png)

Request Lab
![image](https://user-images.githubusercontent.com/5468546/102173258-4a2d3480-3ea3-11eb-8592-fbe14234b086.png)

This issue must be fixed for the following forms :

- Patients (new, view/edit)
- Appointment (new, view/edit)
- Medications (new, view/edit)
- Lab (new, view/edit)
- Imaging (new, view/edit)
- Incident (new, view/edit)

## Expected behavior

For a great UX the buttons right margin must be aligned with the righ margin of the container immediately above them.

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by Adarsh710** [comment]
Hi @blestab, I would like to take this.

**Comment by blestab** [comment]
> Hi @blestab, I would like to take this.

Thanks @Adarsh710, all yours.

**Comment by TD-17** [comment]
Is this issue fixed ?

**Comment by tehKapa** [comment]
@TD-17 not yet

**Comment by TD-17** [comment]
can I work on this ? @tehKapa

**Comment by tehKapa** [comment]
@TD-17 It only needed to be merge
