### ISSUE TITLE
Improve sample data

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#252]
Shout out to @jkleinsc for getting us a way to load sample data for development, and creating the initial sample data file. :metal: :zap:

The sample data could use some improvement, though. Currently most screens only have 1 example, and there are still a few that don't have any from the sample data. I'm happy to use the current sample data as the basis and work on making it more extensive.

Would be good to document the process for exporting a data dump, too.

**Comment by jkleinsc** [comment]
Exporting a data dump is the same as explained here:
https://github.com/HospitalRun/hospitalrun-frontend#fixtures-for-acceptance-tests

Basically, you use [pouchdb-dump-cli](https://github.com/nolanlawson/pouchdb-dump-cli).
e.g. run ```pouchdb-dump http://localhost:5984/main -u hradmin -p test | cat > tests/fixtures/nameofdump.txt.```

**Comment by tangollama** [comment]
@jglovier I'd like to unassign this and put this out in Help Wanted. I feel like someone who's not you could work on this.

**Comment by jglovier** [comment]
@tangollama 

![thumbs-up-80s-kid](https://cloud.githubusercontent.com/assets/1319791/13862361/0a51ac7e-ec50-11e5-8600-e3a01dcd8d7d.gif)

**Comment by jglovier** [comment]
cc @jkleinsc for issue number reference.

**Comment by tangollama** [comment]
@jglovier can we close this or no?

**Comment by jglovier** [comment]
@tangollama I still think there is big room for improvement here worth leaving this open. Right now the sample data file we load only has a small set of data (many views have 1 or 0 records), which isn't really vert effective for working with the app in a truly representative way.

I've been able to get around that via the private anonymized data set we have, but I'd like to keep this open until we have a set of anonymized sample data that any contributor can use when getting setup. Correct me if I'm mistaken on whether that data is still private or available to all contributors.

**Comment by Eric-Arellano** [comment]
@jglovier What would this case entail to do? As in would I just create plausible sounding records arbitrarily, or does it need to be based off of this anonymized sample data?

**Comment by jglovier** [comment]
@Eric-Arellano I think the anonymized sample data is the best route here, and actually @jkleinsc has something like this in progress IIRC, which is why we don't have a help-wanted label on this issue. @jkleinsc @tangollama can you confirm?

**Comment by jkleinsc** [comment]
@jglovier @Eric-Arellano yes I have a dataset, I just haven't had time to add it.
@jglovier the dataset is about 39M over 6 files, so I'm hesitant to add that to the repo.

**Comment by jglovier** [comment]
>@jglovier the dataset is about 39M over 6 files, so I'm hesitant to add that to the repo.

Sure, that's fair. We could workaround that by just adding instructions on how to get it and install it to the README, and then host the dataset elsewhere like a dropbox account or something.

**Comment by gnowoel** [comment]
Since it's CouchDB, is it possible to set up a public database that we all can sync from?
