### ISSUE TITLE
Mobile Navbar - remove visit links 

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2530]
## 🐛 Bug Report

The mobile navbar has 2 visits related entries at the bottom that should not be there.

## To Reproduce

- Access staging https://staging.hospitalrun.io
- Resize browser window to be mobile sized (you may use browser dev tools or just resize the browser window)
- Open the navbar and notice the 2 entries at the bottom (see screenshot below)
![image](https://user-images.githubusercontent.com/5468546/103168267-4fdb3080-483a-11eb-920b-183d42d9694a.png)

Source file: `src/shared/components/navbar/pageMap.tsx`

```js
viewIncidentWidgets: {
    permission: Permissions.ViewIncidentWidgets,
    label: 'incidents.visualize.label',
    path: '/incidents/visualize',
    icon: 'incident',
  },
  newVisit: {
    permission: Permissions.AddVisit,
    label: 'visits.visit.new',
    path: '/visits',
    icon: 'add',
  },
  viewVisits: {
    permission: Permissions.ReadVisits,
    label: 'visits.visit.label',
    path: '/visits',
    icon: 'visit',
  },
  settings: {
    permission: null,
    label: 'settings.label',
    path: '/settings',
    icon: 'setting',
  },
```

Remove the `newVisit` and `viewVisits` 

## Expected behavior

The visit links should not be there as they fall under the patients menu option i.e. you can only add or view visits once you have a patient.

![image](https://user-images.githubusercontent.com/5468546/103168373-54ecaf80-483b-11eb-9097-f173543a67db.png)

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by cpondoc** [comment]
Hi, @blestab @fox1t @tehKapa @jackcmeyer -- would love to take this on!

**Comment by blestab** [comment]
> Hi, @blestab @fox1t @tehKapa @jackcmeyer -- would love to take this on!

Sure thing @cpondoc all yours
