### ISSUE TITLE
Patient: Care Goal action button label

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2534]
## 🐛 Bug Report

The action button label on the Care Goals table shows the translation key instead of the text

![image](https://user-images.githubusercontent.com/5468546/103346524-e6a72780-4a9c-11eb-8b6d-05314d543b94.png)

## To Reproduce

- Access staging: https://staging.hospitalrun.io/
- Create a patient is one does not exist
- Create a visit 
- Record a diagnosis
- Record a care plan for the diagnosis above
- Record a care goal for the care plan above
- View the list of care goals and notice the action button label shows `actions.view` instead of `View`

## Expected behavior

Action button label must show `View `and not the translation key `actions.view`

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by shiwangi20** [comment]
@blestab would like to work on it

**Comment by blestab** [comment]
Sure thing @shiwangi20, all yours.
