### ISSUE TITLE
Incidents: Filter by status labels 

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2535]
## 🐛 Bug Report

Incident filter status labels should start with capital letters i.e. All, Reported, Resolved

## To Reproduce

- Access staging https://staging.hospitalrun.io/
- Access the incidents view and click on the filter by status field. Notice the labels are all lowercase. 
![image](https://user-images.githubusercontent.com/5468546/103348597-27a23a80-4aa3-11eb-8abc-abbec379b988.png)

## Expected behavior

Filter by status labels should start with a capital letter.

![image](https://user-images.githubusercontent.com/5468546/103348637-486a9000-4aa3-11eb-9678-e4f1d9394f22.png)

## Technical Details

`src/shared/locales/enUs/translations/incidents/index.ts`

```
    status: {
      reported: 'Reported',
      resolved: 'Resolved',
      all: 'All',
    },
```

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by shiwangi20** [comment]
@blestab can I work on this

**Comment by blestab** [comment]
Sure @shiwangi20
