### ISSUE TITLE
Imaging Request - requestedBy should store the currently logged in user id

### ISSUE THREAD

**Issue by blestab** [HospitalRun/hospitalrun-frontend#2540]
## 🐛 Bug Report

Imaging request is currently hardcoded to set `requestedBy` to **test** instead of the currently logged in user's id. This needs to be corrected to user the current user id from the redux store.

## To Reproduce

- Access staging https://staging.hospitalrun.io/
- Create a patient and add a visit to this patient
- Create an imaging request for the above patient/visit
- View the list of imaging requests and notice that the requested by field shows 'test'

## Expected behavior

- The `requestedBy` should be the currently logged in `user.id` at the time the imaging request is created
- The list of imaging requests should display the `user.fullName` based on the imaging request's `requestedBy`

## Notes
- See `src/shared/components/navbar/Navbar.tsx` on how to access the user from the store

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by riiniii** [comment]
could i take this bug?

**Comment by blestab** [comment]
> could i take this bug?

Absolutely @riiniii

**Comment by riiniii** [comment]
@blestab do i need some type of permissions to commit? i keep on getting this: 

ERROR: Permission to HospitalRun/hospitalrun-frontend.git denied to riiniii.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists. 

tried creating new ssh key and updating remote url

**Comment by blestab** [comment]
Ar what stage are you getting this error? Checkout? May you advise what steps have you followed so far. Perhaps join our slack so we can discuss your challenges further, https://hospitalrun-slackin.herokuapp.com

**Comment by blestab** [comment]
> @blestab do i need some type of permissions to commit? i keep on getting this:
> 
> ERROR: Permission to HospitalRun/hospitalrun-frontend.git denied to riiniii.
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> 
> tried creating new ssh key and updating remote url , successfuly ran "ssh -T [git@github.com](mailto:git@github.com)", and also tried on github desktop to no avail

I see you have opened a PR, can we safely assume you managed to resolve the error?

**Comment by riiniii** [comment]
yes! it was a stupid error on my end. thank you!

**Comment by riiniii** [comment]
@blestab could you help review this? 
https://github.com/HospitalRun/hospitalrun-frontend/pull/2544
