### ISSUE TITLE
Lab - In the Request Lab routine make the visit field required

### ISSUE THREAD

**Issue by SamuelQZQ** [HospitalRun/hospitalrun-frontend#2551]
## 🐛 Bug Report

When **Request Lab** for a patient without any visit, it will crash.

## To Reproduce

1. Create an patient without adding a visit
2. Click **Request Lab**, input the patient field, leave the visit field blank since it is not required.
3. Notice the crash/error (see screenshot in comments)

## Expected behavior

Request Lab should behave similar to **New Imaging Request** i.e. make the visit field required

## Technical Details

Make the visit field required (as in Imaging Request)

## Your Environment

- *node version*: 12
- *os*: Windows

**Comment by SamuelQZQ** [comment]
I'd like to fix this bug.

**Comment by blestab** [comment]
> Steps to reproduce the behavior:
> 
> 1. Create an empty patient

May you elaborate how you achieved this or what you mean by 'empty patient', 

in staging, i created a patient with the minimum required/allowed i.e Just a name, no visit was added.

![image](https://user-images.githubusercontent.com/5468546/105066946-ef7d8e80-5a87-11eb-8a5c-8c36bff27dc2.png)

I then requested a lab for this patient and did not manage to reproduce the crash you mention

![image](https://user-images.githubusercontent.com/5468546/105067105-10de7a80-5a88-11eb-9e32-edc612c5c769.png)

**Comment by SamuelQZQ** [comment]
@blestab Interesting.
Also in staging. I just create a patient, only with a given name.
![image](https://user-images.githubusercontent.com/19623228/105068001-58cac500-5abb-11eb-8b0b-e058c6b41bc8.png)

Then I click the "Request Lab" from the left navigation menu. And input the patient's name. And click the auto-suggested patient. Then, crash.
![image](https://user-images.githubusercontent.com/19623228/105068108-7bf57480-5abb-11eb-81d5-f42166633d48.png)

And get the error message below:
![image](https://user-images.githubusercontent.com/19623228/105068649-25d50100-5abc-11eb-9c2b-8f98471abd06.png)

I can reproduce this in Edge or Chrome.

**Comment by blestab** [comment]
Yeah, interesting thing is the version of staging i was looking at did not have a Visit selection field. 

![image](https://user-images.githubusercontent.com/5468546/105069629-e3df9700-5a8a-11eb-8e29-3f7e507f5270.png)

I have opened a new session in another chrome instance and I can see the visit option, which is not required, which i guess if why this bug occurs. So if you make the visit required then the issue should be resolved. 

![image](https://user-images.githubusercontent.com/5468546/105069851-2bfeb980-5a8b-11eb-985b-cd189bc4628f.png)


Thanks for picking this up

**Comment by blestab** [comment]
All yours @SamuelQZQ , thanks again for this
