### ISSUE TITLE
phantomjs-2.0.0-linux-x86_64 installation not working

### ISSUE THREAD

**Issue by ronikb** [HospitalRun/hospitalrun-frontend#256]
As part of installing this, not able to install phantomjs2 (npm install -g phantomjs2) 

While executing this command (npm install -g phantomjs2) I am getting the following error. It seems that the installation not able to download phantomjs-2.0.0-linux-x86_64.tar.bz2 file from https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2 .How to solve it. It will be good to get a resolution for it
-------------Error LOg------------------------------------------------------------------
root@hospitalrun:/opt/hospitalrun-frontend# npm install -g phantomjs2
â
â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:adm-zip â mapToRe â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:which â addNameRa â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:which â addNameRa â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:which â addNamed  â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:which â afterAdd  â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
loadDep:wrappy â request  â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:brace-expansion â â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:uid-number â cach â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:stringstream â ad â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:stringstream â ca â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:sntp â addNamed   â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
loadDep:throttleit â get  â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
extract â gunzTarPerm     â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
extract â gunzTarPerm     â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
extract â gunzTarPerm     â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
extract â gunzTarPerm     â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
extract:graceful-fs       â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
extract:progress          â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
preinstall â lifecycle    â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
finalize                  â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
build:combined-stream     â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
build:form-data â linkBin â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
build:qs                  â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
build:request â linkStuff â â¢âââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââââ
/usr/bin/phantomjs -> /usr/lib/node_modules/phantomjs2/bin/phantomjs

> phantomjs2@2.0.2 install /usr/lib/node_modules/phantomjs2
> node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2
Saving to /usr/lib/node_modules/phantomjs2/phantomjs/phantomjs-2.0.0-linux-x86_64.tar.bz2
Receiving...

Error requesting archive.
Status: 404
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie, Accept-Encoding",
  "cache-control": "max-age=900",
  "content-type": "text/html; charset=utf-8",
  "strict-transport-security": "max-age=31536000",
  "date": "Thu, 07 Jan 2016 06:41:47 GMT",
  "x-served-by": "app-107",
  "content-language": "en",
  "etag": "\"24070a8151d63543d8f408728c2526f7\"",
  "x-static-version": "d96c42eab630",
  "x-render-time": "0.0328800678253",
  "connection": "close",
  "x-request-count": "360",
  "x-frame-options": "SAMEORIGIN",
  "x-version": "d96c42eab630",
  "content-length": "24035"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm ERR! Linux 3.13.0-71-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "phantomjs2"
npm ERR! node v5.3.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs2@2.0.2 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/hospitalrun-frontend/npm-debug.log

**Comment by ronikb** [comment]
Able to install it using npm install phantomjs and installed HospitalRun. Able to install its web interface with the default username and password. How can i change this default pasword?
NOt able to create new users also

**Comment by jkleinsc** [comment]
@ronikb it looks like there are issues with the static build on PhantomJS on Linux.  You can follow directions here to build PhantomJS from source: http://phantomjs.org/download.html

As far as the user update/create, it turns out that an update to the npm package nano caused this issue.  I am checking in a fix shortly.

**Comment by MarceloBorgesP** [comment]
Was this problem already solved? I'm still getting the same as above @jkleinsc :

 npm install -g phantomjs2
npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
/home/marcelo/.nvm/versions/node/v0.12.5/bin/phantomjs -> /home/marcelo/.nvm/versions/node/v0.12.5/lib/node_modules/phantomjs2/bin/phantomjs

 phantomjs2@2.0.2 install /home/marcelo/.nvm/versions/node/v0.12.5/lib/node_modules/phantomjs2
 node install.js

Looks like an `npm install -g`; unable to check for already installed version.
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.0.0-linux-x86_64.tar.bz2
Receiving...
  [===-------------------------------------] 9% 0.0s
Error requesting archive.
Status: 404
Request options: {
  "uri": "https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.0.0-linux-x86_64.tar.bz2",
  "encoding": null,
  "followRedirect": true,
  "headers": {},
  "strictSSL": true
}
Response headers: {
  "server": "nginx/1.6.2",
  "vary": "Accept-Language, Cookie, Accept-Encoding",
  "cache-control": "max-age=900",
  "content-type": "text/html; charset=utf-8",
  "strict-transport-security": "max-age=31536000",
  "date": "Mon, 18 Jan 2016 17:22:41 GMT",
  "x-served-by": "app-106",
  "content-language": "en",
  "etag": "\"afb28aae3a8d4ed6e4b73c884454c7f5\"",
  "x-static-version": "cb7c09ad73aa",
  "x-render-time": "0.0259730815887",
  "connection": "close",
  "x-request-count": "437",
  "x-frame-options": "SAMEORIGIN",
  "x-version": "cb7c09ad73aa",
  "content-length": "24043"
}
Make sure your network and proxy settings are correct.

If you continue to have issues, please report this full log at https://github.com/Medium/phantomjs
npm ERR! Linux 4.2.0-22-generic
npm ERR! argv "/home/marcelo/.nvm/versions/node/v0.12.5/bin/node" "/home/marcelo/.nvm/versions/node/v0.12.5/bin/npm" "install" "-g" "phantomjs2"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! phantomjs2@2.0.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs2@2.0.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/marcelo/projects/zertico-web-customer/npm-debug.log

**Comment by jkleinsc** [comment]
@MarceloBorgesP If you are using Linux, you will need to build PhantomJS from source following directions here: http://phantomjs.org/download.html.
The "fix" here was to update the README to reflect this.

**Comment by MarceloBorgesP** [comment]
Hmm right, thanks @jkleinsc !
