### ISSUE TITLE
ViewAppointments Tests Have a Console Error

### ISSUE THREAD

**Issue by DrewGregory** [HospitalRun/hospitalrun-frontend#2564]
## 🐛 Bug Report

Even though the ViewAppointments tests pass, there is a React Hooks error logged regarding inconsistent hook call ordering.

## To Reproduce

Run `npm run test:ci src/__tests__/scheduling/appointments/ViewAppointments.test.tsx`

## Your Environment

- *node version*: v11.10.1
- *os*: Mac

**Comment by morrme** [comment]
HI @DrewGregory , are you working on a solution for this one?

**Comment by DrewGregory** [comment]
I have not been working on a solution, but feel free to assign me if you think I would be best served to tackle it!

**Comment by tehKapa** [comment]
@DrewGregory assigned. See what you can do. Thank you!

**Comment by DrewGregory** [comment]
Now that I have revisited this issue, I cannot reproduce the bug. I might have been running the old enzyme tests.
