### ISSUE TITLE
Test patients/care-goals/CareGoalTab.test.tsx on MacOS runner fails

### ISSUE THREAD

**Issue by tehKapa** [HospitalRun/hospitalrun-frontend#2593]
## 🐛 Bug Report

Test patients/care-goals/CareGoalTab.test.tsx on MacOS runner fails

## To Reproduce

```js

FAIL src/__tests__/patients/care-goals/CareGoalTab.test.tsx (35.381s)
  ● Care Goals Tab › should be able to create a new care goal if user has permissions

    : Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Timeout - Async callback was not invoked within the 30000ms timeout specified by jest.setTimeout.Error:

      71 |   })
      72 |
    > 73 |   it('should be able to create a new care goal if user has permissions', async () => {
         |   ^
      74 |     const expectedCareGoal = {
      75 |       description: 'some description',
      76 |       status: CareGoalStatus.Accepted,
      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (src/__tests__/patients/care-goals/CareGoalTab.test.tsx:73:3)
      at Object.<anonymous> (src/__tests__/patients/care-goals/CareGoalTab.test.tsx:64:1)

```

## Expected behavior

The test must work on Linux and Windows runners

**Comment by jrmkim50** [comment]
I'd like to take a look at this issue.

**Comment by tehKapa** [comment]
thanks @jrmkim50 !

**Comment by jrmkim50** [comment]
I ran this test on my Mac (I made no changes to the code), and all the tests passed:

MBP% npm run test:ci src/__tests__/patients/care-goals/CareGoalTab.test.tsx

> @hospitalrun/frontend@2.0.0-alpha.7 test:ci /Users/min/Documents/hospitalrun-frontend
> cross-env CI=true react-scripts test  --testPathIgnorePatterns=src/__tests__/test-utils --passWithNoTests --env=jest-environment-jsdom-sixteen --maxWorkers=2 "src/__tests__/patients/care-goals/CareGoalTab.test.tsx"

PASS src/__tests__/patients/care-goals/CareGoalTab.test.tsx (28.18s)
  Care Goals Tab
    ✓ should not render add care goal button if user does not have permissions (703ms)
    ✓ should be able to create a new care goal if user has permissions (17680ms)
    ✓ should open and close the modal when the add care goal and close buttons are clicked (463ms)
    ✓ should render care goal table when on patients/:id/care-goals (19ms)
    ✓ should render care goal view when on patients/:id/care-goals/:careGoalId (43ms)

Test Suites: 1 passed, 1 total
Tests:       5 passed, 5 total
Snapshots:   0 total
Time:        30.026s
Ran all test suites matching /src\/__tests__\/patients\/care-goals\/CareGoalTab.test.tsx/i.

Could I get some clarification on this issue please?

**Comment by tehKapa** [comment]
Look this https://github.com/HospitalRun/hospitalrun-frontend/pull/2560/checks?check_run_id=1881181847
