### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by ronikb** [HospitalRun/hospitalrun-frontend#260]
How can I brand this hospitalrun as our company label? Means I wanted to replace left top corner +hospitalrun as our Company name.Is this possible?

**Comment by tangollama** [comment]
Thanks for the question @ronikb. Branding an instance for a specific hospital makes perfect sense, and it's a feature that we'll likely have in place (at least in it's most rudimentary form) before we ship a 1.0 version. 

However, at present, we're not actively encouraging people to download and install the software. As such, the feature isn't available and won't be part of the master branch until we're ready for someone to download and install the system.

If you have more questions, I'm happy to discuss.

**Comment by ronikb** [comment]
@tangollama Thanks for your reply. However, at present, we're not actively encouraging people to download and install the software. What this statement meant?, this software is not ready?

**Comment by enyachoke** [comment]
@ronikb Am thinking the feature request makes more sense for a production setup. If am not wrong the software is in beta currently version 0.8.7. So the short answer is the software is not ready for production and it is not encouraged to run it as such.

**Comment by tangollama** [comment]
@ronikb @enyachoke is correct. The software - since it is not in a 1.0 state - has not been released and therefore is not ready. Our objective, at present, is to reach a 1.0 release by July of this year.

**Comment by fox1t** [comment]
@tehKapa what about white labbeling integration?
