### ISSUE TITLE
Creating new patient - validation of the phone number is wrong

### ISSUE THREAD

**Issue by jayavardhan3112** [HospitalRun/hospitalrun-frontend#2675]
## 🐛 Bug Report

The validation of the phone number is missing,
PFA the Image

## To Reproduce

- Try creating a new patient with contact number being 11 digits
- its accepting the number

## Expected behavior

- validation should be a proper 10digit number of if ok `country code`

<img width="1434" alt="Screenshot 2021-05-14 at 8 44 10 PM" src="https://user-images.githubusercontent.com/22497670/118291916-ba44f280-b4f5-11eb-92a4-bef4aa4d54b9.png">

## Your Environment

- *node version*: 6,8,10
- *fastify version*: >=1.0.0
- *os*: Mac, Windows, Linux
- *any other relevant information*

**Comment by poojavirgo** [comment]
Hi , Can you please assign this issue to me. Looking forward to your response.
