### ISSUE TITLE
Fix styling for login alert

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#273]
This styling (added in #250) doesn't match the app's design. Also, the alert should be above the button, or maybe above the input fields.

![image](https://cloud.githubusercontent.com/assets/1319791/12516210/4aa7fab6-c0fa-11e5-845d-48a946d2a677.png)

**Comment by alexpelan** [comment]
I can fix (it looks like you may have already started, though?) I did cause
it, after all...

**Comment by jglovier** [comment]
@alexpelan thanks, but I've got a branch in progress with some other login tweaks as well.

**Comment by jglovier** [comment]
@alexpelan FWIW, it's really not your fault. We really have a long way to go on the styling of the app, and I'd like to get to a place that we have all the components available and styled correctly so that contributing devs can just jump in and use the existing styles. Right now, we have a lot of default bootstrap styles that should really be themed. So properly theming bootstrap and removing unused styles is one of the things I'm focusing on now. :heart:
