### ISSUE TITLE
Localization for Patients Module

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#274]
Now that i18n support has been added to HospitalRun via PR #248 and issue #141 we need to localize the app.  This issue is to track localization for the patients module.Localization in HospitalRun uses [Ember-I18n](https://github.com/jamesarosen/ember-i18n).  The translations/default text will be placed in app/locales/en/translations.js.
See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text for information on how to localize the templates.

**Comment by jonkoops** [comment]
@jkleinsc I am willing to take this one, could you assign it to me?

**Comment by jkleinsc** [comment]
@jonkoops it's yours.

**Comment by billybonks** [comment]
@jonkoops are you still working on this ?

**Comment by jonkoops** [comment]
No sorry, I thought I had the time but I keep being distracted by other things to get done. I believe I have a WIP pull request on my machine, I'll try to get it finished by this week.

**Comment by billybonks** [comment]
@jonkoops how is it going ? 👍

**Comment by jglovier** [comment]
Resolved in #489.
