### ISSUE TITLE
Localization for Appointments Module

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#275]
Now that i18n support has been added to HospitalRun via PR #248 and issue #141 we need to localize the app.  This issue is to track localization for the appointments module.  Localization in HospitalRun uses [Ember-I18n](https://github.com/jamesarosen/ember-i18n).  The translations/default text will be placed in app/locales/en/translations.js.
See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text for information on how to localize the templates.

**Comment by billybonks** [comment]
ill translate this guy. :+1:  been a while since i made a contribution

**Comment by billybonks** [comment]
working with @mellisdesigns  on this one https://github.com/HospitalRun/hospitalrun-frontend/pull/329

**Comment by billybonks** [comment]
should be able to close this

**Comment by tangollama** [comment]
Per @billybonks closing. Confirming with @jkleinsc

**Comment by jglovier** [comment]
Thanks @billybonks & @mellisdesigns! 

In the future please put `Fixes #275` in your pull request so the associated issue gets referenced and closed once merged. :heart:

**Comment by billybonks** [comment]
Can
