### ISSUE TITLE
Localization for Inventory Module

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#276]
Now that i18n support has been added to HospitalRun via PR #248 and issue #141 we need to localize the app.  This issue is to track localization for the inventory module.  Localization in HospitalRun uses [Ember-I18n](https://github.com/jamesarosen/ember-i18n).  The translations/default text will be placed in app/locales/en/translations.js.
See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text for information on how to localize the templates.

**Comment by nerdkid93** [comment]
I'm working on this in my fork

**Comment by billybonks** [comment]
@nerdkid93 are u still working on this ?

**Comment by nerdkid93** [comment]
Yes, it will be done by tomorrow.

**Comment by billybonks** [comment]
:+1:

**Comment by tangollama** [comment]
Setting to In progress, per the new policy in the [Contributing.MD](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md)
