### ISSUE TITLE
Localization for Imaging Module

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#277]
Now that i18n support has been added to HospitalRun via PR #248 and issue #141 we need to localize the app.  This issue is to track localization for the imaging module.  Localization in HospitalRun uses [Ember-I18n](https://github.com/jamesarosen/ember-i18n).  The translations/default text will be placed in app/locales/en/translations.js.
See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text for information on how to localize the templates.

**Comment by alexpelan** [comment]
I can take a stab at this one this weekend whilst snowed in - imaging looks like the simplest module, so easiest to get a feel for the i18n process.
