### ISSUE TITLE
Localization for Labs Module

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#279]
Now that i18n support has been added to HospitalRun via PR #248 and issue #141 we need to localize the app.  This issue is to track localization for the labs module.  Localization in HospitalRun uses [Ember-I18n](https://github.com/jamesarosen/ember-i18n).  The translations/default text will be placed in app/locales/en/translations.js.
See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text for information on how to localize the templates.

**Comment by James1x0** [comment]
Getting started on the project with this issue.

**Comment by tangollama** [comment]
Assuming that @James1x0 has this, so setting to In Progress per the new [Contribution policy](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md)

**Comment by James1x0** [comment]
Will tackle this at some point this week. :+1:

**Comment by tangollama** [comment]
Thx. 

Typed or dictated imperfectly on my iPhone (717.385.9970)
