### ISSUE TITLE
Localization for Billing Module

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#280]
Now that i18n support has been added to HospitalRun via PR #248 and issue #141 we need to localize the app.  This issue is to track localization for the billing module.  Localization in HospitalRun uses [Ember-I18n](https://github.com/jamesarosen/ember-i18n).  The translations/default text will be placed in app/locales/en/translations.js.
See https://github.com/jamesarosen/ember-i18n/wiki/Doc:-Translating-Text for information on how to localize the templates.

**Comment by renato04** [comment]
Hello!

I'll try to do this.

**Comment by tangollama** [comment]
@renato04 can you confirm that you're working on this? Unless you say otherwise, I'm marking this as In Progress per the new [contribution policy](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/.github/CONTRIBUTING.md)

**Comment by renato04** [comment]
@tangollama no, i can't processed with this right now, Sorry. You can put this with HelpWanted tag

**Comment by billybonks** [comment]
i will finish this one off

**Comment by mellisdesigns** [comment]
Hey Guys, I will take this one. I am working on this as of now! Have discussed with @billybonks already.

**Comment by tangollama** [comment]
Thanks @mellisdesigns

**Comment by mellisdesigns** [comment]
This is complete and ready for QA
https://github.com/HospitalRun/hospitalrun-frontend/pull/479

**Comment by billybonks** [comment]
still need to translate invoices section, in order to complete this issue

**Comment by jkleinsc** [comment]
This is complete so I am closing it.
