### ISSUE TITLE
Get ember-cli-content-security-policy working

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#285]
I have temporarily removed [ember-cli-content-security-policy] (https://github.com/rwjblue/ember-cli-content-security-policy) from package.json because in development it is throwing errors that are confusing new developers.  We need someone to correctly configure the app for ember-cli-content-security-policy so that we don't get these errors.

**Comment by pete-the-pete** [comment]
@tangollama I can take this on.  I already created a pr (I'll stick to the steps in the contributing file next time).

I basically just added the package and got rid of errors while working locally.

Are there specific urls I should add for plugins or any other specifics when in a production environment?

**Comment by jkleinsc** [comment]
Fixed by #335
