### ISSUE TITLE
Determining the best HL7 node library solution for HospitalRun

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#286]
We need to integrate with an imaging solution using HL7 (https://www.hl7.org/) as the standard. There are a number of Node-based libraries for accomplishing this. We need to determine which is the best solution to use (https://www.npmjs.com/search?q=hl7). Thus creating an issue requesting help.

**Comment by tangollama** [comment]
@jkleinsc, given that this is a research topic that will likely involve tasks on both the server and frontend, I elected to add this issue here. Any objections?

**Comment by jkleinsc** [comment]
@tangollama I think this is probably the best place to put it for now.

**Comment by gtramontina** [comment]
Hi there,
I've just came across this project on [the latest issue of Offline First](http://us4.campaign-archive2.com/?u=12d36bbe9418ed6a43127cd62&id=4fb72e0584) and found it really interesting.

I have worked with medical imaging software a while ago (~7/8 years ago) and I'm willing to help out! I've dealt mainly with DICOM (leveling, windowing, measuring, ROI…) and PACS servers. My concepts and understandings are a little rusty and outdated, though.

**Comment by tangollama** [comment]
@gtramontina thanks for reaching out. 

We'd love to have your assistance in working towards the best decisions for the product / project / platform. It might be productive for the two of us to move any back-and-forth conversation into our [Slack](https://hospitalrun-slackin.herokuapp.com/). You can find me there, as here and everywhere, by the handle tangollama.

**Comment by tangollama** [comment]
@gtramontina question for you. Have you looked into this issue at all yet? No worries either way. I just want to know for planning purposes.

**Comment by gtramontina** [comment]
Hey there @tangollama I'm really sorry for the silence! My move to Australia has happened sooner than I expected, so I haven't had much time to look into OSS lately… I'm still settling down, so it might take a little while until I'm able to provide more valuable contribution.

**Comment by jupiter** [comment]
I have mentioned a library that I think may be suitable for this here: https://github.com/HospitalRun/hospitalrun-frontend/issues/342#issuecomment-226946828

**Comment by tangollama** [comment]
Here's additional documentation we put together on this issue. https://drive.google.com/open?id=1nGufQ3gSgdZSsQkhQAJN470xjx1HR4QR9ffRUqNyayc
