### ISSUE TITLE
Daily payment report

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#304]
A time-bound report for tracing payments. See functional needs on this document https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Cashier-Role

**Comment by DerekTBrown** [comment]
@tangollama would be willing to start working on this.  Anything changed in this regard since the feature was proposed?

**Comment by tangollama** [comment]
Again, swing away. Thank you.
