### ISSUE TITLE
npm start error with Windows

### ISSUE THREAD

**Issue by nerdkid93** [HospitalRun/hospitalrun-frontend#312]
The following error is returned after trying to run `npm start` in the root folder of hospitalrun:

```
> hospitalrun@0.9.0 start Z:\Projects\hospitalrun-frontend
> ./script/server

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! hospitalrun@0.9.0 start: `./script/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hospitalrun@0.9.0 start script './script/server'.
npm ERR! This is most likely a problem with the hospitalrun package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./script/server
npm ERR! You can get their info via:
npm ERR!     npm owner ls hospitalrun
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     Z:\Projects\hospitalrun-frontend\npm-debug.log
```

**Comment by renato04** [comment]
@nerdkid93 i solved this useing "ember serve" in the root folder. I dont know why but windows did not execute the start bat.

**Comment by nerdkid93** [comment]
I know you can use `ember serve` or `ember s` to launch the live server, but that won't run `npm install`, `bower install`, or check to see if CouchDB is running like `npm start` is supposed to do. If `npm start` isn't changed to work on Windows, then the [README](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/README.md) should be updated for new users to see.

**Comment by renato04** [comment]
@nerdkid93 I agree with that.
I had problems to execute on windows.

**Comment by jkleinsc** [comment]
We may be able to use this for better cross platform use:
https://www.npmjs.com/package/shelljs

**Comment by tangollama** [comment]
@jkleinsc where is this? Can we close it?

**Comment by PaulKish** [comment]
Still have this problem on Windows, am on win10 and the version of HospitalRun is 0.9.15

**Comment by tangollama** [comment]
@PaulKish is this still an issue or can we close (Mac guy asking)?

**Comment by PaulKish** [comment]
@tangollama haven't tried used the latest HR version, will try and test it out over the weekend

**Comment by nzidol** [comment]
The error message comes from the slashes being wrong for Windows cmd environment ('.' is not recognized....) and since the file has no extension no program will be started for it even if you have a unix shell like git-bash in Windows... 

According to https://github.com/npm/npm/issues/6543 npm will always start cmd on Windows for scripts.
> The usual advice on this is to write scripts in Node themselves, and to not rely on bash or sh in lifecycle scripts. If you really want to do that, though, the correct way is to write your script stanza as "do-thing": "bash do-thing.sh" and to document the dependency in the package's README. This is a tough setting to make global, because different packages are going to want to do different things in lifecycle scripts.> 

Note that 'bash ./scripts/server.sh' also does not work for git-bash on Windows....

**Comment by BogdanAlexandru** [comment]
Since there's already something about moving to yarn: https://github.com/HospitalRun/hospitalrun-frontend/issues/1156

It may be worth noting that this issue has been fixed in yarn: https://github.com/yarnpkg/yarn/pull/2082

**Comment by nzidol** [comment]
Those slashes are only part of the problem, line-endings, single/double-quotes and the nature of bash scripts translate poorly to Windows. Am rewriting the scripts with shelljs and now converting the initcouch to use nano rather then curl, such that you get a clean install on all environments with just node installed. WIP is here https://github.com/nzidol/hospitalrun-frontend/tree/resolve%23312/script.
Yarn migration is still complex based on experience with trying to upgrade upstream packages like ember-cli and ember-pouch....

**Comment by BogdanAlexandru** [comment]
Ah you're right, I got my brain stuck on the `.` issue and completely ignored the other things.

**Comment by falexsandro** [comment]
It's my first time on github, if i'm doing something wrong or not in right place, please give some orientation that i'll make it right.

Preparing to test and understand a little about HR, i got this situation, when i was preparing to run the application and them found this issue.
@nzidol made a good work and was based on theirs, that i've got an ideia.
Looking to the scripts and environment, i was thinking if would bad ideia to swap the shell scripts to only nodejs scripts to kick everything, like 'build', 'start', 'test', etc... This way it will run on windows or linux, just needing the nodejs.
I imagine that it would take some time, and somethings that are so simple in shell are not easy to do in nodejs.

**Comment by nzidol** [comment]
@falexsandro Have a look here https://github.com/nzidol/hospitalrun-frontend/tree/resolve%23312/script most scripts are there, just needs a lot of testing..... and anything can be done on nodejs!!!! 
Just having an incredible summer down here so not spending a lot of time behind a PC....

**Comment by natbityou** [comment]
FYI - I ran into this problem and I was able to solve it by editing package.json to use `bash script/server` (note the lack of the `./`). This works running `npm start` using git bash on windows 10.
