### ISSUE TITLE
Inconsistent Checkbox Spacings

### ISSUE THREAD

**Issue by nerdkid93** [HospitalRun/hospitalrun-frontend#322]
There are a couple of forms in inventory that use checkboxes, but they look out of place on the page with their labels. For example, on the "+ new request" [page](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/inventory/request/template.hbs), the "fulfill" checkbox seems to have a lot more whitespace then the rest of the page. When it's selected, a new "consumed" checkbox appears that also looks out of place in terms of element padding. The labels for the checkboxes seem to be too far away from the checkboxes as well.

This seems like it could be solved by either removing the labels for checkboxes, by adjusting the checkbox row height to be only half the other rows' heights, or by removing the bottom margins for the checkbox labels.

![Image of New Request Page](http://i.imgur.com/H67DSnP.png)

**Comment by tangollama** [comment]
@jglovier, I see what's being referenced. Unless you disagree, I'm going to add this to the design list. Could we put this in "Help Wanted"?

**Comment by jglovier** [comment]
Yeah, this def needs cleaned up. :+1: for `help-wanted`

**Comment by mvanstaalduinen** [comment]
Hello, I am an undergrad in computer science and MacEwan University in Edmonton. For one of my course we have to participate in an open source project and contribute to it in a few ways. 

If no one has solved this issue I was wondering if I could take it on, @tangollama?

**Comment by tangollama** [comment]
Swing away. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by tangollama** [comment]
Marketing as In Progress w/ @mvanstaalduinen working on this.

**Comment by jglovier** [comment]
>This seems like it could be solved by either removing the labels for checkboxes

:+1: for solving by removing the labels for checkboxes.

**Comment by tangollama** [comment]
@jglovier, I'm thinking this needs to move back to Help Wanted, yes?

**Comment by jglovier** [comment]
>thinking this needs to move back to Help Wanted, yes?

@tangollama 👍 . Added back.

**Comment by jscottchapman** [comment]
This looks like a good one for my first contribution.  I'm on it @tangollama. 🎯
