### ISSUE TITLE
Need Indicator for Sortable Columns

### ISSUE THREAD

**Issue by nerdkid93** [HospitalRun/hospitalrun-frontend#328]
On the /inventory/listing page, there are a bunch of sortable columns to view the inventory and sort accordingly. However, prior to clicking on the column header, there is no indication that you can sort the column. Even on mouse over, the cursor is the text-selector and not the link-clicker. ![Before sorting](http://i.imgur.com/oG1XuHb.png) ![After sorting](http://i.imgur.com/yPqj3vN.png)

I would recommend adding an icon like [fa-sort](http://fortawesome.github.io/Font-Awesome/icon/sort/) as part of each sortable-column. Other sorting icons can be found [here](http://fortawesome.github.io/Font-Awesome/icons/) and searching with "sort" as the search phrase.

**Comment by jglovier** [comment]
:+1:

**Comment by jglovier** [comment]
PS - we have [Octicons](https://octicons.github.com/) included right now, so we should just use the arrow up/down from that set.

**Comment by nerdkid93** [comment]
Can you superimpose two icons together in octicons? I'm not seeing an icon usually used for "sortable" on that webpage.

**Comment by jglovier** [comment]
Swapping out the [triangle up](https://octicons.github.com/icon/triangle-up/) and the [triangle down](https://octicons.github.com/icon/triangle-down/) arrows on click would be appropriate.

**Comment by jkleinsc** [comment]
@jglovier we do swap up and down on click, but the issue is we don't show anything to indicate you *can* sort a column, so discoverability there isn't great.

**Comment by jglovier** [comment]
>@jglovier we do swap up and down on click, but the issue is we don't show anything to indicate you can sort a column, so discoverability there isn't great.

Right, so adding those octicons as indicators would resolve, right? Or am I missing something?

**Comment by pete-the-pete** [comment]
Is this being actively worked on? If not, I'd like to look into it.

We could show both https://octicons.github.com/icon/arrow-small-up/ and https://octicons.github.com/icon/arrow-small-down/ when a column isn't active, and then show only the up or down to indicate the sorted column.

I think we should also change the cursor to pointer, so that it is obvious the column headings are clickable.

**Comment by jkleinsc** [comment]
@pete-the-pete @mongolianprincess was looking for an issue to start contributing and I had suggested this one.  @mongolianprincess are you interested in taking this issue?  If not @pete-the-pete it's yours.
