### ISSUE TITLE
Allow adjustment when there are no items left?

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#333]
Feedback from our Kenya hospital:
When the quantity of an item is zero, the "adjust" button is gone so if they happen to find some of the item on a shelf, to add them to the listing, they need to go through a purchase even though a purchase hasn't been made.

**Comment by darrylpargeter** [comment]
hey, @tangollama is this issue still up for grabs?

**Comment by tangollama** [comment]
@darrylpargeter swing away.
