### ISSUE TITLE
Payment profiles should support specifying a set fee

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#35]
Patient pays set fee of 1000/2000/3000, etc

**Comment by LennonR** [comment]
@tangollama I'll give this a go.  Are there any additional requirements besides adding "set fee" to the Pricing Profile forms and display pages in the Billing/Price Profiles section?

**Comment by LennonR** [comment]
@tangollama Also, when I run the tests on a newly cloned project, I get 60 test fails out of 684.  Is that expected or is something wrong with my local build?

**Comment by jkleinsc** [comment]
@LennonR when did you fork?  Yesterday I committed a fix for tests that were failing but they should be all passing now.  Maybe try to rebase?

**Comment by LennonR** [comment]
@jkleinsc I forked today a few hours ago

**Comment by jkleinsc** [comment]
@LennonR what tests are failing?

**Comment by LennonR** [comment]
@jkleinsc 1, 4-7, 10-13, 16-33, 36-40, 43-45, 48, 51-54, 57-65, 68-76, 79, 622

**Comment by jkleinsc** [comment]
Is that happening running npm test/ember test ?  Do you have phantomjs installed and if so what version?  The command line tests rely on phantomjs v2.  You can also run the tests in the browser by running ember serve and then going to localhost:4200/tests

**Comment by LennonR** [comment]
I had phantomjs < version 2 so that was probably the problem.  I ran them in the browser and they all passed.  Thanks for the help.

OK, so back to my original question: 

Are there any additional requirements besides adding "set fee" to the Pricing Profile forms and display index page in the Price Profiles section?

**Comment by jkleinsc** [comment]
The intention for this feature is that a patient would only pay a set fee regardless of how much they were charged on an invoice.  So the two places this needs to be addressed in are the crud for pricing profiles and then in the invoice section, when a patient with a pricing profile of this type is selected for an invoice, the total that the patient owes is pulled from the profile and the invoice reflects the amount as what the patient owes by applying a hospital discount for the difference.  Does that make sense?

**Comment by LennonR** [comment]
I think so.  Let me try an example.  

We have an invoice for $2000.  The pricing profile is chosen that has a set fee of $500.  The invoice then needs to have a hospital discount of $1500 applied so that the final total is $500.

Is that correct?

**Comment by tangollama** [comment]
Correct.

**Comment by tangollama** [comment]
@LennonR, if you're going to work on this, great. If so, I'll change the status from Help Wanted to In Progress.

**Comment by LennonR** [comment]
@tangollama Sorry about this.  You can change the status to help wanted.

**Comment by tangollama** [comment]
no worries @LennonR. Thanks for replying back to confirm.

**Comment by tangollama** [comment]
Discussing this with @worrlo and therefore updating the requirements. Ideally the edit interface would now include an option to describe what kind of payment profile this is: a discount or a capped amount. I'm guessing this involves two new attributes on a payment profile:

1. a payment profile type
2. a capped amount (this would be only be displayed in a scenario where capped amount was selected as the "type")

This information would then be applied when the involve is being built. If capped, do capped logic (i.e. the patient is only responsible up to a certain amount), else do the existing discount logic.

<img width="652" alt="screen shot 2016-05-30 at 3 46 23 pm" src="https://cloud.githubusercontent.com/assets/929261/15657353/14fefc86-267e-11e6-9bc7-c99db0a4bdeb.png">

**Comment by tangollama** [comment]
FYI, I've made some progress on this, but it's not done yet. I'll keep working on it and try to get in in for 1.0.

**Comment by tangollama** [comment]
Resolved in master
