### ISSUE TITLE
List of missed appointments

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#351]
Create a new route in Appointments that lists the missed appointments. (suggested: /appointments/missed). The purpose for this is to create a mechanism for followup.

**Comment by pete-the-pete** [comment]
I can look into this one if no one else has it.

**Comment by tangollama** [comment]
Go for it. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by tangollama** [comment]
Assuming @pete-the-pete has this.

**Comment by pete-the-pete** [comment]
Yep.  I'll take a crack at it in the next few days.

**Comment by pete-the-pete** [comment]
@tangollama I have started; I created a new applications/missed pod, and have looked at the other applications code for inspiration.  I wanted to get your thoughts on my approach and assumptions, and maybe ask a few questions, before getting too far into it.

## Assumptions/Requirements
- this will add an 'appointments/missed' url
- it will also add a 'Missed' sub-nav item in the the left menu
- each missed appointment will have the _edit_ and _delete _ functionality
- the missed appointments will **not** have the _add visit_ functionality

## Approach
This will be very similar to the other appointments code; the route will extend AbstractIndexRoute and load the data; the controller will set the flags for the buttons, and the template will loop over the data, using the appointments' item/template.hbs for each row.

A 'missed' appointment will be any which has `endDate < Date.now() && status !== canceled`

## Questions
Is the 'missed' logic correct?
Do we want to limit the functionality at all (not allowing adding a visit)?
Is the right approach to define the `_filterParams` in the appointments/missed/route?

Thanks for any feedback.
