### ISSUE TITLE
Expiring in the next X days Inventory screen

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#353]
Create a new screen similar to the inventory expiration report that shows the list of inventory items with purchases that are set to expire in the coming 30/60/90 days. List the items similarly to the Inventory Items screen, just limited by the given date selection. I recommend a route on /inventory/expiring.

Two variables:
- Support a dropdown in the screen that support 30 days, 60 days, and 90 days in the drop down. Default to 30 days.
- Support a drop down to limit the search by Inventory type (Medication, Supplies, etc.)

Add this screen to the Inventory navigation.

Look to the Inventory Reports, Expiration Date report for _most_ of the code needed.

**Comment by billybonks** [comment]
can assign to me

**Comment by tangollama** [comment]
It's all yours @billybonks. Removed the Help Wanted tag. Marked In Progress

**Comment by billybonks** [comment]
can you also add me to the asignee so its easier to find again :)

**Comment by tangollama** [comment]
Will do. I'm traveling today but will tonight. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by tangollama** [comment]
@billybonks finally assigned you.

**Comment by billybonks** [comment]
Ye sorry i haven't actually made a pull request yet. Is this an urgent
feature?

**Comment by billybonks** [comment]
I have done a bit more work on this

`Support a drop down to limit the search by Inventory type (Medication, Supplies, etc.)`

is this a multi select dropdown ?

**Comment by billybonks** [comment]
currently the page looks like this

<img width="1437" alt="screen shot 2016-05-06 at 12 39 38 am" src="https://cloud.githubusercontent.com/assets/1640136/15049841/18789606-1323-11e6-8775-f287304cff1d.png">

i am sure @jglovier will have some opinions 👍

**Comment by tangollama** [comment]
@jglovier concerns with this? Trying to gauge if this can be closed out.

**Comment by jglovier** [comment]
>@jglovier concerns with this?

Yeah, a couple, but some of it I think is a matter of global form styling that still needs addressed. The only thing really that stands out is why the view title isn't in the title bar in the screenshot above?

**Comment by billybonks** [comment]
probably because i am missing, the title property :)

**Comment by tangollama** [comment]
@billybonks we're getting close to a 1.0 beta release. Any chance this is ready to go? If not, no worries.

**Comment by tangollama** [comment]
@billybonks  are you still interested in this issue? If not, I'll move it back to Help Wanted.
