### ISSUE TITLE
'No patients found' helper link not presented after removing all patients

### ISSUE THREAD

**Issue by dswanson** [HospitalRun/hospitalrun-frontend#357]
**Expected behavior:**
When you remove all patients, you should get the helper starting link back

**Actual behavior:**
The helper starting link is not presented

**Steps to reproduce:**
Be in the state with only one patient
Delete that patient
The 'No patients found. Create a new patient record' starting helper is not presented.

**Comment by brianlindsy** [comment]
This seems like a good first contribution, ill take a crack at it @tangollama.

**Comment by cacqw7** [comment]
I wasn't able to reproduce this bug. Is this still an issue?

**Comment by jkleinsc** [comment]
@cacqw7 this was fixed as part of the PR #431, so I am going to close this issue.
