### ISSUE TITLE
Diagnosis coding

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#36]
Right now we are pulling in ICD-10-CM diagnosis codes, but this is a US-centric list.  At the very least we should be pulling in WHO's version of ICD-10, but this list may need to vary per install

**Comment by jkleinsc** [comment]
One surgeon commented that using the ICD10 typeahead it is too hard to find stuff (“need better search engine”).  This may have been due to the fact that we were using ICD-10-CM, but more research may be needed here.

**Comment by jkleinsc** [comment]
Commit 128742d67a4c7e1f15d480cb80c84127de7ea1b2 removes the ICD10 typeahead and replaces it with a simple typeahead of user specified diagnosis which at some point should be able to be loaded with ICD10 data.

**Comment by tangollama** [comment]
Working on the requirements here. https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Diagnosis-Coding.

I'll remove the tag when the doc is "done."

**Comment by tangollama** [comment]
I'm going to close this issue and break it into multiple feature tickets tied back to these "requirements." 

https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Medical-Coding
