### ISSUE TITLE
Improve view content header layout

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#361]
**Existing experience:** In the view header area, we have a view title bar, a section subnav, and buttons for the views primary actions. Currently they are stacked with the title bar on top, then the subnav and action buttons below, followed by the view content, like so:

![image](https://cloud.githubusercontent.com/assets/1319791/13814942/c0820216-eb45-11e5-8116-f72cc797ae58.png)

**Better experience:** We can add some vertical space for the content and simplify the information structure in the view by moving the action buttons to the title bar, and :fire: the subnav (which is redundant now because of the sidebar nav, and often confusingly inconsistent with the sidebar nav).

![image](https://cloud.githubusercontent.com/assets/1319791/13815101/793c609e-eb46-11e5-8b80-dc667e7ed5b8.png)

**Comment by dswanson** [comment]
Another affordance I have seen work is to de-emphasize the actions except when the specific row has focus.

When the user "selects" the row, that row is highlighted and then the actions are made more apparent.
This can be done by making the actions invisible until the highlighting, or just changing their opacity.

**Comment by dswanson** [comment]
I am going to attempt removing the sub-nav..wish me luck!

**Comment by jglovier** [comment]
>I am going to attempt removing the sub-nav..wish me luck!

@dswanson:

![carl-sagan-youre-awesome](https://cloud.githubusercontent.com/assets/1319791/13819973/9d159fbe-eb58-11e5-9f43-f3bf7b8325ba.gif)

**Comment by tangollama** [comment]
@jglovier, @dswanson where is this issue? Should I move it back to Help Wanted?

**Comment by jglovier** [comment]
This was resolved in #369. :sparkles:
