### ISSUE TITLE
Requesting clinician needs to be added to the Imaging Request list

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#362]
The request list does not contain the requesting user (clinician). We need to see this for the purposes of ensuring the person processing the requests that they are appropriately authorized. Even though we permission specific people to issue those requests, we still want the user experience to verify that.

**Comment by cacqw7** [comment]
@tangollama I'll take this one. 

**Question/Suggestion**: 
What do you think of adding an `Add ___` link to blank notes and results?
![link](https://cloud.githubusercontent.com/assets/3615754/14840677/0b17e742-0bfc-11e6-9f9d-b70991b401b5.png)

And then maybe greyed out `No ____` for blank notes and results.
![light](https://cloud.githubusercontent.com/assets/3615754/14840777/fefd7a3e-0bfc-11e6-8378-ee9f921d8877.png)


Let me know what you think. Either way I can make a PR for this.

**Comment by tangollama** [comment]
@cacqw7 I really like this suggestions. I think it would aid in the usability of the interface. That said, I'm going to ask @jglovier to quick weigh in on this, as we're asking him to help guide the design paradigms. JAG?

Regardless, I'm going to flag this as in progress.

**Comment by jglovier** [comment]
FYI I provided feedback over in #437.
