### ISSUE TITLE
Requesting clinician needs to be added to the Medication Request list

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#363]
The request list does not contain the requesting user (clinician). We need to see this for the purposes of ensuring the person processing the requests that they are appropriately authorized. Even though we permission specific people to issue those requests, we still want the user experience to verify that.

**Comment by alvesjtiago** [comment]
Hi @tangollama, I'd like to start contributing to HospitalRun and this seems like a good issue to start with. I believe the requested functionality is this correct?

<img width="1280" alt="screen shot 2016-05-08 at 02 55 48" src="https://cloud.githubusercontent.com/assets/407470/15095624/8bdaff5c-14c8-11e6-9078-dcc3712af6be.png">
<img width="1280" alt="screen shot 2016-05-08 at 02 55 53" src="https://cloud.githubusercontent.com/assets/407470/15095626/91ad15aa-14c8-11e6-871f-55eabf33e172.png">

As soon as you confirm I will submit a pull request.

Thank you

**Comment by tangollama** [comment]
@alvesjtiago sorry that I missed this. Yes. That is correct.

**Comment by alvesjtiago** [comment]
No problem @tangollama. I just submitted a pull request with the modifications I previously showed.
