### ISSUE TITLE
Procedural coding

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#37]
ICD-10-PCS has been removed from HospitalRun and has been replaced with two fields:
A freeform typeahead text field called Procedure and a CPT Code freeform text field for medical coding of CPT codes.  We can leave it as is, but should we do something better here?

**Comment by tangollama** [comment]
I'm closing this ticket in favor of creating multiple feature tickets which all tie back to these requirements. https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Medical-Coding
