### ISSUE TITLE
Need to be able to customize invoice header and footer

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#370]
Right now the invoice header and footers are hard coded to values for the Tebow Cure hospital, but we need them to be customizable per install.

**Comment by jkleinsc** [comment]
@reybango and @taras here is the issue for customizing the invoice header and footer.

**Comment by tangollama** [comment]
@reybango just clarifying given our slack conversation. Do you still have this, is @taras working on it instead, or should I have this back to Help Wanted? Just let me know.

**Comment by reybango** [comment]
@tangollama I think that @taras should wrap this one up. We've made some great progress with @taras doing most of the work and I think it's near completion.

**Comment by tangollama** [comment]
@reybango how is this coming?

**Comment by reybango** [comment]
@tangollama I'm going to defer to @taras on this one.

**Comment by tangollama** [comment]
@taras any chance you'd be able to close this out sometime soon?

**Comment by tangollama** [comment]
@jkleinsc based on the PR submitted by @taras, can we close this?

**Comment by jkleinsc** [comment]
@tangollama that PR is complete, so this issue should stay open until it is complete.

**Comment by tangollama** [comment]
Resolved.
