### ISSUE TITLE
Add documentation for SCSS linter and tooling to CONTRIBUTING.md

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#375]
With the addition of the scss linter, we need to provide clear documentation about how the linter works, how to use the linter in your code editor, and how your styles should be structured to pass the linters.

**Comment by billybonks** [comment]
1. Can we assume developers know what a linter is ?
2. Do we add documentation for `atom` and `sublime` ?
3. Should we explain why we lint ?

We could just add links to the official documentation for some of these topics, then add docs how to setup linter on your editor.

**Comment by jglovier** [comment]
@billybonks heh, good questions.

>Can we assume developers know what a linter is?

Probably not. :smile:

>Do we add documentation for atom and sublime?

Yeah, that'd probably be ideal. Although I've only used the linting package on Atom myself and I don't even know that there is one for Sublime (but I'd be surprised if there wasn't).

>Should we explain why we lint?

Yes, absolutely.

>We could just add links to the official documentation for some of these topics, then add docs how to setup linter on your editor.

Sounds like a good strategy to me. Even if just as a first pass and then we iterate more later. 👍 :zap:
