### ISSUE TITLE
Show patient update confirmation as inline alert rather than modal

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#377]
**Current experience:** When you update a patient record, you are shown a confirmation dialog as a modal that lets you go back, or simply close the dialog. It is superfluous and requires an extra click to keep working if you don't want to return to the patient record screen.

![image](https://cloud.githubusercontent.com/assets/1319791/13888053/65e3a9e6-ecfc-11e5-9f66-fcf503f13629.png)

**Better experience:** Instead, we should render the alert inline just above the button so that you don't have the extra step of dismissing the modal if you want to do anything other than returning to the patient index. We can still include the patient index link in the confirmation alert for convenience if that is your next destination.

**Steps to reproduce:** Go to a patient record and update any piece of information.

**Comment by dswanson** [comment]
I propose this would be an improvement for the user experience. I would encourage most of the modal confirmation dialogs be "retired". Nice!

**Comment by jglovier** [comment]
>I would encourage most of the modal confirmation dialogs be "retired".

+:100:

**Comment by eddiesholl** [comment]
There's a couple of options I evaluated recently for ember notifications. We went with:
http://stonecircle.github.io/ember-cli-notifications/

Another nice option is:
http://simonwade.me/assets/ember-demos/#/ember-notify

**Comment by jkleinsc** [comment]
@eddiesholl thanks for the suggestions.  I really like ember-cli-notifications.  @jglovier what do you think?

**Comment by jglovier** [comment]
I'm not really interested in any of the default styling or animations, but anything that solves the basic case of showing an inline alert without a modal is fine with me.

The placement of the alert should be in close proximity to the button where the alert was generated from, or at the top of the page if it is generated as part of a general page load condition. I'll create some design mocks to show what I think we want visually.

**Comment by jkleinsc** [comment]
@jglovier perfect :+1:

**Comment by cacqw7** [comment]
I can take this one if no one else is working on it. I have a _very_ rough `wip` using [ember-cli-notifications](http://stonecircle.github.io/ember-cli-notifications/)

![alert](https://cloud.githubusercontent.com/assets/3615754/15093864/3c30f5f2-1459-11e6-989b-6dec800ab631.gif)

**Comment by amyrlam** [comment]
I'll work on this

**Comment by jscottchapman** [comment]
@amyrlam  It looks like you are working on this one. Is that right? Just wanted to make sure two people aren't working on the same issue unknowingly.

**Comment by amyrlam** [comment]
@jscottchapman hi! I have a branch https://github.com/amyrlam/hospitalrun-frontend/tree/amyrlam/no-modal, but since I have another issue in work, feel free to give to someone else. You could run my branch locally to see a demo. @jglovier mentioned moving the notification above the button (right now it's at the top center of the page)

**Comment by ivanlori** [comment]
@tangollama , Hi I am new on this project, I would like to work on this, can I?

**Comment by jkleinsc** [comment]
@ivanlori it is yours to work on.

**Comment by jglovier** [comment]
@ivanlori any update on this? If you've not had a chance to work on it, and don't think you will in the immediate future, I'd like to add the `help-wanted` label back on it.

**Comment by ivanlori** [comment]
Hi Joel,
yes, it would be better with help-wanted label

2017-01-17 15:22 GMT+01:00 Joel Glovier <notifications@github.com>:

**Comment by melissahie** [comment]
taking this issue
