### ISSUE TITLE
Flag patients as archived rather than deleting them entirely

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#381]
This will involve not only a new status on patients but also adjustments to the various views to exclude patients that are flagged as "archived."

**Comment by pete-the-pete** [comment]
@tangollama i can take a look at this and #382

**Comment by jkleinsc** [comment]
@pete-the-pete I started working on this and I checked in a branch here with my work: https://github.com/HospitalRun/hospitalrun-frontend/tree/archive-records

If you look at the code here, basically what I am doing is adding a new attribute called archived.  Then in the pouch/couch views, any records with that attribute are ignored.  Tests are not passing right now on this branch, but the basic concepts are implemented.  If you want to continue work on it, feel free, but I would use that branch as a starting point.

**Comment by jkleinsc** [comment]
This issue was resolved in commit 20dd5b29cf697b23f0df179d30fe951e31744d0f.
