### ISSUE TITLE
A separate screen for handling permanent deletion of archived data

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#384]
Once #380 and #381 are completed, we need a screen where:

[ ] archived items can be deleted in mass (i.e. delete all items that have been archived for 6 months or more
[ ] a specific archived item can be searched for a deleted permanently

**Comment by pete-the-pete** [comment]
How will permissions for this page work? As in, are there restrictions around which type of users would have access to see the page, or delete certain records?

How should the data be organized?  Would you want to filter or sort the data in anyway?
