### ISSUE TITLE
Adjustment types for inventory need to localized

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#390]
**Expected behavior:** Inventory adjustment types display localized text.  

**Actual behavior:** Inventory adjustment types display hard coded text.  Right now values displayed for adjustment types are hard coded in app/mixins/inventory-adjustment-types.js

**Steps to reproduce:** Edit an inventory item and click on the adjust button.  The adjustment type dropdown and the button at the bottom of the modal are being pulled directly from the mixin.

One thing to keep in mind with this issue is that the 'Type' values in the mixin is used in the code and gets saved to to the database, so those values should not be localized, but anywhere we display those "type" values we need to localize them.

**Comment by dswanson** [comment]
Working on this issue at OSCON Contribute!

**Comment by dswanson** [comment]
![image](https://cloud.githubusercontent.com/assets/626044/15368456/b130c1de-1ce2-11e6-8089-c2cb2982d03f.png)

**Comment by billybonks** [comment]
ye this is something i have been thinking about as well. @dswanson i presume you haven't made any progress on this ?

**Comment by sweeneydavidj** [comment]
Going to start looking at this issue.

**Comment by jkleinsc** [comment]
@sweeneydavidj go for it.  I'll set the issue to In Progress.  If for some reason you can't complete this issue, let me know and I'll update the status on the issue.
