### ISSUE TITLE
'No items found' helper link not presented after removing all items

### ISSUE THREAD

**Issue by brianlindsy** [HospitalRun/hospitalrun-frontend#395]
**Expected behavior:**
When you remove all items, you should get the helper starting link back

**Actual behavior:**
Helper link is not present

**Steps to reproduce:**
Be in the state with only one item
Delete that item
The 'No items found. Create a new item record' starting helper is not presented.

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by esbanarango** [comment]
@tangollama I want to solve this issue.

**Comment by tangollama** [comment]
@esbanarango swing away. Marked as in progress, per process.
