### ISSUE TITLE
'No imaging found' helper link not presented after removing all imaging

### ISSUE THREAD

**Issue by brianlindsy** [HospitalRun/hospitalrun-frontend#397]
**Expected behavior:**
When you remove all imagning, you should get the helper starting link back

**Actual behavior:**
The helper link is not present

**Steps to reproduce:**
Be in the state with only one image
Delete that image
The 'No imaging found. Create a new imaging record' starting helper is not presented.
**Screenshots (if applicable):**

**OS and Browser:**

**Comment by rohansp** [comment]
Is there an option to delete an imaging request?
I can see only the edit button
![imaging request](https://cloud.githubusercontent.com/assets/11171608/14130650/336b0bc4-f5fa-11e5-896c-3c9985d24e3c.png)

**Comment by tangollama** [comment]
@rohansp you can fulfill the request to empty the queue.
