### ISSUE TITLE
RFC: dockerize the app

### ISSUE THREAD

**Issue by techthumb** [HospitalRun/hospitalrun-frontend#407]
Hi,

I am interested in dockerizing this app, for local dev, CI & deployment.

I am considering rallying up support for doing this at: http://www.meetup.com/NY-JavaScript/events/228231065/

I want to know if this would add value for a project goals perspective.

**Comment by tangollama** [comment]
Hi @techthumb. Thanks for asking. The short answer is: absolutely. 

The one thing I'd want to do is check in on our Slack. I heard rumor a few weeks ago that someone was about to submit a PR for that. Since that hasn't happened yet, I'll circle back and give you the "all's clear."

**Comment by tangollama** [comment]
This work is being carried on in the server repo. https://github.com/HospitalRun/hospitalrun-server/issues/7

**Comment by tangollama** [comment]
Closing this in favor of the server ticket.
