### ISSUE TITLE
Incorrect Column Labels in Admin/Users

### ISSUE THREAD

**Issue by nerdkid93** [HospitalRun/hospitalrun-frontend#415]
**Expected behavior:**
In admin/users, the column labels are mislabeled. The left-most column should read `Display Name` and the 2nd column from the left should read `Username`.

**Actual behavior:**
The left-most column reads `Username` and the 2 column from the left reads `Name`.

**Steps to reproduce:**
Navigate to the Users page within the Admin module.

**Screenshots (if applicable):**
![image](https://cloud.githubusercontent.com/assets/6289786/14430342/30d8bada-ffcf-11e5-930b-5436e068be81.png)

**OS and Browser:**
Ubuntu (in [Cloud 9](c9.io)) with Chrome Version 49.0.2623.110 m

**Comment by juanjcsr** [comment]
@tangollama I can work in this one. Seems the labels and the data in the table are switched in the template.
