### ISSUE TITLE
Need a way to reset locally stored data

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#438]
**Expected behavior:**
If there was a need to reset the data at the server level, any data stored locally (offline) in user's browsers would need to be invalidated/flushed from the local pouchdb storage
**Actual behavior:**
If the couchdb database is deleted and recreated as an empty database, user's offline data ends up repopulating the data because of the sync between pouch and couch
**Steps to reproduce:**
1. A user navigates to a hospitalrun site that has records in it.
2. A couchdb admin deletes the main database and creates a new (empty) main database.
3. The user from #1 navigates to the hospitalrun site which causes the pouch/couch sync to run which in turn pushes the locally stored records back to couch, thus repopulating the database that was intentionally emptied.
**Screenshots (if applicable):**
N/A
**OS and Browser:**
All

**Comment by jkleinsc** [comment]
The solution here is to write a script that issues deletes for all the records in the database vs deleting the database and recreating the database as new.

The problem with this is that you cannot then reload the same data dump, because the load DB function in the app does a replication.  Load DB should be changed to instead of doing replication it should load the records in the dump as new records/revs.

**Comment by darrylpargeter** [comment]
@tangollama  would it be possible to give this a try?

**Comment by tangollama** [comment]
Please do.
