### ISSUE TITLE
Patient listing paging back button doesn't always go to start

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#45]
There seems to be an issue where paging on patient listing doesn't let you go all of the way back to the first page.  Not sure what steps to reproduce are.

**Comment by tangollama** [comment]
Need help reproducing and then fixing. Do one or both to make a contribution. Thanks!

**Comment by gnowoel** [comment]
Not sure if it's what @jkleinsc experienced, but the pagination buttons will indeed mess up the patient list when using descending order of a field.

To produce it, please visit the [Patient Listing](https://beta.hospitalrun.io/#/patients) page on the Beta site, and then:

  * Click twice the `Id` header to sort the items in descending order
  * Click the Next button (the right arrow in the table header)
  * Click the Previous button (the left arrow) to go back

![screen_shot_2016-10-14_at_12_28_09_am](https://cloud.githubusercontent.com/assets/543961/19357898/28c13b9c-91a6-11e6-8bff-ef86ab62cf60.png)

Now the pagination buttons will disappear and only one listing item will be left.

![screen shot 2016-10-14 at 12 30 51 am](https://cloud.githubusercontent.com/assets/543961/19358022/bc482ca4-91a6-11e6-94f6-233b0aaa82ed.png)

I'm working on a simple solution to this. A PR would be coming soon for your review.

cc @tangollama
