### ISSUE TITLE
Relative Value Unit based Report required for Medical Staff evaluation

### ISSUE THREAD

**Issue by sentana** [HospitalRun/hospitalrun-frontend#451]
**New Feature**
Due to the vast number of Medical staff in the hospital, it is becoming difficult to evaluate the doctors and Nurses based on their involvement in any of the treatment per month.

RVU based Physicians and Nurses evaluation system Report required:
- How many procedures does the doctor did per day
- What are the type of procedures the doctor did
- How many procedures does the Nurse assist
- A monthly report for each Doctor and Nurses will be generated and paid for additional hours
- There is an excel sheet that contain the List of Physician Relative Value (RVU) By Procedure Code and the value which is attached with this story.

Attached  the CPT code and RVU value with sample productivity report to be generated monthly.

[Sample RVU Productivity Report.xlsx](https://github.com/HospitalRun/hospitalrun-frontend/files/257410/Sample.RVU.Productivity.Report.xlsx)
[2014 Relative Value Units File For St. Paul Medical College.xlsx](https://github.com/HospitalRun/hospitalrun-frontend/files/257411/2014.Relative.Value.Units.File.For.St.Paul.Medical.College.xlsx)

**Comment by mqchau** [comment]
Hi. Do you guys still want/need this feature?

**Comment by jkleinsc** [comment]
@mqchau this is a low priority item, but if you have interest in implementing it, feel free!
