### ISSUE TITLE
Clinical work queue as the home screen

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#452]
For a person(s) logging into the system, "what's important now" is unclear, particularly when it comes to appointment and visit management for doctors. I propose the following changes.

1. Borrowing from the Search interface in Appointments, clinicians should see lists of Appointments that have not yet spawned a Visit, open Visits, current Labs, and current Imaging requests, depending on one's role.
2. Filtering by Assigned To (again, as it possible in the Appointment Search interface) is critical for doctors to focus their time.
3. The Search interface should include "quick link" views to Today, This Week
4. Searching by patient should be possible
5. Items should be governed by their status to support the workflow of requiring payment before something ends up in a work queue.

This needs discussion amongst the project team before we give it a help wanted tag. 

cc: @jkleinsc @jglovier 

<img width="1202" alt="screen shot 2016-05-11 at 9 45 06 am" src="https://cloud.githubusercontent.com/assets/929261/15182992/22842640-175d-11e6-9113-e62534416c1c.png">

**Comment by jglovier** [comment]
@tangollama lets move this discussion into the existing issue for the dashboard #387.

**Comment by mnorbeck** [comment]
I second the @jglovier motion.  Close this issue, make it part of the dashboard discussion
