### ISSUE TITLE
Barcode for inventory is inconsistent with browser Go back 

### ISSUE THREAD

**Issue by sentana** [HospitalRun/hospitalrun-frontend#458]
**Expected behavior:**
Barcode has to be generated for each items in the inventory.
**Actual behavior:**
Inconsistent label and wrong
**Steps to reproduce:**
1. Login as admin
2. Click the Inventory Items
3. Select the Barcode button of any of the item and take a note of the label
4. Go back using the browser go back button
5. Select another item from the list and click the Barcode button again
6. Notice the label under the barcode which will be the previous one
**Screenshots (if applicable):**

**OS and Browser:**
Windows, Chrome

**Comment by tangollama** [comment]
Thanks for this @sentana. Any chance you'd be up for looking into this and trying to provide a solution? If so, I'll move this to In process.
