### ISSUE TITLE
Add an option to create a new Visit on the creation of a new Patient

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#460]
Include at the bottom of the New Patient screen a checkbox (by default unchecked) to automatically create an Outpatient Visit for this Patient. If unchecked, maintain current behavior. If checked, create the Visit after the creation of the Patient record and navigate to the New Visit screen.

This will aid in the admission process.

**Comment by omoabobade** [comment]
@tangollama i am working on this

**Comment by tangollama** [comment]
thx @omoabobade

**Comment by tangollama** [comment]
@omoabobade any update on this issue?

**Comment by omoabobade** [comment]
Sorry been held up at work and also reading up on emberjs should submit a
push request by Tuesday. Sorry for the delay

**Comment by omoabobade** [comment]
@tangollama pls i have a question what is the difference between admittance and visit?? I am currently at a loss here

**Comment by omoabobade** [comment]
@tangollama any update ??

**Comment by tangollama** [comment]
An admission is a type of visit. The workflow of the visits and some of the confusion around the way the data is presented is one of the clear gaps we hope to close.
I have limited availability this weekend, but if you ping me on the project slack, we can at least set a time to talk.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.40&pv=9.3.1&source=email_footer_2]
On Thu, Jun 30, 2016 at 1:38 PM, Abobade Kolawole <notifications@github.com> wrote:
@tangollama [https://github.com/tangollama] pls i have a question what is the difference between admittance and visit?? I am currently at a loss here

**Comment by omoabobade** [comment]
Thanks for the explanations. I have already submitted a pull request, it my
first open source contribution so am kind of excited and looking forward to
you reviewing it. Would go on and look for another bug to fix. Thanks again

**Comment by tangollama** [comment]
Thank you for contributing. I'm looking forward to reviewing your PR.

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.40&pv=9.3.1&source=email_footer_2]
On Sun, Jul 3, 2016 at 7:51 AM, Abobade Kolawole <notifications@github.com> wrote:
Thanks for the explanations. I have already submitted a pull request, it my
first open source contribution so am kind of excited and looking forward to
you reviewing it. Would go on and look for another bug to fix. Thanks again

**Comment by jkleinsc** [comment]
Closing in favor of outpatient screen/workflow.
