### ISSUE TITLE
Create an administrative screen where workflow rules can be toggled on/off

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#462]
As a part of the [Workflow features](https://github.com/HospitalRun/hospitalrun-server/labels/Workflow) in the server project, we need a screen that houses the workflow administrative toggles for the following:

- Admission deposit required? (Yes/No) [defaiult No]
- Clinic prepayment required? (Yes/No) [default No]
- Followup prepayment required? (Yes/No) [default No]
- Outpatient Lab prepayment required? (Yes/No) [default No]
- Outpatient Imaging prepayment required? (Yes/No) [default No]
- Outpatient Medication prepayment required? (Yes/No) [default No]

These configurations will be used on the frontend and server projects as a part of the Workflow rules.

**Comment by vanakema** [comment]
@tangollama I am considering easing myself into the codebase by doing this one. What is the scope of this task? Is this task just asking someone to make the view and maybe the route?

**Comment by tangollama** [comment]
@vanakema basically, yes. We need to store the configurations in couch so that they're available for reading on the server end. If you want to go after this, that would be fine. This issue is technically part of a hack day event we're running in [Lisbon in mid-June](http://hospitalrun.io/lisbon); but if you tackle and deliver it ahead of June 18, that would be a great benefit to the team that needs this functionality.

**Comment by chinmaybhatk** [comment]
is this issue fixed? if yes where is the option?? i didnt get any option to do
    Admission deposit required? (Yes/No) [defaiult No]
    Clinic prepayment required? (Yes/No) [default No]
    Followup prepayment required? (Yes/No) [default No]
    Outpatient Lab prepayment required? (Yes/No) [default No]
    Outpatient Imaging prepayment required? (Yes/No) [default No]
    Outpatient Medication prepayment required? (Yes/No) [default No]
under User Roles. I couldnot check while adding  user bcz of session issue.

Please let me know where it is?

**Comment by tangollama** [comment]
No. This feature is not built yet. 

Typed or dictated imperfectly on my iPhone (717.385.9970)

**Comment by chinmaybhatk** [comment]
Thank you for the reply @tangollama , but in #518 they mentioned code has been committed but build failed ... is there any info on this?

**Comment by tangollama** [comment]
I'll look into it.

**Comment by tangollama** [comment]
@chinmaybhatk so here the thing. The code for accessing the configuration is - in fact - in the system. You can navigate to it directly if you have the server installed or you are running the dev environment (i.e. Frontend) at http://<your url>#/admin/workflow. 

However, it hasn't been exposed in the navigation yet. Why? B/c the code behind the scenes that consumes those configurations are actually modifies those rules has not been written. 

If you're interested in getting involved in completing that feature, that would be great. I'm happy to discuss requirements more in the project Slack.

**Comment by chinmaybhatk** [comment]
yes i am interested in completing this feature..
