### ISSUE TITLE
Create a new screen for Followup and Clinic Visits

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#463]
Under Patients, create a new screen title Outpatient that lists each visit of type Clinic or Followup that does not have a Visit status of Discharged.

List columns: Visit Start Date, Examiner (Visit field), Patient ID, Patient Full Name, Patient Sex, Patient DoB, Visit Type, Actions
Click Action: Edit Visit
Actions: Edit (Edit Visit), Discharge (set Visit to Discharged, set End Date to now), Delete (if permission)
Search / Filter: similar to the Appointments Search section at the top of the page (see below). The filters should be: Examiner, Start Date, toggle Visit payment_state (Clear or Pending Payment), Search by Patient (name, ID, phone number)

<img width="905" alt="screen shot 2016-05-12 at 2 42 49 pm" src="https://cloud.githubusercontent.com/assets/929261/15226218/d5d5e718-184f-11e6-9445-c5dad1180630.png">

The point of this List page is to aid the outpatient clinic process.

**Comment by bnisbett** [comment]
Hi @tangollama I am interested in taking a look at this issue if it's available.

**Comment by tangollama** [comment]
Go for it @bnisbett

**Comment by bnisbett** [comment]
@tangollama I have a few questions about this feature.

I'm not clear on the search/filter feature. Should this be a separate page as well under Patients or part of this new Outpatients page?

**Comment by tangollama** [comment]
@bnisbett thanks for your patience. Do you have what you need on this? If not, the intention with the filter was to make it part of the template / view. So that outpatients page would include both the list and the ability to filter.

**Comment by mnorbeck** [comment]
@tangollama:  Visits are active things.  So, if there was a single screen of open visits, and you could filter on type, I think you have this covered.   There is also the possibility that visits are not updated properly, and are actually closed (or done).  So, a means to filter to show only the bogus visits would be great.  Maybe a filter (or sort) on visit start date.   Or a simple "visits more than a week old".

**Comment by akong** [comment]
@tangollama I'd like to pick this up if it isn't being worked on.

**Comment by jkleinsc** [comment]
@akong I just saw this issue because of your PR... unfortunately this is something I have been working on for a while under a branch https://github.com/HospitalRun/hospitalrun-frontend/tree/outpatient

I was unaware of this ticket, but at this point this issue isn't available to be worked on.
