### ISSUE TITLE
Add a payment_state field to Visit

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#464]
Add a payment_state field to Visit that contains (for starters) two states: Clear and Pending Payment. Clear would be the default state. 

Then modify the following screens:
- [ ] Don't show [Outpatient Visits](https://github.com/HospitalRun/hospitalrun-frontend/issues/463) with a Visit payment_state of Pending Payment
- [ ] Don't show Imaging Requests with a Visit payment_state of Pending Payment
- [ ] Don't show Lab Requests with a Visit payment_state of Pending Payment
- [ ] Don't show Medication Requests with a Visit payment_state of Pending Payment

**Comment by mattplatoff** [comment]
@tangollama working on this
