### ISSUE TITLE
Loading new list on Imaging Requests can not be stopped

### ISSUE THREAD

**Issue by cs09g** [HospitalRun/hospitalrun-frontend#465]
**Expected behavior:**
1. move to Imaging tab
2. click next page button(below the button 'new imaging')
-- showing progress pop up --
3. close the pop up by clicking 'x' during loading time
4. keeps the current page

**Actual behavior:**
1. move to Imaging tab
2. click next page button(below the button 'new imaging')
-- showing progress pop up --
3. close the pop up by clicking 'x' during loading time
**4. move to the next page**

**Steps to reproduce:**
explains above

**Screenshots (if applicable):**

**OS and Browser:**
Windows, latest Chrome

**Comment by tangollama** [comment]
@jglovier @jkleinsc I understand why this was logged as a bug. Technically, the system is functioning as designed, but there's clearly a UX issue in the way notifications are displayed and the sense that the X button in the waiting dialog should be able to cancel the action. Any further thoughts from anyone in the project?

**Comment by jglovier** [comment]
>but there's clearly a UX issue in the way notifications are displayed and the sense that the X button in the waiting dialog should be able to cancel the action.

Probably a good topic for discussion in our Notifications sync up later this week.
