### ISSUE TITLE
Add review/manual resolution of couchdb conflicts.

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#466]
Right now all couchdb conflicts are solved automatically by the couchdb listener here:
https://github.com/HospitalRun/hospitalrun-dblisteners/blob/master/dblisteners/merge-conflicts.js

While this should produce a hands free resolution process it could be nice to have a screen where admins can see conflicts that were resolved and (optionally) manually resolve those conflicts differently if needed.
**Expected behavior:**
There should be an admin screen where administrative users can see automatically resolved conflicts and manually override those conflicts if needed.
**Actual behavior:**
The screen doesn't exist
**Steps to reproduce:**
NA
**Screenshots (if applicable):**
NA
**OS and Browser:**
All

**Comment by hosghf** [comment]
is there any manual about how to use software itself for users and not develooers?
