### ISSUE TITLE
When logging in for the first time, server crashes with TypeError: Cannot read property 'deleted' of undefined in node_modules/hospitalrun-server-routes/routes/30-auth.js:134

### ISSUE THREAD

**Issue by gr2m** [HospitalRun/hospitalrun-frontend#475]
**Expected behavior:**

Should show logged in state

**Actual behavior:**

Shows sidebar, but only the HospitalRun header and the cog icon. The login remains

```
/Users/gregor/Projects/hospitalrun/frontend/node_modules/hospitalrun-server-routes/routes/30-auth.js:134
      if (body.deleted) {
              ^

TypeError: Cannot read property 'deleted' of undefined
    at /Users/gregor/Projects/hospitalrun/frontend/node_modules/hospitalrun-server-routes/routes/30-auth.js:134:15
    at Request._callback (/Users/gregor/Projects/hospitalrun/frontend/node_modules/nano/lib/nano.js:241:7)
    at Request.self.callback (/Users/gregor/Projects/hospitalrun/frontend/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/gregor/Projects/hospitalrun/frontend/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/gregor/Projects/hospitalrun/frontend/node_modules/request/request.js:988:12)
    at emitNone (events.js:72:20)
```

**Screenshot:**

![screen shot 2016-05-20 at 15 37 39](https://cloud.githubusercontent.com/assets/39992/15439974/d54acc9e-1ea0-11e6-9da7-0eb137f039f3.png)

**Steps to reproduce:**

- Open Google Chrome Private mode to make sure you have a clear cache
- start server with `npm start`
- Open app at [http://localhost:4200](http://localhost:4200)
- Login with `hradmin` and `test`

**OS and Browser:**

- Chorme Version 50.0.2661.102 (64-bit)
- Mac 10.11.4

- Latest version of `master` (2adfdea). 
- node v4.2.2, npm 3.8.6

**Comment by jkleinsc** [comment]
@gr2m did you run the script `./script/initcouch.sh`?

That code could be more bullet proof, but I'm trying to figure out why/how you got that error in the first place.

Were you able to login at some point then?

**Comment by gr2m** [comment]
yes I run it before (with admin username / password). Tried to run it again, got conflict errors as expected:

```
$ ./script/initcouch.sh admin funkyfresh
{"ok":true}
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
{"ok":true}
{"error":"file_exists","reason":"The database could not be created, the file already exists."}
{"ok":true}
"{couch_httpd_oauth, oauth_authentication_handler}, {couch_httpd_auth, proxy_authentification_handler}, {couch_httpd_auth, cookie_authentication_handler}, {couch_httpd_auth, default_authentication_handler}"
"true"
{"error":"conflict","reason":"Document update conflict."}
```

**Comment by jkleinsc** [comment]
@gr2m Were you able to login after the first time?

**Comment by gr2m** [comment]
yes, looks like the `POST /_session` request goes through. Here are all requests as har: https://gist.github.com/a4cf5f284ad42b11468712abcdcefbde
