### ISSUE TITLE
Printing a patient record

### ISSUE THREAD

**Issue by tangollama** [HospitalRun/hospitalrun-frontend#476]
The standard, out-of-the-box printed version of a patient record, including their history needs to be added to the primary patient summary screen, perhaps as a button opposite to the "Add Note" action @jglovier?

<img width="866" alt="screen shot 2016-05-22 at 2 58 49 pm" src="https://cloud.githubusercontent.com/assets/929261/15455835/bb1a0824-202d-11e6-9cbd-e32fa6520990.png">

For starters, the printed report should involve:

- [ ] A standard header that includes customizable language around the fact that this report is for authorized person(s) only
- [ ] A printable version of the upper section "patient summary" fields (as shown in the screenshot above)
- [ ] A list of the patient history, streatching as many pages as needed

**Comment by dapierce** [comment]
I'm interested in this project and would like to take on this issue to start! I have determined how to remove the left padding for print, and will look into the header and print formatting in the next few days.
