### ISSUE TITLE
After login, nothing happens

### ISSUE THREAD

**Issue by gr2m** [HospitalRun/hospitalrun-frontend#478]
follow up for https://github.com/HospitalRun/hospitalrun-frontend/issues/475. I updated to latest master and updated all dependencies. The server does not crash anymore, but now nothing happens after signing in

![hospitalrun-nothing-after-login](https://cloud.githubusercontent.com/assets/39992/15484978/c05f2052-210a-11e6-9a8e-f5db3344f11b.gif)

**Comment by pgte** [comment]
I also have this issue. By digging into devtools, I could see that the chkuser response is:

```js
{"error":true,"errorResult":{"message":"Name or password is incorrect.","stack":"Error: Name or password is incorrect.\n    at Request._callback (/Users/pedroteixeira/projects/hospitalrun/hospitalrun-frontend/node_modules/nano/lib/nano.js:248:15)\n    at Request.self.callback (/Users/pedroteixeira/projects/hospitalrun/hospitalrun-frontend/node_modules/request/request.js:200:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/Users/pedroteixeira/projects/hospitalrun/hospitalrun-frontend/node_modules/request/request.js:1067:10)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/Users/pedroteixeira/projects/hospitalrun/hospitalrun-frontend/node_modules/request/request.js:988:12)\n    at emitNone (events.js:91:20)","name":"Error","error":"unauthorized","reason":"Name or password is incorrect.","scope":"couch","statusCode":401,"request":{"method":"GET","headers":{"content-type":"application/json","accept":"application/json"},"uri":"http://XXXXXX:XXXXXX@localhost:5984/_users/org.couchdb.user%3Aadmin"},"headers":{"date":"Tue, 24 May 2016 15:22:36 GMT","content-type":"application/json","cache-control":"must-revalidate","statusCode":401,"uri":"http://XXXXXX:XXXXXX@localhost:5984/_users/org.couchdb.user%3Aadmin"},"errid":"non_200","description":"couch returned 401"}}
```

Before the chkuser request, the POST /_session request succeeded (CouchDB replied with `{ok: true, ...}`... 


BTW, I'm trying this with Node 4 and 6.

**Comment by jkleinsc** [comment]
@gr2m @pgte  I cannot duplicate this.  What version of couch are you using?
One thing to check is the server/config.js file to verify that the 
`couchAdminUser` and `couchAdminPassword` are correct for your couch install.
By default these values are couchAdmin/test, but if you already had couch running/setup with an admin party, the initcouch.sh script will not create this user.  In that case, you can use hradmin/test or any other admin user that has been created.

**Comment by pgte** [comment]
@jkleinsc yup, that was it, solved for me.
Sorry about this.

**Comment by gr2m** [comment]
yup, same here. At what point does `couchAdminUser` and `couchAdminPassword` get set? I’ve run `./script/initcouch.sh USER PASS` with USER and PASS of an existing admin account in my local CouchDB – maybe that was the problem?

**Comment by jkleinsc** [comment]
@gr2m `couchAdminUser` and `couchAdminPassword` do not get set by the script.  They are just set to default username/pw that the script creates.  The README needs to be updated to reflect this.

**Comment by chobberoni** [comment]
@jkleinsc any reason as to why i'd be getting this error?

![image](https://cloud.githubusercontent.com/assets/4432363/18735478/fa56a262-8032-11e6-917b-26048460c301.png)

In, the couchdb local tool, it shows that `couchadmin` and `test` are valid, but the app doesn't recognize them for some odd reason.

**Comment by jkleinsc** [comment]
@chobberoni can you click on the headers tab and see what url it is trying to go to?

**Comment by chobberoni** [comment]
@jkleinsc 

this is what I get back in the Headers tab (for _session response):
![image](https://cloud.githubusercontent.com/assets/4432363/18738734/442e8e52-8053-11e6-86da-d789ce051c04.png)


and for (chkuser response):
![image](https://cloud.githubusercontent.com/assets/4432363/18738753/6f0b36ac-8053-11e6-90e1-e17b36dec15e.png)

and on the Fauxton page for couchdb it shows that I can verify things from the DBs end:
![image](https://cloud.githubusercontent.com/assets/4432363/18738791/b9c83dfc-8053-11e6-91e5-40cb3f9e2b0e.png)

**Comment by jkleinsc** [comment]
@chobberoni In fauxton can you verify that there is a database called main and another one called config?  Also, in the _users db there should be a user with the id org.couchdb.user:hradmin
If any of these are missing, you will need to run script/initcouch.sh: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/script/initcouch.sh

**Comment by chobberoni** [comment]
@jkleinsc I got it to work by manually creating the `_users` db in fauxton.
The main and config dbs were already in there. 

However, the `initcouch.sh` script is still not running properly (oh well for now) -- here's the output for now:
![image](https://cloud.githubusercontent.com/assets/4432363/18740659/b24af82e-805f-11e6-9b4e-272f4d167a31.png)


thanks!!! <3

**Comment by vpeg49** [comment]
> @chobberoni you fixed your problem? I'm getting the same error here using "hradmin" "test".
> 
> ![image](https://user-images.githubusercontent.com/4200487/38248892-c1ca2d66-3741-11e8-9ffd-127d0300df5f.png)

@JoseCage  i'm getting this same error, do yoy fixed it?

**Comment by JoseCage** [comment]
> @JoseCage I'm getting this same error, do yoy fixed it?

Not. I didn't find a solution.

**Comment by vpeg49** [comment]
> > @JoseCage I'm getting this same error, do yoy fixed it?
> 
> Not. I didn't find a solution.


i added admin and hradmin as admin users on fauxton's main db permissions, and it's working now

http://127.0.0.1:5984/_utils/#/database/main/permissions

**Comment by JoseCage** [comment]
> i added admin and hradmin as admin users on fauxton's main db permissions, and it's working now

Great. I'm not using anymore. But i'll remember if i need again. Thanks
