### ISSUE TITLE
Improve load database view by adding more data

### ISSUE THREAD

**Issue by jglovier** [HospitalRun/hospitalrun-frontend#483]
I just ran through loading a set of 6 databases from an anonymized dump. One of the major painpoints was that even with just six files, it was hard to remember which one I had just loaded (and to know which one to load next) because the load confirmation doesn't show the filename which was just uploaded, or a persistent history of any recent uploads.

**Expected behavior:**
- [ ] loading databases should show confirmation of what you just loaded (i.e. the filename)
- [ ] loading databases should show a persistent, recent history of what was loaded

**Actual behavior:**
- loading a database file just shows a generic load success message (which is oddly worded), and a start time and end time, as well as some info about "Docs read" and "Docs written", which was confusing because with each of the files I loaded the number there was 0 each time.

**Steps to reproduce:**

Go to `Administration > LoadDB` and load a database file (this can be reproduced with the `sample-data.txt` file in the project root).

**Screenshots (if applicable):**

<img width="1001" alt="screenshot 2016-05-31 21 47 00" src="https://cloud.githubusercontent.com/assets/1319791/15695851/54d7e1fa-2779-11e6-9ac9-89644cf01226.png">

**OS and Browser:**
- OSX, Chrome

**Comment by xmudrii** [comment]
I'm trying now to make it works, will report how it goes, if problem arises :)

**Comment by jscottchapman** [comment]
@xmudrii It looks like you are working on this one. Is that right? Just wanted to make sure two people aren't working on the same issue unknowingly.

**Comment by xmudrii** [comment]
@jscottchapman I finished first part of it, showing file name after it is imported. It is in #685 .
I tried second task, but it was not going very well, also I'm bit out of time, so if you want to take over it, do it. :+1: :) Just write so I know someone another is doing it

**Comment by emadehsan** [comment]
@jglovier 

>  loading databases should show a persistent, recent history of what was loaded

Quick question about this problem's design decision:
I think the information must be permanently stored in CouchDB. Are the following fields enough to distinguish each loading? What else must be saved?
* `filename`
* `loadedBy`
* `startTime`
* `endTime`
* `docsRead`
* `docsWritten`

**Comment by jkleinsc** [comment]
@emadehsan I think we could just keep this in memory, eg in the controller keep track of recently loaded files.  They would disappear when you close the browser, but would be visible during your current "session".

**Comment by afreem66** [comment]
Is this still open and/or being worked on?

**Comment by tangollama** [comment]
@afreem66 yes. @jglovier opened this originally. He might be able to provide more color if you need it.

**Comment by afreem66** [comment]
Seems pretty reasonable, just wondering why @xmudrii PR was closed?

**Comment by xmudrii** [comment]
‎@afreem66 PR was merged, but due to commit message PR was closed. You can check it out here https://github.com/HospitalRun/hospitalrun-frontend/commit/dac2eb72acb17289d70543c06b0f5531697f6748

This PR only implemented "half" of issue. It shows imported file name, but there is no history - once you refresh page, history will be lost. However, I don't know current status of issue.
