### ISSUE TITLE
 Keep all translation files up to date

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#493]
Keeping translations up to date, i am thinking of using https://www.transifex.com/ to translate our main english JSON file, using their community. currently there will be manual effort involved. i am not sure if anyone has an issue with this.

@jkleinsc we should also talk about how the deployment process from master works.

**Comment by billybonks** [comment]
so we should probably build a linter that lints translations files based of master translation file keys and identifies missing keys

**Comment by mqchau** [comment]
Helped by https://github.com/HospitalRun/hospitalrun-frontend/pull/1037
