### ISSUE TITLE
Prune stale translation keys

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#494]
As features are added and removed some translation keys will be become stale, and should be pruned from json file

**Comment by tangollama** [comment]
@billybonks agreed. do you have specific processes that you want to be sure people follow for translations, or is this something that could be put into a linter? That seems to me to be ideal. Thoughts?

**Comment by tangollama** [comment]
If the action here would be to add a linter to the system that validated that all translation keys were referenced (if that's possible), then we can do something with this. If not, we need to document this as part of the contribution guide.

**Comment by mqchau** [comment]
Helped by #1037
