### ISSUE TITLE
Cursor on links appears as a text cursor on Firefox and MS Edge

### ISSUE THREAD

**Issue by tompaana** [HospitalRun/hospitalrun-frontend#496]
**Expected behavior:**
The cursor indicates a clickable object (i.e. link).

**Actual behavior:**
The cursor appears to be a text cursor giving no indication that e.g. clicking a patient name leads to the patient record.

**OS and Browser:**
OS: Windows 10
Browsers:
- Firefox 46.0.1
- Edge

**Comment by mnorbeck** [comment]
This is also present on Chrome 51.0.2704 for Image, Med and Lab Requests, Appointments and  Invoices.  Any place other than a patient record where the patient name and ID is displayed.   On the patient record the cursor is the text insert, but there are no links.

**Comment by Eric-Arellano** [comment]
This is happening on all OS X El Capitan browsers too:
- Safari 9.1.2
- Firefox 47.0.1
- Chrome 52.0.2743

@tompaana please update issue's title to remove "on Firefox and MS edge" - it's not a browser specific issue.

**Comment by Eric-Arellano** [comment]
### Where bug happens
Lists of records, e.g. patient list, labs list, do correctly render the pointer cursor; however, several other links show the text cursor (Chrome default cursor) on other links, i.e. the patient's name/ID, and in certain tables.

<img width="1280" alt="text-cursor_screenshot" src="https://cloud.githubusercontent.com/assets/14852634/18071307/5ea0b81e-6e1a-11e6-9bb7-bd156c1efbb4.png">

**Comment by Eric-Arellano** [comment]
FYI @tangollama I've started to work on this today. Found a very basic [fix](https://github.com/Eric-Arellano/hospitalrun-frontend/commit/c40d00c4380b9605e0d97919a057aec5551e9eaa), however it produces a lot of false positives. Going to try to find a better solution tomorrow/this week.

**Comment by jscottchapman** [comment]
@Eric-Arellano @tangollama Is this "in progress?"

**Comment by Eric-Arellano** [comment]
@jscottchapman just submitted [PR](https://github.com/HospitalRun/hospitalrun-frontend/pull/686) to fix this basic issue, but it opens up a new issue of false positives. Might be able to build off of my change?

P.S. sorry for my late reply! I hadn't seen this message

**Comment by natbityou** [comment]
FYI @tangollama I am currently working on a fix for this issue that builds on the feedback in Eric-Arellano's PR; I will have a new PR ready soon.

**Comment by natbityou** [comment]
@tangollama here's a [PR](https://github.com/HospitalRun/hospitalrun-frontend/pull/1374) to resolve this issue. What do you think?
