### ISSUE TITLE
Cannot find module 'sw-toolbox/sw-toolbox.js'

### ISSUE THREAD

**Issue by chair91** [HospitalRun/hospitalrun-frontend#497]
**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by chair91** [comment]
When I start hospitalrun in nitrous it says "Cannot find module 'sw-toolbox/sw-toolbox.js'"

How can I solve this issue ?

I also try on ubuntu it says the same

Please provide me a solution

Thanks

**Comment by alexchan7432** [comment]
Hi chair91,
I had this issue as well.  This is what I wrote in the slack channel.

> there is a dependency  "broccoli-serviceworker": "0.0.9" which in turn has a dependency "sw-toolbox": "^3.1.1".  This semantic versioning caused it to download sw-toolbox: 3.2.0 which is missing sw-toolbox.js and sw-toolbox.map.json in the sw-toolbox directory.  I manually did npm install sw-toolbox@3.1.1 to override this and was able to start the server

**Comment by chair91** [comment]
Hi Alex
Thanks for the solution  . I will try it tonight

**Comment by chair91** [comment]
Hi Alex 
It's work now 
thanks

**Comment by jkleinsc** [comment]
@chair91 this is now fixed.  I'm also going to make sure that broccoli-serviceworker gets updated.  I know the author :wink:.
