### ISSUE TITLE
hospitalrun loading for long time

### ISSUE THREAD

**Issue by chair91** [HospitalRun/hospitalrun-frontend#500]
**Expected behavior:**

**Actual behavior:**

**Steps to reproduce:**

**Screenshots (if applicable):**

**OS and Browser:**

**Comment by chair91** [comment]
After starting hospital run using command npm start and go to localhost:4200

it show loading page for long time (not show hospital run welcome page)

How can I solve this ?

Thanks in advance

**Comment by jkleinsc** [comment]
@chair91 I believe you ran into an issue with broken dependencies that has now been fixed.  
Pull the latest from github, then do the following in the hospitalrun frontend directory:
```rm -rf node_modules bower_components dist tmp```
```npm install```
```bower install```

**Comment by chair91** [comment]
Thanks I will try

**Comment by chair91** [comment]
it's work now 

thanks
