### ISSUE TITLE
Add patient copay field

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#51]
Need a field to track patient responsibility. In the Philippines this field is called Patient counterpart.

**Comment by jkleinsc** [comment]
While bigger than this issue, when we implement this, we should add [ember-i18n](https://github.com/jamesarosen/ember-i18n) so that we can customize the label for the Philippines

**Comment by jkleinsc** [comment]
#141 is the ticket for internationalization

**Comment by tangollama** [comment]
@jkleinsc can we close this?

**Comment by jkleinsc** [comment]
@tangollama I don't think we ever added this field

**Comment by wolfieorama** [comment]
my proposed plan is to add a field to capture whatever amount the patient
contributes on top of what the other parties take responsibility of.
My thought is to have it as a  non-required field handling different currencies (number
type) -- an addon may be to handle different currencies

**Comment by taras** [comment]
@wolfieorama your plan looks good. 

I would suggest that we break this into 2 parts:
1. add this copay number field
2. make it work properly for with currency indicator

For 1, we might want to use the code that was introduced in #668
For 2, we need to figure out how to handle currency across the entire app (we might need a localize currency format)

**Comment by jkleinsc** [comment]
@wolfieorama the intention is that we add a configuration to set a system wide currency, so any monetary values put into the system would be in that currency.  I don't think HospitalRun should try to support multiple currencies in one location.

**Comment by wolfieorama** [comment]
@jkleinsc @taras I will jump on another issue as that is sorted

**Comment by jkleinsc** [comment]
I am closing this issue as this enhancement request is satisfied by the custom forms feature.
