### ISSUE TITLE
New Feature: Enable user feedback from the user interface

### ISSUE THREAD

**Issue by morsh** [HospitalRun/hospitalrun-frontend#517]
**Background**
Currently, there is not way for the users of the system to communicate:
- Is the current screen understandable, has bugs, missing options
- Suggestion of new/missing features on a certain page or the system in general
- Is the user satisfied with the system and is there something he would want to communicate back to the developers

**Expected behavior:**
Add a basic ability to the system to click like\dont like or happy\sad smiley to communicate their satisfaction\dissatisfaction from a certain page.
Once they click on that icon, the choice will be stored in the DB and the user will be offered the option to elaborate in a small popup under the icon on why he pressed that button.

The feedback data can be stored in a separate offline database or the same database. Once the system goes online, the feedback data should be sent to the an online service (not the online database for the system).

A nice addition would be for the user to follow that issue in some way to see how it is being handled.

**Comment by BogdanAlexandru** [comment]
Suggestion: the feedback button could go to a bottom bar. The app currently extends all the way to the bottom of the page, and the URL preview from Chrome that shows up when you hover on links covers part of the menu. This results in this slightly annoying behavior (gif):

![Imgur](https://i.imgur.com/kn7KQnw.gif)

Something like this, but with a proper design:

![Imgur](https://i.imgur.com/AEB1Kyi.png)

The bar could also contain something like a copyright notice, for extra legitness points 👍 

> Add a basic ability to the system to click like\dont like or happy\sad smiley to communicate their satisfaction\dissatisfaction from a certain page.

I think a nicer approach would be for the feedback button to open a simple popup window with a text box for a message, and maybe three mood smileys: happy, neutral and sad. I'd say most of the feedback I send to products is in the neutral area ("I can't really decide whether I like this or not, but here's my thoughts"), and seeing a program that forces me to either like or dislike something makes me feel like my feedback (that doesn't fit in the like/dislike category) is pointless and will be ignored.

**Comment by tangollama** [comment]
@BogdanAlexandru Another really good recommendation. Same question here. Do you want to work this issue or shall I turn this into a Help Wanted issue?

**Comment by BogdanAlexandru** [comment]
@tangollama I can pick this up right after I'm done with the dropdown changes tracked by https://github.com/HospitalRun/hospitalrun-frontend/issues/1245, which should not take longer than a couple of days.

**Comment by BogdanAlexandru** [comment]
> Once the system goes online, the feedback data should be sent to the an online service (not the online database for the system).

Do we want the feedback to always be relevant solely to the development team? Could there be a case where a HospitalRun user would want to send feedback that can be followed upon at the site (i.e. by the administrator of the HR instance)?

Aside from that, any recommendations for a service that could receive and store all the user feedback? The minimal feature set would be to accept entries, store them and allow us to query. Can't think of any free (even for open source) services that would handle all the data for us.

One quick and free approach would be to follow the example of Microsoft and let users tweet their feedback. But with this coming at the expense of forcing the users to create a Twitter account, and not only that but also forcing their feedback to be both public and non-anonymous... I'm not sure it's the right path.
