### ISSUE TITLE
Medication/inventory typeahead issues

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#519]
**Expected behavior:**
If multiple values matched the typed in value, they should all display, perhaps via a scrollbar
**Actual behavior:**
Unless you start typing more specific text, the typeahead just picks the first 5 matches without scrolling.  
**Steps to reproduce:**
Go to medication/new request and type in a single letter into the medication type ahead
**Screenshots (if applicable):**
<img width="711" alt="screen shot 2016-06-18 at 5 42 04 pm" src="https://cloud.githubusercontent.com/assets/609052/16172236/22f4b35a-357c-11e6-9d7c-bc9097c1fc9b.png">
The first typeahead didn't show "Hyoscine 10mg tablet (Buscopan) - m00177 (104 available)"
<img width="701" alt="screen shot 2016-06-18 at 5 41 42 pm" src="https://cloud.githubusercontent.com/assets/609052/16172239/2e8e9744-357c-11e6-8509-5fe696cee7f2.png">

**OS and Browser:**
All

**Comment by billybonks** [comment]
i presume this happens in all these components across the application

**Comment by cmwebby** [comment]
If no one is working on this I'm happy to make a fix for it and do a PR? @tangollama

**Comment by billybonks** [comment]
@cmwebby no one seems to be working on it so go ahead 👍

**Comment by jkleinsc** [comment]
@cmwebby... It is yours to work on... I noticed you closed your PR though?

**Comment by cmwebby** [comment]
@jkleinsc I managed to sort out the typeahead but it wasn't passing any of the tests on my machine or Travis CL, so I've closed it and will submit a hopefully better one when I've discovered why
