### ISSUE TITLE
Non admins cannot add procedures

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#526]
**Expected behavior:**
A non-admin with the capability to add a procedure (such as a doctor), should be able to add a procedure
**Actual behavior:**
A non-admin with the capability to add a procedure (such as a doctor) doesn't see a button to add a procedure.
**Steps to reproduce:**
1. Login as doctor
2. Go to patient 
3. Add visit
4. Click on Add Procedure
5. Add button does not appear at bottom of screen
**Screenshots (if applicable):**
<img width="968" alt="screen shot 2016-06-21 at 4 56 27 pm" src="https://cloud.githubusercontent.com/assets/609052/16245958/25c2f676-37d1-11e6-867c-6cf4e5433047.png">

**OS and Browser:**
All

**Comment by alexpelan** [comment]
I can look into this one
