### ISSUE TITLE
lint label properties of htmlbars

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#542]
Currently the handlebars linter only lints for bare strings. Bare strings may be present under a `label=` property of HTMLbars. this should be linted as well.

The best solution i think is to add a rule to the the linter then activate it here.

**Comment by billybonks** [comment]
https://github.com/rwjblue/ember-template-lint/issues/99

**Comment by mdarmani** [comment]
@tangollama I am looking into this one today

**Comment by mdarmani** [comment]
Here are the rules of using ember-template-lint: https://github.com/rwjblue/ember-template-lint/#rules

**Comment by mdarmani** [comment]
Didn't come further with this today. Changes need to be made to the [Ember Template Lint](https://github.com/rwjblue/ember-template-lint/ ) project to accommodate the change.

**Comment by tangollama** [comment]
@mdarmani are you still interested in this issue? If not, I'll move it back to Help Wanted.
