### ISSUE TITLE
Refactor translations file to match model setup

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#547]
In order to have scalable, maintainable and clean translation files we should, model them according to their data models.

This means:

Every model should have it's name translated in singular and plural,
Every attribute should have a translation 1 to 1 relationship.
Model names could share the same namespace as attributes, but that could cause conflicts, so we would rather keep them seperate.

Take the following application models:
```
Model = Ember.Data.Model.extend({
  name: DS.string(),
  age:    DS.number(),
})
Model = Ember.Data.Model.extend({
  surname: DS.date(),
  age:    DS.number(),
})
````
The resultant translation file would look as follows:
```
models: {
  patient: {
    names: {
       singular: 'patient'
       plural: 'patients
    },
    labels: {
        firstName: 'First Name',
        lastName: 'Last Name'
     },
     placeholders: {
      firstName: 'Enter your first bame',
      lastName: 'Enter your first last Name'
     },
     hints: {
       firstName: 'This is the name that your parents gave you, unless you changed it',
       lastName: 'this is the name you share with your family, , unless you changed it'
     }
  },
  inventory: {
    names: {
      singular: 'inventory'
      plural: 'inventory items'
    },
    labels: {
      default: {
        name: 'Name',
        quantity: 'Quantity'
      }
    },
    placeholders: {
      name: 'Name of inventory item',
      quantity: 'Quantity of item'
     },
     hints: {
       name: 'What do you call',
       quantity: 'Go to storage and count :)'
     }
  }
}
```

**Comment by jkleinsc** [comment]
@billybonks I think I'm in favor of this, but I think we should maybe make the prefixing a little clearer.  
For example the path for attributes for the patients would be something like `models.patient.name`.  For example:
```javascript
models: {
  patient: {
    firstName: 'First Name',
    lastName: 'Last Name'
  },
  inventory: {
    name: 'Name',
    quantity: 'Quantity'
  }
}
```

The other thing to keep in mind is will it make sense for translators who aren't developers?

**Comment by billybonks** [comment]
So i am up for your prefixing, if we agree, that the models won't share strings for their attributes. like `startDate` may appear in multiple places, but each place will have it's own string. There is definitely benefit in that, because it will allow each model attributes label to not be bound to another. just means more translations. but in theory if we use transfix it will help with that :).

**Comment by jkleinsc** [comment]
@billybonks I absolutely agree we shouldn't share strings for attributes.  Reusability is great for programming, but not so great for translations because context matters.

**Comment by billybonks** [comment]
cool ill update the issue with this :)

**Comment by billybonks** [comment]
@jkleinsc i updated the issue description based on https://gist.github.com/billybonks/925a37e70dcde840a4205d065ea937e7

**Comment by billybonks** [comment]
i left default in in case we ever wanted to expand
