### ISSUE TITLE
Translate bare strings in mixins

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#548]
The following mixin files have bare strings that need to be translated
  - [ ] result-validation.js
  - [x] navigation.js
  - [ ] fulfill_request.js
  - [ ] dob-days.js

**Comment by jkleinsc** [comment]
@billybonks navigation.js automatically translates the strings there in the `localizedNavItems` function, so it doesn't need to be translated.

**Comment by billybonks** [comment]
cool 👍 

@jkleinsc the following strings don't seem to be propagated to the ui ?

https://github.com/billybonks/hospitalrun-frontend/blame/master/app/mixins/fulfill-request.js#L100

https://github.com/billybonks/hospitalrun-frontend/blame/master/app/mixins/fulfill-request.js#L223

**Comment by jkleinsc** [comment]
@billybonks in regards to the strings not being propagated to the ui, you are correct - the only place you would see them is in the ember inspector if you were looking at promises you would see the text there.
