### ISSUE TITLE
Page Titles

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#551]
We currently assign page titles manually, instead we can make the following abstract classes, automatically figure out the page title, using the route name space.

  -AbstractIndexRoute
  -AbstractEditRoute
  -AbstractModuleRoute
  -AbstractDeleteController

i.e we have a titles.js translation that follows the same name spacing as the routes in the application. so for example:

~~inventory.index the page title will be under either `titles.inventory.index = 'asd'` or `inventory.index.titles = 'asd'`.~~

inventory.index the page title will be under `inventory.index.title = 'asd'`

  the advantage of this is that the:
- CI will throw and error if a page title translation doesn't exist
- If needed the developer can always override the existing behaviour
- keeps title, translations in a tidy format for ever :).
- automatically fix the remaining titles to be translated :).

**Comment by tangollama** [comment]
I like this. @jkleinsc what do you think?

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.40&pv=9.3.1&source=email_footer_2]
On Sun, Jul 3, 2016 at 5:04 AM, Sebastien Stettler <notifications@github.com> wrote:
We currently assign page titles manually, instead we can make the following abstract classes, automatically figure out the page title, using the route name space.

-AbstractIndexRoute
-AbstractEditRoute
-AbstractModuleRoute
-AbstractDeleteController

i.e we have a titles.js translation that follows the same name spacing as the routes in the application. so for example:

inventory.index the page title will be under either titles.inventory.index = 'asd' or inventory.index.titles = 'asd' .

the advantage of this is that the:

 * CI will throw and error if a page title translation doesn't exist
 * If needed the developer can always override the existing behaviour
 * keeps title, translations in a tidy format for ever :).
 * automatically fix the remaining titles to be translated :).

**Comment by jkleinsc** [comment]
@billybonks I think this is a great idea.  I would prefer the path to be` inventory.index.title = 'asd'`

**Comment by billybonks** [comment]
ye that is better 👍, also allows us to use route structure for other things if needed

**Comment by taras** [comment]
@wolfieorama would like to work on this issue. I'd like to assign it to him. No sure why it's not letting me.

**Comment by yasirunilan** [comment]
can i work on this?

**Comment by jkleinsc** [comment]
@yasirunilan @wolfieorama is currently assigned to this issue.  

@wolfieorama are you working on this?

**Comment by wolfieorama** [comment]
@jkleinsc yes should be next in line

**Comment by yasirunilan** [comment]
I'm working on it

**Comment by wolfieorama** [comment]
cool no worries

**Comment by tangollama** [comment]
@yasirunilan any progress here?

**Comment by yasirunilan** [comment]
@tangollama sorry couldn't do it
