### ISSUE TITLE
Translations for components

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#557]
i am not sure what is the best method to do this

<img width="1016" alt="screen shot 2016-07-07 at 8 44 38 pm" src="https://cloud.githubusercontent.com/assets/1640136/16665389/b9bc5660-4483-11e6-8b8a-576cbe82ff11.png">

currently i was thinking

```
  components: {
    'charges-by-type-tab':{
      charges: 'charges'
    }
```
for this template

```
<a href={{tabHref}} role="tab" data-toggle="pill">{{pricingType}} charges</a>
```

which would look like this

```
<a href={{tabHref}} role="tab" data-toggle="pill">{{pricingType}} {{t 'charges-by-type-tab.charges'}}</a>
```

**Comment by jkleinsc** [comment]
@billybonks works for me.

**Comment by billybonks** [comment]
👍
