### ISSUE TITLE
Handle 3rd party payments made after final bill

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#57]
EG We mark 1000 covered by the Hospital, but 3rd party gives us 500 after the fact.

**Comment by tangollama** [comment]
HospitalRun's billing system is not meant to be the all-encompassing, system of record for financial interactions with a patient. It has features for defining a bill and collecting simple actions about payments and deposits. Once an invoice transitions out of the system into a more complicated finance system, we need to ensure that further financial actions cannot be taken on the invoice.
What we need is a new state on an Invoice called Closed. That breaks down into the following changes:

1. Add a boolean field to the invoice object that can be programmatically or explicitly set, called "Closed." A transfer process that moves Invoices into an outside financial system might set an invoice (or a batch of invoices) to closed.
2. Allow an invoice to be explicitly set to Closed. I suggest a button "Set to Closed" that sets the closed flag.
<img width="459" alt="screen shot 2016-02-13 at 2 53 06 pm" src="https://cloud.githubusercontent.com/assets/929261/13030476/90c733a4-d261-11e5-8e74-26c10b217efc.png">
3. Once an invoice is set to closed, payments cannot be added. When an invoice is set to closed, remove the "Add Payment" button. Also remove the "Update" button.
4. When an invoice is in Closed state, we need to provide a way for an accountant to revert to an unclosed state. Thus, add a button on closed invoices called "Reopen" which will unset the boolean closed flag.

**Comment by marcorosas1991** [comment]
@jkleinsc @tangollama I can work on this issue.
