### ISSUE TITLE
Patient ID can be made the same

### ISSUE THREAD

**Issue by cmwebby** [HospitalRun/hospitalrun-frontend#572]
**Expected behavior:**
The Patient ID should be completely unique to the patient. Although the database has its own unique id for each patient and the patient ID is just a user-friendly one, it should still be completely unique to avoid mixing up patients. 

**Actual behavior:**
When making a new patient the Patient ID can be edited to a patient ID  that already exists. 

**Steps to reproduce:**
- Make a new patient and take note of the ID
- Make another patient and edit the ID to be the same

**Screenshots (if applicable):**
![patient id](https://cloud.githubusercontent.com/assets/15896226/16869670/e755f944-4a75-11e6-9ad5-69004fdf3989.png)

**OS and Browser:**
OS - Windows 10
Browser - Version 51.0.2704.103 m

**Comment by JSchneidler** [comment]
I'll see if I can tackle this. Would it be acceptable to just make an API request when the Id field is changed to check if it has already been used?

**Comment by jkleinsc** [comment]
Thanks @JSchneidler !  If you look at app/mixins/patient-id, there is code there that generates this id on a new record via the `generateFriendlyId` function.  That function queries a couch view called `patient_by_display_id`.  You can query this same view to find out if an id is being used.

**Comment by taras** [comment]
@JSchneidler are you able to look at this issue? If you are, I'd like to assign it to you. Otherwise, we'll assign it to someone else. 

Please, let us know if you're able to work on it.

**Comment by gnowoel** [comment]
@taras Since I'm working on a related issue (#485) , I'd be happy to take this if no one else does.

**Comment by mdarmani** [comment]
Is this assigned? I don't see anyone assigned yet.

**Comment by jkleinsc** [comment]
@mdarmani @gnowoel is working on this.

**Comment by yasirunilan** [comment]
is this one assigned? I would like to work on this.

**Comment by jkleinsc** [comment]
@yasirunilan @gnowoel is working on this one.

**Comment by mdarmani** [comment]
@jkleinsc Shouldn't they be assigned to this? I am looking for a Hackathon story to pick up. Or van we work on this as a trio?

**Comment by jkleinsc** [comment]
@mdarmani I can't assign issues to outside contributors, so our workflow for issues is to remove the help wanted tag once someone starts working on it, so if you are looking for something to work on, take a look at the help wanted issues:
https://github.com/HospitalRun/hospitalrun-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22Help+Wanted%22

**Comment by mdarmani** [comment]
@jkleinsc Right thanks for the reply. Is this software currently being used by Cure International in Dubai? Is it ready to use? Seems like more development is necessary.

**Comment by jkleinsc** [comment]
@mdarmani This software is currently being used by some CURE International Hospitals, but not the one in the UAE.  As far as ready to use, from our perspective, we are trying to get to a 1.0 by the end of the year, which we would consider in a state for general use.  You can use it as is right now, but we are actively adding new features.
