### ISSUE TITLE
Insurance number

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#58]
Philippines needs to track a PhilHealth number.  Other locations may need to track insurance number(s).

**Comment by jkleinsc** [comment]
May need to address in invoices/billing as well

**Comment by jkleinsc** [comment]
We should be able to implement insurance fields as generic fields and then use [ember-i18n](https://github.com/jamesarosen/ember-i18n) to customize labels for the Philippines (see #141)

**Comment by tangollama** [comment]
@jkleinsc same here? Did the Internationalization address this?

**Comment by jkleinsc** [comment]
@tangollama Not sure we added this or not

**Comment by jkleinsc** [comment]
Closing this issue because custom forms satisfies this enhancement request.
