### ISSUE TITLE
Linters

### ISSUE THREAD

**Issue by charlespeters** [HospitalRun/hospitalrun-frontend#596]
the simple long loved jscs is being end of life'd and consolidating with eslint. this project is using dockyard's ember-suave. they've started working on an [eslint port](https://github.com/DockYard/eslint-plugin-ember-suave) of it; it's still experimental but worth trying. 

**Expected behavior:**  keeping the code style focused and unified

**Actual behavior:** deprecation warnings

**Steps to reproduce:** being dumb enough (like me) to update your global installation of jscs.

**OS and Browser:** os x 10.11.5 and chrome (atom/vim)

**Comment by jkleinsc** [comment]
@charlespeters are you still interesting in working on this?

**Comment by charlespeters** [comment]
yep will fix tonight!
