### ISSUE TITLE
Don’t force login if offline

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#60]
If a user is offline and not using google auth for login, the user ends up on the login screen

**Comment by mongolianprincess** [comment]
Hi i am new to contribute and hoping to help out with this bug - in terms of not forcing the user to end up on login page when offline, should we display a warning or reroute the user to another offline page? Would appreciate some clarification. thanks!

**Comment by jkleinsc** [comment]
Closing because this issue no longer haapens.
