### ISSUE TITLE
Allow partial offline usage

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#61]
Offline needs to be reconsidered/refactored to allow users to only download what they want and what they have access to.  The original approach pouchdb of pulling down the whole DB just doesn't scale.

**Comment by tangollama** [comment]
@jkleinsc given recent work, is this issue still relevant.

**Comment by jkleinsc** [comment]
@tangollama yes this issue is still relevant.  We need to do some server work for HospitalRun/hospitalrun-server#5 but then we also need to update the frontend to work with per-role databases.

**Comment by tangollama** [comment]
@jkleinsc removing Help Wanted on this for now. This feels like a conversation between us before we ask for more help. Assigning to you for the time.

**Comment by jkleinsc** [comment]
Using https://github.com/cloudant-labs/envoy could be a possibility here.  Something to investigate at some point.

**Comment by mnorbeck** [comment]
FYI.  When considering off-line, we need to nail the issue of generating patient IDs while off-line.   @jkleinsc and I kicked this around a bit.   Just noting it here for a reminder.
