### ISSUE TITLE
Result form(s) for labs

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#65]
Right now there is a generic result field for labs.  At some point we should support generation of result forms like the following:
![screen shot 2015-04-06 at 11 41 05 am](https://cloud.githubusercontent.com/assets/609052/7006807/f3b24a5a-dc51-11e4-8777-2da4397ad9c8.png)

**Comment by tangollama** [comment]
The same technology solution we need for #90 is what we need here. Form-builder capability.

**Comment by tangollama** [comment]
@taras this is another example of where a configurable form component is needed.

**Comment by jkleinsc** [comment]
@tangollama again we should be able to use this addon for this: https://github.com/toddjordan/ember-cli-dynamic-forms

**Comment by jkleinsc** [comment]
This feature should be implemented using the custom-form component available in the app:
https://github.com/HospitalRun/hospitalrun-frontend/wiki/Custom-Form-Component

**Comment by jkleinsc** [comment]
This feature can be implemented by extending the custom forms feature to work with labs.  This means doing the following:
1. Add a new form type to https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/admin/custom-forms/edit/controller.js#L77-L82 
2. Modify https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/labs/edit/route.js to setup custom forms for new objects.  
```js
  customForms: inject.service(),
 
  getNewData() {
    let customForms = get(this, 'customForms');
    let newData = {
      customForms: Ember.Object.create()
    };
    return customForms.setDefaultCustomForms(['lab'], newData);
  },
```
3. Add the following to https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/labs/edit/template.hbs:
```hbs
{{custom-form-manager model=model formType="lab"}}
```

This will allow custom forms to be created and added to lab results.
