### ISSUE TITLE
enable block-indentation in .template-lintrc.js

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#673]
We currently have many html indentation errors.

in order to prevent new commits to not have these errors we need to enable `block-indentation`.

To see errors:
1. Open `.template-lintrc.js` in your editor
2. set `block-indentation` to true 
3. ember build

you can fix errors and run `ember build` to see more at any point in time Please note if you don't fix all of them that is ok, open a pr with the ones you fixed omitting the change to `.template-lintrc.js`

**Comment by jmabry111** [comment]
I'll work on this! 😄

**Comment by billybonks** [comment]
👍

**Comment by rahulrana95** [comment]
I wamt to work on it . can you assign me this ?

**Comment by billybonks** [comment]
@rahulrana95 , @jmabry111 has already opened a pull request
