### ISSUE TITLE
Build acceptance test for admin.query

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#688]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `admin.query` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by billybonks** [comment]
i will do this

**Comment by jkleinsc** [comment]
@billybonks we should remove this route.  originally I was using it as a debug tool to query couchdb, but I think the route and corresponding files should be removed at this point.
