### ISSUE TITLE
Build acceptance test for appointments.search

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#689]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing appointments.search acceptance test

for ember new commers the value some.route is the route that's missing you can find them under router.js

**Comment by billybonks** [comment]
i will do this

**Comment by richiethomas** [comment]
Hi, any progress on this?  If not, is it OK if I take this over?
