### ISSUE TITLE
Build acceptance test for inventory.search

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#695]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `inventory.search` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by agileraymond** [comment]
I can work on this issue.

**Comment by jkleinsc** [comment]
@agileraymond it is yours.  Thanks!
