### ISSUE TITLE
Build acceptance test for invoices.search

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#696]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `invoices.search` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by remotevision** [comment]
I can work on this.

**Comment by jkleinsc** [comment]
@remotevision it's yours.  Thanks for contributing!

**Comment by tangollama** [comment]
@remotevision, same here. Any progress? I ask b/c we're getting close to a 1.0 beta release.

**Comment by wildaces215** [comment]
I'll look into this issue!
