### ISSUE TITLE
Build acceptance test for medication.completed

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#697]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `medication.completed` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by billybonks** [comment]
i will do this

**Comment by jscottchapman** [comment]
@billybonks  It looks like you are working on this one.  Is that right?  Just wanted to make sure two people aren't working on the same issue unknowingly.

**Comment by baoqchau** [comment]
Hello @jkleinsc, I would like to help with this issue. Can you show me how should I test this route? Thanks a lot.

**Comment by jkleinsc** [comment]
@baoqchau you should be able to test this by modifying the fulfilling a medication request test here:
https://github.com/HospitalRun/hospitalrun-frontend/blob/master/tests/acceptance/medication-test.js#L66-L93

You can add checks in this test to check medication/completed before and after the medication request is fulfilled.  Does that make sense?
