### ISSUE TITLE
Build acceptance test for patients.admitted

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#699]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `patients.admitted` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by sanketmaru** [comment]
I can work on this.

**Comment by jkleinsc** [comment]
@sanketmaru it's yours to work on.
