### ISSUE TITLE
Build acceptance test for patients.search

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#700]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `patients.search` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by remotevision** [comment]
I can work on this.

**Comment by jkleinsc** [comment]
@remotevision it's yours. Thanks for contributing!

**Comment by emadehsan** [comment]
Since there is no update on this. I want to work on this issue.

**Comment by jkleinsc** [comment]
@emadehsan it is yours to work on.

**Comment by emadehsan** [comment]
[Posting here for community]
@jkleinsc  I have been working on this. I have written the following acceptance test for `patients.search` route:
```
test('search patients', function(assert) {
  runWithPouchDump('default', function() {
    authenticateUser();
    visit('/patients');
    waitToAppear('.view-current-title:contains(Patient Listing)');
    andThen(function() {
      assert.equal(currentURL(), '/patients', 'on patients listing page');

      fillIn('[role="search"] div input', 'Joe');
      click('[role="search"] button');
      waitToAppear('.view-current-title:contains(Search Results for Joe)');
      andThen(function() {
        assert.equal(currentURL(), '/patients/search/Joe', 'should be on patient search list page');
      });
    });
  });
});
```
Asserts work fine but following error shows up. I have no prior experience with ember tests. Could you please explain about fixtures etc? And how to pass this test?

![image](https://cloud.githubusercontent.com/assets/7283624/24532678/aec559ee-15db-11e7-8306-f06528ff3edc.png)

**Comment by emadehsan** [comment]
Hello everyone. I am no longer working on this issue. So if anyone is interested please do it. 
[**If it helps here is the test I wrote **](https://github.com/emadehsan/hospitalrun-frontend/commit/a2fd41101f200179a10db30762bdd6469c67b776)
I am getting the same error as show in the image in my last comment.

**Comment by jkleinsc** [comment]
@emadehsan the issue is that you need to use the patient db dump, not the default dump.  Eg, change:
```js
runWithPouchDump('default', function() {
```
TO:
```js
runWithPouchDump('patient', function() {
```
