### ISSUE TITLE
Build acceptance test for pricing.search

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#701]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `pricing.search` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by remotevision** [comment]
I can work on this.

**Comment by jkleinsc** [comment]
@remotevision it's yours. Thanks for contributing!

**Comment by baoqchau** [comment]
Since there is no update on this, can I work on this issue? @jkleinsc Can you give me suggestion how to test the "search" functions?

**Comment by jkleinsc** [comment]
@baoqchau sure feel free to work on this.  As far as testing, you need to navigate to the module you are testing as the search is context sensitive to which module you are currently on.  So to testing pricing, you need to navigate to /pricing and then put a value in the search text box at the top of the navigation pane and then click on the magnifying glass to execute the search.  Does that make sense?

**Comment by emadehsan** [comment]
@jkleinsc should Elasticsearch be installed & running for Search (in general & for tests)?

**Comment by jkleinsc** [comment]
@emadehsan there is a default search that runs when Elasticsearch isn't installed and that is used for testing.

**Comment by emadehsan** [comment]
For some reason default search is not working on my machine. One searching for a patient for example, it gives `Uncaught TypeError: Cannot read property 'constructor' of undefined` error

**Comment by jkleinsc** [comment]
@emadehsan is that with the latest from GitHub?  If you have the latest, you will need to also run `npm install`

**Comment by emadehsan** [comment]
> @emadehsan is that with the latest from GitHub? If you have the latest, you will need to also run `npm install`

@jkleinsc I have the latest clone of the repo but still **Search doesn't work with CouchDB 2.** When I tested with CouchDB 1.6, the search is working fine.

Can you confirm this?

**Comment by jkleinsc** [comment]
@emadehsan I haven't tested it in CouchDB 2 so it is possible it doesn't work right now.  I think in general for our upcoming 1.0 release we need to back away from CouchDB 2 as there are other issues with using it right now.

**Comment by nzidol** [comment]
Note that the actual search function does not seem to work....
![image](https://user-images.githubusercontent.com/13618973/30413392-e6b3f710-9971-11e7-90f4-112f01396ece.png)
