### ISSUE TITLE
Build acceptance test for procedures.index

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#703]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `procedures.index` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by billybonks** [comment]
@jkleinsc i think this route is never visited so we can close this ?

**Comment by jkleinsc** [comment]
@billybonks yes... though should we remove it from router.js in order to make sure your testing for untested routes works?

**Comment by emadehsan** [comment]
@jkleinsc is there any update on this?

**Comment by jkleinsc** [comment]
@emadehsan there doesn't seem to be a good way to remove an (unused) index route, so I am going to close this issue.
