### ISSUE TITLE
Build acceptance test for visits.index

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#704]
In order to effectively use the no missing translations test, we need to make sure that every page is visited during acceptance tests.

This issue tracks the missing `visits.index` acceptance test

for ember new commers the value `some.route` is the route that's missing you can find them under router.js

**Comment by billybonks** [comment]
@jkleinsc i think this route is never visited so we can close this ?

**Comment by jkleinsc** [comment]
@billybonks yes... though should we remove it from router.js in order to make sure your testing for untested routes works?

**Comment by WilliamJefferies** [comment]
@jkleinsc I will work on this

**Comment by billybonks** [comment]
👍

**Comment by wildaces215** [comment]
I want to work on this as well!
