### ISSUE TITLE
left menu is covering the content

### ISSUE THREAD

**Issue by cybernet** [HospitalRun/hospitalrun-frontend#705]
left menu should automatically hide, or open on a button tap

left menu is covering the content

**Steps to reproduce:**
Open the site in a mobile browser
**Screenshots (if applicable):**
![image](https://cloud.githubusercontent.com/assets/125879/19021765/5f1bddc4-88d1-11e6-947b-25e82ad43d72.png)

**OS and Browser:**
iOS & Safari

**Comment by tvanantwerp** [comment]
Also happens in Chrome DevTools emulation on Windows 10. I don't see any media queries that change how it looks at different breakpoints.

![image](https://cloud.githubusercontent.com/assets/2487968/19045357/64995cdc-8966-11e6-9501-1c255b35b60c.png)

**Comment by WalterC87** [comment]
To fix this, need some kind of button to hide the menu like @cybernet says, I'll be watching this issue today, just finish to install all dependencies to run the project.

**Comment by yasirunilan** [comment]
can i work on this?

**Comment by jkleinsc** [comment]
@yasirunilan you can work on this, but please ping @jglovier on any UI changes you make here.

**Comment by tangollama** [comment]
@yasirunilan are you still interested in this issue? If not, I'll move it back to Help Wanted.
