### ISSUE TITLE
Show error when search fails

### ISSUE THREAD

**Issue by billybonks** [HospitalRun/hospitalrun-frontend#722]
**Expected behavior:**
Show error

**Actual behavior:**
Continues to search

**Steps to reproduce:**
- don't run elastic search
- login as  a non db admin user.
- navigate to users
- enter search term
- press enter

**Screenshots (if applicable):**
<img width="1436" alt="screen shot 2016-10-12 at 12 46 30 am" src="https://cloud.githubusercontent.com/assets/1640136/19279826/8eac44f2-9015-11e6-9ae6-d18ef45730e5.png">

**OS and Browser:**
Mac OS
Chrome

**Comment by yasirunilan** [comment]
can i work on this issue

**Comment by jkleinsc** [comment]
@yasirunilan it is yours to work on.  Thanks!

**Comment by yasirunilan** [comment]
thanks,, i'll be looking into this

**Comment by codebychr1z** [comment]
I assume this hasn't been completed yet? Just looking for a quick task to jump on with my spare time and get my open source github goodness going! 

Thanks

**Comment by jkleinsc** [comment]
@codebychr1z feel free to take a look at this

**Comment by tangollama** [comment]
@codebychr1z are you still interested in this issue? If not, I'll move it back to Help Wanted.

**Comment by jpeterson88** [comment]
I'll pick this one up since it looks like no one is work
