### ISSUE TITLE
Operative plan for patients

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#758]
SEE link below for the updated requirements.

There is a need to create operative plans OpPlans for patients.   

1. There will be only one active or open Operative plan (OpPlan) per patient.
2. Operative plans will be created during a visit, so some UI control is needed to create them on a visit page.  
3. Although OpPlans are created during visits, they should be associated with the patient, and it needs to be very easy to located a patient, then find the OpPlan.   A link to the OpPlan would be on the patient header.
4. For audit and future reporting needs, all OpPlans for a patient do need to be retained. 
5. OpPlan (the page) will display the following data elements:

- Patient ID  (pre-populated, and a link)
- First Name (pre-populated)
- Last Name (pre-populated)
- Diagnosis (a snapshot of the current patient diagnosis, not editable here)
- Operation Description (free form text)
- Procedure List (one or more selections from the list of procedures)
- Case complexity (a number from 1 - 10)
- Surgery Date (with a button to go to calendars, to find a surgery date, this field may be left blank when the OpPlan is first created)
- Surgeon   (picked from the physicians list)
- Required resources  (free form text)
- Instructions upon Admission (free form text - for instructions such as x-rays, labs, blood. etc.)   
- Additional Notes (free form text)
- A create Operation Report (OpReport) button.

6. Doctors will create an OpPlan, and then come back to edit them, prior to the admission visit.
7. OpPlans will be completed or closed when the Operation Report is completed.
8. During an admissions visit, the Doctor would click on the OpPlan in the patient header area, they would then click on the Create OpReport button on the OpPlan.   This would set the OpPlan to closed or completed, and then direct the doctor to a new OpReport, that is prepopulated with data from the Plan.   See the Operation Report requirements for more details on OpReports.

**Comment by mnorbeck** [comment]
Latest requirements are now in Github at:

[]([](https://github.com/HospitalRun/planning/blob/master/Requirements/v1_0/Operative-Plan.md)l)
