### ISSUE TITLE
Add calendar view to appointments

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#760]
We need to add a calendar view.  This calendar view should support a weekly view and a daily view.
Like the appointment search (/appointments/search), you should be able to filter on:
Doctor
Type
Location

On the calendar the following items should display with a link to appointment details:

First Name
Last Name
Doctor to be seen

**Comment by BogdanAlexandru** [comment]
I can take this one if nobody minds.

**Comment by jkleinsc** [comment]
It's yours @BogdanAlexandru.

**Comment by garylm** [comment]
Date Format Question:  Since a lot of countries use a date format of DD/MM/YYYY vs MM/DD/YYYY should the format be an option/setting?

**Comment by jkleinsc** [comment]
@garylm HospitalRun uses [Moment.js](http://momentjs.com/) to do date formatting, in particular we use the locale formatting options available.  See http://momentjs.com/docs/#/displaying/format/, in particular the subsection there titled "Localized formats".

**Comment by BogdanAlexandru** [comment]
### Info on progress:
![Pic](http://i.imgur.com/AapLLRp.png)
I've used [FullCalendar](https://www.npmjs.com/package/ember-fullcalendar) for this. As far as features are concerned, the only thing left to do is filtering. Plenty left in the testing and polishing area though.

A neat thing to add I think would be double-clicking a day in the calendar to start a new appointment creation at that day, but this feels like a good candidate for a separate issue (the PR for this is already growing big).

Will be back with a WIP PR soon.

**Comment by garylm** [comment]
So.... Does this imply there will be a 'calendar  date format' setting?

**Comment by jkleinsc** [comment]
@garylm there doesn't need to be a calendar date format setting.  Moment.js' localized format allows us to display dates localized to the user's locale.

**Comment by garylm** [comment]
So how do we set the user's locale?

**Comment by jkleinsc** [comment]
@garylm I was under the impression that momentjs automatically set the user's locale based on the user's browser using navigator.language (https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language), but it turns out that we need to add code to do that, eg:
```js
moment.locale(navigator.language.toLowerCase());
```

**Comment by garylm** [comment]
The reason I was asking is that I have spent the last 3 months in Europe and I have yet to have any web form default to the European date format.
