### ISSUE TITLE
Add theatre scheduling

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#761]
We need to add theatre scheduling to the app.  Theatre scheduling is very similar to appointments and can probably reuse some of the appointment code.  The major difference between appointments and theatre scheduling is that a theatre "appointment" is tied to a procedure/operative plan.

This issue is also dependent on #760 which will add a calendar view to appointments.

Requirements can be found here:
https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Theater-Scheduling

Ping @mnorbeck for questions on requirements.

**Comment by suresach** [comment]
@jkleinsc Hi John, Can I take up this? :)

**Comment by jkleinsc** [comment]
@suresach sure!  Go for it!
