### ISSUE TITLE
Not Moving Beyond Login Screen

### ISSUE THREAD

**Issue by lijulat** [HospitalRun/hospitalrun-frontend#765]
I have forked the latest repo .

I have followed the readme to set up the application.

As npm start was throwing error (Windows) I had to use ember serve.

I get the login screen but when i enter the credentials and click sign in ,it doesn't move beyond the login screen. 

Note: If I enter wrong password ,i get the incorrect user name password message.

**Comment by jkleinsc** [comment]
@lijulat do you know what version of CouchDB you are running?

**Comment by lijulat** [comment]
couch db 2.0

**Comment by jkleinsc** [comment]
@lijulat I think that is the problem.  There was an issue with the Couch 2 init script that I recently fixed.  If you get the latest from git and rerun `./script/initcouch2.sh`, it should hopefully correct the problem.

**Comment by broerse** [comment]
If you are on the latest windows 10 you can enable `Windows Subsystem for Linux (Beta)` to get the bash prompt to run .sh scripts.

**Comment by tangollama** [comment]
@lijulat can we close this?

**Comment by jkleinsc** [comment]
Closing due to no response.
