### ISSUE TITLE
Customizable Print Header

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#790]
We need a configuration screen where we can specify a header image and text to include when printing from HospitalRun.  Those configurations should be read/used by the print-this component

**Comment by baoqchau** [comment]
Hello @jkleinsc. I want to work on this issue. You know where should i put the configuration screen file? I.e should I put it in app/models or app/components? Thanks a lot.

**Comment by jkleinsc** [comment]
@baoqchau my apologies for not getting back to you sooner on this one.  Please let me know if you still want to work on this.  This configuration screen will be a new screen in the admin section of the app, so it will require creating a new route and controller.  It should use the existing `option` data model, have an id of `print_header` and it should store the following properties:
facilityName - String
headerLine1 - String
headerLine2 - String
headerLine3 - String
logoURL  - String
You should be able to copy the code from app/admin/address (screen the displays when you go to Administration/Address Fields) and modify to store these properties instead of the address fields and then save into the `print_header` option instead of the `address_options` option.

Let me know if you want to work on this and if you have further questions.

**Comment by baoqchau** [comment]
Thanks for replying back to me. I will definitely want to work on this. I will ask you if I have further questions.
