### ISSUE TITLE
Add Discharge Report

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#791]
We need a discharge report added to the system.  This report should be created using custom forms (once #788 is complete)

Requirements can be found here:
https://github.com/HospitalRun/hospitalrun-frontend/wiki/Requirements:-Discharge-Report

**Comment by karunkannan** [comment]
I can try to tackle this

**Comment by jkleinsc** [comment]
@karunkannan my apologies.  Someone is already working on this, and thus it doesn't have the help wanted tag.
