### ISSUE TITLE
/db/* routes are not properly redirected when deployed outside of ember serve.

### ISSUE THREAD

**Issue by anjayajodha** [HospitalRun/hospitalrun-frontend#801]
**Expected behavior:**

After ```ember build -prod``` is run and the files from ```/dist``` are copied to an Apache or IIS server that has been configured to redirect all nonexistent URLs to index.html, I should be able to login. 

**Actual behavior:**

Any request to http://{url}/db/* is not redirected and I am unable to login. I can only login from a server started using ```ember serve```.

What rewrite rules are enabled to make the database routes work?

**Steps to reproduce:**

Copy the contents of the /dist folder to an Apache or IIS server's document directory. Enable rewrite rules so that anything that returns a 404 gets sent back to index.html (standard procedure for other Ember apps). 

In Apache, set a ```.htaccess``` file to have:

```FallbackResource /index.html```

or in IIS, set ```web.config``` to include: 

````
<rewrite>
      <rules>
        <rule name="DynamicContent">
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="True"/>
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="True"/>
          </conditions>
          <action type="Rewrite" url="index.html"/>
        </rule>
      </rules>
    </rewrite>
````

**OS and Browser:**

Apache on Windows 10,
IIS 8 on Windows Server 2012,

Chrome & Edge Browsers

**Comment by jkleinsc** [comment]
@anjayajodha if you are intending to run in a production environment (eg outside of `ember serve`), you need to use the https://github.com/HospitalRun/hospitalrun-server project.  The hospitalrun-server project is the one for production deploys and contains all the routes you need.  Also, you do not need IIS or Apache as the server runs via node.js

**Comment by anjayajodha** [comment]
@jkleinsc Thanks for the clarification! I hadn't read the documentation for each repo correctly. It's working beautifully now.  Cheers!
