### ISSUE TITLE
Appointments Error with date range End Time, never displays

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#812]
**Expected behavior:**

Allow selecting End Time Minutes on Appointments.

**Actual behavior:**

1) All types of appointments fail to display the selected minutes.
2) Clinic Appointments fail to save because of lack of end time minutes, even after the minutes have been selected.
   *** Only happens on fresh load of module.  Any additional appointment works as 1) above.

**Steps to reproduce:**

- Select Appointments
    - Click '+ new appointment'
    - Chose Type 'Clinic'
    - Uncheck "All Day'
    - Fill in the boxes
    - Click 'Add'

        The result is a popup about filling in the required fields.
       ** This only happens on the 1st try at an appointment.
**Screenshots (if applicable):**

![hr new clinic apointment end date failure](https://cloud.githubusercontent.com/assets/1472283/20387884/36fce286-acba-11e6-8673-4d467c0ed2a9.png)

**OS and Browser:**
Ubuntu 16.04  & Firefox

**Comment by mqchau** [comment]
I can't reproduce this on beta.hospitalrun.io. Can you try it again?

**Comment by jkleinsc** [comment]
@garylm I refactored how this component works.  I haven't seen this particular issue, but given the change I just made, the issue you encountered should no longer happen.

**Comment by garylm** [comment]
Works for me…  I just updated and it now works as expected.

Nice Work

Gary
Gary Miller
gary@groupmiller.com<mailto:gary@groupmiller.com>

**Comment by garylm** [comment]
Now Works for me…  I just updated and it now works as expected.

The problem has been fixed.

Gary
Gary Miller
gary@groupmiller.com<mailto:gary@groupmiller.com>
