### ISSUE TITLE
New Medication Request - Fails to accept selected medication

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#814]
**Expected behavior:**

When making a New Medication Request, you should be able to type either the Item# or the Medication Name to select a medication.

**Actual behavior:**

Using sample data, typing 'm' or 'c' will cause a drop down selection choice of m00001/Cefrazolin.  However, selecting the item will cause an error 'Please select a valid medication'.

The same result happens if I create a new medication by adding it as a new inventory item.  It will display as a drop down selection, but will trigger 'Please select a valid medication'

**Steps to reproduce:**

**Screenshots (if applicable):**
![hr new medication selection 1](https://cloud.githubusercontent.com/assets/1472283/20390828/79b5483a-acc8-11e6-9419-81a6983958d0.png)
![hr new medication selection 2](https://cloud.githubusercontent.com/assets/1472283/20390849/841e0fd2-acc8-11e6-9a9e-f4ce77643cfd.png)

**OS and Browser:**
Ubuntu 16.04 Firefox

**Comment by BogdanAlexandru** [comment]
Similar behavior can be seen when adding a new appointment, and trying to reference the patient via his ID instead of the name.

**Comment by mqchau** [comment]
It seems that if you click away from the box after you select it then it will be green.

**Comment by pgbonino** [comment]
Hello.
Sorry, but I am new in the project. I have installed properly HospitalRun in my local environment, so I get it run apparently well in a local browser.

So now I wanted to contribute for the first time. And I have seen this issue as a start point.

Could you give further information on how to reproduce the issue? Take into account that I have a totally plane HospitalRun. Empty database with just two patients I just created.

With that in mind, I go to Medication Request and when I push letter C (or any other) in Medication field, I don't get any autocomplete help. It would seem to a newbe like me that it hasn't got any medication, so it doesn't finde anything to autofill.

Any orientation just to see if I can start understanding the way it works?

Thanks!

**Comment by Shivv33** [comment]
still the issue is same, when i try to add a medication its throwing an error like please select valid medication :(
