### ISSUE TITLE
Editing appointments seems to display old data/wrong button labels at times

### ISSUE THREAD

**Issue by BogdanAlexandru** [HospitalRun/hospitalrun-frontend#815]
**Expected behavior:**
I can view the latest (correct) appointment data.
The Cancel/Return button does not change labels.

**Actual behavior:**
Sometimes I see appointment data from a previous edit.
The Cancel/Return button changes labels.
When clicking Cancel, I see new data pop in before being taken away.

**Steps to reproduce:**
1. Create an all day appointment.
2. Edit the appointment, make it not be all day.
3. Restart the browser (optional?)
4. Go to search and click the appointment.
5. Notice that it's back to being all day.
6. Button says "Cancel" rather than "Return".
7. Clicking "Cancel" changes the label to "Return".
8. Going back to the appointment the same way now should make it show "Return" and the latest data (it will not be all day).

**Screenshots (if applicable):**
This is a gif taken with the current beta build (beta.hr.io).
http://imgur.com/a/ohrGc
Gif taken with the current local build (showing the invalid data):
http://imgur.com/ncKpJe8

**OS and Browser:**
Windows 8.1 64 bit & Firefox 49.0.2 (beta.hr.io)
Lubuntu 16.10 32 bit & Firefox 49.0.2 (local)

**Comment by BogdanAlexandru** [comment]
Edited to provide local behavior gif. It seems to happen consistently locally. On the online beta I haven't had luck with the All Day -> Not All Day update repro steps, but the Cancel/Return bug shows up for other appointments.

**Comment by mqchau** [comment]
I'll try to tackle this issue.

**Comment by mqchau** [comment]
It looks like @jkleinsc has solved this issue with https://github.com/HospitalRun/hospitalrun-frontend/commit/c0d191fa9dd2e7d914b77d8dc3a3dbf1932ba37b .

**Comment by jkleinsc** [comment]
Closing this issue as resolved.
