### ISSUE TITLE
Upgrade Diagnoses

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#816]
The existing functionality around diagnostics needs to be updated.   The desired behavior would be:

1. When entering a diagnosis, either directly at the patient level, or in a visit, the doctor needs to be able to add and delete one or more primary and secondary diagnoses.   Further, any diagnoses can be made inactive (i.e. the condition was treated, and is no longer present).    

2. Currently diagnoses can only be entered / updated within a visit.   This needs to be changed to allow Doctors to go to the patient object and update diagnoses there.

3. However, any diagnoses entered during previous visits needs to be retained.

4. The patient record would always show the current list of active primary and secondary diagnoses. More or less the same as it does now.    When a new visit is created, it is pre-populated with the current list of diagnoses.   If during the visit that list of current diagnoses is added to, the patient object would also show the additions.   However, no other visits (or other objects) are to be updated, they would still show the list in effect when they were last modified.  In this way, the patient record is always up-to-date, BUT visits retain the record of what diagnoses were in effect at the time of the visit.

5. If a diagnosis is deleted from a visit, the patient associated diagnosis would NOT be changed.   The clinician would need to go to the patient record and make the deletion. (at least for v1.0 of HospitalRun)

5. Doctors do need to be able to view the list of inactive diagnoses from the patient record, perhaps as a popup.   

6. The terminology of Admitting Diagnoses can drop.   The UX/UI should simply present Primary and Secondary Diagnoses.   Billing Diagnoses, seen only by Billing role, remains unchanged at this time.

**Comment by mnorbeck** [comment]
@jkleinsc can you please review and critique?

**Comment by mnorbeck** [comment]
@jkleinsc if this is good to go, do we need to label it for 1.0, and put it on the project board?

**Comment by jkleinsc** [comment]
@mnorbeck this is done in the outpatient branch.
