### ISSUE TITLE
'+ new item' allows negative numbers.

### ISSUE THREAD

**Issue by marcorosas1991** [HospitalRun/hospitalrun-frontend#824]
Is there a reason for allowing negative quantities when adding a new item on the system?
Playing with the form, it doesn't accept 0 as a quantity, but it allows negative numbers.

**Expected behavior:**
It should prevent entering negative numbers on the form.

**Actual behavior:**
Negative numbers can be inputted on 'new item form', and saved to inventory.

**Steps to reproduce:**
- Open and login to Hospital Run.
- Click Inventory on left side panel
- Click Items
- Click '+ new item'
- Fill required fields
- Enter a negative number for quantity
- Press 'Add'
- Click Items again to see the new list
- Look for entered product

**Screenshots (if applicable):**
<img width="1440" alt="screen shot 2016-11-26 at 9 54 06 pm" src="https://cloud.githubusercontent.com/assets/5996255/20645772/04f87634-b425-11e6-8de6-963ac24637b8.png">
<img width="1438" alt="screen shot 2016-11-26 at 9 54 36 pm" src="https://cloud.githubusercontent.com/assets/5996255/20645771/04d9603c-b425-11e6-9a6f-7535d1ddb433.png">

**OS and Browser:**
Chrome Version 54.0.2840.98 (64-bit) 
MacOS 10.12.1

**Comment by marcorosas1991** [comment]
Do you agree @jkleinsc with this issue?

**Comment by jkleinsc** [comment]
@marcorosas1991 I agree... you shouldn't be able to enter in a negative value.  
This should be a pretty simple fix.  There is data validation on quantity on the [inventory model](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/models/inventory.js) that just needs to be modified to disallow numbers less than 1.  Docs for number validation are here: 
https://github.com/DockYard/ember-validations#numericality

**Comment by marcorosas1991** [comment]
Ok sounds good. I'll work on it.

**Comment by marcorosas1991** [comment]
@jkleinsc I updated the quantity field in the inventory model, and it works. The form is not submitted when there is a negative quantity. I found an issue with this solution. There is not a visual feedback about the error. 

I look around and found https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/quantity-conv.js lines 29-47 determine if there is an error with the quantity and add a CSS class. I thought I could check here if the number is negative, but if I'm right, this change would apply to all quantities. Is there any use case when the quantity can be negative?

Probably users won't input negative values too often, but it is nice to have the right feedback about it.

Thanks!

<img width="1061" alt="screen shot 2016-12-07 at 9 38 42 pm" src="https://cloud.githubusercontent.com/assets/5996255/20997737/9f4f9a48-bcc5-11e6-857c-0f01595afd43.png">
Form is not submitted.
<img width="248" alt="screen shot 2016-12-07 at 9 38 57 pm" src="https://cloud.githubusercontent.com/assets/5996255/20997740/a1dd3342-bcc5-11e6-8054-88d13baf309d.png">
No visual feed back on quantity field.

**Comment by jkleinsc** [comment]
@marcorosas1991 there isn't anywhere in the app where a negative number should be used, so it would be fine to modify https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/components/quantity-conv.js#L33 to check for negative numbers.  

Thanks for working on this issue!
