### ISSUE TITLE
Add new user page is not intuitive after pressing add

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#833]
**Expected behavior:**
After adding a new, the next page should either be an edit user page for the user you just added, OR clear out the fields and remain an add user page 

**Actual behavior:**
User is added, but the page remains titled "New User".   Not intuitive, as any edits to that page will edit the user you just created.   

**Steps to reproduce:**

1. Navigate to the new user page, either directly from the sidebar menu, or the button on the users list page.
2. enter data to create a new user and press "add"
3. Note the page title.  

**Screenshots (if applicable):**
![screen shot 2016-12-02 at 4 15 41 pm](https://cloud.githubusercontent.com/assets/6825179/20850693/9d2899e6-b8aa-11e6-9bb2-454366a9dda1.png)

**OS and Browser:**
OSX  10.10.5  Chrome 54.0.2840.98

**Comment by mnorbeck** [comment]
@jkleinsc ...just to let you know!

**Comment by tangollama** [comment]
@Anisha1234 I think you should change the title of the edit page in this workflow vs. change the location of the successful add event. Is that helpful?
