### ISSUE TITLE
Possible bug with the import feature

### ISSUE THREAD

**Issue by marcorosas1991** [HospitalRun/hospitalrun-frontend#834]
**Expected behavior:**
If I have existing data, imported data should not get the same IDs

**Actual behavior:**
Imported data gets hardcoded IDs from import file. It doesn't check for existing ones.

**Steps to reproduce:**
Add some data, for example to the patient, and item lists.
Import a db through the  Administration > Load DB option. (You can use the sample-data.txt in the root folder)

Check patient or item list, you will see duplicated IDs

**Screenshots (if applicable):**
<img width="1159" alt="screen shot 2016-12-03 at 8 34 00 pm" src="https://cloud.githubusercontent.com/assets/5996255/20864097/8494a1cc-b99f-11e6-80c5-d66a8b3a2e66.png">

**OS and Browser:**
Chrome Version 54.0.2840.98 (64-bit)
MacOS 10.12.1

**Comment by jkleinsc** [comment]
@marcorosas1991 it turns out there was an issue with duplicating patient ids.  I fixed that with d2004bfa18693e674f852fb83f2b1868bf0e20b3.
