### ISSUE TITLE
Is Invoice Number required on an item purchase?

### ISSUE THREAD

**Issue by marcorosas1991** [HospitalRun/hospitalrun-frontend#837]
**Expected behavior:**
Invoice number should be marked as required, or it should not prevent to submit the purchase form.

**Actual behavior:**
'Invoice number' field is not marked as required, but it prevents to submit the form if the field is empty and pristine.

If the invoice field is dirty (has been changed), even if the new value is set back to empt, it allows the form to be submitted.

**Steps to reproduce:**
-Go to Inventory > Items
-Edit any of the items
-Under the purchase label press '+ add purchase'
-Fill all required fields (leave invoice empty).
--You won't be allow to submit
-Modify the value of the invoice field
--The 'add' button gets active
-Delete the content of the invoice field
--The 'add' button is still active

**Screenshots (if applicable):**
<img width="613" alt="screen shot 2016-12-06 at 8 52 38 pm" src="https://cloud.githubusercontent.com/assets/5996255/20954470/d8b71928-bbf8-11e6-8932-d3b312cb1f9a.png">
<img width="609" alt="screen shot 2016-12-06 at 8 52 45 pm" src="https://cloud.githubusercontent.com/assets/5996255/20954472/d8d81312-bbf8-11e6-8f77-127494130d4a.png">
<img width="607" alt="screen shot 2016-12-06 at 8 52 53 pm" src="https://cloud.githubusercontent.com/assets/5996255/20954473/d8db9104-bbf8-11e6-8233-e79b061392db.png">

**OS and Browser:**
Chrome Version 54.0.2840.98 (64-bit)
MacOS 10.12.1

**Comment by jkleinsc** [comment]
@marcorosas1991 I think the issue was being caused by changes I made to accommodate Ember 2.10.  I'll have a fix very shortly.
