### ISSUE TITLE
Social Work section changes

### ISSUE THREAD

**Issue by jkleinsc** [HospitalRun/hospitalrun-frontend#90]
Social work needs to be changed to reflect this form and allow printing of form:
![assessment](https://cloud.githubusercontent.com/assets/609052/7011250/91e6e0be-dc75-11e4-9c32-e0fab2c142b2.png)
![assessment2](https://cloud.githubusercontent.com/assets/609052/7011251/96011336-dc75-11e4-80a7-979c51ab6c09.png)
![assessment3](https://cloud.githubusercontent.com/assets/609052/7011276/cf71eec4-dc75-11e4-94e9-fa7cefb2478f.png)

**Comment by jkleinsc** [comment]
This is a Philippines specific requirement, but we may need a generic version of this for HospitalRun.

**Comment by jkleinsc** [comment]
@tangollama I think the bigger requirement here is to create functionality to create custom forms per install.  I've been thinking about this and I think we could create a custom form generator within HospitalRun.  I believe it could be useful in terms of being able to generate forms from HosptialRun that can be (optionally) printed out.

**Comment by tangollama** [comment]
Discussed with @jkleinsc recently. @taras is looking into a form-building Emberjs solution for this and other use cases in the system (intake forms, etc).

**Comment by jkleinsc** [comment]
@tangollama it looks like we can use this addon: https://github.com/toddjordan/ember-cli-dynamic-forms

**Comment by tangollama** [comment]
Best news of day!

Sent using CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.11.40&pv=9.3.1&source=email_footer_2]
On Wed, May 18, 2016 at 4:48 PM, John Kleinschmidt <notifications@github.com> wrote:
@tangollama [https://github.com/tangollama] it looks like we can use this addon: https://github.com/toddjordan/ember-cli-dynamic-forms [https://github.com/toddjordan/ember-cli-dynamic-forms]

**Comment by jkleinsc** [comment]
There is a custom component called `custom-form` available in the app that is currently being used to add custom form elements to the social work tab.  Right now this requires creating a document directly in couchdb with the id `option_2_custom_form_social`.  The form definition used is defined here:
https://github.com/HospitalRun/hospitalrun-frontend/wiki/Custom-Form-Component

The outstanding issue here is to make sure the whole form can be duplicated and that it can then be printed.

**Comment by jkleinsc** [comment]
The custom forms feature satisfies this requirement so I am closing this issue.
