### ISSUE TITLE
Appointments's test not correctly done

### ISSUE THREAD

**Issue by hsorellana** [HospitalRun/hospitalrun-frontend#905]
I hope not using the original template of issues isn't too bad but for this, i don't it applies correctly. The thing is that project itself uses the standard of Dockyard to write well code. Well, the appointments models isn't applying correctly the code guidelines, for example, on its functions for computed attributes.

**Comment by hsorellana** [comment]
I can see this issue myself and, of course, make sure the other models follow this convention, if tests is a important part of the project, as i think they are.
Cheers!

**Comment by jkleinsc** [comment]
@hsorellana feel free to submit PRs to correct code style issues like this.
