### ISSUE TITLE
Upload Import to "Lookup List" not working.

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#921]
**Expected behavior:**
Create a text file of Diagnoses, as a string per line in the file.
  Ex:  Acute Flaccid Paralysis
        Cholera
       Neonatal tetanus

Link the text file using the Browse Button
Upload the text file using the Import Button
List Upload Successful Dialog Box pops up.

Should see the new items in the list.
**Actual behavior:**

No new items appear in the list even though the success dialog does confirm success.

**Screenshots (if applicable):**
![hr list import file screen](https://cloud.githubusercontent.com/assets/1472283/21944919/6f281bc6-d98d-11e6-8c9d-f1c5191972f3.png)
![hr upload success dialog box](https://cloud.githubusercontent.com/assets/1472283/21944928/75af5a0e-d98d-11e6-8386-169354efcfa8.png)

I have tested using single quotes, double quotes, no quotes, etc.

**OS and Browser:**
Linux, Firefox

**Comment by jkleinsc** [comment]
@garylm this has now been fixed.  The import accepts CSV files with one value per line, though technically a text file with values separated by newlines works as well.  So a file formatted as follows would work:
```
Foo
Bar
Baz
```

**Comment by garylm** [comment]
John, thanks!

Gary
Gary Miller
gary@groupmiller.com<mailto:gary@groupmiller.com>
