### ISSUE TITLE
Spaces in username, during logging

### ISSUE THREAD

**Issue by tleb** [HospitalRun/hospitalrun-frontend#922]
**Expected behavior:**

Space trimming

**Actual behavior:**

A `Username or password is incorrect.` error.

**Steps to reproduce:**

Go on demo, try an ID with a space in front or behind it ; it doesn't work.

Great projet BTW!

**Comment by Jaden-Giordano** [comment]
A simple fix would be to just trim the spaces, but couldn't it be a breach in security if you allowed the user access if they accidentally entered a space, or any invalid character, _anywhere_ in the credentials?

**Comment by tleb** [comment]
I don't see why, you just delete the ones at the beginning and at the end and those in between are part of the username. But, should spaces be allowed at all?

**Comment by jkleinsc** [comment]
Usernames shouldn't have spaces in them, and it makes sense to trim any spaces on login.  It is a simple change that should produce a better user experience.
