### ISSUE TITLE
Add Value Button missing from Lab Pricing Types List screen

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#928]
**Expected behavior:**
Attempting to add Lab Pricing Types to the list thru the Administration module.
**Actual behavior:**
The "Add Value" button is missing from the screen.
**Steps to reproduce:**
Choose the "Lab Pricing Types" List under Administration
**Screenshots (if applicable):**
![hr lab pricing types add button missing 01-31-17](https://cloud.githubusercontent.com/assets/1472283/22481490/5533fe26-e7aa-11e6-931b-29382c246262.png)

**OS and Browser:**
Ubuntu 16.02 & Firefox.  Code Updated thru yesterday.

**Comment by jkleinsc** [comment]
@garylm this is intentionally working this way.  You can't add lab pricing types because there isn't anywhere in the system that uses different lab pricing types.  Same thing goes for imaging pricing types.

**Comment by garylm** [comment]
Does this mean that these pricing types are intended future functionality? Or are these depreciated design concepts?

**Comment by jkleinsc** [comment]
@garylm intended future functionality.
