### ISSUE TITLE
Ability to change the name of User Roles

### ISSUE THREAD

**Issue by mnorbeck** [HospitalRun/hospitalrun-frontend#935]
This is an enhancement request.

Allow for the changing of user role names in the Admin module.    Roles are going to correspond to job titles in a hospital ( that is how users will think about them)......and those titles may be unique to a hospital (or country, or region).   Flexibility to change the role name would be very useful.

For the target contexts, I think we have enough roles in the system (15-16?) at this point.  So, while adding and deleting roles *may* be useful, for v1.0 I do not think they are needed.

@jkleinsc

**Comment by robrighter** [comment]
@tangollama Looks like this one needs somebody to pick it back up. I am going to start working on it.

**Comment by DerekTBrown** [comment]
Looks like this has an open PR: https://github.com/HospitalRun/hospitalrun-frontend/issues/935

**Comment by fox1t** [comment]
@tehKapa I think this is till an interesting feature to have.
