### ISSUE TITLE
Concider ember-concurrency addon

### ISSUE THREAD

**Issue by sukima** [HospitalRun/hospitalrun-frontend#969]
I am planning on joining Slack but also thought it would help documenting this question here for discussion.

Has this project considered [ember-concurrency](http://ember-concurrency.com/)?

> An Ember add-on that uses ES6 generator functions to reduce the boilerplate around concurrency while adding structure to complex asynchronous code. [[LinkedIn's] experience has been overwhelmingly positive][1].

It would make [code like this](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/admin/address/route.js#L11-L28):

```js
model() {
  return new Ember.RSVP.Promise((resolve, reject) => {
    this.get('store').find('option', 'address_options').then((addressOptions) => {
      resolve(addressOptions);
    }, (err) => {
      if (err instanceof UnauthorizedError) {
        reject(err);
      } else {
        let store = this.get('store');
        let newConfig = store.push(store.normalize('option', {
          id: 'address_options',
          value: {
            address1Label: this.get('i18n').t('admin.address.addressLabel'),
            address1Include: true
          }
        }));
        resolve(newConfig);
      }
    });
  });
}
```

Look like this:

```js
model() {
  return this.get('addressTask').perform();
},

addressTask: task(function * () {
  const store = this.get('store');
  const i18n = this.get('i18n');

  try {
    return yield store.find('option', 'address_options');
  } catch (err) {
    if (err instanceof UnauthorizedError) {
      throw err;
    }
    return store.push(store.normalize('option', {
      id: 'address_options',
      value: {
        address1Label: i18n.t('admin.address.addressLabel'),
        address1Include: true
      }
    }));
  }
})
.keepLatest()
.cancelOn('deactivate')
```

It can exists with the current code but allow refactors, clean up, and expand new features. I mention this because I and many others in the community have found this invaluable and door opening.

- [A Match Made In Heaven (DockYard)](https://dockyard.com/blog/2016/04/10/a-match-made-in-heaven)
- [ember-concurrency or: How I Learned to Stop Worrying and Love the Task (LinkedIn)][1]

[1]: https://engineering.linkedin.com/blog/2016/12/ember-concurrency--or--how-i-learned-to-stop-worrying-and-love-t

**Comment by jkleinsc** [comment]
@sukima I've heard of ember-concurrency but haven't had time to look into to it.  I am in favor of simplifying things and I see how this could help.  If you (or others) want to submit a PR introducing ember-concurrency (on a small subset of code), that would be encouraged and would probably be a good next step in demonstrating ember-concurrency.

**Comment by sukima** [comment]
I would be happy to make a PR with the above initial conversion. Any troublesome async areas you would want tackled (I am new to the code base) let me know I can look at them too. I kinda like refactoring like this.
