### ISSUE TITLE
Inclusion of a Patient Dashboard 

### ISSUE THREAD

**Issue by Anisha1234** [HospitalRun/hospitalrun-frontend#979]
I would like to propose the idea for a dashboard for patients which is presently absent in the app. There are dashboards for the admin, doctors, labs etc but the inclusion of this feature would make the app more accessible from the patient side.The features would include:

1. Book an appointment from the list of available doctors.
2. Manage appointments, i.e., if there would be a change in the schedule of the doctor, it would be notified to the patients and a new appointment would be fixed.
3. Check-up reminders for patients.
4. Reminders for the refill of medicines.
5. Reports of checkups and imaging lab reports.

These are the basic features that would make the experience for the patients more convenient, however, more ideas and features would be appreciated to be worked upon.

**Comment by emadehsan** [comment]
Great ideas! What do you think about **Signup** feature for Patients? Currently patients are added only through dashboard. But if he/she has to book an appointment for the very first time, he/she must be able to Signup!

**Comment by emadehsan** [comment]
I think currently the core team is focused on Release 1.0 since the release date (April 1st) is approaching. These features might get included in next versions of the software.

**Comment by aanchan** [comment]
I'm currently working on this issue. I approached it by creating a new route called patientrole.index.
