### ISSUE TITLE
Search function in pricing does not return correct result

### ISSUE THREAD

**Issue by baoqchau** [HospitalRun/hospitalrun-frontend#986]
**Expected behavior:**
Search for specific pricing name "Elbow AP-L", should return exact result with "Elbow AP-L"
**Actual behavior:**
Return results with term "AP-L" in it. And most important, the results don't contain the result for "Elbow AP-L".
**Steps to reproduce:**
Go to website beta.hospitalrun.io
Logged in with "Hospital admin" role
Go to tab navigation on the left => Billing => Prices => search for the term in "search" box above
**Screenshots (if applicable):**
![error-search-function-pricing](https://cloud.githubusercontent.com/assets/8473870/23869697/225b705e-07e1-11e7-827f-419657d59ec8.png)

**OS and Browser:**
Chromium Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by jkleinsc** [comment]
I am look at this one.  There is an issue with the search proxy used if you are not using ElasticSearch.

**Comment by jkleinsc** [comment]
This is now fixed.
