### ISSUE TITLE
Website not running locally with docker in Windows

### ISSUE THREAD

**Issue by aravindGear4** [HospitalRun/hospitalrun-frontend#988]
**Expected behavior:**
It is supposed to open website with localhost:4200 or docker-machine-ip:4200

**Actual behavior:**
Now when I try to open the website with localhost:4200 or <docker-machine-ip>:4200 there is nothing on it.

**Steps to reproduce:**
Followed the steps under "Running with Docker" in README.md
***Running with Docker***
To run HospitalRun with Docker please do the following:
- Goto [https://docs.docker.com/engine/installation](https://docs.docker.com/engine/installation) to download and install Docker.
- Clone the repository with the command `git clone https://github.com/HospitalRun/hospitalrun-frontend.git`.
- Change to the hospitalrun-frontend directory `cd hospitalrun-frontend`.
- Build the HospitalRun image with `docker build -t hospitalrun-frontend .`
- Execute `docker run -it --name couchdb -d couchdb` to create the couchdb container.
- Execute `docker run -it --name hospitalrun-frontend -p 4200:4200 --link couchdb:couchdb -d hospitalrun-frontend` to create the HospitalRun container.

>docker ps -a
2b8c72a851c7        couchdb                "tini -- /docker-entr"   21 minutes ago      Up 21 minutes                 5984/tcp            couchdb

>docker logs --details couchdb
> WARNING: CouchDB is running in Admin Party mode.
         This will allow anyone with access to the
          CouchDB port to access your database. In
          Docker's default configuration, this is
          effectively any other container on the same
          system.
          Use "-e COUCHDB_USER=admin -e COUCHDB_PASSWORD=password"
          to set it in "docker run".
 >****************************************************
 Apache CouchDB 1.6.1 (LogLevel=info) is starting.
 Apache CouchDB has started. Time to relax.
 [info] [<0.32.0>] Apache CouchDB has started on http://0.0.0.0:5984/

**Screenshots (if applicable):**

**OS and Browser:**
Windows and Chrome

**Comment by tangollama** [comment]
@aravindGear4 is this still an issue?

**Comment by nzidol** [comment]
It can be an issue when GIT is installed with configuration to change line-endings to windows format. Then the docker COPY command will copy .sh files into the linux environment with incorrect line endings and the container will fail to start. 

To avoid the issue use:
`git clone https://github.com/HospitalRun/hospitalrun-frontend.git --config core.autocrlf=input`

See also: 
- http://willi.am/blog/2016/08/11/docker-for-windows-dealing-with-windows-line-endings/
- https://help.github.com/articles/dealing-with-line-endings/

**Comment by abc985** [comment]
what version OS and Browser?

**Comment by stukalin** [comment]
@aravindGear4 you haven't put the logs from the HR container, but there is a chance that my fix will suit for your problem as well.
