### ISSUE TITLE
Date format is not universal

### ISSUE THREAD

**Issue by emadehsan** [HospitalRun/hospitalrun-frontend#990]
**Expected behavior:**
My suggestion is that date format must be `YYYY/MM/DD`, which is understandable in all areas.

**Actual behavior:**
HospitalRun is currently using format `MM/DD/YYYY` for saving dates. This format of date is sometimes confusing and misleading for people in countries where standard format is `DD/MM/YYYY`.

**Steps to reproduce:**
Click Add Appointment, select Start date from calendar.

**Screenshots (if applicable):**
![hr date format](https://cloud.githubusercontent.com/assets/7283624/23933484/a5248112-0960-11e7-9ee4-8727d11c8351.png)

**OS and Browser:**
Chrome on Windows 10

**Comment by jkleinsc** [comment]
@emadehsan thanks for filling this issue.  HospitalRun is wired to use locale specific date formats, but the problem is we do not set the user's locale when the application first loads.  In order to do so,  we need to add code here https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/controllers/application.js#L5 or here: https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/routes/application.js#L81 to set the [Moment.js locale] (http://momentjs.com/docs/#/i18n/changing-locale/)

**Comment by emadehsan** [comment]
If one has to set user's locale with moment.js in [Application Controller](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/app/controllers/application.js#L5), would Application Controller look like this?
```
import Ember from 'ember';
import moment from 'moment';
import config from '../config/environment';
export default Ember.Controller.extend({
  filesystem: Ember.inject.service(),
  session: Ember.inject.service(),
  _setup: function() {
    moment.locale(config.i18n.defaultLocale);
    let fileSystem = this.get('filesystem');
    fileSystem.setup();
  }.on('init')
});
```

**Comment by emadehsan** [comment]
But still there is a concern here. For example `DD/MM/YYYY` is widely adopted date format in Pakistan. And a lot of users prefer to use apps in English instead of Urdu language `ur`. And that I think would be the case with many locales.

**Comment by jkleinsc** [comment]
@emadehsan setting the date locale should ultimately be a per user setting, not a system wide configuration.  One way to do this is to get the user's locale from the browser using [navigator.language](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language)
This wouldn't address your second concern where a user wants English but desires that the date be formatted as DD/MM/YYYY.

Ideally I think the solution is to have application settings for a default language and date format and then give the user the option of overriding the system defaults with their preferences.

**Comment by travismchan** [comment]
Would it be possible to render the date in the input field as the formatted version of the dates so there is no confusion? Eg: 15 Mar 2017

**Comment by jkleinsc** [comment]
@travismchan that is a great idea.  Having placeholder text would be helpful.  Keep in mind that when you click on a date field, a calendar pops up and when you select a date it displays in the text field in the proper format.

**Comment by emadehsan** [comment]
@travismchan rendering as `15 Mar 2017` is good idea. 

But @jkleinsc clicking on the date filed brings up the calendar, and if the a patient's DoB is 13 Jan 1970, clicking through the calendar to get to that year takes dozens if not hundreds of clicks. The solution currently is, again, inserting the date as `MM/DD/YYYY`.

**Comment by jkleinsc** [comment]
@emadehsan that is true.   I just wanted to clarify for @travismchan that the calendar does set the date in the current format.

**Comment by pwaweru-mdsol** [comment]
Hey there, what is the status of this issue? I am new to this open source project, and thought this issue was easy enough to start off with.

**Comment by jkleinsc** [comment]
@pwaweru-mdsol I'm not so sure this is a simple issue.  There are several things in this issue:
1. We need to at a bare minimum set the date locale to the current user's locale using [navigator.language](https://developer.mozilla.org/en-US/docs/Web/API/NavigatorLanguage/language)
2. We need a way for users to select/change their date locale.  This is a more complicated feature and probably deserves its own issue.

**Comment by masanori1102** [comment]
I think that it is better to use [Date.prototype.toLocaleDateString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString) function for date format.

This is the case of the default value.
As @jkleinsc wrote in number 2, I also think that it is better to allow the user to select the date format.

In order to solve this problem by using `Date.prototype.toLocaleDateString()` function, it is necessary to solve the following 2 problems.
1. Older browsers do not support `locales` and `options` arguments of `Date.prototype.toLocaleDateString()`.
    * e.g. IE10 or earlier does not support these parameters.
1. Currently, the date format `.format('l')` in several files.
    * I think that it is good to summarize the processing on the date format.

**Comment by tangollama** [comment]
@masanori1102 I'm not sure that the older browser concern is as valid in this case. HospitalRun is a business app that intentionally makes use of more modern capabilities like offline storage. That's not to totally disregard your comment. Only to set scope to an appropriate level. We're assuming with this project that to use this free, modern solution, you can bother to deploy a modern browser. 

@jkleinsc feel free to contradict me if I'm off.

**Comment by masanori1102** [comment]
@tangollama Thank you.
I understood that this application is focused on the modern browsers.

So, I strickthrough about older browser description in [my previous comment](#issuecomment-330064348).

**Comment by philayres** [comment]
Has this issue been addressed yet? If not, I agree with displaying using `Date.prototype.toLocaleDateString()` although very carefully. My current project uses this extensively across US and UK locales. I will say that it is worth having acceptance tests cover daylight savings time dates, as I had an unfortunate bug for some time that would display date of birth incorrectly by not handling the hour change, or by missing timezone differences (my date of birth is always written the same, irrespective of the actual UTC time when I was born, but other event dates might not be). Specifically, when converting from YYYY-MM-DD strings passed as HTTP parameters the parsed date could fall the wrong side of the time change.

To handle this I have some scruffy code that checks whether the date string has a timezone indicator attached, and if not sets it to be UTC. Something like this...

```
_fpa.utils.YMDtoLocale = function(stre){

    // Take special care to avoid issues with timezones and daylight savings time quirks
    if((stre.indexOf('t')>=0 && stre.indexOf('z')>=0) || (stre.indexOf('T')>=0 && stre.indexOf('Z')>=0)){
        startTime = new Date(Date.parse(stre));
        startTime =   new Date( startTime.getTime() + ( startTime.getTimezoneOffset() * 60000 ) );
        var d = startTime.toLocaleDateString();
    } else {
        var d = new Date(stre).toLocaleDateString(undefined, {timeZone: "UTC"});
    }
    return d;
};
```
Also, beware that Firefox 57 has added a date picker of its own finally. I don't know if you use `<input type="date"` but they broke my existing datepicker shim. They do at least convert to YYYY-MM-DD correctly as an input value whenever the input is queried or submitted, which is a plus.

Anyway, I'm happy to lend a hand if I can be useful. Sorry if this is already a non-issue. You weren't tagged as closed, so I stuck my nose in.

**Comment by drakemedic** [comment]
As an implementer of the software and trainer of users, I would find it useful to be able to set the date format system-wide. I work with users who have little computer experience and very basic literacy, so confusion between DD/MM/YYYY and MM/DD/YYYY will happen very easily. Setting the locale per browser is an acceptable approach for me, as I can set this as systems are rolled-out.
