### ISSUE TITLE
Imaging Type should be a Lookup List 

### ISSUE THREAD

**Issue by garylm** [HospitalRun/hospitalrun-frontend#998]
**Expected behavior:**
It makes sense to have a "fixed" or set list of possible imaging types to be requested, rather than allowing random text entries.  There is a note field that allows additional specific information, if needed.  

**Actual behavior:**
Currently a general text field.  

Also, any reporting on imaging will be subject to the randomness of whatever way users describe the requests.

**Comment by jkleinsc** [comment]
@garylm Imaging types are tied to the Imaging Pricing Type lookup list, but they are
managed as pricing items and by default all users can add new imaging types.  If you want to turn off the capability for all users to add new types, you do so by editing the Imaging Pricing Type lookup list and unchecking the checkbox labeled `User Can Add New Values`.

Editing of the imaging types can be accomplished by going to /pricing/imaging.  

BTW lab types work the same way.

**Comment by garylm** [comment]
John, there are still a couple of issues on this.

  1.  You can only add to the Imaging Pricing Type list by giving a user the ability to edit the field when adding an imaging request.
     *   *** List Upload Fails.

  2.  No Way to Edit the List….  Under Administration\List Menu, only the two check boxes appear.
     *   *** The Imaging Pricing List does not show as with other lists.

Thanks,

Gary
Gary Miller
gary@groupmiller.com<mailto:gary@groupmiller.com>
